dfinity/oisy-wallet

- src/backend/backend.did
- src/backend/src/lib.rs
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.did.js
This change adds a method to compute the ETH address of a given principal, `eth_address_of`.
> feat(backend): get ETH address of a principal

- src/frontend/src/lib/providers/metamask.providers.ts
> The value parameter is a hex-encoded...
https://docs.metamask.io/wallet/how-to/send-transactions/#value
> fix(frontend): metamask expect an amount provided in hexstring

- src/airdrop/src/guards.rs
- src/airdrop/src/lib.rs
- src/airdrop/src/state.rs
- src/airdrop/src/utils.rs
After multiple rewrites/change directions, some fields' names do not reflect their actual use.
> chore(airdrop): Rename fields

- src/airdrop/airdrop.did
- src/airdrop/src/lib.rs
- src/declarations/airdrop/airdrop.did.d.ts
- src/declarations/airdrop/airdrop.factory.did.js
We have three endpoints for adding resources to the canister state:
- admins
- managers
- code
We need to make sure none of them are added multiple times:
- admins - stored in a hashest - no issue 
- managers - we return an error as we add them one by one 
- code - silently failed as an early error return would mean we do not add the rest - otherwise we can create a list of codes that were not added and return them.
> fix(airdrop): Prevent duplicate key creation

- src/frontend/src/lib/services/auth.services.ts
- src/frontend/src/lib/utils/route.utils.ts
- src/frontend/src/routes/+layout.svelte
> We encountered an issue while testing the Oisy Wallet of the foundation with the `@dfinity/auth-client library`. In Safari, following a logout, the subsequent login using the library gets blocked by the browser, which prevents the opening of a new window or popup. The only feasible workaround is to force a window.location.reload() after signing out.
> fix(frontend): workaround for AuthClient issue in Safari after logout

- Cargo.lock
- src/airdrop/Cargo.toml
- src/backend/Cargo.toml
I will tag the repo with a starting version `v0.0.1` therefore I use the same starting points for both canisters.
> docs: v0.0.1 for airdrop and backend

- Cargo.lock
PRs https://github.com/dfinity/oisy-wallet/pull/409 and https://github.com/dfinity/oisy-wallet/pull/411 lead to update newer dependencies that are incompatible with our wasi generation of the did files.
This PR reverts the package lock and manually add shared. Tomorrow or so I'll upgrade dependencies and pipeline.
> build: fix cargo lock dependencies and manually add shared

- src/frontend/src/lib/components/wallet-connect/WalletConnectSession.svelte
otherwise button remains displayed as connected
> fix(frontend): reset walletconnect listener on unexpected error

- src/frontend/src/lib/providers/wallet-connect.providers.ts
During testing, we frequently encountered session approval failures with Uniswap due to the following reason:
> Unexpected error while communicating with WalletConnect. / No matching key. pairing: 12345c....
The issue appears to be linked to incorrect cached information used by the WalletConnect library.
To address this, we clear the local storage of any WalletConnect keys to ensure the proper instantiation of a new Wec3Wallet object.
> feat(frontend): clear WalletConnect related localstorage entries before initialization

- src/frontend/src/app.html
- src/frontend/static/robots.txt
This reverts commit #430
No crawler is the default but a post build opens it, I forgot that for 1min
> Revert "feat: allow crawlers (#430)"

- src/frontend/src/lib/components/layout/HeaderHero.svelte
The header shifted of 2px on navigation after the introduction of Tailwind.
> style: fix header size after tailwind

- package-lock.json
- package.json
Yesterday we have removed the node polyfillier for local development, therefore we can bump Wallet Connect as  #478 gets resolved.
> build: bump wallet connect

- src/frontend/static/manifest.webmanifest
The SW is gone, we can use effective custom domain based URL for the images in the manifest as well
> build: manifest img urls

- svelte.config.js
- tsconfig.json
> > svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
>
> You have specified a baseUrl and/or paths in your tsconfig.json which interferes with SvelteKit's auto-generated tsconfig.json. Remove it to avoid problems with intellisense. For path aliases, use `kit.alias` instead: https://kit.svelte.dev/docs/configuration#alias
> build: resolve sveltekit v2 alias

- src/frontend/src/icp/components/transactions/IcTransaction.svelte
- src/frontend/src/icp/components/transactions/IcTransactionModal.svelte
- src/frontend/src/icp/components/transactions/IcTransactions.svelte
- src/frontend/src/icp/services/ic-transactions.services.ts
- src/frontend/src/icp/services/worker.icrc-wallet.services.ts
- src/frontend/src/icp/stores/ic-transactions.store.ts
- src/frontend/src/icp/types/ic.ts
- src/frontend/src/icp/utils/icp-transactions.utils.ts
- src/frontend/src/icp/utils/icrc-transactions.utils.ts
- src/frontend/src/icp/worker-utils/wallet.worker-utils.ts
- src/frontend/src/icp/workers/icp-wallet.worker.ts
- src/frontend/src/icp/workers/icrc-wallet.worker.ts
- src/frontend/src/lib/types/post-message.ts
We need this because we have to fetch and map ckBTC pending Utxo to pseudo transactions for display purpose.
In addition, this improves performance by deferring some addition work to the workers.
So, win win.
> feat: hold mapped IC transaction in store and map in workers

- src/frontend/src/eth/components/fee/FeeDisplay.svelte
- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/components/transactions/IcTransaction.svelte
- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/lib/utils/format.utils.ts
UX/UI choice rather than precision choice here. The full value with the number of decimals of the token is available in the modal.
> feat: up to height decimals on transactions list

- src/frontend/src/tests/icp/utils/cketh-memo.utils.spec.ts
Use similar memo and expected value as the `encode` purpose tests implemented in ckETH backend: https://docs.google.com/document/d/1rmOWTL7_MrkiUHVUlX1UP7_cqB97VSNFEcedHiF5cIc/edit
> test: align values on backend similar memo test

- src/frontend/src/icp/constants/ckbtc.constants.ts
That way everything ckBTC has to be manually triggered and it's consistent for a first version.
> feat: disable btc status timer as well

- src/frontend/src/icp/components/receive/IcReceiveBitcoin.svelte
- src/frontend/src/icp/components/receive/IcReceiveBitcoinProgress.svelte
Manually firing "Check for incoming BTC" also triggers the wallet which refreshes the BTC statuses, therefore it actually checks for "incoming and outgoing BTC" that's why I suggest to rename the call to action.
> feat: rename ckbtc check incoming BTC

- src/frontend/src/eth/components/core/EthWalletAddress.svelte
- src/frontend/src/eth/components/transactions/TransactionModal.svelte
- src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts
- src/frontend/src/icp/utils/ckbtc-transactions.utils.ts
- src/frontend/src/icp/utils/cketh-transactions.utils.ts
- src/frontend/src/icp/utils/icp-transactions.utils.ts
- src/frontend/src/lib/constants/explorers.constants.ts
Staging configuration inherits prod environments, so to disable some explorer links on staging, we have to set empty.
> feat: handle also explorer url set to empty

- scripts/deploy.cketh.sh
- Deploy ckETH minter with an initial block index closer to last that way the minter does not scrap the all eth at starts
- Use expected ecdsa_key_name by the minter
- Given 18 decimals, provides more funds for the ckETH ledger
> build: fix local ckETH deployment

- src/frontend/src/lib/components/hero/Balance.svelte
Easier to read with 8 decimals on mobile.
> style: on mobile display balance token in column

- src/frontend/static/manifest.webmanifest
Always thought we need icons so had to invest time but, looks like just links is supported according https://webkit.org/blog/15063/webkit-features-in-safari-17-4/
> feat: manifest shortcuts

- scripts/build.csp.mjs
We do not need that workaround anymore given that the SW has been moved.
> build: remove raw for images rule in csp

- src/frontend/src/env/eip155-chains.env.ts
Given that I often develop locally using Uniswap (prod) which always requires Eth, if Eth is not present in the list of Eip155 I cannot connect. So let's redo having it always in the list.
> feat: redo eip155 for eth on local

- src/frontend/src/icp-eth/api/cketh-minter.api.ts
- src/frontend/src/icp/api/ckbtc-minter.api.ts
- src/frontend/src/icp/api/cketh-minter.api.ts
- src/frontend/src/icp/api/ic.api.ts
- src/frontend/src/icp/api/icp-index.api.ts
- src/frontend/src/icp/api/icp-ledger.api.ts
- src/frontend/src/icp/api/icrc-index-ng.api.ts
- src/frontend/src/icp/api/icrc-ledger.api.ts
No stores usage in API because used by workers as well.
> build: fix prod build

- Cargo.toml
> warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
> build: set cargo resolver 2

- dfx.json
Given that we delete the outcome of dfx generate anyway, we do not need that option
> chore: remove unused dfx option

- src/backend/src/lib.rs
- src/backend/src/token.rs
We are looking to introduce support for ICRC tokens. This feature will be similar to the already supported feature that involves adding, removing, or listing ERC20 custom user tokens.
We are not planning to migrate right now but are planning to introduce support for ICRC in a new generic memory (PR #1037). This additional feature will share common logic with the existing feature, notably the addition and removal of custom tokens.
That's why this PR refactors the mutation of the state into reusable generic functions.
> refactor(backend): extract add and remove user token

- src/frontend/static/.ic-assets.json
Not required anymore following the removal of the SW
> build: remove raw exception for favicons

- src/backend/src/lib.rs
- src/backend/tests/it/custom_token.rs
- src/backend/tests/it/token.rs
- src/backend/tests/it/upgrade.rs
- src/backend/tests/it/utils/assertion.rs
- src/shared/src/impls.rs
- src/shared/src/types.rs
In PR [#1100](https://github.com/dfinity/oisy-wallet/pull/1100#discussion_r1565499000) we discussed the fact that using `UserToken` and `CustomToken` was confusing. This was the result of the fact that the original custom token for user for ERC20 which exists on mainnet are called `Token` and the related functions are called `add_user_token`.
To clean-up and make this more comprehensive, this PR rename the various structs.
- `Token` -> `UserToken` (ERC20, already in prod and relates to `add_user_token` which won't change)
- `UserToken` -> `CustomToken` (new custom token type we have recently added)
- `CustomToken` -> `Token` (the token enum that contains either ICRC token or future other tokens)
After this PR, I'll provide a PR that renames the new functions that are not yet live on …
> refactor: rename Token and UserToken

- src/backend/src/lib.rs
To clean-up the naming structure, we are renaming `UserCustomToken` to use only `CustomToken`. This is a follow-up of PR #1110.
This PR changes the name of the state from `user_custom_token` to `custom_token`. We can do this change now as this feature is not in production nor on staging nor even deployed anywhere else than on my machine.
> refactor: state custom token

- src/backend/src/lib.rs
- src/backend/tests/it/custom_token.rs
We are renaming `UserCustomToken` to `CustomToken`. This PR follows #1110 and #1111.
Rename exposed update and query functions from `*_user_custom_token_*` to `*_custom_token_*`.
Did files will be updated in a separate PR. Likewise for the frontend. Worth to note that we can do this change as the impacted code is not yet deployed anywhere - i.e. has not been yet proposed on production.
> refactor: rename user_custom to custom

- src/backend/backend.did
- src/backend/src/lib.rs
- src/backend/tests/it/custom_token.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
We are not using `remove_custom_token` function. Given that the changes are not yet live nor deployed anywhere, it's a good time to remove it instead of building tech depth.
> feat: delete remove custom token

- src/frontend/src/lib/services/analytics.services.ts
When pages are accessed directly - e.g. oisy.com/transactions... - it seems that the canister cannot resolve the route if the url contains a `./` instead of `/` as the default path to load the worker.
> fix: init analytics on sub-pages direct access

- package-lock.json
- package.json
`withdrawErc20` was merged in ic-js main.
> build: bump cketh js

- src/frontend/src/env/networks.cketh.env.ts
- src/frontend/src/icp-eth/services/eth.services.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
The signatures are similar on homestead and sepolia.
We still keep those hardcoded values as environments values rather than in constants.
> feat: revert cketh signatures

- src/frontend/src/env/networks.cketh.env.ts
- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/components/send/ConvertToCkERC20.svelte
- src/frontend/src/eth/components/send/ConvertToCkETH.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendNetwork.svelte
- src/frontend/src/eth/components/send/SendNetworkICP.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/services/send.services.ts
- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/components/send/ConvertETH.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
- src/frontend/src/icp-eth/utils/cketh.utils.ts
- src/frontend/src/icp/components/convert/ConvertToEthereum.svelte
- src/frontend/src/icp/components/convert/HowToConvertEthereumModal.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
Temporary workaround to resolve the address as long as the `minterInfo` breaking changes have not been executed on mainnet.
> feat: hardcode ckEth mainnet helper contract address

- .github/workflows/backend-tests.yml
Microsoft has issue so downgrade ubuntu at least for now.
Our pipeline issue: https://github.com/dfinity/oisy-wallet/actions/runs/8816195026/job/24199782484?pr=1150
Thread: https://github.com/orgs/community/discussions/120966
> build: run backend tests on ubuntu 20.04

- Cargo.lock
- src/backend/Cargo.toml
Update the `ic-stable-structures` crate to inherit the fix a memory leak in the `BTreeMap`.
See release notes: https://github.com/dfinity/stable-structures/releases/tag/v0.6.4
> build: upgrade stable structures to embed fix for memory leak

- src/backend/backend.did
- src/backend/tests/it/custom_token.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/frontend/src/icp/components/tokens/IcHideTokenModal.svelte
- src/frontend/src/icp/services/ic-custom-tokens.services.ts
- src/frontend/src/icp/services/icrc.services.ts
- src/shared/src/types.rs
We've noticed that many custom ICRC tokens on the IC currently have no indexer or are not using the so-called "Index" canister for such a purpose. While an Index canister is currently mandatory in the Oisy frontend, we cannot rule out that at some point in the future we might decide to make this information optional. This would provide fewer features for those tokens that do not have an index or to handle features differently.
Given that our latest changes are not yet in production, I think it's the right moment to change how we handle the Index canister information in the backend—i.e., to make it optional instead of mandatory. This approach will make us less prone to potential migration if we ever decide to take such action as described above.
- Make `index_id` in `IcrcToken` optional
- …
> feat(backend): optional index canister id

- src/frontend/src/eth/constants/ckerc20.constants.ts
The contract was "moved". See https://forum.dfinity.org/t/cketh-a-canister-issued-ether-twin-token-on-the-ic/22819/165?u=peterparker
> docs: update link to contract

- scripts/build.csp.mjs
- scripts/build.metadata.mjs
- scripts/did.delete.types.mjs
- scripts/did.update.types.mjs
- vite.utils.ts
Nodejs refers to UTF-8 as `utf8` rather than `utf-8`.  The list of nodejs encodings is [here](https://github.com/nodejs/node/blob/main/lib/buffer.js#L615).
De-facto this has no effect as `utf-8` is supported as an alternative: https://github.com/nodejs/node/blob/main/lib/buffer.js#L717 
Meh, probably not worth changing.
- For `readFile` and `writeFile` use `utf8` rather than `utf-8`.
Existing tests should suffice.
> fix: Nodejs uses utf8 not utf-8

- src/frontend/src/eth/components/fee/FeeDisplay.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectReview.svelte
While reviewing #1294 I noticed existing issue where `clearInterval` are used on destroy to clean potential on going timeout.
- replace `clearInterval` with `clearTimeout`.
> fix: clearTimeout instead of clearInterval

- scripts/send.tokens.sh
The `PRINCIPAL` variable of the script `send.tokens.sh` was hard-coded. To facilitate local development testing, it now accepts the principal as input.
Changed the script to either accept it as variable during command or to have it as user input:
```sh
$ ./script.sh renlj-oxj5e-cma2d-yzt2e-tb5s5-wm7wi-xaytr-kxa43-2ehrp-xzkik-zae
(variant { Ok = 12 : nat })
(variant { Ok = 120 : nat })
(variant { Ok = 11 : nat })
$ ./script.sh
Enter the PRINCIPAL: renlj-oxj5e-cma2d-yzt2e-tb5s5-wm7wi-xaytr-kxa43-2ehrp-xzkik-zae
(variant { Ok = 12 : nat })
(variant { Ok = 120 : nat })
(variant { Ok = 11 : nat })
```
Successful manual testing for both input types on local development deployment.
> refactor: changed send.tokens script to accept the principal as input

- src/frontend/src/icp/components/tokens/IcManageTokens.svelte
Remove list of custom tokens bottom margin as requested by Artem.
Before:
After:
> style: remove list of custom tokens bottom margin

- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/providers/infura-cketh.providers.ts
- src/frontend/src/eth/providers/infura-erc20-icp.providers.ts
- src/frontend/src/eth/providers/infura-erc20.providers.ts
- src/frontend/src/eth/services/fee.services.ts
- src/frontend/src/eth/types/contracts-providers.ts
Estimating the gas for USDC transactions has consistently failed, whereas it has always worked for other ERC-20 contracts. According to Ben and [Stackoverflow](https://stackoverflow.com/a/78481144/5404186) the root cause of the issue is the missing from address, which appears to be unprovidable using ethers.js. However, today I discovered that the library has a somewhat hidden option called [overrides](https://docs.ethers.org/v5/api/contract/contract/#Contract--readonly) which allows developers to override parameters when calling an ABI. By using it, we can provide the from address for contracts like USDC, which do not default to the zero address.
- extends interface `GetFeeData` with the `from` address
- rename `GetFeeData` param `address` to `to` in order to distingish it
- implement …
> fix: estimateGas for Usdc

- src/frontend/src/lib/components/common/MaxButton.svelte
Whenever the Send form was triggered with a `keydown` event (consequentially triggering the `submit` event), the MaxButton was triggered too, overwriting the current amount in the Input component.
Change the type of button of MaxButton component to be non-submit.
Manual testing in local development deployment.
> fix: classified MaxButton as non-submit button type to prevent being triggered on keydown

- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/services/fee.services.ts
- src/frontend/src/eth/utils/send.utils.ts
So this morning I was looking to transfer some ERC20 transactions for PR [1294](https://github.com/dfinity/oisy-wallet/pull/1294#discussion_r1602609249) but, none of my transactions were successful. Root cause of the problem was the gas fee being entirely consumed.
A few weeks ago the cross-chain team recommended us to add a 10% to the fee as buffer, so I tried to implement this solution but, even with this amount it falled close enough.
That's why this PR adds 25% to the calculation of the ERC20 fees.
- in `getErc20FeeData` adds a 25% to the fee result
Example of transaction that ended in error without enough gas:
https://sepolia.etherscan.io/tx/0x5b76eedfb25b6a11ad72a2b882ac624eec612c38fc57eb676fdc1e510b4429ba
https://sepolia.etherscan.io/tx/0x2dc1183471247604cf979d46d773ce21343c2db82ec1 …
> feat: add 25% to amount to calculate fee

- src/frontend/src/eth/components/fee/FeeDisplay.svelte
- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/lib/components/send/SendInputAmount.svelte
- src/frontend/src/lib/types/send.ts
- src/frontend/src/lib/utils/token.utils.ts
- src/frontend/src/tests/lib/utils/token.utils.spec.ts
Components `SendAmount` should use the generic component `SendInputAmount` that provides the Max button optionality.
- Refactored component and its parents and peers to use the bound `fee` variable.
- Modified the validation function to return an `Error` object or `undefined`.
- Created a `calculateMax` function for each component, using function `getMaxTransactionAmount` from `token.utils.ts` file.
- Created test for `functiongetMaxTransactionAmount`.
Manual test in the local development web-interface to confirm the correct behavior. Unittest for `functiongetMaxTransactionAmount`.
> refactor: modified ETH Amount Input component to use SendInputAmount generic component

- src/frontend/src/icp/components/transactions/IcTransactionModal.svelte
From and to information of an IC transaction can be principals or account identifiers; therefore, the field that displays the information in the transaction modal should not be capitalized.
- remove `capitalize` in related fields
Before:
After:
> style: do not capitalize from and to

- .github/workflows/update-sns-tokens.yml
- package.json
- scripts/build.tokens.sns.mjs
We might/will add some more weekly jobs to build list of tokens automatically (for example PR #1314), that's why this PR rename `build.sns.tokens.mjs` and to `build.tokens.sns.mjs`. Just a bit more handy to retrieve those jobs in the project if they are all indexed with the same prefix `build.tokens`.
Unrelated to PR, I added the header `#!/usr/bin/env node` to the script that way it can also be run without referencing node. in a terminal.
- rename script
- update reference to script
> refactor: build.sns.tokens module name to build.tokens.sns

- src/frontend/src/lib/components/send/SendInputAmount.svelte
The `SendInputAmount.spec.ts` has types error because the property `error` was mandatory. I could have resolve the input in the test but, I actually think it was a better idea to set a default `undefined` value for the property within the component `SendInputAmount`.
> feat: input error property undefined default value

- src/frontend/src/eth/components/fee/FeeDisplay.svelte
- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/stores/fee.store.ts
Instead of imperatively evaluating the maximum and minimum gas fees and passing around a fee property, we can derive these values within the Ethereum fee context.
This PR resolves a TODO created in PR #1294.
- derive `minGasFee` and `maxGasFee` in `FeeContext`
- use those values instead of imperative calls
- resolve and remove TODO by removing property `fee`
> feat: derive min and max gas fee

- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/eth/components/send/SendDestination.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/stores/fee.store.ts
- src/frontend/src/lib/components/send/SendInputAmount.svelte
- src/frontend/src/lib/components/send/SendInputDestination.svelte
The "Max" feature is available when fees are set. In its current implementation, clicking "Max" modifies the "amount," which triggers a reevaluation of the fee. This can potentially result in a different fee being calculated.
In other words, the amount is calculated based on a fee that may change after the calculation, making the amount incorrect.
- Add a function to reevaluate the fee in FeeContext.
- Expose an imperative feature in the fee component to trigger the fee calculation.
- Bind the reevaluate function with the effective calculation.
- Update the fee on mount and only when the user inputs (amount and destination) are manually updated by the user.
- Debounce fee calculation to ensure it is called as few times as possible.
> fix: call to fee evaluation on max race condition

- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/lib/components/send/SendInputAmount.svelte
- src/frontend/src/tests/components/send/SendInputAmount.spec.ts
Similar to Metamask, if "Max" is used to evaluate the amount to send and the user does not modify the amount, then if the fees change, the amount should be reevaluated.
- add a state `amountSetToMax` to `SendInputAmount` to keep track of usage of "Max" button
- expose a function to trigger the evaluation of the amount within the component
- reevalute the amount on fees change
> feat: reevaluate max when fees are changing

- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/lib/utils/token.utils.ts
- src/frontend/src/tests/lib/utils/token.utils.spec.ts
Changing the check getMaxTransactionAmount to consider the tokenStandard instead of using defined functions. 
Function getMaxTransactionAmount will now take tokenStandard as input parameter.
Changed test `token.utils.spec.ts` to consider all possible non-ERC20 values.
> fix: using tokenStandard in calculation for max amount

- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/lib/components/common/MaxButton.svelte
- src/frontend/src/lib/components/send/SendInputAmount.svelte
- src/frontend/src/tests/components/send/SendInputAmount.spec.ts
Fees are not instantly calculated, but the "Max" button is instantly available. This can lead to a UI race condition where the user clicks on the "Max" button early, which calculates the maximum amount without considering the fees. Milliseconds later, an error will inform the user that the balance is insufficient to cover the amount because the fees are ultimately estimated.
- `MaxButton` always displayed in send amount input but disabled if no function is provided
- Provide `calculateMax` only if fees are loaded
> fix: early click on max UI race condition

- .prettierignore
- package-lock.json
- package.json
- scripts/build.tokens.ckerc20.mjs
- src/frontend/src/env/tokens.ckerc20.json
Similar to SNSes, we aim to set up a weekly job that collects the ckERC20 tokens that exist on mainnet for staging and production.
This PR provides a script that queries the ckETH orchestrator to retrieve the list of tokens with their corresponding IC ledger and index canisters.
- Update `@dfinity/cketh@next`, which contains an update to introduce the ckETH orchestrator canister (see ic-js PR [632](https://github.com/dfinity/ic-js/pull/632)).
- Create a new script that queries the orchestrator and generates a JSON file.
The script contains a check that asserts that token symbols are provided only once per environment. This allows us to prefix the information per token as we are still going to integrate that information manually within our codebase.
> feat: script to retrieve the current list of ckErc20

- src/frontend/src/eth/components/send/SendAmount.svelte
Webstorm has issue intepreting an `isNullish` and displays a positive negative error regarding a lint issue. So here's just a pragmatic PR.
- use a nullish coalish to make editor linter happy
> chore: lint nullish

- src/frontend/src/icp/derived/icrc.derived.ts
The ckSepoliaUSDC is currently displayed even if user does not select the "testnet" flag. This is incorrect.
This bug exists in production.
- list ckSepoliaUSDC only if derived testnet store is selected
> fix: ckSepoliaUSDC display

- src/frontend/src/lib/styles/global/gix.scss
Toast content overflow in case of error does not work as expected. Gix-cmp relies on a CSS variable that is not set in Oisy and therefore no maximal height is set.
Issue in prod:
> fix: style overflow toast error

- src/frontend/src/eth/components/send/SendAmount.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
The usage of `nativeEthereumToken` to get the balance of the ETH/SepoliaETH token was incorrectly replaced in #1294 which leads any USDC transform form to become invalide as the balance of the ERC20 token is used instead.
- revert usage of `nativeEthereumToken` to access ETH/SepoliaETH balance
> fix: ERC20 fee validation (revert usage of nativeEthereumToken)

- src/frontend/src/lib/derived/exchange.derived.ts
- src/frontend/src/lib/services/exchange.services.ts
ckUSDC dollar exchange is not display on production because coingecko does not use the same character case as the one we pass for the query.
- `toLowerCase` address for comparison
> fix: resolve USDC dollar exchange value

- src/frontend/src/env/networks.ircrc.env.ts
- src/frontend/src/icp-eth/services/eth.services.ts
- src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts
- src/frontend/src/icp/components/fee/CkErc20TokenFee.svelte
- src/frontend/src/icp/components/fee/IcTokenFee.svelte
- src/frontend/src/icp/components/send/IcFeeDisplay.svelte
- src/frontend/src/icp/types/ck-listener.ts
- src/frontend/src/icp/types/ic.ts
Turns out, the fees to convert ckErc20 to Erc20 have to be paid in ckEth.
- rename type `IcCkTwinToken` to add more information such as the ledger canister id to use for the ck fee within the same type
- configure USDC ck token to specifiy such canister ID
- duplicate / copy component to display the IC to a new type dedicated to ckErc20
- display either ckErc20 or ckEth fees for ckErc20
Is:
Fix:
> feat: display ckErc20 fees in ckEth

- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
- src/frontend/src/icp/components/send/IcFeeDisplay.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/stores/ethereum-fee.store.ts
We will need the Ethereum `maxTransactionFee` estimation, currently only used  for display purpose, in the validation of the user amount. Therefore this PR introduces a new fee context for Ethereum and refactor the code logic to calculate those fees from the display component to the context.
No logic changes. Load and derivation has been moved.
- New context and store (similar to BitcoinContextFee)
- New context component
- Move logic from display to context component
- Used store for display purpose
- Init fee store context in `IcSendModal`
> feat: ethereum fee context for ckEth

- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
The estimated fee for a converstion ckErc20 -> Erc20 should be display with the ckEth symbol instead of ETH.
> feat: ckErc20 estimated fee symbol ckEth instead of Eth

- src/frontend/src/env/networks.ircrc.env.ts
- src/frontend/src/icp-eth/services/eth.services.ts
- src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts
- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/types/ck-listener.ts
- src/frontend/src/icp/types/ic.ts
Turns out we still need parts of #1334 because on the "Convert ckUSDC -> USDC" modal we need to display the estimated fee with symbol ckSepoliaETH or ckETH, not the first symbol we find.
- add a `feeLedgerCanisterId` to the environment, that way in ckErc20 we can find the ckEth ledger and from there the token
> feat: display either ckEth or ckSepoliaEth on convert ckUsdc or ckSepoliaUsdc

- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/stores/ethereum-fee.store.ts
In #1333 we will need the `tokenCkEth` in more components so, instead of duplicating the code, given that it's related to the fees, we can add it to the ethereum fee context. That way we reduce the number of times we have to iterate on the icrc tokens.
> feat: add tokenCkEth to Ethereum fee store

- src/frontend/src/lib/components/send/SendInputAmount.svelte
- src/frontend/src/tests/components/send/SendInputAmount.spec.ts
In #1333 we need to update the validation of the amount if the Ethereum estimated fees are updated. This is really specific to ckErc20 and IC, so I added an imperative call to debounce the validation within the amount field.
- Expose a component function to trigger the validation
> feat: trigger validation imperatively

- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/derived/ethereum-fee.derived.ts
- src/frontend/src/icp/stores/ethereum-fee.store.ts
The token ckEth used to display and validate the fee for converting ckErc20 can actually be derived globally, therefore it's cleaner to implement it that way rather than in a context.
- Implement globally derived store instead of holding the value in a writable context.
> feat: clean up tokenCkEth by deriving it globally

- src/frontend/src/tests/lib/components/send/SendInputAmount.spec.ts
This simple refactoring is just to keep the tests well organized and in the correct places.
Moved the path `src/frontend/src/tests/components` to `src/frontend/src/tests/lib/components`
> refactor: moved the components test folder inside the lib test folder

- src/frontend/src/icp/services/ic-send.services.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
Referring to review of PR #1339 , we changed the word **_address_** to **_destination_** to be more generic for the scope of Oisy.
> chore: changed 'address' to 'destination' in i18n error text

- rust-toolchain.toml
The team has identified an issue in Rust v1.78 with CI jobs that started failing after the upgrade.
The root cause of the issue appears to be linked to the wasm-bindgen issue documented here: https://github.com/rustwasm/wasm-bindgen/issues/3801. Although this issue is fixed, it has not been patched in Rust 1.78 (more information can be found on Slack in #dev channel).
I believe that Oisy might not be impacted since the backend canister was updated a few weeks ago without any reported errors. Nevertheless, it is probably safer to downgrade the Rust version.
I am using v1.75 in Juno, which is why I suggest downgrading to this particular version.
- downgrade rust toolchain from 1.78 to 1.75
> fix: downgrade Rust 1.78 to 1.75

- vite.config.ts
- vite.utils.ts
- vitest.config.ts
There is a ENV variable error, when trying to run some test using the token stores, for example when:
```typescript
import { ICP_TOKEN, SEPOLIA_TOKEN } from '$env/tokens.env';
import { tokens } from '$lib/derived/tokens.derived';
```
In `vitest.config.ts`, we will use the same `VITE_APP_VERSION` and `VITE_DFX_NETWORK` as defined in `vite.config.ts` (for example that we take it from package.json for the version).
> test: created env variables useful for running tests with token stores

- src/frontend/src/eth/components/send/SendTokenModal.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/components/tokens/AddTokenModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSignModal.svelte
- src/frontend/src/eth/constants/steps.constants.ts
- src/frontend/src/eth/services/send.services.ts
- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/eth/types/send.ts
- src/frontend/src/icp/components/convert/HowToConvertEthereumModal.svelte
- src/frontend/src/icp/components/receive/IcReceiveBitcoin.svelte
- src/frontend/src/icp/components/receive/IcReceiveBitcoinProgress.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/components/send/IcSendProgress.svelte
- src/frontend/src/icp/components/tokens/IcManageTokensModal.svelte
- src/frontend/src/icp/services/ck.services.ts
- src/frontend/src/icp/services/ckbtc.services.ts
- src/frontend/src/icp/services/ic-custom-tokens.services.ts
- src/frontend/src/icp/services/ic-send.services.ts
- src/frontend/src/icp/types/ckbtc.ts
- src/frontend/src/icp/types/ic-send.ts
- src/frontend/src/lib/components/core/Loader.svelte
- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/components/ui/InProgressWizard.svelte
- src/frontend/src/lib/constants/steps.constants.ts
- src/frontend/src/lib/enums/progress-steps.ts
Relates to #1350. There are two types of "steps" in Oisy. The "steps" of the wizard modal (this screen, then this screen, then this screen) and the "steps" of the progress component when actions are effectively executed (signing a transaction before transferring it).
Renaming the enums which are currently used for the latests hopefuly makes their usage a bit more clear.
> refactor: steps to progress-steps

- src/frontend/src/eth/components/send/SendTokenModal.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/config/send.config.ts
- src/frontend/src/icp/components/convert/HowToConvertEthereumModal.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/lib/enums/progress-steps.ts
- src/frontend/src/lib/enums/wizard-steps.ts
The Wizard steps for the send flow were hard-coded strings in the code. We want them to be enums as to be better controlled and compared.
There is no clear advantage in creating different sets of enums for ETH and for IC, since the Wizard steps are in the end customized for each case at modal-level, but are based on the same basic flow.
- Adding enums referring to the Wizard steps of the send flow.
- Adapt the send scripts to use such enums.
All the hard-coded Wizard steps should be transformed as enum. We will work on it in another PR.
> refactor: created enums for the wizard steps related to send flow

- src/frontend/src/lib/types/qr-code.ts
- src/frontend/src/lib/utils/qr-code.utils.ts
- src/frontend/src/tests/lib/utils/qr-code.utils.spec.ts
- src/frontend/src/tests/mocks/qr-generator.mock.ts
To improve the range of URNs that can be decoded, first of all, we created a custom `decodeUrn` function that takes into consideration the schema and the possible cases of the currently onboarded tokens:
- [IC & ICRC](https://github.com/dfinity/ICRC/issues/22)
- [ETH and ERC20](https://eips.ethereum.org/EIPS/eip-681)
- [BTC](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki)
To be noted that, for the ERC20 tokens, the process is not the same as the ICRC tokens: ERC20 tokens provide their respective contract address as additional URN parameter. That means that even if the prefix is `ethereum`, to find out the correct token, we need to loop among the ERC20 token addresses.
- Created new function `decodeUrn` that receives as input a generic URN and returns it deconstructed into …
> feat: created URN decoder function to treat generic URN cases

- src/frontend/src/tests/mocks/tokens.mock.ts
With PR #1344 , we removed the necessity to create mock tokens, and we started using the concrete list from the token store that is depending on the test environment.
At some point, for the complete test on all the possible tokens that could be available, we will need to create a thorough list of tokens, independently of the environment it is running the test.
For example, if it is running locally, it will test only the Sepolia ETH according to the snippets below:
```typescript
// tokens.derived.ts
export const enabledEthereumTokens: Readable<RequiredToken[]> = derived(
[testnets],
([$testnets]) => [
...(ETH_MAINNET_ENABLED ? [ETHEREUM_TOKEN] : []),
...($testnets ? [SEPOLIA_TOKEN] : [])
]
);
// networks.eth.env.ts
export const ETH_MAINNET_ENABLED = …
```
> chore: removed unused token.mocks file that became useless with PR #1344

- src/frontend/src/eth/utils/qr-code.utils.ts
- src/frontend/src/icp/utils/qr-code.utils.ts
- src/frontend/src/lib/components/send/QRCodeScan.svelte
- src/frontend/src/lib/utils/qr-code.utils.ts
- src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts
- src/frontend/src/tests/icp/utils/qr-code.utils.spec.ts
- src/frontend/src/tests/lib/utils/qr-code.utils.spec.ts
Since we are going to use different decoders to deconstruct the QR code URN, we are going to create separate functions for each universe.
Moved `decodeQrCode` function in two different utils modules.
Created a set of tests for each new function.
> refactor: created two different functions for ICP and for ETH to decode the QR code

- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/config/ic-send.config.ts
We moved the Wizard Steps for IC in a separate config files, to be centralized and consistent with the ETH. This will be helpful when we will have to add the QR Code scan step.
Furthermore, it is a first step for when we will want to further refactor and unify the Wizard Steps for all the universes, avoiding repetition of code.
- Created an IC Send Wizard Step list.
- Changed component `IcSendModal` to use the list.
> refactor: moved IC Wizard Steps in separate file

- src/frontend/src/lib/components/send/SendInputDestination.svelte
We include the `QRButton` component into the common `SendInputDestination`, to be used in the main Send Modals.
- Included `QRButton` in the `inner-end` of the destination input.
- Added a prop function that is triggered by the button.
> feat: add QRButton component in Destination Input

- package-lock.json
- package.json
I released a new version of the gix-cmp so we can use it instead of a next version.
> build: use released gix-cmp

- src/frontend/src/eth/components/send/SendDestination.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendTokenModal.svelte
- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/lib/components/send/QRCodeScan.svelte
To trigger the QR Code scan step, we created specific events `qrCodeScan` and `qrCodeBack`.
- Create event `qrCodeScan` that is dispatched by the QR Code Button.
- Create event `qrCodeBack` that is dispatched by the Cancel button in the QR Code Scan step.
- Assign them to navigate to the appropriate Wizard Step, using new function `goToWizardStep`. 
Manual testing done on local environment.
> feat: added code to trigger the QR Code Scan step on ETH

- src/frontend/src/lib/components/common/QRButton.svelte
The color of the QR Button will be the same as the Max Button.
> style: changed color of QRButton to be the same as MaxButton

- src/frontend/src/eth/utils/qr-code.utils.ts
- src/frontend/src/lib/types/qr-code.ts
- src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts
There was a mistake when choosing what property consider when the QR code refers to ERC-20 tokens. According to [EIP-681](https://eips.ethereum.org/EIPS/eip-681):
> Requesting payments in [ERC-20](https://eips.ethereum.org/EIPS/eip-20) tokens involves a request to call the `transfer` function of the token contract with an `address` and a `uint256` typed parameter, containing the _beneficiary address_ and the _amount in atomic units_, respectively. For example, requesting a Unicorn to address `0x8e23ee67d1332ad560396262c48ffbb01f93d052` looks as follows: `ethereum:0x89205a3a3b2a69de6dbf7f01ed13b2108b2c43e7/transfer?address=0x8e23ee67d1332ad560396262c48ffbb01f93d052&uint256=1`
The function `decodeQrCode` was adapted to get the prop uint256 in case the QR code refers to an ERC20 token, …
> fix: corrected ERC20 amount property, according to EIP-681

- src/frontend/src/icp/components/send/IcSendDestination.svelte
- src/frontend/src/icp/components/send/IcSendForm.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/config/ic-send.config.ts
To trigger the QR Code scan step, we created specific events `icQRCodeScan` and `icQRCodeBack`.
- Create event `icQRCodeScan` that is dispatched by the QR Code Button.
- Create event `icQRCodeBack` that is dispatched by the Cancel button in the QR Code Scan step.
- Assign them to navigate to the appropriate Wizard Step, using new function `goToWizardStep`. 
Manual testing done on local environment.
> feat: added code to trigger the QR Code Scan step on ICP

- src/frontend/src/eth/components/send/SendTokenModal.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/lib/utils/wizard-modal.utils.ts
- src/frontend/src/tests/lib/utils/wizard-modal.utils.spec.ts
To centralize the utils, we moved the merged the functions `goToWizardSendStep` into a single common one, to be used throughout the code.
- Created common `goToWizardSendStep` in utils folder.
- Removed `goToWizardSendStep` from ETH universe and adapted the code.
- Removed `goToWizardSendStep` from ICP universe and adapted the code.
Created small tests for `goToWizardSendStep`.
> refactor: moved function goToWizardStep in common utils

- src/frontend/src/eth/services/eth-listener.services.ts
I noticed an issue in production yesterday, the Ethereum WebSocket listener wasn't working anymore and way throwing an error in the console log. I was able to reproduce it locally and narrow the issue to the fact that we expect receiving only the hash of the transaction while we were actually receiving the all pending transaction (an object).
- Set the WebSocket option to only provides hash.
> fix: ETH transaction listener

- src/frontend/src/lib/utils/qr-code.utils.ts
I spotted an `=== undefined` comparison which I think can be an `isNullish` comparison.
> chore: isNullish comparison

- src/frontend/src/lib/components/send/SendQRCodeScan.svelte
Changed to opacity of the QR Code Scan background to **60%** (value agreed with @artkorotkikh-dfinity) and using the theme color.
> style: changed the background of QRCodeScan to have more opacity

- src/frontend/src/lib/components/tokens/Tokens.svelte
- src/frontend/src/lib/utils/nav.utils.ts
When creating the token URL, the network was given as prop. 
```typescript
const tokenUrl = ({
token: { name },
networkId,
path
}: {
token: Token;
networkId: NetworkId;
path: '/transactions/' | '/';
}): string => [...]
```
However, the `Token` object has the `network` property, and it would be better to use directly that prop, to avoid inconsistencies.
- Removed `networkId` from function `tokenUrl`.
- Adapted the usage of such function throughout the code:
- function `transactionsUrl`
- component `Tokens`
Behavior unchanged during manual testing in local development env, on each network.
> refactor: change function tokenUrl to use the token network instead of a prop

- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/lib/constants/analytics.contants.ts
We have an anonymous "track events" analytics metric for the conversion of ckETH to ETH, but not for ERC20. While we can identify the two according to their token symbols collected as anonymous metadata, it would be interesting to distinguish the two, as both conversions require different calls.
- Add success and error events for ckErc20 to Erc20
> feat: ckErc20 to Erc20 anonymous analytics track events

- playwright.config.ts
To develop Playwright test locally, it's interesting to resuse the same dev server as `npm run dev` and also to run the tests not in an headless mode.
- Update `playwright.config` to use dev server and no headless in development.
> chore: playwright adjustements for dev

- vitest.config.ts
Vitest are failing currently because it includes the E2E test.
- Include only tests under `src` for vitest.
> chore: vitest include src path for tests only

- src/frontend/src/env/networks.env.ts
- src/frontend/src/lib/derived/network.derived.ts
- src/frontend/src/lib/derived/networks.derived.ts
- src/frontend/src/lib/utils/network.utils.ts
For the single-page view, we create the network **Chain Fusion** that allows the user to select all the available _mainnet_ networks at once. We refactor the derived store `networkTokens` to filter for the `network.env` prop of the tokens (instead of the `network.id`) when the selected network is Chain Fusion.
- Created Chain Fusion mainnet network.
- Moved derived store `selectedNetwork` higher to be re-used.
- Included filter by environment in derived store `networkTokens`.
- Included Chain Fusion Networks among the selectable networks.
Manual test in local replica.
> feat: chain fusion/create networks

- src/frontend/src/eth/components/receive/Receive.svelte
We have extracted a common `ReceiveButton` in #1415 so we can use it as well for ETH.
- Use component. This will help us reduce code with the upcoming required styling (future PRs).
> feat: use receive button in eth receive

- src/frontend/src/lib/derived/tokens.derived.ts
Since we will have a single-view with the list of all tokens of all networks, as part of the requirements, the Ethereum native tokens will be put before the list of ICRC tokens, but after ICP.
Changed order of store `tokens`.
> refactor: re-ordered store tokens to show Ethereum native tokens before ICRC tokens

- src/frontend/src/eth/components/receive/Receive.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkBTC.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
- src/frontend/src/icp/components/receive/IcReceiveICP.svelte
- src/frontend/src/icp/components/receive/IcReceiveIcrc.svelte
- src/frontend/src/lib/stores/modal.store.ts
By adding multiple calls to action to open modals, we will end up with multiple listeners and potentially multiple modals opened at once if we don't prevent it. One way to address this would have been to move all modals to the root, but that’s quite a change, and I like that the modals are scoped next to their calls to action. It's also useful to be able to use context. That's why this PR introduces a local ID, which can be used to ensure that the modal that needs to open is the one triggered next to the button.
- Use `symbol` to identify receive modal.
> feat: unique receive modals

- src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
Now that we use a token as property for the "Receive" modal, we should also derive the twin token from it and not used the global derived `$ckEthereumTwinToken`.
> feat: derive twinToken for ckEth Receive modal

- src/frontend/src/lib/components/core/Back.svelte
- src/frontend/src/lib/utils/nav.utils.ts
The "Back to Wallet" button in each `transaction` page was using the networkId defined by default in the current URL.
For example, if we are in `(app)/transactions/?token=ICP&network=ICP`, it would have returned to `(app)/?network=ICP`.
However that is an incorrect behavior when we deal with Chain Fusion, since the URL network parameter does not match Chain Fusion.
For example:
1) We are in `(app)/?network=ChainFusion`
2) We click on the ICP token that redirects to `(app)/transactions/?token=ICP&network=ICP`
3) We click on "Back to Wallet"
4) We are redirected to `(app)/?network=ICP`, **that is not what we would expect**.
- Change function `back` in `nav.utils.ts` to have an optional parameter `fromUrl` that, if it is defined, takes priority over `networkId`.
- Change `Back` component to …
> fix: changed back function to use the previous route if defined

- src/frontend/src/lib/components/core/Back.svelte
- src/frontend/src/lib/components/networks/Network.svelte
- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/utils/nav.utils.ts
We noticed in PR #1425, that function `back` had the param `pop` that was actually alway `true`, except when passed the param `fromUrl`. To simplify, we removed such parameter and adapted the function logic.
- Changed params and logic of function `back`.
- Adapted usage of such function.
Behavior remains unchanged in manual tests in local replica.
> chore: removed unused param  from util back

- src/frontend/src/eth/components/send/SendReviewNetwork.svelte
- src/frontend/src/icp/components/send/IcReviewNetwork.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte
- src/frontend/src/icp/components/tokens/IcManageTokens.svelte
- src/frontend/src/icp/components/tokens/IcTokenModal.svelte
- src/frontend/src/lib/components/hero/Hero.svelte
- src/frontend/src/lib/components/tokens/HideTokenReview.svelte
- src/frontend/src/lib/components/tokens/Token.svelte
- src/frontend/src/lib/components/tokens/TokenLogo.svelte
It is better to use `i18n` when giving the `alt` string to `Logo` components.
Changed all uses of snippet ``alt=`{...} logo` `` to use `i18n.core.alt.logo`.
> chore: use i18n for alt string of logos

- src/frontend/src/btc/derived/networks.derived.ts
- src/frontend/src/lib/derived/networks.derived.ts
Preparing for the BTC onboarding, we created a list of Bitcoin networks to add to the `networks` derived store.
- Create store of native BTC networks: mainnet and testnet.
- Include Bitcoin networks derived in the main `network` store.
> feat: include list of BTC networks in derived 'networks'

- src/frontend/src/env/networks.env.ts
- src/frontend/src/eth/components/tokens/AddTokenReview.svelte
- src/frontend/src/eth/components/transactions/TransactionStatus.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/lib/components/hero/Hero.svelte
- src/frontend/src/lib/components/networks/Network.svelte
- src/frontend/src/lib/components/networks/NetworkButton.svelte
- src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/derived/network.derived.ts
- src/frontend/src/lib/derived/networks.derived.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/lib/utils/nav.utils.ts
- src/frontend/src/lib/utils/network.utils.ts
The term "Chain Fusion" is not a network but a marketing term. Introducing it into the code base as a networks.env environment is prone to errors.
Firstly, each token is linked to a network, which could lead to a situation where a token is associated with a marketing term instead of an actual network. Secondly, networks are used to load various data (e.g., minter information) or create providers for effective interaction with their corresponding networks (e.g., Etherscan provider). Therefore, treating "Chain Fusion" as a network is potentially problematic and should be avoided.
Instead, we should consider "Chain Fusion" as a filter. When no specific network is selected, all networks should be displayed.
The PR introduces a few changes, but there was no clear path for "CHAIN_FUSION" to be …
> feat: remove Chain Fusion network

- src/frontend/src/lib/assets/chain_fusion.svg
- src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
We introduce the Chain Fusion logo in its first version.
- Add Chain Fusion logo as SVG.
- Include the logo in the `NetworksSwitcher` component.
> style: include Chain Fusion logo

- src/frontend/src/lib/stores/token.store.ts
See comment in code of the PR.
- Deprecate token store.
- Add a function `reset()` to the store (for consistency reason).
> feat: reset and deprecate token store

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte
- src/frontend/src/lib/utils/format.utils.ts
On one hand we have now less space to display balances, on the other, if you've got lots of money, numbers are hard to read anyway with some much zero in the dollars 😉.
So, let's display the balance in dollars in a compact way.
> feat: display exchange currency compact

- src/frontend/src/lib/components/hero/Hero.svelte
Due to the network changes we did, the background of the hero pane wasn't dynamic anymore. This PR fixes this issue and also set a grandient color for chain fusion defined by Artem.
> fix: hero background and chain fusion gradient

- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
Did a first test with WalletConnect and already spotted a first issue with our refactoring of the network and token. The incorrect destination was displayed (UI display error "only").
- Use token network as fallback to fix the display issue.
Issue: 
Fix:
> fix: wallet connect send network

- src/frontend/src/icp/components/send/IcSendAmount.svelte
- src/frontend/src/icp/components/transactions/IcTransactionsCkBTCListeners.svelte
I spotted two cast that wrongly assumed that the `$token` was defined which isn't true anymore.
> fix: undefined token

- .eslintrc.cjs
- scripts/build.copy-workers.mjs
- scripts/build.metadata.mjs
- scripts/did.update.types.mjs
- tsconfig.eslint.json
We want to include scripts in the ESLint to check code style. However, we exclude them from the **no-console** rule, since it is useful to have console feedbacks in their case.
It raised the following problems:
```shell
/Users/antonio.ventilii/projects/oisy-wallet/scripts/build.copy-workers.mjs
9:20  warning  'destination' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
/Users/antonio.ventilii/projects/oisy-wallet/scripts/build.metadata.mjs
34:19  error  Unnecessary escape character: \/  no-useless-escape
34:21  error  Unnecessary escape character: \/  no-useless-escape
34:27  error  Unnecessary escape character: \.  no-useless-escape
46:19  error  Unnecessary escape character: \/  no-useless-escape
46:21  error  Unnecessary escape …
```
> lint: include scripts in the ESLint configs

- .eslintrc.cjs
- src/frontend/src/icp/schedulers/wallet.scheduler.ts
- src/frontend/src/lib/services/worker.exchange.services.ts
- src/frontend/src/lib/utils/error.utils.ts
We introduce two new rules:
1. `no-continue` as warn ([source](https://eslint.org/docs/latest/rules/no-continue))
2. `@typescript-eslint/no-unnecessary-type-assertion` as error ([source](https://typescript-eslint.io/rules/no-unnecessary-type-assertion/))
It raised the following problems:
```shell
/Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/icp/schedulers/wallet.scheduler.ts
140:14  error  This assertion is unnecessary since it does not change the type of the expression  @typescript-eslint/no-unnecessary-type-assertion
/Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/lib/services/worker.exchange.services.ts
36:17  error  This assertion is unnecessary since it does not change the type of the expression  @typescript-eslint/no-unnecessary-type-assertion
71:11 …
```
> lint: include rules no-continue and no-unnecessary-type-assertion

- scripts/did.update.types.mjs
> npm run lint
>
> /Users/daviddalbusco/projects/dfinity/oisy-wallet/scripts/did.update.types.mjs
>  10:16  error  Promise executor functions should not be async  no-async-promise-executor
>
>✖ 1 problem (1 error, 0 warnings)
> chore: fix script lint

- .eslintrc.cjs
We want to include the ESLint rule `no-delete-var` ([doc](https://eslint.org/docs/latest/rules/no-delete-var))
> lint: include rule no-delete-var

- src/frontend/src/icp-eth/components/tokens/IcManageTokens.svelte
To start generalizing its usage, we change the way that tokens are indexed in IcManageTokens component. Before they were using property `ledgerCanisterId`, that is unique for token of type `IcrcCustomToken`. However, we would prefer to use it for the more generic type that could be `Token` or a close child.
Changed indexing of modifiedTokens variable to use token ID and network ID, which combination is considered unique for any token in our list throughout the code.
> refactor: changed indexing in component IcManageTokens

- src/frontend/src/icp-eth/components/tokens/IcManageTokenToggle.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
Previous label was saying:
"Hide zero balances"
and now 
"Show or hide token"
> chore: change aria label of IcManageTokenToggle

- src/frontend/src/lib/components/tokens/ManageTokenToggle.svelte
- src/frontend/src/lib/types/manage-token.ts
- src/frontend/src/lib/types/token.ts
We will need to have a generic toggle button to use for object Token. However we create the custom type DisplayToken, to facilitate the usage:
`export type DisplayToken = Token & { show?: boolean };`
- Created type `DisplayToken`.
- Create `ManageTokenToggle` that is a copy of `IcManageTokenToggle` but without the specific ICRC features.
> feat: created component ManageTokenToggle to be used for generic token

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/icp/utils/icrc.utils.ts
There was an issue with ICP due to PR #1492 : it was not considered as an ICRC custom token type.
> fix: function isIcrcCustomToken shall include icp standard

- src/frontend/src/eth/components/tokens/ManageTokensMenuButton.svelte
- src/frontend/src/icp/components/tokens/IcManageTokensMenuButton.svelte
- src/frontend/src/lib/components/tokens/TokensMenu.svelte
Somewhere along the past weeks, I removed incorrectly the behavior that would close the Overflow Menu once clicked on it to open a modal.
> fix: now the overflow menu closes after opening a new modal

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
Since there could be tokens with same symbol once we merge into a single list all of them (for example native ICP and Ethereum ICP), we change the key used in the EACH loop to avoid duplicates error.
Changed key of loop to `${token.network.id.description}-${token.id.description}`.
> fix: change index key of loop EACH in ManageTokens

- src/frontend/src/env/networks.env.ts
It will be useful to have separate variables for the string representation of Ethereum networks symbol. Otherwise we would need to use the `.description` prop. Also, for consistency with the other networks.
> refactor: created new variables for symbols of Ethereum networks

- src/frontend/src/eth/components/tokens/AddTokenForm.svelte
- src/frontend/src/eth/components/tokens/AddTokenModal.svelte
Since we would like to use `AddTokenForm` as non-first step of a Wizard modal (for example for the single ManageTokens), it changes to have an optional variable to define if it is the first step of the modal or not.
I think that the default should be that it is not the first step, that is why the variable defaults to `false`.
- Add variable `isFirstWizardStep` that defaults to `false`.
- Change AddTokenModal to use the variable as `true`.
> feat: AddTokenForm can be used as non-first step in a modal now

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
We include the list of all non IC tokens in component `ManageTokens`, respecting the visual order that the user sees in the single-view page (basically the ICRC tokens are last).
Furthermore we provide the ManageTokenToggle to the new tokens (for now disabled).
- Created `allTokens` as merged list of `networkTokens` and `allIcrcTokens`. Note that we remove the duplicates, but IC tokens take priority. 
- Change index of loop EACH for `tokens`: it was giving duplicates indices, since the symbol may be repeated for different tokens on different networks (ICP native vs ICP Ethereum network).
- Use `ManageTokenToggle` for non-IC tokens.
See below a local replica simulation:
> Feature/chain fusion/include network tokens in manage modal

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
Since we disabled all non-ICRC token toggle with PR #1509 , we are safe to turn on the event listener for `ManageTokenToggle`
> feat: we turn on the listener to event icShowOrHideToken for ManageTokenToggle

- .github/workflows/checks.yml
- .github/workflows/frontend-tests.yml
PR #1515 is blocked despite being approved because `may-merge` is required, but no steps have been performed for that particular PR.
On the other hand, I also noticed that checks and linters were not run for changes in the root config file (e.g., vite.config.ts) or JS scripts within the scripts folder.
That's why this PR moves the frontend tests to a particular action that runs only for frontend (similar to what we do for backend) and removes the scope frontend for the checks.
> chore: split CI checks and frontend tests

- src/frontend/src/icp-eth/components/tokens/ManageTokensModal.svelte
We now proceed to merge the flow of adding Erc20 tokens into the general modal `ManageTokensModal`.
- Substituted component `IcAddTokenForm` with component `AddTokenByNetwork` to have the network choice (default to current network, if defined).
- Included use of ERC20 component `AddTokenReview`.
- Create additional variables necessary for the merged flow.
On local replica, adding tokens wroked as expected.
> feat: adapted component ManageTokensModal to be able to treat both IC and Ethereum tokens

- src/frontend/src/eth/components/tokens/AddTokenModal.svelte
- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/icp-eth/components/tokens/ManageTokensModal.svelte
In service `saveErc20Contract`, variable `chainId` can be extracted from param `network` since is of type `EthereumNetwork`.
- Removed param `chainId` from `saveErc20Contract`.
- Adapted usage of function `saveErc20Contract`.
> chore: remove param chainId from saveErc20Contract because is redundant

- src/frontend/src/lib/components/tokens/Tokens.svelte
Related to PR #1520, there is no need anymore to show modal `AddTokenModal`, since it was triggered by `ManageTokensMenuButton`.
Removed condition to show `AddTokenModal`.
> refactor: remove unnecessary modal AddTokenModal from tokens list

- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/stores/modal.store.ts
With PRs #1523 and #1524 , there is no need anymore for modal `add-token`.
Removed `add-token` related functions.
> chore: remove deprecated add-token modal from modal store

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
I noticed an incongruence: we discussed with Artem that if a network is selected, then the tokens that can be managed are only the one related to it.
However the list was always including ICRC tokens too.
We fix it with this PR.
Changed list of allTokens in component ManageTokens to include ICRC tokens only for IC network and Chain Fusion (undefined network).
Test on local replica show correct behavior for each selected network.
> fix: token list in ManageTokens shows ICRC tokens when required

- src/frontend/src/eth/components/tokens/AddTokenForm.svelte
- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte
User needs a way to go back to manage tokens from the add token wizard step when there is no network selected as well.
> feat: back if no network on add token form

- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
Given that we display a message to the user informing they are managing tokens on a particular network, we can also disable the network dropdown in the wizard otherwise user might import a token which ultimately won't directly be displayed on the main screen after being added.
> feat: disable token selector dropdown if network is selected

- src/frontend/src/lib/components/ui/ButtonMenu.svelte
For UX reason, it's better to make the menu button clickable on the all width of the popover.
> feat: button menu actionable on the full width

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
According Figma with should also display the network next to the tokens in the manage modal which makes sense given that "chain fusion" pseudo view is also supported there.
> feat: display network in logo for tokens in manage modal

- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
I inverted the check to disable the "Next" action in add modal.
> fix: disable add token "next" action was inverted

- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
- src/frontend/src/icp-eth/components/tokens/ManageTokensModal.svelte
- src/frontend/src/icp-eth/types/add-token.ts
- src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte
- src/frontend/src/icp/services/ic-add-custom-tokens.service.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/lib/utils/input.utils.ts
- src/frontend/src/lib/utils/ts.utils.ts
In `AddTokenByNetwork` we are setting only the relevant values when they are set. Those values are then destructed in the manage modal to assign contract address and edger/index canister ids.
Currently we assumed those values were always string defined but, becaure of this assignation those information were potentially undefined.
This PR improves types and adds few guards that throws an error if the information are undefined which can mostly happens in case of race condition.
> feat: contract address and ledger/index canister ids are potentially undefined

- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
If we do not init the values on mount, then the user might loose their entry if they go next with the wizard but, the validation detects and error and send back the user to previous step.
> feat: init input values in add token by network

- package-lock.json
- package.json
Resolve `npm audit` while still using Etherjs v5 (which we aim to bump once we got automatic tests).
> chore: pin ws at least v7.5.10

- src/frontend/src/eth/components/tokens/AddTokenReview.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
This should not happens given the flow but, potentially the token address can be undefined.
> feat: the contract address is per definition potentially undefined

- src/frontend/src/eth/components/tokens/AddTokenReview.svelte
- src/frontend/src/icp-eth/components/tokens/ManageTokensModal.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
Importing erc20 token currently fails at the validation step because it does not use the selected network.
> fix: use selected network to import erc20 custom token

- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
We do not list testnets token on "Chain Fusion" therefore when user is adding a custom token, testnet network should not be available in the dropdown.
> feat: no testnet in dropdown for chain fusion

- src/frontend/src/eth/components/transactions/TransactionStatus.svelte
- src/frontend/src/icp/components/transactions/IcTransaction.svelte
- src/frontend/src/icp/components/transactions/IcTransactionModal.svelte
- src/frontend/src/lib/components/tokens/Token.svelte
Capitalizing only the first letter of sentence to prevent unexpected capitalization such as following (CkUSDC instead of ckUSDC):
> style: text capitalize first-letter only

- .github/workflows/update-snapshots.yml
That way is uses NodeJS v20 as well and fixes per extension: https://github.com/dfinity/oisy-wallet/actions/runs/9643372633/job/26593223611
> chore: use action prepare for update snapshots ci

- src/backend/src/assertions.rs
- src/backend/src/lib.rs
In #1550 we will require the assertion of the token symbol length in two functions. That's why I'm extracting here the function to a utility.
- Move assertion `assert_token_symbol_length` to a new module `assertions`.
- Inverse order where the assertion is made - i.e. first assert and then, if everything is ok, parse the eth address.
The assertion was already covered by an existing test `test_add_user_token_symbol_max_length`.
> refactor(backend): assert token symbol length

- scripts/test.backend.sh
- src/backend/tests/it/upgrade/constants.rs
- src/backend/tests/it/upgrade/impls.rs
- src/backend/tests/it/upgrade/mod.rs
- src/backend/tests/it/upgrade/token_version.rs
- src/backend/tests/it/upgrade/types.rs
- src/backend/tests/it/utils/assertion.rs
- src/backend/tests/it/utils/pocketic.rs
As we aim to introduce new fields into the stable structure, this PR sets the current upgrade test, which was previously developed to test a particular upgrade, to use the WASM of the last release instead of the generated WASM.
This PR also refactors the test and splits the files into separate modules, making it easier to add more tests.
> test: use v0.0.19 wasm for current upgrade test

- .github/workflows/backend-tests.yml
- .github/workflows/checks.yml
- .github/workflows/frontend-tests.yml
It is useful to be able to trigger CI checks manually.  For example, the backend test is triggered only on changes to certain files, so it is not easy to check that it works on main.  With "workflow dispatch" enabled, the backend tests can be run on main with the click of a button.
- Add "workflow_dispatch" as a trigger for those GitHub CI jobs that don't have it yet.
- This needs to be merged into main before the "workflow dispatch" functionality can be exercised.
> feat (ci): Support manually running CI tests

- .github/workflows/backend-tests.yml
The backend test [fails on main](https://github.com/dfinity/oisy-wallet/actions/runs/9658380600) with "invalid workflow file".  In particular Ci doesn't like the use of env in the `runs-on` clause.  The backend tests [have been failing without exception for a couple of months](https://github.com/dfinity/oisy-wallet/actions/workflows/backend-tests.yml).
I see no evidence of env variables being supported for runs-on in the CI docs or functioning examples in GitHub.  `var` can be used but that is different.
While it would be nice to factor out the runner, something simple that works is better than something fancy that doesn't. (yet!)
- Specify the backend test runner manually.
- See the backend tests succeeding with this change: https://github.com/dfinity/oisy-wallet/actions/runs/9658643523 …
> fix (ci): Env vars are not supported for the runner

- .github/workflows/backend-tests.yml
Some changes that affect the rust builds do not trigger the backend (rust code) CI job.  For example, [updating the Rust version did not cause any rust build to be run in CI](https://github.com/dfinity/oisy-wallet/pull/1513/checks).
- Include rust and docker files in the list of files that, when changed, cause the backend ci job to be exercised.
See CI: The backend build [was triggered](https://github.com/dfinity/oisy-wallet/pull/1559/checks) by changing the backend test.
> fix (ci): Add files that trigger the backend test

- src/frontend/src/icp/derived/icrc.derived.ts
Current name `icrcDefaultTokens` works fine so we can just remove the todo.
> chore: remove todo

- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/derived/nav.derived.ts
- src/frontend/src/eth/services/transactions.services.ts
- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/lib/derived/exchange.derived.ts
- src/frontend/src/lib/derived/page-token.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts
We want to introduce custom erc20 tokens store, therefore it makes sense to rename `erc20Tokens` to `erc20DefaultTokens`. Similar to `icrcDefaultTokens`.
> refactor: rename erc20Tokens derived store

- .github/workflows/backend-checks.yml
- .github/workflows/backend-tests.yml
We have `frontend-tests`, `backend-tests` and `checks` which I just renamed to `frontend-checks`. Extracting the backend checks in a dedicated action brings consistency.
- Move `format` to `backend-checks`.
> refactor: move backend checks action

- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/derived/nav.derived.ts
- src/frontend/src/eth/services/transactions.services.ts
- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/lib/derived/exchange.derived.ts
- src/frontend/src/lib/derived/page-token.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts
Revert #1563. We actually want to continue to use `erc20Tokens` within the code base. So we can introduce the default derived store later.
> refactor: revert "rename erc20Tokens derived store"

- src/frontend/src/icp/components/tokens/IcHideTokenModal.svelte
- src/frontend/src/icp/services/ic-custom-tokens.services.ts
- src/frontend/src/icp/services/icrc.services.ts
`loadUserTokens` effectively load `CustomToken` and we are about to add a function to load `UserToken` (erc20) so makes sense to rename current function to something closer to the type it loads.
> refactor: rename loadUserTokens to loadCustomTokens

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/derived/network.derived.ts
It's handy to have a shorthand for chain fusion, that way we don't have to check for nullability in code without exactly knowing why when we read the code.
> feat: derive a shorthand for pseud network chain fusion

- src/frontend/src/lib/components/core/Menu.svelte
Discussed in today's Oisy meeting. For a first iteration we simply do not want to display the wallet address in the user menu (popover) if the not network is selected - i.e. if Chain Fusion is on.
> feat: hide wallet address in menu if chain fusion

- src/frontend/src/icp/stores/certified-icrc.store.ts
Even if it does not make a big difference in this particular use case, spreading the data of the custom token first given that we try to retrieve the id is better.
> feat: spread custom token order

- scripts/build.tokens.sns.mjs
Not sure if it's an issue or a typo (I tend to the latest) but noticed that `ICX `  governance name contains an empty.
- trim alternative name in our Sns script
> feat: trim sns alternative name (ICX contains an empty space)

- src/frontend/src/lib/api/backend.api.ts
Implement new backend apis `set_user_token` and `set_many_user_tokens` in `backend.api` and deprecate the functions which will be ultimately replaced by the new implementation.
> feat: implement set_user_token in backend api

- src/frontend/src/icp-eth/components/tokens/ManageTokensModal.svelte
- src/frontend/src/icp-eth/services/manage-tokens.services.ts
- src/frontend/src/icp/services/ic-custom-tokens.services.ts
We want to save ERC20 user tokens in the "Manage tokens" modal the same way we do for ICRC. That's why this PR extract some interfaces and common code that we can reuse for such purpose.
No logical changes here.
> feat: extract interface and generic function to save icrc custom tokens

- src/frontend/src/lib/derived/networks.derived.ts
Similarly to tokens #1583, product want ICP to be listed as first network (after pseudo network chain fusion)
> feat: network ICP listed first

- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/eth/stores/erc20-default-tokens.store.ts
We now use the erc20.store for default tokens only so it makes sense to use a more verbose name for readability.
> refactor: rename erc20 tokens store

- src/frontend/src/eth/components/send/SendTokenWizard.svelte
- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/derived/nav.derived.ts
- src/frontend/src/eth/services/transactions.services.ts
- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/lib/derived/exchange.derived.ts
- src/frontend/src/lib/derived/page-token.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts
Rename few derived erc20 stores for consistency reason and also to prepare next PR that introduces more complexity.
> refactor: rename enabled erc20 derived stores

- src/frontend/src/eth/components/tokens/AddTokenReview.svelte
- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
Product want default ERC20 tokens to be toggeable so we have to derive more information and user different derived stores according the view to amend the ERC20 tokens custom state and also make those available in the manage tokens modal regardless of their state.
In this PR, `AddTokenReview` is also adjusted to check the potential token to the list of all erc20 tokens.
> feat: erc20 list of tokens and manageable

- src/frontend/src/eth/stores/erc20-user-tokens.store.ts
- src/frontend/src/eth/utils/erc20.utils.ts
With all the requested mumbo jumo we might end up with default token added (enabled or disabled) in the backend.
For example: Oisy provide USDC, user disabled USDC -> entry in the backend -> two tokens in memory for same token.
> fix: prevent duplicate ids

- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/components/tokens/TokenMenu.svelte
- src/frontend/src/lib/derived/token.derived.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
"Hide Token" on the transaction page used to be accessible in the token menu only for "custom" token. Given that user can now disable default ERC20 tokens as well, the feature should also be made available for those.
> feat: make "hide token" available for default ERC20 tokens as well

- src/frontend/src/lib/api/backend.api.ts
Unlike #1598, we can remove unused code in the frontend dapp - i.e. remove implementation of `backend.api` that aren't used anymore.
> chore: remove unused backend functions

- src/frontend/src/icp-eth/components/core/CkEthLoader.svelte
- src/frontend/src/icp/derived/icrc.derived.ts
- src/frontend/src/icp/services/ic-custom-tokens.services.ts
- src/frontend/src/icp/services/icrc.services.ts
- src/frontend/src/icp/stores/icrc-default-tokens.store.ts
Similarly to Erc20, product want Icrc default tokens provided by Oisy to be toggleable by the users. So, as a first step, to implement the feature we rename `icrcTokensStore` to `icrcDefaultTokensStore` given that it contains the default tokens.
> feat: rename icrcTokensStore to default

- src/frontend/src/icp/services/ic-custom-tokens.services.ts
Renaming the default icrc store in #1607 lead me to find a bug in the action to hide a custom token - i.e. the incorrect store was resetted.
> fix: reset icrc custom store

- package-lock.json
- package.json
TS 5.5 is not compatible with the eslint version we have to use. So redo 5.4.5.
> build: redo typescript 5.4.5

- src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte
- src/frontend/src/icp/derived/ethereum-fee.derived.ts
- src/frontend/src/icp/derived/icrc.derived.ts
- src/frontend/src/lib/derived/exchange.derived.ts
- src/frontend/src/lib/derived/page-token.derived.ts
In #1610 we have a split between all and enabled Icrc tokens. So similarly to erc20, it makes sense to rename `icrcTokens` into `enabledIcrcTokens`.
> refactor: rename icrcTokens to enabledIcrcTokens

- src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
There could be two ETH ledger canister IDs on IC network - a production and staging. So, we actually need to compare the type to be sure we select the correct token to calculate the ETH fee on IC.
> fix: find tokenCkEth to calculate ETH fee on IC

- src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte
- src/frontend/src/icp/derived/ethereum-fee.derived.ts
- src/frontend/src/icp/derived/icrc.derived.ts
- src/frontend/src/icp/services/icrc.services.ts
- src/frontend/src/icp/types/ic-token-toggleable.ts
- src/frontend/src/icp/types/icrc-custom-token.ts
- src/frontend/src/lib/derived/tokens.derived.ts
Product want to allow user to disable or enable default Icrc tokens. Default tokens are provided in the frontend and user, upon disabled or enabling custom tokens, save a copy of the information with the related state in the backend. So, when Oisy load tokens it loads default and custom tokens and the latest might contains duplication of the first. Likewise, a default might have been disabled.
That's why, similarly to Erc20, the icrc derived tokens should merge those information.
> feat: load default and custom icrc tokens with duplicate

- src/frontend/src/routes/+layout.svelte
There could be lots of errors which lead the screen to be flooded with toasts. We can probably solve this gracefully by filtering the memory and state, but as a pragmatic first step, we can limit the number of toasts displayed on screen.
> feat: display max three toasts on screen

- .github/workflows/update-tokens.yml
We can run the job to detects sns and tokens a bit more often.
> chore: run tokens cron twice a week

- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/stores/modal.store.ts
A bit more descriptive event that way we can add a more generic event for chain fusion.
> refactor: rename eth modal event

- src/backend/tests/it/address.rs
- src/backend/tests/it/custom_token.rs
- src/backend/tests/it/sign.rs
- src/backend/tests/it/token.rs
- src/backend/tests/it/upgrade/token_enabled.rs
- src/backend/tests/it/upgrade/token_version.rs
- src/backend/tests/it/user_token.rs
We do not need to cast `CALLER.to_string()` in our test. Just `CALLER` is fine.
> chore: remove unused to_string()

- src/backend/tests/it/custom_token.rs
- src/backend/tests/it/user_token.rs
As recommended in #1554, list tokens before and after set in tests.
> test: list tokens before and after set

- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/eth/stores/erc20-user-tokens.store.ts
After deploying on Staging we noticed that the skeleton never fade away. The root cause of the issue is user who do not have user tokens. Because no tokens are loaded, the store stays undefined, because undefined, skeletons are displayed for ever.
- If not tokens then load an empty array in store.
> fix: load oisy when user has now erc20 user token

- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/eth/stores/erc20-user-tokens.store.ts
For consistency reason rename to `setAll` the setter in the erc20 user tokens store.
> refactor: rename setAll for store

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/icp/services/icrc-custom-tokens.services.ts
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/utils/network.utils.ts
I deployed a first version on staging and we noticed that the Sns tokens were not listed, if never enabled or disabled, in the "Manage Tokens" modal.
> fix(frontend): sns tokens not listed in manage tokens

- src/frontend/src/lib/derived/network-tokens.derived.ts
On "Chain Fusion" we want to display a custom list of tokens with some various rules. After last enhancement to make the Icrc toggleable, those rules were fully functional anymore. This PR fixes the display and add a comment about those rules.
> fix(frontend): chain fusion tokens subset display

- src/frontend/src/icp/components/tokens/IcManageTokenToggle.svelte
As it was confirmed by product, ckBTC, ckETH and ckUSDC cannot be disabled.
> feat(frontend): ckETH|BTC|USDC cannot be disabled

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/tokens/Tokens.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/utils/token.utils.ts
I'm quoting myself:
> I detected an issue with the UX. As discussed, we want to display a subset of the tokens by default on "Chain Fusion" but display all default tokens on their respective networks.
>
>For example, PEPE is not displayed by default on Chain Fusion but is displayed by default on the Ethereum network.
>
> This approach leads to an inconsistency in the "Manage Tokens" modal. Currently, the same token is displayed as "Enabled" by default in this modal. Therefore, when a user opens this modal on "Chain Fusion," they see a list of "Enabled" tokens that are actually not displayed.
>
> We could potentially display those tokens as "Disabled" in the modal when "Chain Fusion" is selected. However, this might be confusing because these tokens would still be shown as "Enabled" when …
> feat(frontend): review display of enabled tokens

- .github/workflows/e2e-tests.yml
The downloaded artifact file name was missing the correct extension `oisy-e2e-image.tar.gz`.
> fix(ci): typo artifact name

- src/frontend/src/eth/derived/erc20.derived.ts
USDC in dollars were not displayed, that's because the exchange rate was only loaded for the enabled ERC20 tokens. Given that none are enabled per default, no exchange rate was loaded. So, for simplicity reason, let's load the rate for all ERC20 tokens regardless if disabled or enabled.
> fix(frontend): usdc and other ck erc20 tokens dollar display

- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/types/address.ts
- src/frontend/src/icp-eth/derived/icrc-erc20.derived.ts
- src/frontend/src/lib/components/exchange/ExchangeWorker.svelte
There was a quick fix to load all ERC20 exchange rates (issue #1666), but that isn't very efficient as it loads all rates, even for those ERC20 tokens that are disabled. This PR collects the ERC20 tokens of the twin tokens to limit the number of exchanges to load, assuming that merging the addresses of the derived stores requires fewer resources than querying the CoinGecko API unnecessarily.
> feat(frontend): load less erc20 exchanges

- src/frontend/src/lib/components/exchange/ExchangeWorker.svelte
It will slow down the very first queries by a bit but, I noticed that we make too many queries as the derivation of the stores become too complex and reevaluated more often.
> feat(frontend): debounce exchange queries

- src/frontend/src/icp-eth/derived/icrc-erc20.derived.ts
Casting the address was not accurate which had for effect, once again, to display no ckUSDC dollar rate as the exchange was not queried.
> fix(frontend): enabledIcrcTwinTokensAddresses mapping

- src/frontend/src/eth/utils/erc20.utils.ts
For readability make the string of the erc20 user token symbol more unique by including the chain id given that a same contract address can be potentially be used on various chain.
> feat(frontend): unique erc20 symbol string improved

- src/frontend/src/eth/derived/erc20.derived.ts
While testing the staging version, I encountered an issue. I was unable to enable the Uniswap token because the `version` provided by the frontend was not the one expected by the backend. After debugging, I discovered that the frontend was providing the version of the Sepolia user token instead of using the Mainnet version. The root cause was that both contract addresses on both networks use the same address. Since the chain ID was not considered when matching default tokens and user tokens, the state memory ended up with an incorrect version number mismatch.
> fix(frontend): match erc20 user token with chain id

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
Ck tokens are set with names equals to their symbols. As a result, a user looking for a particular tokens in the manage tokens modals might not found a twin tokens. For example, a user looking for "Chainlink" will not find ckLINK. To overcome this issue, this PR extend the filter with comparing twin tokens as well.
> feat(frontend): filter manage tokens twin tokens

- src/frontend/src/env/tokens.env.ts
In Figma "Internet Computer" is used for the name of the ICP token. So I double checked the metadata of the ICP ledger canister and indeed, it's "Internet Computer".
> feat(frontend): ICP token name is Internet Computer

- src/frontend/src/lib/styles/global/layout.scss
I compared Figma and existing implementation and it feels that the Figma design is a bit less wide on mobile. I also feel that just a bit of margin on X axis would be appreciated on mobile so this PR add just a bit more of padding within the layout for mobile.
> style(frontend): mobile layout a bit less wide

- .github/workflows/update-tokens.yml
There is a `pr-checks` now that checks the title of the pr for semantic version with context. The automated PR used to generate `build: ...` which does not comply.
- Update title to comply - i.e. add `(frontend).
- Change goal from `build` to `feat`. Feels more approriate.
> chore(ci): update automated PR title

- .github/workflows/update-snapshots.yml
- playwright.config.ts
Let's stick to Chrome for now. When we have everything in place we can use more browsers but, this makes easier to run the Ci without the need to install all browsers.
> test(ci): chrome only

- scripts/deploy.backend.sh
- scripts/deploy.ckbtc.sh
- scripts/deploy.ckerc20.sh
- scripts/deploy.cketh.sh
Few canister were deployed locally with `--specified-id` and few not. For the E2E it's easier if the canisters are deployed with predictable IDs, so let's deploy locally with all canisters known.
> chore(scripts): deploy locally with specified ids

- canister_e2e_ids.json
- vite.utils.ts
There are probably other way but, this is just the most pragmatic solution to load those canister IDs the frontend app requires when the E2E tests are running in the CI.
> chore(ci): canister ids config for e2e

- src/frontend/src/eth/services/fee.services.ts
We faced some issues transferring Pepe Erc20 while the network was busy, that's why we decided to bump a bit more the calculation of the fee allowance.
> feat(frontend): bump erc20 fee allowance

- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/eth/services/balance.services.ts
- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
Because of the introduction of "Chain Fusion" the balances for Erc20 tokens were not loaded anymore on the "Tokens" view. The root cause was the fact that we checked for various condition to only load those when required but, nowadays, there are basically always required but, enabled or disabled with a flag.
> fix(frontend): load erc20 tokens balance on "Tokens" view

- src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
- src/frontend/src/lib/components/ui/ButtonHero.svelte
We might have to re-use the same button style. This PR extract the "network switcher" button to a UI component.
- Extract and create `ui/ButtonHero` cmp.
> feat(frontend): button hero

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/hero/Balance.svelte
Close enough, we can replace some custom inline style with tailwind class.
- Use `text-6xl` for balance and exchange rate in hero.
> style(frontend): use tailwind class instead of inline style

- src/frontend/src/lib/components/ui/ButtonHero.svelte
Ultimately the `disabled` option of the new cmp `ButtonHero` won't be used.
- Remove unused prop.
> feat(frontend): remove unused disabled option

- src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte
The Network selection dropdown when adding a new token will show the "Select Network" option as disabled, but only the first time, when the network is still not selected.
> style(frontend): network dropdown in manage tokens will display 'Select network' only once

- .github/workflows/update-tokens.yml
The CI job `update-tokens-ckerc20` was not considering the new icon files created after PR #1713 .
> feat(ci): job update-tokens will save ocons of ckERC20 tokens

- src/frontend/src/env/networks.icrc.env.ts
After updating the JSON file with the new ckERC20 tokens, and after having created the Shiba Inu env variables for the ERC20 token, we can include ckSHIB in the ICRC token list.
> feat(frontend): include Shiba Inu in the ICRC token list

- src/frontend/src/lib/styles/global/theme.scss
Maybe we should style focus-visible but, until we do so, at least we should be consistent and display a focus when link are selected.
- Remove no focus visible for links
No focus on link (currently)
Focus on button (currently)
Focus on link (after PR)
> style(frontend): a focus-visible

- src/frontend/src/lib/components/core/Alpha.svelte
Now that everything is aligned to left I felt like the "Alpha" message could be aligned left on mobile as well.
Before:
After:
> style(frontend): alpha msg on mobile

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/lib/styles/global/gix.scss
Use [overscroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) for inner modal scroll to avoid scrolling body when inner scroll length is reached.
> style(frontend): overscroll-behavior contain for inner modal

- src/frontend/src/lib/styles/global/body.scss
On desktop it does not bother too much that user can scroll the body while a modal is open but, on mobile, particularly iOS, it feels a bit glitchy for some reason even though the modal are full screen on mobile. To prevent the glitch we can disable the overflow when a modal (dialog) or popover (menu) is open and I just figured out that we can solve this with CSS only using `has` which is now well supported.
> style(frontend): disable body scroll when menu or dialog (modal) are open

- src/frontend/src/env/networks.icrc.env.ts
- src/frontend/src/env/tokens.ckerc20.env.ts
To be able to re-use the list of ckERC20 tokens that are in the JSON, we move the parsing to a separate file.
> refactor(frontend): move ckERC20 JSON parsing to separate file for reusability

- src/frontend/src/lib/components/hero/HeroSignIn.svelte
We would like to have the "to Oisy" part of the main title on a separate line.
> style(frontend): adjust the main title to show 'to Oisy' on separate line

- dfx.json
- scripts/deploy.sh
- src/frontend/src/lib/constants/app.constants.ts
We would like to present the Proof Of Humanity credentials in Oisy.
In this PR, I introduce the issuer into the enviornment for Oisy. I added the entry to dfx.json pointing to a dummy issuer that will return any requested credential. As canister id, I used the canister id that Modclub gave us and we can use to test it in mainnet.
* Update Internet Identity version to support VCs.
* New entry in dfx.json `poh_issuer`.
* Deploy the `poh_issuer` in `deploy.sh`.
* Add issuer canister id to constants.ts to confirm that it's added by the scripts.
I even tested that we can present a credential using the JS library and passing all the necessary details.
> feat(env): Add Proof Of Humanity issuer to environment

- src/frontend/src/lib/derived/tokens.derived.ts
It was recently decided that, in any case, the generic tokens orders shall have Bitcoin tokens before Ethereum tokens.
> refactor(frontend): put BTC tokens before ETH tokens

- src/frontend/src/lib/services/exchange.services.ts
As request for sorting, we will need the market cap of the ERC20 tokens. So we request it to Coingecko.
NOTE: for sorting we don't really need the market cap for ICP, BTC and ETH because the logic of sorting them (or their ck* tokens) is different.
> feat(frontend): request market cap to Coingecko in the same request of price

- src/frontend/src/lib/rest/goincecko.rest.ts
- src/frontend/src/lib/services/exchange.services.ts
- src/frontend/src/lib/types/coingecko.ts
After PR #1737 , the response type of function `exchangeRateERC20ToUsd` returns the prop `usd_market_cap` as `number` (and not possibly `undefined`). To be type-safe, we create a new type specific to this function.
- Create type `CoingeckoSimpleTokenPriceResponse` that remove optionality of `usd_market_cap`.
- Use the type for function `exchangeRateERC20ToUsd`.
- Adapt function that fetches prices to have variable type on response.
> chore(frontend): improve response types for Coingecko requests

- src/frontend/src/lib/stores/exchange.store.ts
- src/frontend/src/lib/types/coingecko.ts
- src/frontend/src/lib/types/exchange.ts
- src/frontend/src/lib/types/post-message.ts
I just noticed that in PR #1738 , I forgot to update the types in the stores that use Coingecko rest wrappers.
I am not using the dynamic type `T extends CoingeckoSimplePriceResponse | CoingeckoSimpleTokenPriceResponse` because the stores effectively provide a record of possibly both types, and not selectively only one of them.
> fix(frontend): missing new Coingecko Response types in exchange stores

- src/frontend/src/env/tokens.erc20.env.ts
There is a pipeline of ERC20 tokens that will be onboarded with the respective ckERC20 token. However, it was requested to already include the Ethereum contracts in the list of available token.
We include them as tokens which details are fetched at runtime.
We need to remember to remove them once the respective ckERC20 token is approved, so that the normal flow of onboarding can function properly.
> feat(frontend): include a list of ERC20 tokens that will soon have the ckERC20 token

- dfx.json
- scripts/deploy.sh
- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/services/request-pouh-credential.services.ts
- src/frontend/src/lib/types/i18n.d.ts
We agreed that the name of the credential is Proof Of Unique Humanity, not Proof Of Humanity.
In this PR, I rename all the variables, files etc from POH to POUH.
* Rename canister poh_issuer in dfx json to pouh_issuer
* Rename env vars that use dfx.json canister name
* Rename a file with the service.
* Rename constants.
* Rename i18n keys.
I tested by redeploying the canister and checking that the env vars are still there as expected.
> refactor(frontend): Rename POH to POUH

- src/frontend/src/env/explorers.env.ts
- src/frontend/src/env/networks.icrc.env.ts
- src/frontend/src/icp/services/worker.icrc-wallet.services.ts
- src/frontend/src/icp/utils/ckbtc-transactions.utils.ts
- src/frontend/src/icp/utils/cketh-transactions.utils.ts
- src/frontend/src/icp/utils/ic-transactions.utils.ts
- src/frontend/src/icp/workers/icrc-wallet.worker.ts
- src/frontend/src/lib/types/post-message.ts
The dashboard team has added support for ck test tokens.
- Add links for ckTESTBTC https://dashboard.internetcomputer.org/testbtc
- Add links for ckSepoliaETH https://dashboard.internetcomputer.org/sepoliaeth
- Add links for ckErc20 https://dashboard.internetcomputer.org/sepoliaeth/<ledger-id>
- Add new explorer urls constants
- Map staging urls in environment variables
- Path `env` testnet or mainnet to web workers
- Extend `mapIcrcTransaction` utility to support those testnet explorer urls
Tested manually on staging.
> feat(frontend): ck btc testnet and sepolia explorer links

- src/frontend/src/lib/components/tokens/TokenMenu.svelte
Because not all tokens have the action "Hide token" in the token menu, it's worth updating the order of the displayed for consistency reason.
That way, "View on Explorer" and "Token details" are always displayed next to each other.
> feat(frontend): token menu actions order

- src/frontend/src/lib/styles/global/button.scss
I feel like the "Connect with" button is a bit compressed. Adding just a bit of padding make it a bit more pleasant.
> style(frontend): "Connect with" padding

- src/frontend/src/eth/components/tokens/TokenMenu.svelte
- src/frontend/src/icp/components/tokens/IcTokenMenu.svelte
- src/frontend/src/lib/components/ui/ExternalLink.svelte
"View on explorer" does not match the full with in the context menu which is a bit inconsistent given that other actions (buttons) of the same menu do.
> style(frontend): external link full width

- src/frontend/src/lib/derived/token.derived.ts
A TODO to derive the toggleable tokens was not yet resolved and as a result, accessing "Hiden token" for ck tokens on the transactions view was not yet displayed.
- if token contains "enabled" then it's a toggleable token
> feat(frontend): access to hide ck tokens

- src/frontend/src/lib/components/ui/ButtonMenu.svelte
The alignment in the `ButtonMenu` is centered which is incovenient when the provided slot text is long.
> style(frontend): fix button menu aligment

- src/frontend/src/lib/components/hero/Balance.svelte
I spotted a leftover of our chore modification that transformed the global `$token` in an optional information.
> fix(frontend): display undefined token symbol

- src/frontend/src/env/tokens.erc20.env.ts
I had to resolve a merge conflict and I inervedatly reincluded the Erc20 WBTC back. Sorry for that.
- Remove Erc20 WBTC has it was supposed to be removed in #1757
> fix(frontend): remove erc20 contract address

- src/backend/tests/it/main.rs
- src/backend/tests/it/user_profile.rs
Some Rust tests were introduced in #1743 but they were not being executed in the CI pipeline nor with the script `test.backend.sh`.
* Add user_profile to main.rs in tests.
* Fix tests.
Only test changes.
> chore(backend): Add user_profile tests to backend tests

- scripts/download.ckbtc.sh
To run script `deploy.memecoin.sh`, it is necessary to have the wasm zip files of ckBTC ledger and index. We change the script that downloads such files to keep the zipped archives.
> ci(frontend): keep wasm zip files to deploy memecoin

- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/frontend/src/lib/services/request-pouh-credential.services.ts
- src/frontend/src/lib/stores/settings.store.ts
We want to use the new endpoints introduced #1743 in the frontend.
In this PR, I recreated the types for the JS client with `npm run generate` and also used one of the types in the userProfileStore.
* Changes in `.did` files and related done with `npm run generate`.
* Change the type of userProfileStore to the UserProfile from the generated files.
* Change the faked user profile in requestPouhCredentials.
Not necessary. No new functionality added, only some types (that are not used yet) have changed.
> chore(frontend): Recreate backend types in FE

- scripts/test.backend.sh
- src/backend/tests/it/upgrade/constants.rs
- src/backend/tests/it/upgrade/credentials_init_args.rs
- src/backend/tests/it/upgrade/mod.rs
- src/backend/tests/it/upgrade/token_enabled.rs
- src/backend/tests/it/upgrade/token_version.rs
- src/backend/tests/it/upgrade/types.rs
- src/backend/tests/it/utils/pocketic.rs
We introduced new init args and we'd like to test that the canister is upgradable from a previous canister without them.
* Add an optional argument to `setup_with_custom_wasm` and `upgrade_latest_wasm` which are the arguments and set it to `None` in all current calls.
* Add v0.0.25 backend wasm.
* New init types for the v0.0.25 canister.
* New upgrade test credentials_init_args.
Only test changes.
> test(devops): Add upgrade test for new credentials init args

- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
- src/frontend/src/icp/components/fee/BitcoinFeeContext.svelte
- src/frontend/src/icp/components/fee/BitcoinKYTFee.svelte
- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/components/transactions/IcTransactions.svelte
- src/frontend/src/icp/components/transactions/IcTransactionsBitcoinStatusBalance.svelte
- src/frontend/src/icp/derived/ic-token.derived.ts
Since we cast global stores `token` and `tokenWithFallback` to IcToken a few times, it is better to unify under a global store, so that it is easier to control it, and eventually remove it in future.
- Create global store `tokenAsIcToken`.
- Create global store `tokenWithFallbackAsIcToken`.
- Adapt the code.
> refactor(frontend): unify IcToken casting under a global store

- src/frontend/src/eth/components/wallet-connect/WalletConnectSession.svelte
- src/frontend/src/eth/stores/wallet-connect.store.ts
- src/frontend/src/lib/components/core/Menu.svelte
- src/frontend/src/lib/components/ui/ButtonMenu.svelte
We move the connect button of WalletConnect inside the items in the main menu. However we want to leave the disconnect button in the same place.
> refactor(frontend): move WalletConnect inside the main menu

- src/frontend/src/env/networks.env.ts
We remove "Mainnet" from the name of Ethereum mainnet network.
> chore(frontend): change Ethereum network name

- src/frontend/src/lib/components/hero/HeroSignIn.svelte
As suggested by @peterpeterparker , the z-index was not necessary and could lead to possible issues in conflicting positions. In our case it was giving the issue below:
> fix(frontend): z-index of header logo was overlapping modals

- src/frontend/src/lib/styles/global/button.scss
- src/frontend/src/lib/styles/global/colors.scss
- src/frontend/src/lib/styles/global/variables.scss
- tailwind.config.js
We update the style of primary buttons. Furthermore, the `border-radius` for every button type is now `4px`.
> style(frontend): update style of primary buttons

- scripts/deploy.backend.sh
- src/backend/backend.did
- src/backend/src/config.rs
- src/backend/tests/it/utils/pocketic.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/shared/src/types.rs
Set the config with the proper type (Principal) as soon as possible. In this case, when the init arguments are passed on deploy.
* Set ii_canister_id and issuer_canister_id fields of SupportedCredentials from InitArg as Principal instead of a string.
* Change client types.
* Remove unnecessary conversion to Principal.
* Fix init args in tests.
* Tested deploy to the local replica.
> refactor(backend): Change SupportedCredential type

- scripts/build.csp.mjs
Redo `unsafe-inline` in CSP for backwards compatibility reasons.
> chore(frontend): redo unsafe-inline for backwards compatibility

- src/frontend/src/lib/components/hero/HeroSignIn.svelte
- src/frontend/src/lib/components/ui/ButtonIC.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/styles/global/button.scss
- src/frontend/src/lib/types/i18n.d.ts
We change the Authenticate button to be simpler:
P.S. we delete `ButtonIC` component that is deprecated.
> refactor(frontend): updated the Authenticate button when logged out

- src/frontend/src/lib/components/pages/SettingsSignedIn.svelte
- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/lib/constants/credentials.constants.ts
- src/frontend/src/lib/derived/has-pouh-credential.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/services/request-pouh-credential.services.ts
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/lib/utils/credentials.utils.ts
- src/frontend/src/tests/lib/utils/credentials.spec.ts
We want users to present the POUH credetial to Oisy.
In this PR, I introduce the different UIs that will be rendered in the Settings page based on the value of the user profile store.
* New env var `VITE_POUH_ENABLED` and app feature flag `POUH_ENABLED`.
* Move `POUH_CREDENTIAL_TYPE` to a credentials constants file.
* New util `hasPouhCredential`.
* New derived store `userHasPouhCredential`.
* New i18n keys for new copy.
* New UI section in SettingsSignedIn.
* Tested manually the different UIs.
* Add test for the new util.
> feat(frontend): Credentials section in settings

- src/frontend/src/lib/components/hero/Actions.svelte
- src/frontend/src/lib/components/hero/Hero.svelte
- src/frontend/src/lib/components/hero/HeroContent.svelte
- src/frontend/src/lib/components/tokens/TokenMenu.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/routes/(app)/+layout.svelte
We move the `ContextMenu` component among the Hero buttons.
> refactor(frontend): move ContextMenu as More button among Hero buttons

- src/backend/backend.did
- src/backend/src/lib.rs
- src/backend/src/oisy_user.rs
- src/backend/src/user_profile.rs
- src/backend/tests/it/get_users.rs
- src/backend/tests/it/list_users.rs
- src/backend/tests/it/main.rs
- src/backend/tests/it/user_profile.rs
- src/backend/tests/it/utils/assertion.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/shared/src/impls.rs
- src/shared/src/types.rs
The Rewards canister needs to have the list of Oisy users and whether they have a verified POUH credential or not.
In this PR, get_users is implemented, which is the endpoint that Rewards canister will call to get Oisy users.
* New helper `get_oisy_users`.
* New helper in user_profile `store_user` to avoid code duplication.
* New implementation of OisyUser `from_profile` to convert one from a StoredUserProfile.
* Implement `get_users`.
* Test the new endpoint.
> feat(backend): Implement get_users endpoint

- src/frontend/src/lib/constants/app.constants.ts
The mainnet domain for the issuer was set to ic0.app but it should be the new icp0.io
* Change `MAINNET_DOMAIN`.
Only testeable not in local.
> fix(frontend): Fix mainnet domain

- dfx.json
With the addition of verifiable credentials, the `backend` WASM resulted in a size above 2.5 MB which lead to us to not being able to deploy the backend.
```
Upgrading code for canister backend, with canister ID tdxud-2yaaa-aaaad-aadiq-cai
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
Failed while trying to install all canisters.
Failed to install wasm module to canister 'backend'.
Failed during wasm installation call: The replica returned an HTTP Error: Http Error: status 413 Payload Too Large, content type "text/plain; charset=utf-8", content: Request 0xdf849e021bf0e64ef22ad4f0f7c5001edf26aa5332ae42745164c1b70bba56d5 is too large. Message byte size 2485012 is larger than the max allowed 2097152.
```
To resolve the issue we set the …
> chore(deploy): gzip wasm for deployment

- scripts/build.metadata.mjs
- src/frontend/static/.well-known/ic-domains
We were requested to setup a custom domain `staging.oisy.com` therefore we need such domain in the `./well-known/ic-domains`. While it might works out having both `oisy.com` and staging within the file, I find it cleaner to have distinctive file per domains given that both dapps are configured differently and live on two different canisters.
- Update static file with a markup `{{VITE_OISY_DOMAIN}}`
- Replace markup at build time similarly to what we already do to populate environment variables within html or json files.
+ unrelated to the PR, I renamed a parameter `html` to content in the script as it was already use for other purpose than stricly html.
> feat(frontend): parse ic-domains at build time for staging.oisy.com

- src/frontend/src/icp/components/convert/ConvertToBTC.svelte
During PR #1830 , I forgot to adjust the slot of the icon in `ButtonHero` for component `ConvertToBTC`.
> fix(frontend): adjust ButtonHero of ConvertToBTC

- src/frontend/src/lib/services/actions.services.ts
- src/frontend/src/lib/utils/timeout.utils.ts
I was having a look at the code and just felt like renaming the parameters of `waitReady` could improve readability.
Also noticed that we could eliminate duplicate code by reusing `waitForMilliseconds` function.
> refactor(frontend): rename parameters of waitReady

- src/frontend/src/lib/components/hero/Actions.svelte
- src/frontend/src/lib/components/ui/ButtonHero.svelte
It is preferable to have equal spacing between the buttons of `Actions` instead of distribute them on the available space.
> style(frontned): adjust spacing of buttons of component Actions

- src/frontend/src/lib/styles/global/button.scss
The CSS class `ic` is deprecated.
> chore(frontend): remove CSS class 'ic' that is deprecated

- scripts/deploy.backend.sh
We want to be able to validate the credentials semantically (check the data is the expected one). One of the fields is `iss`, which is the issuer id (which a url is used most of the times).
In this PR, I change the hardcoded `POUH_ISSUER_VC_URL` and set it depending on the environment.
The values were confirmed by Decide AI team.
* Change `deploy.backend.sh` to set `POUH_ISSUER_VC_URL` per environment.
I tested deploying it locally and it was working.
> feat(devops): Set expected POUH issuer id

- src/frontend/src/lib/components/hero/HeroContent.svelte
Token logo was not at the center in the `/transactions` page.
> style(frontend): center token logo

- src/backend/src/impls.rs
- src/backend/src/lib.rs
- src/backend/src/oisy_user.rs
- src/backend/src/token.rs
- src/backend/src/types.rs
- src/backend/src/user_profile.rs
Restructure where types are defined so that they can be reused and grow in complexity.
* Move the stable structure types to a module called "types" in the backend and the implementation to a module calles "impls". Following the pattern of "shared".
* Import the new types where needed.
* Use the new types instead of defining the whole type again in user_profile and oisy_user modules.
No new tests needed, code was just moved.
> chore(backend): Refactor and reuse types

- HACKING.md
- canister_ids.json
- dfx.json
- scripts/build.utils.mjs
- src/frontend/src/env/networks.icrc.env.ts
- src/frontend/src/lib/constants/app.constants.ts
- vite.config.ts
We were requested to deploy a new frontend under `beta.oisy.com` that points to production. For this purpose, the frontend will communicate with the same backend and canisters as production, and we will use a derivation origin to sign in with `oisy.com`.
We will use two separate environments because, while they are the same right now, I would not be surprised if "beta" has to be tweaked with different environment properties. Moreover, it is more straightforward to do so.
To make `beta.oisy.com` point to the `oisy.com` backend, we will duplicate the backend ID in `canister_ids.json`.
We reviewed the changes offline with @AntonioVentilii-DFINITY
> chore(frontend): beta configuration

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/services/load-user-profile.services.ts
- src/frontend/src/lib/types/errors.ts
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/services/load-user-profile.spec.ts
We want to use the profile stored in the backend in the frontend.
In this PR, a new service is introduced `loadUserProfile` which loads gets or creates a profile and stores it in the store. It also performs an update call to store the certified data in the background.
* New api function `getUserProfile` and `createUserProfile`.
* New error `UserProfileNotFoundError`.
* New service `loadUserProfile`.
* Unit tests for `loadUserProfile`.
* I also tested triggering the service when the user visited settings and it worked as expected.
> feat(frontend): Add service to load user profile

- src/frontend/src/lib/components/tokens/TokenCardWithUrl.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
The aria label for `TokenCardWithUrl` now uses `i18n`.
> chore(frontend): set i18n for TokenCardWithUrl aria label

- src/frontend/src/lib/components/hero/about/AboutHowModal.svelte
- src/frontend/src/lib/components/hero/about/AboutWhatModal.svelte
We use the dedicated `Img` component in the new `About` modals.
> refactor(frontend): use Img component in modals About

- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
Similar to how it is done for ETH, we extract the sub-component inside the `IcSendModal`. The final scope is to re-use it elsewhere too.
- Create new component `IcSendTokenWizard`.
- Adjust component `IcSendModal`.
Local test of sending to myself some ICP worked as expected.
> refactor(frontend): extract sub-component from IcSendModal

- src/frontend/src/lib/components/core/Back.svelte
- src/frontend/src/lib/components/networks/NetworkButton.svelte
- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/lib/utils/nav.utils.ts
There was a bug so that the `Back` component would always go in loop between the last two navigational page (transactions and settings).
- Rename `Back to wallet` to `Back`
- Use native navigation history and goto to execute browser's back on, back
- Replace specific call to function back that were actually meant as navigation with a new function that navigate and replace the history with the root
> fix(frontend): back

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/components/pages/SettingsSignedIn.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/services/load-user-profile.services.ts
- src/frontend/src/lib/services/request-pouh-credential.services.ts
- src/frontend/src/lib/types/i18n.d.ts
We want to validate the credentials presented by users and store some metadata in their profiles.
In this PR, the service `requestPouhCredential` is connected to the backend.
* New api function `addUserCredential`.
* Load the user profile in settings page and render the credentials only when present.
* Change the parameter of `requestPouhCredential` to the `Identity`.
* Add two new i18n messages.
* Export `loadCertifiedUserProfile`.
* Add a helper `addPouhCredential` to be used within the handle success of `requestPouhCredential`.
See screencast of the successful flow.
> feat(frontend): Verify and add credential to user profile after presentation

- src/frontend/src/icp/components/send/IcSendForm.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
Since we would like to re-use `IcSendTokenWizard` as an intermediate step in a wizard modal, we add the possibility of having `Back` button instead of just `Close`.
Note: it is similar to what we have in `EthSendTokenWizard`.
> refactor(frontend): add 'back' option to IcSendForm

- .github/workflows/frontend-remove-unused-components.yml
Having tested the workflow with PR #1883 , I noticed that the `.txt` file used to store the deleted files is included in the PR. Furthermore, the list is not printed in the PR body.
So we change it to use ENV variables instead.
> fix(ci): remove txt file and using env variables for deleted files

- src/frontend/src/lib/components/pages/SettingsSignedIn.svelte
- src/frontend/src/lib/derived/has-pouh-credential.ts
- src/frontend/src/lib/services/load-user-profile.services.ts
- src/frontend/src/lib/services/request-pouh-credential.services.ts
- src/frontend/src/lib/stores/settings.store.ts
- src/frontend/src/lib/stores/user-profile.store.ts
- src/frontend/src/tests/lib/services/load-user-profile.spec.ts
Simplify how user profile is stored in the frontend.
In this PR, create and use a new userProfileStore that doesn't persist data in localStorage.
* New store user-profile.store
* User the new userProfileStore instead of the one from settings.store.
* Remove the userProfileStore from settings.store
Tested manually.
> feat(frontend): New user profile store not persisted in localStorage

- dfx.json
The `orbit` canister entry in `dfx.json` was missing candid data, causing `npm run generate` to fail.
* Add Candid and Wasm information for the Orbit canister.
* I have run `npm run generate` locally, with success.  (After deploying canisters locally!)
It would be nice to run this in CI but at present we run `dfx start` and deploy canisters only in docker, which complicates this.
> fix(devops): Add Wasm and did file for orbit

- src/frontend/src/lib/components/send/SendWizard.svelte
We merge `EthSendTokenWizard` and `IcSendTokenWizard` into a single component `SendWizard`, to be used as content for the future, general Send modal.
> feat(frontend): create SendWizard as content for generic send modal

- src/backend/backend.did
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
`npm run generate` was blocked for a while.  In the meantime a new `issuer` field was added to `UserCredential`.  That change was not propagated to the generated files.  Now that generation works again, the field needs to be propagated.
* Run `npm run generate` and commit the changes.
* The changes are only the addition of the `issuer` field in auto-generated files.
None.  Existing CI should suffice.
> fix(backend): Add missing issuer field to generated files

- vite.config.ts
After some test on mainnet we decided to move three.js chunk from `vendor` to `index` that way it is load with other UI chunks.
- Update rollup config to chunk three.
> build(frontend): chunk three.js into index

- src/frontend/src/lib/components/send/SendTokensList.svelte
- src/frontend/src/lib/components/tokens/TokensSignedIn.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/lib/utils/tokens.utils.ts
It is not really necessary to sort by balance (and pin the tokens with balance on top) at the tokens level. To spare computational time we apply the function `pinTokensWithBalanceAtTop` to the list of network tokens (that supposedly is smaller or has the same length).
Unrelated: we add some docstring to the sorting functions.
- Remove `pinTokensWithBalanceAtTop` from derived `sortedTokens`.
- Create global derived store `sortedNetworkTokensUi` that pins tokens with balance on top (and sorts them).
- Adapt other stores and usage.
No changes on local replica.
> refactor(frontend): move sorting by balance to network tokens

- src/frontend/src/lib/components/ui/ButtonAuthenticate.svelte
The border was missing when hovered.
Unrelated: we cleaned a bit the style.
> style(frontend): add border to ButtonAuthenticate

- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/components/send/SendTokensList.svelte
- src/frontend/src/lib/config/send.config.ts
- src/frontend/src/lib/enums/wizard-steps.ts
The following is the generic `SendModal` that has as first step the choice of token. The rest will be the same as the modals for ETH and IC.
> feat(frontend): create SendModal with initial step of choosing the token

- scripts/add.tokens.erc20.mjs
The script `add.tokens.erc20.sh` use ckERC20 symbol stripped of `ck` to generate the symbol of the ERC20 counter part. 
However, while importing `WSTETH`, I noticed that the effective symbol is actually `wstETH`.
Therefore the script has to fetch the symbol from the contract (in addition to name and decimals) to generate an accurate symbol.
- Use `'function symbol() public view returns (string)'` and apply symbol to corresponding fields of the generated TS code.
> feat(frontend): use erc20 contract to populate token symbol

- src/frontend/src/lib/config/send.config.ts
During PR #1907  , I forgot to add the QR code step among the `sendWizardSteps`.
> feat(frontend): include QR code step in new generic SendModal

- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
I forgot event `icSendBack` in the `SendModal` component.
> fix(frontend): missing event icSendBack in SendModal

- src/frontend/src/lib/components/send/SendTokensList.svelte
- src/frontend/src/lib/components/tokens/TokenBalance.svelte
- src/frontend/src/lib/components/tokens/TokenCardContent.svelte
- src/frontend/src/lib/components/tokens/TokenCardSignedOut.svelte
- src/frontend/src/lib/components/tokens/TokenCardWithOnClick.svelte
- src/frontend/src/lib/components/tokens/TokenCardWithUrl.svelte
- src/frontend/src/lib/components/tokens/TokensSignedIn.svelte
- src/frontend/src/lib/components/tokens/TokensSignedOut.svelte
This PR aims at extracting re-used components from the `TokenCard` component and its parent/child.
- Create component `TokenBalance` to show formatted balance with symbol.
- Create `TokenCardContent` to show the balance and the exchange value, inside a `TokenCard`.
- Create `TokenCardSignedOut` that shows no values.
- Adapt code in the parent components that were using `TokenCard`.
No changes on local replica.
> refactor(frontend): extract balance component from TokenCard

- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
Rollback PR #1779 - Pin tokens with balance at the top - which introduces an endless loop. The sorting updates the stores, which in turn triggers Infura, which re-triggers the store, which re-triggers Infura, etc.
As a result, we are facing many Infura 429 errors and have exceeded the daily quota of requests.
- Rollback PR #1779
> fix(frontend): rollback pin tokens with balance at top PR #1779

- src/frontend/src/lib/components/core/Menu.svelte
- src/frontend/src/lib/components/hero/Header.svelte
- src/frontend/src/lib/components/hero/about/AboutItem.svelte
- src/frontend/src/lib/components/hero/about/AboutMenu.svelte
- src/frontend/src/lib/components/icons/IconInfo.svelte
- src/frontend/src/lib/i18n/en.json
We add `AboutWhat` and `AboutHow` buttons among the items in `Menu`. Furthermore, we include an icon in both of them: it will be used both for the menu when logged in and the menu when logged out (in small screen).
- Add `IconInfo` to both button `AboutItem`.
- Include `AboutWhat` and `AboutHow` among the `Menu` items.
- Update the labels: from question to affirmation.
- Unrelated: adjust the spacing and the font size of the buttons.
> feat(frontend): add about modals buttons in the main Menu

- src/frontend/src/lib/components/ui/ThreeBackground.svelte
The component ThreeBackground was not refreshing its size when the container changed (for example, when the user comes back from a token page). It was not clearly visible, but the height of the waves was smaller.
> refactor(frontend): adapt ThreeBackground size to container

- src/backend/src/lib.rs
- src/backend/src/user_profile.rs
- src/backend/src/user_profile_model.rs
Refactor the code so that the different maps managing user profiles are not mismanaged and we introduce bugs and inconsistent data.
This was requested in https://github.com/dfinity/oisy-wallet/pull/1827/files#r1695268288
* Create a new struct UserProfileModel and implement it. This entity will have the responsibility to interact with the stable memory to retrieve and store user profiles.
* Use the new struct in the user_profile module instead of expecting the stable memory structures.
Not yet. I want to check that the implementation is the requested one.
> refactor(backend): Add UserProfileModel to interact with user profiles in stable memory

- src/frontend/src/lib/components/hero/Hero.svelte
In Hero component, with ChainFusion background, the overflow was hidden, leading to showing partially the menu popover. This was more clear with bigger menu.
> fix(frontend): wrong overflow-hidden in Hero

- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
I don't know on mainnet but, at least locally, it seems that bumping the debounce time of the load balances from the default 300ms to 500ms can potentially save up to twice the calls to load the balances. While it is not a super solution nor an awesome engineered solution, it feels like given the current situation it's a pragmatic small improvement worth a shot.
> feat(frontend): increase debounce time of load balances

- package-lock.json
- package.json
We have released `gix-cmp` which supports `sass` v1.77.8. So it might become useful the day we also bump sass.
> build(frontend): update gix-cmp

- src/frontend/src/lib/components/hero/about/AboutItem.svelte
When `AboutItem` is part of a menu, it does not behave as standard item in menu (no change in color when hovering for example). This PR adjusts it.
> style(frontend): adjust text style for AboutItem

- src/frontend/src/eth/components/core/EthListener.svelte
- src/frontend/src/eth/services/balance.services.ts
- src/frontend/src/eth/services/fee.services.ts
- src/frontend/src/eth/services/metamask.services.ts
- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/eth/utils/send.utils.ts
- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
- src/frontend/src/icp-eth/utils/cketh.utils.ts
- src/frontend/src/lib/derived/address.derived.ts
- src/frontend/src/lib/derived/network.derived.ts
- src/frontend/src/lib/types/address.ts
To be more consistent (and expecting to integrate BTC too), we rename type `OptionAddress` to `OptionEthAddress`.
> refactor(frontend): rename type to OptionEthAddress

- src/frontend/src/eth/components/core/EthListener.svelte
- src/frontend/src/eth/components/core/EthWalletAddress.svelte
- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/components/receive/EthReceiveMetamask.svelte
- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendReview.svelte
- src/frontend/src/eth/components/tokens/TokenMenu.svelte
- src/frontend/src/eth/components/transactions/Transaction.svelte
- src/frontend/src/eth/components/transactions/TransactionModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendReview.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSession.svelte
- src/frontend/src/eth/services/balance.services.ts
- src/frontend/src/eth/services/transactions.services.ts
- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/icp-eth/components/send/ConvertETHToCkETHWizard.svelte
- src/frontend/src/icp/components/convert/ConvertToEthereum.svelte
- src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte
- src/frontend/src/lib/components/receive/ReceiveAddresses.svelte
- src/frontend/src/lib/derived/address.derived.ts
- src/frontend/src/lib/derived/network.derived.ts
To be more consistent with the scope of the derived store, we rename it `ethAddress`.
> refactor(frontend): rename derived 'address' to 'ethAddress'

- src/frontend/src/lib/components/transactions/TransactionsSignedOut.svelte
- src/frontend/src/lib/i18n/en.json
Only a subset of the tokens is loaded by default when the user is signed out. As a result, the text that should be displayed on the transactions page when not logged in is not necessarily displayed if the token in the URL is not one of those.
- Display a generic non token related text.
> fix(frontend): signed out transactions text

- src/frontend/src/icp-eth/services/user-token.services.ts
ckETH is also linked with a twin token. As a result, the function to `autoLoadUserToken`  interprets it as an Erc20 token an try to match a contract address while there is no such thing leading to an error which prevents user to open the "Receive" modal. 
- Auto load token only for Erc20
> fix(frontend): auto load token only for erc20

- .github/workflows/frontend-remove-unused-components.yml
The GitHub Action` frontend-remove-unused-components` was updated to use a Here Document (`<<EOF`) for setting the `DELETED_FILES` environment variable, ensuring that files in separate lines are correctly printed in the PR body.
> fix(ci): job to remove unused files does not print separate lines

- src/frontend/src/lib/derived/networks.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- svelte.config.js
- vitest.config.ts
To be consistent, we add the BTC folder among the aliases of the project. And we adapt the imports referring to such folder.
> feat(frontend): add BTC folder among aliases

- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/lib/services/auth.services.ts
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/routes/+layout.svelte
We substitute hard-coded strings with `i18n` keys.
> chore(frontend): add i18n keys for a few errors and warnings

- package-lock.json
- package.json
We want to stay up-to-date and resolve some npm audit warnings.
- Pin `elliptic` to inherit various fix of security vunerabilities
- Update WalletConnect last version v1.14.0
- Update Alchemy sdk v3.4.1 which officially inherit axios security fix (issue #2024 still not solved though)
> build(frontend): update dependencies and pin to fix minor vulnerabilities

- src/frontend/src/lib/components/tokens/TokensSignedOut.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/tests/lib/utils/qr-code.utils.spec.ts
As spotted by @peterpeterparker , the ETH/ERC20 balance was being refreshed periodically and that could cause incoherent and asynchronous information between the balance and the transactions.
The cause is most likely a cascade refresh caused by the periodic refresh of `exchanges` store:
`exchanges --> combinedDerivedSortedTokens --> networkTokens --> enabledNetworkTokens --> enabledErc20NetworkTokens --> LoaderBalances`
This PR tries to solve that issue removing the exchanges dependency from `enabledErc20NetworkTokens` dependencies.
To do that, we move `combinedDerivedSortedTokens`, so that the sorting happens after having filtered for `network` and `enabled`. This has the additional effect of potentially reducing the computational work for sorting.
> fix(frontend): avoid multiple balance refresh periodically

- .github/workflows/e2e-tests.yml
- Dockerfile.e2e
- docker/deploy
The goal of this PR is to fix e2e tests pipeline.
1. To prevent "out of space" error while building an e2e docker image, added a small command to remove cache folder.
2. Dockerfile.e2e was missing a few tools required to build and deploy backend canister.
3. To fix the issue described [here](https://dfinity.slack.com/archives/C072H2FMW1F/p1723737578374699), we need to create some canisters before running the deploy script.
> ci(e2e): fix e2e tests pipeline

- .github/workflows/update-snapshots.yml
Same as in e2e-test.yml, before building an e2e docker image, we need to free some space to prevent "out of space" error.
> ci(deploy): prevent "out of space" error in update-snapshots.yml

- src/frontend/src/lib/api/idb.api.ts
- src/frontend/src/lib/types/idb.ts
We replicate the IDB functions for Bitcoin Mainnet address, as they are used for Ethereum.
> feat(frontend): IDB functions for Bitcoin address

- canister_ids.json
- dfx.json
The backend will be split into a signer and a user data canister.  The first step in this process, according to [the plan](https://www.notion.so/dfinityorg/Oisy-frontend-uses-separate-backend-and-signer-6a84a876f6ec434891eafcb56756937c), is to have separate canister names, even though they initially refer to the same canister.
- Add a `signer` canister to `dfx.json` and `canister_ids.json`.
- Existing CI should pass.
- Reviewers should manually verify that, at the time of writing, the canister IDs are identical for the `backend` and `signer`.
> feat(devops): Add signer canister

- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/eth/components/send/SendDestination.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
To enable the conversion of "ICP ERC20" tokens to native ICP tokens, users should be able to input an "old" ICP account identifier in hexadecimal format. Previously, this function worked as expected. However, due to an assertion introduced in early 2024, the destination field in the ETH "Send" wizard now requires a properly formatted ETH address. To accommodate this specific use case, we need to modify the validation process to recognize and accept ICP account identifiers as valid inputs in the destination field.
There might be some more abstracted ways to solve this but, to prevent issues, I rather liked to bit a bit verbose given that it is a really particular use case. 
- Improve `isInvalidDestination` to throw if the address is an invalid account identifier on "ICP Erc20"
- Do not map …
> fix(frontend): ICP Erc20 to native ICP destination account identifier

- scripts/deploy.signer.sh
Step 2 of [the frontend migration plan](https://www.notion.so/dfinityorg/Oisy-frontend-uses-separate-backend-and-signer-6a84a876f6ec434891eafcb56756937c) is to make a deploy script for the signer canister.
This PR implements that step, although the script has no use (yet):
- `deploy.sh` does not deploy the signer separately, and probably never will as signer deployments will (soon) be from another repository.
- Likewise the `HACKING.md` file does not need instructions for deploying the signer (yet).
- Add a deploy script for the `signer` canister.
The script is a copy of `deploy.backend.sh` so most code branches will already be checked there.
I have run:
```
ENV=local WALLET=bnz7o-iuaaa-aaaaa-qaaaa-cai bash -x scripts/deploy.signer.sh
```
Note: `WALLET` needs to be set explicitly when …
> feat(devops): Signer deploy script

- src/frontend/src/lib/components/receive/ReceiveAddresses.svelte
- src/frontend/src/lib/derived/address.derived.ts
- src/frontend/src/lib/types/address.ts
Similar to ETH, we add the BTC address to the `Receive` modal.
> feat(frontend): add BTC address to receive modal

- src/backend/src/migrate.rs
When "prettifying" a recent PR before merge I added `.expect()` lines after data insertion.  In fact, the `.insert()` returns not a result but an option containing the previous value, so all the (still to be merged) tests that use these functions fail.  A bit embarrassing!
- Don't expect() on the returned options.
> fix(backend): Rm erroneous expect

- src/backend/backend.did
- src/backend/src/impls.rs
- src/backend/tests/it/migration.rs
- src/backend/tests/it/stats.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/declarations/signer/signer.did
- src/declarations/signer/signer.did.d.ts
- src/declarations/signer/signer.factory.certified.did.js
- src/declarations/signer/signer.factory.did.js
- src/shared/src/types.rs
User profiles and user timestamps are stored in separate `BTreeMap`s, and migrated in separate `BTreeMap`s.  As a check that the timestamp migration is complete, it would be useful to have a separate count for the timestamps.
- Add `user_timestamps_count` to `Stats`.
None here, this field is used in migration tests.
> feat(backend): Add a separate statistic for timestamp count

- src/frontend/src/lib/api/idb.api.ts
- src/frontend/src/lib/components/core/Loader.svelte
- src/frontend/src/lib/enums/progress-steps.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/lib/types/address.ts
- src/frontend/src/lib/types/errors.ts
- src/frontend/src/lib/types/i18n.d.ts
We join the BTC address loader with the ETH address loader.
- Create function to load all IDB addresses.
- Create function to get addresses from backend by token.
- Make the `Loader` component await **ALL** loading promises of the above functions.
- Adjust the text and the comments.
- Unrelated: remove the useless `export` properties.
Bitcoin address is correctly loaded (and/or re-loaded) during login.
> feat(frontend): add BTC loaders to UX component

- src/frontend/src/icp-eth/services/eth.services.ts
It was reported that pending ck conversions were displayed under the wrong token. e.g. one user converted LINK to ckLINK and then browsed ckUSDC and the frontend was displaying "Pending USDC to ckUSDC". This seems to happens because the pending transactions resolved with logs are not filtered for the selected token.
To solve it, we refine the logs topic including the ERC20 contract address among the parameters.
We can see a practical example [here](https://etherscan.io/tx/0xddbf4aebe292c3d3b33240496db12a1a5622c4edb63017ebcd12ffa32fa5b924#eventlog).
> fix(frontend): pending ck conversions displayed under incorrect token

- src/backend/backend.did
- src/backend/src/migrate.rs
- src/backend/tests/it/migration.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/declarations/signer/signer.did
- src/declarations/signer/signer.did.d.ts
- src/declarations/signer/signer.factory.certified.did.js
- src/declarations/signer/signer.factory.did.js
- src/shared/src/impls.rs
- src/shared/src/types.rs
Testing migrations showed that:
- Some naming was potentially confusing.
- When testing error conditions, it would be useful to have a formal error variant for the migration state.
- Modify the (as yet unused in main) migration state enum:
- Some steps have been renamed or reorganized for clarity.
- A failed state has been added, with various reasons for failure.
- Updated code to match
Tests have been updated to match the changes.
> feat(backend): Update migration states

- scripts/build.csp.mjs
I'm not sure if it the issue is related to bumping `@walletconnect/web3wallet` from v1.12.3 to 1.14.0 - given that nothing related is specified in the [release notes](https://github.com/WalletConnect/walletconnect-monorepo/releases) -  or if the issue started out of the blue but, WalletConnect has started using `walletconnect.org` instead of `walletconnect.com` which lead to Oisy not being able to connect WalletConnect as we are protective about the list of services we are allowing in the dApp CSP.
- Add `wss://relay.walletconnect.org https://verify.walletconnect.org` to `connect-src` in CSP
Issue identified in production:
> fix(frontend): add walletconnect.org to connect-src CSP

- src/frontend/src/lib/components/pages/Settings.svelte
- src/frontend/src/lib/components/pages/SettingsVersion.svelte
Let's display the app version on the settings page.
> feat(frontend): display Oisy version on Settings page

- e2e/utils/pages/homepage.page.ts
- env.utils.ts
- playwright.config.ts
- shared.utils.ts
- tsconfig.eslint.json
- vite.utils.ts
The goal is to access canister_e2e_ids.json in e2e tests as env vars.
> test(e2e): add canister ids as env vars for e2e tests

- canister_e2e_ids.json
- scripts/deploy.sh
Fix issue with missing signer canister id for e2e docker image.
> ci(e2e): issue with missing signer canister id

- src/frontend/src/icp/utils/cketh-transactions.utils.ts
The ETH explorer for ck-conversion transaction was pointing always to Sepolia for ckERC20 tokens that were not ckETH. This fixes it keeping the same logic based on the `ledgerCanisterId` being staging or prod.
> fix(frontend): adjust ETH explorer for ck tokens

- src/frontend/src/lib/components/send/SendTokensList.svelte
- src/frontend/src/lib/components/tokens/TokensSignedIn.svelte
- src/frontend/src/lib/components/tokens/TokensSkeletons.svelte
Component `TokensSkeleton` will have a new prop `loading`, since we expect such a value to be dependent on more factors.
> refactor(frontend): make loading a prop for TokensSkeleton

- src/frontend/src/lib/derived/address.derived.ts
- src/frontend/src/lib/stores/address.store.ts
To avoid repeating code and simplify readability, there is a new derived store that determines the ETH address certified data.
> refactor(frontend): derived store for ETH address data

- src/frontend/src/eth/components/send/ConvertToCkERC20.svelte
As discussed in PR #2104 ([comment](https://github.com/dfinity/oisy-wallet/pull/2104#discussion_r1732623091)), it is better to make the token symbol to fallback on an empty string `''`.
Unrelated: there is a slight mispelling in one of the variables.
> fix(frontend): correct fallback string when converting ckERC20

- src/frontend/src/lib/components/tokens/TokensSignedIn.svelte
There is a concurrency issue: when starting the `TokensSkeleton`, component `TokensDisplayHandler` is not mounted on loading, meaning that `tokens` variable is not updated, and it remains `undefined`. That affects `loading` itself and it keeps being `true`. 
Moved `TokensDisplayHandler` above `TokensSkeletons`.
Screen was stuck to this:
It updates correctly:
> fix(frontend): tokens not showing when loading

- HACKING.md
It was reported that there is an issue when building the backend locally:
```bash
error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-DENABLE_MODULE_RECOVERY=1" "-o" "/Users/userABC/projects/dfinity/oisy-wallet/target/wasm32-unknown-unknown/release/build/secp256k1-sys-67449d6ae1248da9/out/3fec8a5f3c4f77fb-wasm.o" "-c" "wasm/wasm.c" …
```
> chore(docs): add clang patch to HACKING.md

- src/frontend/src/eth/constants/ckerc20.constants.ts
Small mistype, just to reduce the spelling errors.
> chore(frontend): mistype in inline comment

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/lib/components/tokens/TokenCard.svelte
- src/frontend/src/lib/components/tokens/TokenName.svelte
To be consistent, we add the `ck` tag in the token list of the `ManageModal`.
- Separate component specific for the `TokenName`.
- Use such component in `ManageModal`.
> feat(frontend): add prefix tag to tokens in ManageModal

- src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte
Instead of calling again the balances store, we can use directly the `usdBalance` prop of type `TokenUi`.
Local replica unchanged:
All balances
Only non-zero balances
> refactor(frontend): use existing balance prop to filter tokens

- scripts/send.tokens.sh
Since we are testing in local replica some ckERC20 related features, it is useful to have the send.token script send some ckSepoliaUSDC locally.
> ci(frontend): add ckUSDC to local send.tokens script

- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/types/token.ts
- src/frontend/src/lib/utils/exchange.utils.ts
- src/frontend/src/lib/utils/tokens.utils.ts
The balance store is called a few times in the code, related to derived store `combinedDerivedEnabledNetworkTokensUi`. So, to simplify the code, we add the prop `balance` to type `TokenUi`.
After this PR, we will make use of the new prop throughout the code.
- Add `balance` to `TokenUi`.
- Calculate balance in store `combinedDerivedEnabledNetworkTokensUi`.
No changes in local replica, just more loading time (that should be compensated once we use the new prop).
> feat(frontend): add balance to TokenUi

- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
We aim to simplify the sorting logic and reduce the iterations. As first step we merge the functions that were sorting by marketcap and pinning a pre-determined list of tokens on top.
> refactor(frontend): merge functions to sort and pin

- package.json
When discussing release tagging, it was visible that `git tag` is not sorted by semantic version.
Given that we already have the `npm` `semver` package installed, this is an easy pain point to address.
- Add an `npm` command to print git tags sorted by semver.
```
$ npm run tags
> @dfinity/oisy-wallet@0.0.37 tags    <--- Note: This is added by `npm run`.
> node_modules/.bin/semver $(git tag) <--- Without `npm run` we get just the tags and no header.
0.0.1
0.0.2
0.0.3
0.0.4
0.0.5
0.0.6
0.0.7
0.0.8
0.0.9
0.0.10
0.0.11
0.0.12
0.0.13
0.0.14
0.0.15
0.0.16
0.0.17
0.0.18
0.0.19
0.0.20
0.0.21
0.0.22
0.0.23
0.0.24
0.0.25
0.0.26
0.0.27
0.0.28
0.0.29
0.0.30
0.0.31
0.0.32
0.0.33
0.0.34
0.0.35-0
0.0.35
0.0.36
0.0.37
```
> feat(devops): Add npm command to list tags ordered by semver

- dfx.json
Since I was already there, let's also bump a more recent version of II for local development.
- Use newest release of II.
> chore(replica): bump II for local development

- scripts/download.icp.sh
For the Oisy signer we will need few new features, notable the consent message ICRC-21, which are available in the newest version of the ICP ledger.
- Bump commit hash to download ICP ledger and index for local development.
> chore(replica): bump ICP ledger and index version for development

- src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte
- src/frontend/src/lib/types/token.ts
- src/frontend/src/lib/utils/tokens-ui.utils.ts
- src/frontend/src/tests/lib/utils/tokens-ui.utils.spec.ts
We move, to a separate module, the definition of the tokens list to be displayed when re-sorting. Furthermore, there are some tests to verify the actual workflow of the logic.
> refactor(frontend): move defineTokensToDisplay to separate module

- src/frontend/src/env/networks.icrc.env.ts
An entry in `ICRC_TOKENS` was missing which lead the support for ckXAUT to be partial - i.e. ckXAUT is not available in the list of tokens on production.
Before
After
> fix(frontend): ckXAUT not available in the list of tokens

- scripts/build.tokens.ckerc20.mjs
We include `EURC` and `XAUT` among the ERC20 tokens that have different logo between them and their ck-counterparty.
Ran the workflow `Update Tokens` on this branch and [there was no change](https://github.com/dfinity/oisy-wallet/actions/runs/10611870136/job/29412334576).
> ci(frontend): exclude EURC and XAUT from fetching logo

- src/frontend/src/eth/components/fee/FeeDisplay.svelte
- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/stores/fee.store.ts
- src/frontend/src/icp-eth/components/fee/FeeAmountDisplay.svelte
- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
When there is an error for insufficient balance, we would like to show the same number as decimals as the balance already showed.
- Add `feeDecimals` to Fee Context.
- Set `feeDecimals` throughout the code using already existing token values used by `feeSymbol` and `feeTokenId`.
- Add prop `feeDecimals` to `FeeAmountDisplay`.
> style(frontend): show same decimals as balance in fee

- src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte
- src/frontend/src/icp/derived/ethereum-fee.derived.ts
Since the ck-conversions fees related to Ethereum transaction fees are always paid in `ckETH`, we change the component `EthereumEstimatedFee` to reflect that. The change is visible happens only in `ckETH --> ETH` conversion modals.
Both situations below end in the same place and results for the user, nothing changes in final amounts, only the dialectics on how the Ethereum fees are paid by the user, that will reflect [what is happening in the background effectively](https://github.com/dfinity/ic/blob/master/rs/ethereum/cketh/docs/cketh.adoc#cost-of-a-withdrawal), that is how it is effectively already implemented in the Oisy code.
The Ethereum fees were showed in `ETH`, telling the users that it is the amount that it would be subtracted from the final `ETH` amount that they would expect, …
> feat(frontend): show all ck-conversions fees in ck-denominations

- e2e/receive-tokens-modal.spec.ts
- e2e/utils/selectors.utils.ts
As agreed in one of the previous PRs, I moved nested selectors generation in a separate util
> test(e2e): nested selectors generation

- src/frontend/src/lib/i18n/en.json
In the code, apart from conservative hard-coded numbers, we calculate the ck-conversion fees related to Ethereum fetched from the minter using the `eip_1559_transaction_price` call.
The `max_transaction_fee` fetched with call `eip_1559_transaction_price` from the minter is not real-time: it is re-calculated everytime there is a new withdrawal request to the minter. The same call provides the last update timestamp.
So, in this PR we remove the `30 seconds` proxy string.
> chore(frontend): adjust Ethereum estimated fee label

- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/types/token.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
Prop `formattedBalance` (introduced in PR #2150 ) of `TokenUI` is not used, since there is prop `balance` that is the most straightforward way of getting a token balance value. Plus, we slightly reduce computational time.
> feat(frontend): revert unused prop formattedBalance

- src/frontend/src/lib/components/tokens/TokenCardWithUrl.svelte
- src/frontend/src/lib/components/tokens/TokensSignedOut.svelte
When signed out it was possible to select the blurred tokens list using `Tab` clicks. We remove this possibility.
In local replica, clicking in loop `Tab`, will never reach the tokens list.
> feat(frontend): remove tab selector when signed out

- .eslintrc.cjs
- src/frontend/src/lib/components/tokens/TokenCardWithUrl.svelte
We include ES lint rule [no-inferrable-types](https://typescript-eslint.io/rules/no-inferrable-types/) and we fix related issues.
> feat(eslint): add no-inferrable-types rule

- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/utils/exchange.utils.ts
To reduce repetition of codes and optimize processing, function `usdValue` will accepts direct values instead of stores.
> refactor(frontend): simplify code to calculate USD balance

- package-lock.json
- package.json
A new official version of gix-cmp was released. We can use v4.7.0 instead of a "next" version.
> build(frontend): bump gix-cmp

- src/frontend/src/btc/components/BitcoinListener.svelte
- src/frontend/src/lib/components/core/Listener.svelte
There was an error in the console when the Bitcoin token was present in the list of tokens.
The error came because the EthListener was used in the Bitcoin token.
This PR provides the component that must implement the listener for bitcoin. But it doesn't implement it yet.
* New empty BitcoinListener component.
* Check also for bitcoin network in Listener project.
Tested locally that the error is not raised anymore.
> feat(frontend): Set up bitcoin listener

- src/frontend/src/lib/derived/network-tokens.derived.ts
To load balances for all enabled IC tokens, it will be useful to have a specific derived store, similar to what we have for ERC20 tokens.
Note that we are not using `['icp', 'icrc'].includes(....` because this is type checked, i.e. it would give an error if there was a mistype in the right-hand side of the comparison that does not match one of the possible values of TokenStandard.
> feat(frontend): enabled IC network tokens

- src/frontend/src/eth/components/send/EthSend.svelte
- src/frontend/src/icp/components/receive/IcReceive.svelte
- src/frontend/src/icp/components/send/IcSend.svelte
- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/services/token.services.ts
Since `loadTokenAndRun` is used both by components in `eth`, `icp` and `lib` folder, we move it to the `lib` folder.
Unrelated: we remove unused `runAndResetToken` function.
> refactor(frontend): move token.services to lib folder

- src/frontend/src/lib/services/address.services.ts
To be more coherent, function `certifyAddress` should accept a dynamic type that extends `Address`.
> fix(frontend): use dynamical type for certify address function

- src/frontend/src/lib/derived/address.derived.ts
- src/frontend/src/lib/stores/address.store.ts
- src/frontend/src/lib/utils/address.utils.ts
`OptionAddressData` and `OptionCertifiedAddressData` are basically the same thing, so we adapt `OptionAddressData` to "fill the shoes" of `OptionCertifiedAddressData`.
> refactor(frontend): remove redundant address data type

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
Step 1 of updating the chain selector with aggregate USD balance values: re-use util for calculation tokens total USD balance. In the next steps, it will be used to calculate this value for different networks (as shown on the screenshot).
> feat(frontend): util for tokens total USD balance calculation

- src/frontend/src/btc/components/BtcTransactions.svelte
- src/frontend/src/lib/components/hero/Hero.svelte
- src/frontend/src/lib/components/transactions/TransactionsSignedIn.svelte
The transactions page for Bitcoin was not showing balance, nor nice background.
The error was that it was using the ETH transactions page and that the hero didn't have an assigned background for btc.
* Create new component BtcTransactions.
* Use new component in TransactionsSignedIn.
* Add a background when the hero is for "btc".
> feat(frontend): Set up Btc Transactions page

- src/frontend/src/icp/components/transactions/IcTransactions.svelte
Remove unnecessary `h2` in IcTransactions.
* Pass only the text without `h2` to `Header` in IcTransactions.
Tested locally
> fix(frontend): Fix Header slot in IcTransactions

- src/frontend/src/eth/components/receive/EthReceiveMetamask.svelte
The Metamask button currently does not support sending ERC20 tokens - it always populates an ETH transaction.
We aim to fix this, but for now, the functionality is commented out.
- if standard === ethereum then button
> feat(frontend): render Metamask receive button for ETH only (for now)

- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/icp/services/ic-send.services.ts
There is a 2s timeout after an IC send transactions is complemented to optimistically fetch the transactions. Given that we are interested to get to know how long does a send least, it's not really correct to count that timeout within the overall send. Therefore we can track the anonymous metrics when the send is over.
- Pass the analytics as callback for `sendIc` and collect analytics when send is done.
> feat(frontend): track analytics when IC send completed

- src/frontend/src/eth/components/send/SendDestination.svelte
- src/frontend/src/icp-eth/utils/icp-account.utils.ts
- src/frontend/src/icp/services/ic-send.services.ts
- src/frontend/src/icp/utils/ic-send.utils.ts
- src/frontend/src/icp/utils/icp-account.utils.ts
- src/frontend/src/lib/utils/account.utils.ts
Since it is being used both by ETH and ICP components/functions, we move `invalidIcpAddress` to folder `lib`. This is the same practice that other functions in the same module have: for example `isEthAddress` is used both by ETH and ICP modules.
As side effect of this, we have one less possible loop dependency inside `icp` folder.
> refactor(frontend): move invalidIcpAddress to lib folder

- src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
- src/frontend/src/icp/components/core/IcLoaderWallets.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
Step 3 of updating the chain selector with aggregate USD balance values: adjust `network-tokens.derived` to load enabled tokens balance regardless if a network selected by user or not. We discussed with @AntonioVentilii-DFINITY the performance aspect of this change, and since it will be basically the amount of data loaded (and hence time needed to load it) as if we were in Chain Fusion, it should not affect the user experience and performance.
> feat(frontend): update network-tokens to enabled tokens balance

- src/frontend/src/lib/derived/network.derived.ts
Store `notPseudoNetworkChainFusion` was not being used.
> chore(frontend): remove unused store

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
The idea is to highlight that `sumTokensUiUsdBalance` expects a list of `TokenUi`, where `usdBalance` is already pre-calculated. In the following PRs, a new method (`sumTokensUsdBalance`) will be created to do the same but for `Token` (no `usdBalance` available).
> refactor(tokens): adjust sumTokensUsdBalance method name

- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
- src/frontend/src/tests/mocks/balances.mock.ts
- src/frontend/src/tests/mocks/exchanges.mock.ts
- src/frontend/src/tests/mocks/tokens.mock.ts
For readability and reusability we move the mocked values of tokens, balances and exchanges stores in their specific modules.
> refactor(frontend): move test mock values to specific folders

- src/frontend/src/lib/utils/token.utils.ts
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/token.utils.spec.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
Just for coherence, we move the function `calculateTokenUsdBalance` to the `token.util` module.
> refactor(frontend): move util function calculateTokenUsdBalance

- src/frontend/src/lib/utils/token.utils.ts
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/utils/token.utils.spec.ts
For better readability and reusability, we create a function to map an object `Token` to an object `TokenUi`.
> feat(frontend): create map for TokenUi

- src/frontend/src/lib/components/networks/MainnetNetwork.svelte
- src/frontend/src/lib/components/networks/Network.svelte
- src/frontend/src/lib/components/networks/NetworkButton.svelte
- src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
The goal is to display mainnet tokens total USD balances in `NetworkSwitscher`.
> feat(tokens): display mainnet tokens total USD

- src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte
The "zero balance" toggle should show non-zero balances even for token that have no exchange rate.
> fix(frontend): toggle should show all non-zero balances

- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/utils/tokens.utils.ts
It does not make sense to run the sorting by balance if the balance store is not initiated.
> feat(frontend): avoid sorting if no balances store

- src/frontend/src/eth/components/fee/FeeDisplay.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
The label for the ETH fees is localized:
> chore(frontend): localize label of ETH fee

- package-lock.json
- package.json
I want to use `"regtest"` from `BitcoinNetwork` type. The new entry was added in https://github.com/dfinity/ic-js/pull/713 and it hasn't been published in any version but next yet.
* Upgrade ckbtc to `3.0.0-next-2024-09-09`
I checked that the new entry is accessible in node_modules.
> chore(frontend): Upgrade ckbtc

- src/frontend/src/btc/derived/networks.derived.ts
- src/frontend/src/btc/derived/tokens.derived.ts
- src/frontend/src/env/networks.env.ts
- src/frontend/src/env/tokens.btc.env.ts
The goal is to create a new test network and token (`BTC (Regtest` / `Bitcoin (Regtest)`) that are gonna be used for local BTC development.
> feat(btc): add Btc Regtest network and token

- src/frontend/src/lib/components/core/LoadersGuard.svelte
- src/frontend/src/routes/(app)/+layout.svelte
Extract a component for the loader guards which can ultimately be used in various routes - such as the new route in #2293 - as well.
- Move `Loaders` and `NoLoaders` mount according auth in a dedicated module.
> refactor(frontend): extract loader guards component

- .eslintrc.cjs
- src/frontend/src/routes/(app)/+layout.svelte
- src/frontend/src/routes/(app)/transactions/+page.svelte
- src/frontend/src/routes/+layout.svelte
As final step of sorting Svelte imports, we make the rule include all the `.svelte` files.
> feat(lint): sort svelte imports

- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/components/tokens/ManageTokensModal.svelte
- src/frontend/src/icp/components/fee/BitcoinFeeContext.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkBTC.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte
- src/frontend/src/icp/components/transactions/IcTransactions.svelte
- src/frontend/src/icp/components/transactions/IcTransactionsBitcoinStatusBalance.svelte
- src/frontend/src/lib/components/core/Loader.svelte
- src/frontend/src/lib/components/settings/SettingsSignedIn.svelte
- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/derived/auth.derived.ts
- src/frontend/src/routes/+layout.svelte
Instead of accessing `$authStore.identity` in our components we can derive the optional identity `$authIdentity`. 
No big reasons, just a bit cuter to read.
- Derive identity
- Use derived information instead of accessing store
> feat(frontend): derive auth identity

- src/frontend/src/env/tokens.btc.env.ts
- src/frontend/src/lib/api/idb.api.ts
- src/frontend/src/lib/derived/address.derived.ts
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/lib/stores/address.store.ts
Each Bitcoin network has a different address for the user.
Therefore, we need to show Testnet (if testnts) and Regtest (if testnets and local) in the addresses list.
In this PR, I introduce stores for the testnet addresses and adapt current services to them.
* One more index db store for the testnet address (no need to store the regtest).
* Two new stores to save Bitcoin testnet addresses.
* Two new derived stores to get the address for Bitcoin Testnet and Regtest.
* Expand loadBtcAddress to support all Bitcoin networks.
This was tested along the UI code in #2298
> feat(frontned): Add stores and change services for other bitcoin addresses

- .github/workflows/e2e-tests.yml
- .github/workflows/update-snapshots.yml
To fix the `update-snapshots` workflow as well as to make sure that `e2e-tests` always works as expected, we need to add back the checkout step before building oisy-backend (even though the `oisy-backend` action also has the checkout step inside).
> ci(e2e): fix update-snapshots workflow

- .gitignore
- HACKING.md
- scripts/add.tokens.bitcoin.sh
- scripts/dfx.start-with-bitcoin.sh
- scripts/reset.bitcoin-node.sh
- scripts/setup.bitcoin-node.sh
We want to be able to test that the development of the Bitcoin integration works as expected.
In order to do that, we need a local Bitcoin node.
This PR provides two main scripts to set up the local node and start dfx with Bitcoin. As well as some other utilities to be used while testing.
* Add a couple of entries to `.gitignore`.
* Add a script to set up the local Bitcoin node.
* Add a script to start dfx with Bitcoin.
* Add a script to mine tokens.
* Add a section in Hacking.md to explain how to use the scripts.
I and Denys tested locally that the scripts worked as expected.
> feat(devops): Add scripts to set up Bitcoin local node

- src/frontend/src/icp-eth/derived/cketh.derived.ts
According to the type, it is unnecessary to fallback `ckEthereumTwinTokenNetwork` since the property `network` of type `Token` cannot be `undefined`.
> chore(frontend): remove unnecessary undefined condition

- src/frontend/src/eth/components/transactions/Transaction.svelte
For better readability, we extract the logic of the label in the `Transaction` component. That will come useful for a future PR.
For the same reason, unrelated, we move the `pending` variable definition above.
> refactor(frontend): extract label in transaction component

- src/frontend/src/lib/components/core/Loader.svelte
- src/frontend/src/lib/services/address.services.ts
Each Bitcoin network has a different address for the user.
Therefore, we need to show Testnet (if testnts) and Regtest (if testnets and local) in the addresses list.
In this PR, we create a listener of the testnets store to load the btc testnet address in the store and set it up in the `Loader` component.
* New service `listenTestnetNetworksToAddBtcTestnetAddresses` to listen to changes in the testnets store.
* Load the testnet address by listening to the testnet store with listenTestnetNetworksToAddBtcTestnetAddresses used in Loader.
Tested together with the rest of the changes in #2298
> feat(frontend): Load testnet btc address

- scripts/build.signer.sh
- src/declarations/signer/signer.did
- src/declarations/signer/signer.did.d.ts
- src/declarations/signer/signer.factory.certified.did.js
- src/declarations/signer/signer.factory.did.js
The signer has a new method "caller_btc_balance" that we would like to use.
* Update the downloaded signer version from 0.1.1 to 0.1.2.
Note: This is NOT available in production yet, but is expected to be soon.
See CI
> chore(signer): Bump signer release

- src/frontend/src/icp/components/send/IcSend.svelte
I checked and the `nnsClose` event is not used in the parent components where `IcSend` is used, so we remove it.
> chore(frontend): remove unused bubble event in IcSend

- src/frontend/src/env/networks.icp.env.ts
- src/frontend/src/env/networks.icrc.env.ts
- src/frontend/src/lib/types/canister.ts
To avoid repetition of code, we create a common type for optional-nullable type `CanisterIdText`.
> refactor(frontend): common type for optional-nullable CanisterId

- src/frontend/src/eth/derived/wallet-connect.derived.ts
- src/frontend/src/icp/utils/ckbtc-transactions.utils.ts
- src/frontend/src/lib/components/receive/ReceiveAddressWithLogo.svelte
- src/frontend/src/lib/derived/nav.derived.ts
- src/frontend/src/lib/types/string.ts
- src/frontend/src/lib/utils/input.utils.ts
- src/frontend/src/lib/utils/nav.utils.ts
To avoid repetition of code, we create a common type for optional-nullable type `string`.
> refactor(frontend): common type for optional-nullable string

- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/components/fee/FeeAmountDisplay.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
- src/frontend/src/icp-eth/stores/send.store.ts
- src/frontend/src/icp/utils/cketh.utils.ts
- src/frontend/src/lib/components/send/SendData.svelte
- src/frontend/src/lib/components/send/SendSource.svelte
- src/frontend/src/lib/derived/balances.derived.ts
- src/frontend/src/lib/types/balance.ts
- src/frontend/src/lib/types/token.ts
- src/frontend/src/lib/utils/exchange.utils.ts
To avoid repetition of code, we create a common type for balance when is defined as `BigNumber`.
> refactor(frontend): common type for balance as BigNumber

- src/frontend/src/btc/components/BtcManageTokenToggle.svelte
- src/frontend/src/btc/utils/token.utils.ts
- src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
Add BTC to ManageTokens modal.
* New component for toggle of BTC tokens. It's a dummy component which renders a disabled toggle.
* Btc token util to identify bitcoin tokens.
* Add `enabledBitcoinTokens` in the list of tokens in ManageToken and manage the scenario in the toggle for bitcoin tokens.
> feat(frontend): Add BTC to manage tokens

- scripts/build.signer.sh
The command that creates the signer args file leaves unintended characters in the argument file.  The code was moved from a shell variable to a heredoc, thereby introducing these errors.
- Remove quotes and escapes from the signer args heredoc.
Running `scripts/build.signer.sh` now creates a valid candid file.
> fix(devops): Fix shell quoting in signer args file

- scripts/setup.bitcoin-node.sh
New minted blocks were not adding balance to the address.
The reason seemed to be a config parameter when setting up the local node.
* Remove the parameter (it was there to reduce the amount of memory, which is a premature optimization).
> fix(frontend): Fix local bitcoin node setup

- src/frontend/src/icp-eth/services/custom-token.services.ts
- src/frontend/src/icp/services/ic-custom-tokens.services.ts
To avoid repetition of code, we create a function to convert a `SaveCustomToken` type to `CustomToken`.
> refactor(frontend): mapping util to convert to CustomToken

- src/frontend/src/eth/services/erc20-user-tokens-services.ts
- src/frontend/src/icp-eth/services/user-token.services.ts
To avoid repetition of code, we create a function to convert a `SaveUserToken` type to `UserToken`.
> refactor(frontend): mapping util to convert to UserToken

- src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte
- src/frontend/src/lib/components/tokens/TokenExchangeValueSkeleton.svelte
Similar to the balance, we want to show a skeleton for the exchange value if there is no balance loader started.
> style(frontend): skeleton text for loading exchange value

- .eslintrc.cjs
- eslint-local-rules.cjs
- src/frontend/src/icp/stores/bitcoin-fee.store.ts
- src/frontend/src/icp/stores/ethereum-fee.store.ts
- src/frontend/src/lib/types/utils.ts
We create a custom lint rule to use the type wrapper Option introduced in PR #2326 , and we fiz related issues.
UNRELATED: I sorted alphabetically the rules in `eslintrc` file, for better readability.
> feat(lint): create lint rule to use Option type wrapper

- src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte
- src/frontend/src/lib/components/tokens/TokenBalance.svelte
In case the `balance` prop of the token is null (meaning that the loader is there but there is an issue/error, or it was stopped), we would like to show a dash `-` instead of `0`, both for the balance and for the USD balance.
Simulating with random tokens with `null` balance.
> style(frontend): show a dash for null balances

- src/frontend/src/env/tokens.env.ts
- src/frontend/src/eth/components/transactions/Transaction.svelte
- src/frontend/src/eth/utils/eth.utils.ts
- src/frontend/src/lib/types/token.ts
With PR #2350 , we can use the twinTokenSymbol prop of ETH and SepoliaETH.
- Create common type for token that is required and have linked data.
- Create util to check if a token can be one of the supported Ethereum native tokens.
- Adapt usage in `Transaction` component.
Local replica worked as usual.
> refactor(frontend): use twinTokenSymbol prop for Ethereum native tokens

- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/config/send.config.ts
Renamed config `sendWizardStepsComplete` to `allSendWizardSteps`, since it is more clear.
> refactor(frontend): rename config with all send steps

- src/frontend/src/env/onramper.env.ts
- src/frontend/src/lib/components/buy/Buy.svelte
- src/frontend/src/lib/components/buy/BuyButton.svelte
- src/frontend/src/lib/components/buy/BuyModal.svelte
- src/frontend/src/lib/components/hero/Actions.svelte
- src/frontend/src/lib/components/icons/IconBuy.svelte
- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/stores/modal.store.ts
- src/frontend/src/lib/types/i18n.d.ts
As initial step for OnRamper onbarding, we create the `Buy` button and a related modal. The modal will be empty for now and the button visible only through a custom env flag `VITE_ONRAMPER_ENABLED`.
> feat(frontend): add Buy button [GIX-2854][GIX-2705]

- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendReview.svelte
- src/frontend/src/eth/components/tokens/AddTokenReview.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectForm.svelte
- src/frontend/src/icp-eth/components/info/InfoEthereum.svelte
- src/frontend/src/icp/components/info/InfoBitcoin.svelte
- src/frontend/src/icp/components/send/IcSendForm.svelte
- src/frontend/src/icp/components/send/IcSendReview.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte
- src/frontend/src/lib/components/manage/AddTokenByNetworkToolbar.svelte
- src/frontend/src/lib/components/manage/ManageTokens.svelte
With the introduction of a determined opacity for class `disabled` of `primary` and `secondary` buttons (PR #2345 ), we can remove the `opacity` class in the components, since they will be superseded by the CSS definition.
> chore(frontend): remove redundant opacity class [GIX-2929]

- src/frontend/src/lib/components/hero/HeroSignIn.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/styles/global/colors.scss
- src/frontend/src/lib/styles/global/text.scss
- src/frontend/src/lib/types/i18n.d.ts
- tailwind.config.js
New style for the header title when signed out.
> style(frontend): change color of header title when signed out [GIX-2955]

- src/frontend/src/eth/derived/token.derived.ts
- src/frontend/src/eth/derived/tokens.derived.ts
To be more precise, the correct type of the Ethereum tokens are now `RequiredTokenWithLinkedData`.
> chore(frontend): set more correct types for Ethereum native tokens

- src/frontend/src/icp/components/core/IcLoaderWallets.svelte
- src/frontend/src/icp/constants/ic.constants.ts
- src/frontend/src/icp/services/ckbtc-listener.services.ts
- src/frontend/src/icp/services/ckbtc.services.ts
- src/frontend/src/icp/services/ic-send.services.ts
- src/frontend/src/icp/utils/wallet.utils.ts
- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/lib/types/listener.ts
- src/frontend/src/lib/utils/wallet.utils.ts
Move wallet utils from `icp` to `lib` to re-use them for both BTC and IC wallet workers.
> refactor(frontend): move wallet utils to lib

- .github/dependabot.yml
We would like to auto-update devDependencies, with the due exceptions (like `typescript` and `lint`).
> ci(dependabot): add devDependencies auto-updates

- src/frontend/src/eth/components/transactions/Transactions.svelte
- src/frontend/src/icp-eth/utils/cketh.utils.ts
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning util `toCkMinterInfoAddresses`.
> refactor(frontend): use object param for toCkMinterInfoAddresses util

- src/frontend/src/icp-eth/services/custom-token.services.ts
- src/frontend/src/icp-eth/services/user-token.services.ts
- src/frontend/src/lib/services/token.services.ts
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning util `autoLoadToken`'s param `findToken`. Two different functions are fed there: `findCustomToken` and `findUserToken`.
> refactor(frontend): use object param for autoLoadToken util

- src/frontend/src/eth/components/core/EthWalletAddress.svelte
- src/frontend/src/eth/components/transactions/TransactionModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendData.svelte
- src/frontend/src/icp/components/core/IcWalletAddress.svelte
- src/frontend/src/lib/components/receive/ReceiveAddressWithLogo.svelte
- src/frontend/src/lib/components/settings/SettingsSignedIn.svelte
- src/frontend/src/lib/utils/format.utils.ts
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning util `shortenWithMiddleEllipsis`.
> refactor(frontend): use object param for shortenWithMiddleEllipsis util

- src/frontend/src/lib/components/core/Alpha.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/styles/global/colors.scss
- tailwind.config.js
We update the style for the Alpha warning.
> style(frontend): new style for Alpha warning [GIX-2981]

- src/frontend/src/lib/components/ui/Json.svelte
- src/frontend/src/lib/utils/json.utils.ts
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning util `stringifyJson`.
> refactor(frontend): use object param for stringifyJson

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte
- src/frontend/src/lib/components/networks/NetworkButton.svelte
- src/frontend/src/lib/utils/format.utils.ts
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning util `formatUSD`.
> refactor(frontend): use object param for formatUSD

- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/components/send/SendNetwork.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/services/send.services.ts
- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
- src/frontend/src/icp-eth/components/send/ConvertETH.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
- src/frontend/src/icp-eth/utils/cketh.utils.ts
- src/frontend/src/icp/components/convert/HowToConvertEthereumModal.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning util `toCkMinterInfoAddresses`.
> refactor(frontend): use object param for toCkMinterInfoAddresses

- src/frontend/src/lib/components/icons/OisyWalletLogo.svelte
For good form (and to avoid strange behavior during screen re-sizing), we set the width of the logo to a fixed value (that is the same as the SVG that defines it).
> refactor(frontend): fixed width for logo

- src/frontend/src/lib/components/core/Alpha.svelte
- src/frontend/src/lib/components/hero/Header.svelte
- src/frontend/src/lib/components/hero/Hero.svelte
We move the Alpha warning in the header, but with the condition that is only for large screens (>1280px).
> style(frontend): move Alpha warning to header [GIX-2981]

- src/frontend/src/lib/components/hero/about/AboutItem.svelte
Set color of about buttons to primary.
> style(frontend): adjust color of about buttons [GIX-2955]

- src/frontend/src/lib/components/core/Back.svelte
Set the color of the Back button to primary.
> style(frontend): set back button color to primary [GIX-2973]

- e2e/utils/qr-code.utils.ts
- playwright.config.ts
Fix issue that appeared after the `jimp` package got updated. Also, temporary increased timeout value due to tokens not being fully loaded with the default value (30s).
> test(e2e): fix current issues with e2e

- src/frontend/src/eth/providers/alchemy-erc20.providers.ts
Correction on an "temporary" exception create by to the new custom ES lint rule introduced by PR https://github.com/dfinity/oisy-wallet/pull/2416: instead of being temporary, it should be a real exception since the function needs to have sequential arguments.
> chore(frontend): correct exception to lint rule about object param

- src/frontend/src/lib/components/core/Erc20Icp.svelte
- vite.config.ts
Resolve the warnings:
```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
etc.
```
Source: https://stackoverflow.com/a/79003101/5404186
- Use modern compiler for sass
- Remove unused and incompatible `@use` additional data
- Adapt the remaining media reference (we might resolve it with …
> build(frontend): migrate to scss modern-compiler

- src/frontend/src/lib/components/ui/RoundedIcon.svelte
New background color for the icon in the transaction card. Since RoundedIcon component is used only in the transactions card, we change directly the default prop.
> style(frontend): change background of transaction card icon

- src/frontend/src/lib/components/core/Background.svelte
- src/frontend/src/lib/components/icons/OisyWalletLogo.svelte
To be more precise and coherent with the Tailwind definition of small-screens, we adjust the `srcset` conditions to have:
- min width from `641` to `640`
- max width from `640` to `639`
> refactor(frontend): correct media condition in srcset

- src/frontend/src/lib/components/hero/Header.svelte
When logged in, the Alpha warning position is not so pretty, since it could fit inside the header. Thir PR fixes it, making its position when logged in exchangable.
> style(frontend): improve Alpha warning position when logged in [GIX-2981]

- src/frontend/src/lib/components/tokens/ManageTokensButton.svelte
To have a more uniform UI, we expand the manage buttons for smaller screens.
> style(frontend): expand manage button on smaller screens

- scripts/build.tokens.ckerc20.mjs
- scripts/check.i18n.mjs
We remove one of the "temporary" exceptions to the new custom ES lint rule introduced by PR #2416 , and adapt the code. Specifically the one concerning scripts.
> refactor(ci): use object param for scripts

- src/frontend/src/lib/derived/token.derived.ts
Derived store `tokenCategory` was not being used.
> chore(frontend): remove unused derived store

- vite.config.ts
Dependency `three` was deprecated so we don't need to chunk it anymore.
> chore(build): remove three from chunk-able dependencies

- package-lock.json
- package.json
- src/frontend/src/eth/services/send.services.ts
- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/lib/actors/actors.ic.ts
- src/frontend/src/lib/api/signer.api.ts
- src/frontend/src/lib/canisters/signer.canister.ts
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
- src/frontend/src/tests/lib/services/load-user-profile.spec.ts
- src/frontend/src/tests/mocks/identity.mock.ts
The idea is to create a signer canister class (instead of using actors) and refactor `signer.api` methods to use it.
> feat(frontend): use signer API via canister

- scripts/build.signer.sh
The `signer.did` file is included in new cf signer releases, as it should be.  It can be added manually to old releases.  Previously the candid file was taken from within the codebase but that breaks across versions (when the file moves).  Also the release files should contain all files needed to work with that version; users should not have to search through the codebase to find the candid.
- Update the download URL for the `signer.did`.
See CI
> refactor(devops): Get signer.did path from release

- .eslintrc.cjs
- e2e/utils/pages/homepage.page.ts
- env.utils.ts
- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/eth/types/send.ts
- src/frontend/src/icp/types/ic.ts
- src/frontend/src/lib/actors/query.ic.ts
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/lib/stores/user-profile.store.ts
- src/frontend/src/lib/types/network.ts
- src/frontend/src/lib/types/token.ts
- src/frontend/src/lib/types/utils.ts
- src/frontend/src/lib/utils/i18n.utils.ts
- src/frontend/src/lib/utils/nav.utils.ts
- src/frontend/src/tests/lib/utils/certified-store.utils.spec.ts
- vite.utils.ts
We want to add the ES lint rule of [consistent-type-definitions](https://typescript-eslint.io/rules/consistent-type-definitions/), that enforces the usage of `interface` instead of `type`.
- Add new rule to ESlint configs.
- Fix related new issues.
It worked: it flagged new issues that we solved.
> refactor(frontend): enforce use of interface instead of type

- src/frontend/src/lib/types/token.ts
Type `TokenIndexKey` was not used anymore.
> chore(frontend): remove unused token type

- src/frontend/src/lib/components/send/SendTokensList.svelte
We use existing component `ContentWithToolbar`, introduced in PR #2357, for `SendTokensList`.
> refactor(frontend): use existing component for stretched div

- src/frontend/src/app.html
Since the new defaults background and color are respectively white and black (the browser's default), we remove it as from `app.html`
> style(frontend): remove hard-coded colors in app.html

- src/frontend/src/env/tokens.env.ts
- src/frontend/src/lib/types/onramper.ts
- src/frontend/src/lib/types/token.ts
Another step to onboard Onramper is to map the correspondent Crypto ID to each token based [on this list](https://docs.onramper.com/docs/crypto-asset-support).
For now, we will set it just for ICP and ETH, but, after having tested more, map the rest.
- Create new type to define the mapping to Crypto ID.
- Adjust RequiredToken type to excepts new type TokenBuyable.
- Set values for ICP and ETH.
> feat(frontend): add Onramper ID for tokens

- src/frontend/src/lib/styles/global/gix.scss
According to requirements, we use the primary color for the icon and the line of the completed progress steps.
> style(frontend): change color of icon check in ProgressSteps [GIX-2983]

- src/frontend/src/icp/schedulers/wallet.scheduler.ts
- src/frontend/src/lib/types/post-message.ts
Since we are gonna have 2 WalletWorkers, we need to adjust the existing `PostMessageResponseStatus.syncWalletStatus` to make it specific for the IC wallet. The new one for BTC will be called `syncBtcWalletStatus`.
> feat(frontend): rename syncWalletStatus to syncWalletIcStatus

- src/frontend/src/icp/types/ic.post-message.ts
- src/frontend/src/lib/types/post-message.ts
The idea is to re-use wallet worker interfaces as much as possible. For now, BTC will have a separate type, but after I start working on adding transactions to the BTC worker, `PostMessageDataResponseBtcWallet` can be deleted.
> feat(frontend): reuse PostMessageWalletData interface for BTC and IC

- src/frontend/src/lib/components/ui/ButtonHero.svelte
- src/frontend/src/lib/components/ui/HeroButtonGroup.svelte
We reduce a little the size of the Hero button group for smaller screens. Plus we slightly reduce the padding for the other screens too.
> style(frontend): resize Hero buttons group for smaller screens

- src/frontend/src/lib/styles/global/colors.scss
- src/frontend/src/lib/styles/global/theme.scss
- tailwind.config.js
New background color for the selection, without forcing the text color to change.
> style(frontend): new color for selection

- src/frontend/src/lib/derived/exchange.derived.ts
Extend exchange.derived with BTC testnet and regtest in order to calculate `usdBalance` for those tokens.
> feat(frontend): extend exchange.derived with BTC regtest

- src/frontend/src/icp/schedulers/ic-wallet.scheduler.ts
- src/frontend/src/icp/workers/icp-wallet.worker.ts
- src/frontend/src/icp/workers/icrc-wallet.worker.ts
Similar to BTC wallet scheduler, we want to rename `ic/wallet.scheduler` to `ic-wallet.scheduler`.
> feat(frontend): rename IC wallet scheduler

- src/frontend/src/lib/components/ui/ContentWithToolbar.svelte
On mobile (when the screen is longer) it is noticeable that the buttons are not at the bottom of the modal, as they should.
That is because the `stretch` class is not correctly set in component `ContentWithToolbar`: it was passed to `<slot>` that does not accept it.
> fix(frontend): pass class stretch to content of ContentWithToolbar

- src/frontend/src/btc/components/core/BtcWalletAddress.svelte
- src/frontend/src/lib/components/core/MenuWallet.svelte
The goal is to display BTC addresses in the way as it's done for other networks.
Desktop:
Mobile:
> feat(frontend): implement BTC wallet address component

- scripts/build.signer.sh
- src/declarations/signer/signer.did
- src/declarations/signer/signer.did.d.ts
- src/declarations/signer/signer.factory.certified.did.js
- src/declarations/signer/signer.factory.did.js
- src/frontend/src/lib/canisters/signer.canister.ts
- src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
We introduced breaking changes and new endpoints in CFS.
In this PR, I updated the release version of the signer canister which in turn updates the declaration files.
I also fixed the breaking changes with minimal edits. Proper error management will be added in subsequent PRs.
* Change signer release to `0.2.1`.
* Fix breaking changes in the declarations in `canisters/signer.canister.ts`.
All changes within `src/declarations/signer/*` were created by executing `npm run generate` after running `./scripts/build.signer.sh` with the new release.
I deployed the signer to the local replica with `./scrtips/deploy.signer.sh` using `--mode reinstall` because I already had one signer installed and I had to force the reinstallation.
After reinstallation I was able to run Oisy locally.
> chore(devops): Update signer release version

- src/frontend/src/lib/derived/exchange.derived.ts
Add exchange rate for BTC testnet. For now, we will assume that 1 BTC mainnet = 1 BTC testnet.
> feat(frontend): add exchange rate for BTC testnet

- src/frontend/src/lib/components/buy/BuyModal.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
We would prefer to have a clear indication that Onramper is in DEV mode when an user clicks on the Buy button: we adapt the modal title based on the ENV.
> feat(frontend): change Buy modal title based on Onramper env [GIX-3024]

- src/frontend/src/lib/components/hero/about/AboutHowModal.svelte
- src/frontend/src/lib/components/hero/about/AboutWhatModal.svelte
To be more precise, the title in the About modal should be a `<span>` instead of `<p>`.
> style(frontend): change About modals title to be span

- src/frontend/src/lib/styles/global/gix.scss
- src/frontend/src/lib/styles/global/layout.scss
- src/frontend/src/lib/styles/global/variables.scss
The modal style changes: we remove the dark frame and we adjust the layout a bit. Furthermore, for mobile version we leave a bit of margin to sho the backdrop.
UNRELATED: since we are creating a new CSS variable for `--padding-2_5x`, we use it in another similar instance.
Desktop
Mobile with large screen
Mobile with small screen
> style(frontend): new style for modals [GIX-3021]

- src/frontend/src/lib/components/hero/Hero.svelte
The padding for the Hero for larger screen should be adapted to not be negative.
> style(frontend): fix negative padding in Hero for larger screens [GIX-3022]

- src/frontend/src/eth/components/receive/EthReceiveMetamask.svelte
- src/frontend/src/lib/components/settings/SettingsSignedIn.svelte
- src/frontend/src/lib/components/tokens/ManageTokensButton.svelte
- src/frontend/src/lib/styles/global/button.scss
We want to change the secondary buttons to have the style of what we were calling tertiary. However, as discussed with the Design team, we keep the "old" secondary button (now called secondary-alt) to be re-used too.
- Rename button class `secondary` to `secondary-alt`
- Rename button class `tertiary` to `secondary`
- Adjust all instances of `secondary-alt` that should use the new `secondary`
> style(frontend): change secondary button to have lower contrast [GIX-3021]

- src/frontend/src/lib/styles/global/button.scss
New borders and spacing for buttons.
> style(frontend): change buttons borders and spacing [GIX-3021]

- src/frontend/src/eth/components/wallet-connect/WalletConnectActions.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
"Approve" or "Reject" are generic and will be reused in the signer so we can move the keys to "core" in the i18n file.
- Move keys and update references
> refactor(frontend): move i18n approve and reject keys

- src/frontend/src/lib/actors/agents.ic.ts
- src/frontend/src/lib/constants/app.constants.ts
Given that we have a constant file, it's a bit cleaner to also have the DFX replica host set there rather than at the agent level.
- Extract `REPLICA_HOST` constant
> refactor(frontend): extract replica host

- src/frontend/src/lib/styles/global/button.scss
A quick light hover effect for secondary button for consistency given that primary already has a strong hover effect.
No hover
Hover
> style(frontend): secondary hover

- src/frontend/src/lib/components/core/Alpha.svelte
- src/frontend/src/lib/components/ui/WarningBanner.svelte
The warning banner has been styled so we may reuse it to present some warning message such as currently in the signer branch. That's why this PR extract a component.
- Extract warning container from existing `Alpha` message
> feat(frontend): extract warning component

- src/frontend/src/lib/components/hero/Header.svelte
There was an issue with displaying the About buttons when signed out that was making them overflow outside.
> style(frontend): fix overflow of About buttons when signed out

- src/frontend/src/lib/services/address.services.ts
Change requested in a [previous PR's comment](https://github.com/dfinity/oisy-wallet/pull/2509/files#r1776345114).
* Change the type of param `setIdbAddress` from `undefined | fn` to `null | fn`.
Still working locally.
> fix(frontend): Change an `undefined` to `null`.

- src/frontend/src/lib/components/core/Loader.svelte
As noticed by @AntonioVentilii-DFINITY, BTC address for testnet was always loading w/o feature flag consideration. This PR fixes it.
> fix(frontend): hide btc testnet address load under feature flag

- package-lock.json
- package.json
I realized that the BitcoinNetwork from ckbtc didn't have the latest changes. Specifically, it didn't include "regtest" in the Bitcoin networks.
The problem was that even though the package.json indicated a next version, package-lock was still pointing to 3.0.0
In this PR I updated both package.json 
* Change the package.json and package.lock.json with `npm rm @dfinity/ckbtc && npm i @dfinity/ckbtc@next`.
Code still works.
> chore(frontend): Update ckbtc dep in package.lock and package.json

- src/frontend/src/icp/components/send/IcSendBtcNetwork.svelte
The component displaying the network name wasn't taking into account regtest.
* Add a condition to check testnet instead of falling back to testnet if not mainnet.
Works locally in #2528
> feat(frontend): Add regtest to IcSendBtcNetwork

- src/frontend/src/lib/components/core/Loader.svelte
- src/frontend/src/lib/components/receive/ReceiveAddresses.svelte
Regtest and Testnet addresses are not the same for P2WPKH address type.
We already introduced the stores and services for the regtest address. In this PR, I use them.
* Load the regtest address if local and testnets in `Loader`.
* User regtest derived store in ReceiveAddresses instead of the testnet.
> feat(frontend): Load and render regtest address

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/canisters/backend.canister.ts
Follow-up PR to move default `certified` value from BE API to Canister.
> feat(frontend): move certified default value to BE canister

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/api/signer.api.ts
- src/frontend/src/lib/canisters/signer.canister.ts
- src/frontend/src/lib/types/canister.ts
- src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
Follow-up PR for using common canister/api types for Signer.
> feat(frontend): use common canister/api types for signer

- src/frontend/src/btc/types/btc.ts
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/lib/utils/network.utils.ts
Since the `BitcoinNetowrk` type from `@dfinity/ckbtc` now includes `regtest`, the type that I created previously is redundant.
> fix(frontend): remove unnecessary BTC network type

- src/frontend/src/btc/types/network.ts
- src/frontend/src/env/networks.env.ts
- src/frontend/src/eth/types/network.ts
- src/frontend/src/lib/types/network.ts
The goal is to extend BTC networks with already defined explorer URLs. It will be used in the BTC transaction detail modal.
> feat(frontend): add exporerUrl to BTC networks [GIX-2795]

- src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
- src/frontend/src/btc/services/btc-listener.services.ts
- src/frontend/src/btc/services/worker.btc-wallet.services.ts
- src/frontend/src/lib/types/post-message.ts
Removing the temporary type for BTC wallet since we are going to re-use `PostMessageDataResponseWallet`.
> feat(frontend): use PostMessageDataResponseWallet for BTC wallet [GIX-2795]

- src/frontend/src/lib/components/hero/HeroSignIn.svelte
- src/frontend/src/lib/i18n/en.json
The Authenticate button label will change from `Authenticate` to `Create | Open`.
> style(frontend): change authentication button label [GIX-3015]

- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/eth/components/send/SendForm.svelte
- src/frontend/src/eth/components/send/SendNetworkICP.svelte
- src/frontend/src/eth/components/transactions/TransactionModal.svelte
- src/frontend/src/eth/components/transactions/Transactions.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnect.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectReview.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSend.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendReview.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSession.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSign.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSignModal.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSignReview.svelte
- src/frontend/src/eth/constants/erc20-icp.constants.ts
- src/frontend/src/eth/services/eth-listener.services.ts
- src/frontend/src/eth/services/send.services.ts
- src/frontend/src/eth/services/transaction.services.ts
- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/icp/components/send/IcSendForm.svelte
- src/frontend/src/icp/components/send/IcSendReview.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/icp/components/transactions/IcTransactions.svelte
- src/frontend/src/icp/services/worker.icp-wallet.services.ts
- src/frontend/src/icp/services/worker.icrc-wallet.services.ts
- src/frontend/src/lib/components/receive/ReceiveAddressWithLogo.svelte
- src/frontend/src/lib/components/send/SendData.svelte
- src/frontend/src/lib/services/request-pouh-credential.services.ts
- src/frontend/src/lib/types/balance.ts
For consistency, we replace the relative imports with aliases.
> chore(frontend): use aliases for relative imports

- scripts/check.unused.mjs
The script to check for unused components was not taking in count components with same name. For example, let's suppose we have two components `CustomButton`, one in folder `eth` and one in folder `lib`; however, only one is used, so it would be imported as:
```typescript
import CustomButton from 'eth/CustomButton.svelte';
```
The script will not flag the one in `lib` (that is unused) because it matches the same name in the file.
So we check not only for the component name but for its direct parent folder too.
Furthermore, as utility, we print a warn for relative imports that should be using aliases.
> fix(ci): distinguish same-name imports in the script to check unused components

- Cargo.lock
- Cargo.toml
- scripts/test.backend.sh
- src/backend/tests/it/list_users.rs
- src/backend/tests/it/migration.rs
- src/backend/tests/it/utils/pocketic.rs
If we wanto to add integration tests interacting with bitcoin API we need to upgrade pocket-ic.
This is a first step upgrading pocket-ic to the latest release.
* Upgrade Rust and binary versions of pocket-ic according to the [compatibility table](https://docs.google.com/document/d/1VYmHUTjrgbzRHtsAyRrI5cj-gWGs7ktTnutPvUMJioU/edit#heading=h.5wf28dvt742x)
* Create Oisy backend in fiduciary subnet directly.
* Install with II subneet to have access to ecdsa keys.
* Change `ecdsa_key_name` init arg to the test one.
I had to move two timestamps because the tests weren't passing. Not sure what changed the time between versions, but it makes sense to move it after the update call.
> chore(test): Upgrade pocket-ic

- .gitignore
- scripts/test.backend.sh
- src/backend/tests/it/migration.rs
- src/backend/tests/it/utils/pocketic.rs
Bitcoin canister is needed to perform integration tests in the backend that interact with the bitcoin api.
In this PR, the bitcoin canister is installed as part of the pocket ic setup.
* Download the bitcoin canister if not present during test setup.
* Ignore bitcoin canister wasm.
* Refactor `deploy_to` with `deploy_backend` so that we can only install the backend which is needed in the migration test.
* Add bitcoin wasm and canister during the pocket-ic setup.
Only test changes.
> feat(test): Install bitcoin canister to pocket-ic

- src/frontend/src/lib/canisters/signer.canister.ts
- src/frontend/src/lib/canisters/signer.errors.ts
- src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
Have clearer understanding of the errors coming from the signer canister.
This PR doesn't improve UX, but only the logging of the errors. But now, improving the UX could be done by checking the error thrown.
* Create a new helper `signerCanisterError` and two new errors `CanisterSignerPaymentError` and `CanisterSignerInternalError`.
* Use the new helper in the btc endpoints to get balance and address.
* Change and add tests to prove that the helpers will throw as expected.
> feat(frontend): Improve error mgt signer canister

- src/frontend/src/eth/components/receive/EthReceive.svelte
- src/frontend/src/lib/components/receive/ReceiveModal.svelte
The goal is to move  the`ReceiveModal` component to lib so it can be reused by both ETH and BTC.
> feat(frontend): re-use ReceiveModal component

- src/frontend/src/btc/components/receive/BtcReceive.svelte
- src/frontend/src/lib/components/hero/Actions.svelte
- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/stores/modal.store.ts
In this PR, I have added the Receive modal for BTC. It has the same appearance as the respective ETH modal.
> feat(frontend): implement Receive modal for BTC

- src/backend/backend.did
- src/backend/src/bitcoin_api.rs
- src/backend/src/bitcoin_utils.rs
- src/backend/src/bitcoun_utils.rs
- src/backend/src/lib.rs
- src/backend/tests/it/bitcoin.rs
- src/backend/tests/it/main.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/shared/src/types.rs
To make a bitcoin transaction utxos and a fee must be selected.
In this PR, I introduce an endpoint that calculates the utxos for a transaction with a specific amount and then the fee related to it.
* New bitcoin_api module with exposed functions: `get_all_utxos` and `get_fee_per_byte`.
* New bitcoin_utils module with expose functions: `estimate_fee` and `utxos_selection`. These utils are based on the ckBTC minter's code.
* New endpoint `btc_select_user_utxos_fee` that uses helpers to calculate and return utxos and fees.
* New endpoint types.
* Changes in `backend.did` with `./scripts.did.sh`.
* Changes in `src/declarations/backend/*` with `npm run generate`.
* Unit tests for the bitcoin_utils.
* Dummy integration test for the new endpoint. Pocket-ic doesn't support (yet) bitcoin.
> feat(backend): Add endpoint to select utxos and fee for bitcoin transaction.

- src/frontend/src/icp-eth/stores/send.store.ts
- src/frontend/src/icp/components/send/IcSendModal.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
We would like to slowly decommission the `token` store. As one of the first step, we provide a context in the entire Send flow. That means, including the Send context used by Ethereum into the IC Send wizard.
Note: for this PR we just change the immediate child that is `IcSendModal`, but in future PR we will slowly go deeper.
- Add `sendTokenSymbol` to the Send context.
- Move `SendTokenContext` component one level up in the `SendWizard` (to include IC flow).
- Add `SendTokenContext` in `IcSendModal` too, for consistency.
- Modify `IcSendWizard` to deprecate token stores and use Send token context.
I tried a few transactions in the local replica and they worked.
https://github.com/user-attachments/assets/d1f810ba-82b1-4ae7-9df4-618bc1d78edf …
> feat(frontend): use Send context for IcSend flow too

- src/frontend/src/btc/derived/btc-transactions.derived.ts
- src/frontend/src/btc/stores/btc-transactions.store.ts
- src/frontend/src/lib/stores/transactions.store.ts
Add BTC transaction stores. It will be later extended with additional methods, similar to other related stores (e.g. `cleanUp`).
> feat(frontend): BTC transaction stores

- src/backend/backend.did
- src/backend/src/bitcoin_api.rs
- src/backend/src/lib.rs
- src/backend/tests/it/bitcoin.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/shared/src/types.rs
The bitcoin API to get utxos exposes a filter for the mininum confirmations of the transaction.
In this PR, I expose this filter in `get_all_utxos` and use it in the `btc_select_user_utxos_fee` endpoint.
* Add optional parameter min_confirmations to `get_all_utxos`.
* Change page for filter parameter for helper `get_utxos`.
* Call `get_all_utxos` with 6 minimum confirmations.
We can't add integration tests for bitcoin api until pocket-ic supports bitcoin.
> feat(backend): Expose and use min_confirmations filter to get utxos

- src/backend/src/heap_state/btc_user_pending_tx_state.rs
- src/backend/src/heap_state/mod.rs
- src/backend/src/lib.rs
We want to store pending btc transactions to disable users from making transactions while there is one that hasn't finished.
In this PR, I introduce the module to manage the pending transactions. It adds functionality to add, read and prune the pending transaction.
This struc will then be added to the heap, (hence that I put it inside a directory `heap_state`) and used in the backend endpoints.
* New class `BtcUserPendingTransactions` in module `heap_state/btc_user_pending_tx_state`.
* Add new module to lib.
* Test class functionality.
> feat(backend): Class to manage btc pending transactions

- HACKING.md
- src/frontend/src/btc/components/core/BtcLoaderWallets.svelte
- src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
- src/frontend/src/btc/services/worker.btc-wallet.services.ts
- src/frontend/src/lib/types/post-message.ts
The goal is to update the BTC wallet worker to fetch transactions. Similar to other store, we only load a BTC address if it hasn't been already fetched by FE.
> feat(frontend): load BTC transactions

- .env.example
- .env.test
- HACKING.md
- src/frontend/src/btc/components/core/BtcLoaderWallets.svelte
- src/frontend/src/btc/derived/btc-transactions.derived.ts
- src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
- src/frontend/src/btc/services/btc-listener.services.ts
- src/frontend/src/btc/services/worker.btc-wallet.services.ts
- src/frontend/src/btc/stores/btc-transactions.store.ts
- src/frontend/src/btc/types/btc.ts
- src/frontend/src/btc/types/network.ts
- src/frontend/src/btc/utils/btc-transactions.utils.ts
- src/frontend/src/env/networks.env.ts
- src/frontend/src/eth/types/network.ts
- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/rest/blockchain.rest.ts
- src/frontend/src/lib/stores/modal.store.ts
- src/frontend/src/lib/stores/transactions.store.ts
- src/frontend/src/lib/types/blockchain.ts
- src/frontend/src/lib/types/network.ts
- src/frontend/src/lib/types/post-message.ts
- src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts
- src/frontend/src/tests/mocks/btc.mock.ts
This is the base branch for BTC transactions feature.
> feat(frontend): BTC transactions [GIX-2795]

- .github/workflows/binding-checks.yml
The version of the signer was updated in #2592 but CI did not check the bindings.
- Include the build scripts in the list of files that cause the bindings check to run.  The build scripts include the external canister version number.
Alternative considered:
- We could add the canister release number in `dfx.json`.  This would be outside the schema, but dfx has never objected to additional useful data being stored in `dfx.json`.  Theoretically the release number and the location of the candid file are all that are needed to specify the candid exactly and if those are both in `dfx.json` we can keep the list of triggers small, leading to faster CI.
- I leave it up to the reviewer which they prefer.  In the PR I have gone for "conservative but slow" but would be very happy to use this …
> fix(ci): Run the bindings check when build commands are updated

- Cargo.lock
- src/backend/Cargo.toml
- src/backend/src/lib.rs
- src/backend/src/state.rs
The backend will need to  call the cycles ledger.  The PR is a bit large so here are a couple of small  preparation steps we can take:
- We will need the signer and cycles ledger canister IDs in the backend.
- We will need a couple of dependencies.
- Add the parsed canister principals as lazy static variables.
- Add dependencies in cargo.toml
None; these variables are still unused.
> feat(backend): Get canister IDs

- src/frontend/src/icp/stores/ic-transactions.store.ts
Refactor ic-transactions store to use `initTransactionsStore ` available in `transactions.store`.
> refactor(frontend): ic-transactions store

- src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
BTC txs were sent to FE without "certified flag.
> feat(frontend): send BTC txs to FE as CertifiedData

- src/frontend/src/eth/components/receive/EthReceiveMetamask.svelte
- src/frontend/src/lib/components/settings/SettingsSignedIn.svelte
- src/frontend/src/lib/styles/global/button.scss
- src/frontend/src/lib/styles/global/colors.scss
- tailwind.config.js
The `secondary-alt` button class could be substituted by `primary` class, according to the design team (the difference is just the background color). So, that class is deprecated.
Here the only two buttons that still had the deprecated class.
> style(frontend): remove deprecated button class secondary-alt

- src/frontend/src/lib/styles/global/button.scss
Opinionated PR: when a button is clicked, it should not show the `focus` state colors. The `focus` state is visible only when the button is selection interaction.
https://github.com/user-attachments/assets/c08c79a8-ee4e-4ea7-bf88-2e3cbbcb2d97
https://github.com/user-attachments/assets/290770dd-ace8-4b25-9886-f1f6431ad212
> style(frontend): remove focus state if button is clicked

- src/frontend/src/app.html
With this PR we allow smaller screens to have the same background as bigger ones.
> style(frontend): smaller screens will have the same background as larger ones [GIX-3067]

- src/frontend/src/btc/components/transactions/BtcTransactions.svelte
- src/frontend/src/btc/derived/btc-transactions.derived.ts
The goal is to prefix all BTC tx derived stores with "btc".
> fix(frontend): prefix btc-transactions derived stores

- src/frontend/src/lib/components/ui/ButtonIcon.svelte
- src/frontend/src/lib/styles/global/button.scss
- src/frontend/src/lib/styles/global/variables.scss
We introduce a new class of buttons called `tertiary-link`. Its first usage is for the `ButtonIcon` components. 
https://github.com/user-attachments/assets/284bf65d-f9cc-4ecb-b230-cb3654c70bea
> style(frontend): new tertiary-link class for buttons [GIX-3048]

- src/frontend/src/btc/components/transactions/BtcTransactionModal.svelte
- src/frontend/src/btc/components/transactions/BtcTransactions.svelte
- src/frontend/src/btc/types/btc.ts
- src/frontend/src/lib/components/transactions/TransactionModal.svelte
- src/frontend/src/lib/types/transaction.ts
The goal is to have the BTC modal implemented with basic info (e.g. it's missing confirmations number, or a proper component for displaying a tx status). Also, I added a common `TransactionModal` which will be later for IC and ETH cases too.
The further data will be added in separate PRs.
> fix(frontend): BTC transaction modal

- scripts/deploy.sh
The cycles ledger is not deployed into test environments.  We will need it there.
- Add `dfx deploy cycles_{ledger,depositor}` to `scripts/deploy.sh`
Alternatives considered:
- Replace the whole contents of `deploy.sh` with `dfx deploy` to deploy everything in one stroke.
- There are probably details why this is not currently possible.  Maybe something to look into after launch.
See existing CI.  Presumably `deplpoy.sh` is exercised and will fail if the new deployments fail.
> feat(tests): Deploy the cycles ledger & depositor

- src/backend/backend.did
- src/backend/src/lib.rs
- src/backend/tests/it/bitcoin.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/shared/src/types.rs
Avoid users double spending their utxos.
In this PR, before we select the utxos for a transaction, we check whether the user has any pending utxos. If that is the case, then the endpoint fails.
Ideally, we would ignore the pending utxos and use other utxos. But this is an improvement we can do later.
* Add one entry to enum `SelectedUtxosFeeError`: `PendingTransactions`.
* Prune pending utxos and check whether there are any within `btc_select_user_utxos_fee`.
* I added a test to check the return value of the new error. For this, I checked that if we don't prune, the error is returned.
> feat(backend): Check pending transaction before selecting utxos

- dfx.json
The canister `dependencies` specified in the `dfx.json` lead to issue when deploying locally the project. This is because it's spaghetti. Given that we are deploying with a pre-defined scripts and order, `npm run deploy` or `./scripts/deploy.sh`, I think we should remove the inter-dependencies at the dfx level. 
The error when running the deploy script:
```
Creating canister cycles_ledger...
WARN: Canister 'cycles_ledger' has a specified ID in dfx.json: um5iw-rqaaa-aaaaq-qaaba-cai,
which is different from the one specified in the command line: d3nvo-aaaaa-aaaar-qagzq-cai.
The command line value will be used.
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to register all canisters.
Caused by: Failed to create canister 'cycles_ledger'.
Caused by: Canister …
```
> build(local): remove dfx.json dependencies

- src/frontend/src/lib/canisters/backend.errors.ts
- src/frontend/src/lib/canisters/errors.ts
- src/frontend/src/lib/canisters/signer.canister.ts
- src/frontend/src/lib/canisters/signer.errors.ts
- src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
The goal is to handle Backend canister errors, for now only for BTC endpoints.
> feat(frontend): handle backend and signer canisters errors

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/canisters/backend.canister.ts
- src/frontend/src/lib/types/api.ts
- src/frontend/src/tests/lib/canisters/backend.canister.spec.ts
The goal is to expose BTC-related backend endpoint via the BE canister.
Note: the base branch of this PR will be changed to `main` after we merge https://github.com/dfinity/oisy-wallet/pull/2629.
> feat(frontend): expose new BE endpoints

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/canisters/backend.canister.ts
- src/frontend/src/lib/types/backend.ts
- src/frontend/src/tests/lib/canisters/backend.canister.spec.ts
We need to expose the new `allow_signing` function at the API level for #2632.
- Adding `allowSigning` to backend canister and API
> feat(frontend): expose backend allow_signing function

- src/frontend/src/lib/api/signer.api.ts
- src/frontend/src/lib/canisters/signer.canister.ts
- src/frontend/src/lib/canisters/signer.errors.ts
- src/frontend/src/lib/types/api.ts
- src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
Another method needed to send BTC is `btc_caller_send`.
> feat(frontend): expose btc_caller_send via signer canister

- src/frontend/static/.ic-assets.json
I propose to start caching on the client side the assets that are generated from the `$lib/assets` directory. The assets are generated with a hash name.
For example: https://oisy.com/_app/immutable/assets/cover-features.BNqeslTw.png
Given that assets are hashed, I think we can try to use a long living cache - i.e. a year.
- Define a `Cache-Control` header for `_app/immutable/assets`
> feat(frontend): HTTP cache-control for assets (css, png, webp etc.)

- src/frontend/src/lib/canisters/errors.ts
Overriding the constructor in `CanisterInternalError` is not needed given that it overrides the default with the same declaration.
> chore(frontend): remove error constructor

- src/frontend/src/lib/canisters/backend.errors.ts
- src/frontend/src/lib/canisters/signer.errors.ts
- `response` is of type error so rename to `err`
- `SignerCanisterBtcError` type is not needed and can be inlined in its import
- Return types are missing
- `SignerCanisterPaymentError` should extend `CanisterInternalError`
> chore(frontend): improve canister error code

- src/frontend/src/btc/stores/btc-pending-transactions.store.ts
- src/frontend/src/lib/types/store.ts
- src/frontend/src/tests/btc/stores/btc-pending-transactions.store.spec.ts
We will disable sending BTC tokens while the user has pending transaction. Pending transactions will come from Oisy backend.
In this PR, I created a store to save the pending transactions per address.
* New store `pendingTransactionsStore`.
* Test new store.
> feat(frontend): Add btc pending transactions store

- src/frontend/src/btc/components/send/BtcSendAmount.svelte
- src/frontend/src/btc/types/btc-send.ts
As a part of BTC send UX flow, we need to implement `BtcSendAmount`.
> feat(frontend): implement BtcSendAmount component

- src/frontend/src/lib/components/hero/HeroSignIn.svelte
Larger text in header when signed out on mobile.
> style(frontend): increase header text when signed out on mobile [GIX-3044]

- src/frontend/src/eth/components/receive/EthReceiveMetamask.svelte
- src/frontend/src/eth/components/tokens/TokenModal.svelte
- src/frontend/src/eth/components/transactions/TransactionModal.svelte
- src/frontend/src/icp/components/receive/IcReceiveInfoCkBTC.svelte
- src/frontend/src/icp/components/receive/IcReceiveInfoICP.svelte
- src/frontend/src/icp/components/receive/IcReceiveInfoIcrc.svelte
- src/frontend/src/lib/components/hero/about/AboutHowModal.svelte
- src/frontend/src/lib/components/hero/about/AboutWhatModal.svelte
- src/frontend/src/lib/components/receive/ReceiveAddressQRCode.svelte
- src/frontend/src/lib/components/receive/ReceiveAddresses.svelte
- src/frontend/src/lib/components/send/SendTokensList.svelte
- src/frontend/src/lib/components/transactions/TransactionModal.svelte
- src/frontend/src/lib/styles/global/button.scss
The buttons classes `primary`, `secondary` and `tertiary` were using the sub-class `center` in all the instances. Furthermore, it makes sense that, as default, the button have centered content (according to new design too).
This PR removes the sub-class `center` and set the centered content directly in the classes.
> chore(frontend): simplify button class removing center sub-class
