src/frontend/src/lib/components/auth/LandingPage.svelte
We want the main header when signed out central.
=> style(frontend): center the login group when signed out [GIX-3044]

src/frontend/src/icp/utils/ic-send.utils.ts, src/frontend/src/lib/utils/address.utils.ts
One of the steps to move shared between BTC and IC code to $lib.
=> refactor(frontend): move BTC address utils to lib

src/frontend/src/lib/components/buy/BuyButton.svelte
Just to be on the safe side, we disable the Buy button in case there is no OnRamper API key provided. This could happen only in case there is some inconsistency on the `.env` file.
=> feat(frontend): disable buy button if no OnRamper API key is provided [GIX-2854]

src/frontend/src/btc/derived/has-pending-transactions.derived.ts, src/frontend/src/lib/services/address.services.ts, src/frontend/src/tests/btc/derived/has-pending-transactions.derived.spec.ts
We want to display a warning messange and disable the send form if the modal is for bitcoin and the user has pending transactions.
The bitcoin addresses are unique. Therefore, I wanted to take advantage of that instead of checking selected networks or tokens.
The idea is to create a derived store creator that will return `true`, `false` or `"loading"` depending on the address and whether the bitcoin addresses have been loaded:
* Return `true` when the address is a bitcoin address and the pending transactions array is not empty.
* Return `"loading"` if the addresses or the pending transactions are not loaded. This is trickier because we also need to check the `testnets`. If testnets are not enabled, then the addresses for testnet and regtest won't be loaded.
* Return `false` if the pending …
=> feat(frontend): Derived store to find pending transactions

vitest.config.ts
I noticed that the import shorthand `$declarations` was missing for the tests.
=> build(test): missing $declarations

vitest.config.ts
All canister IDs are currently unknown during test because the vitest config does not load those with our "plugins" in the environment.
- Load `readCanisterIds` within `process.env` for vitest config
=> build(test): load canister IDs

package-lock.json, package.json, vitest.setup.ts
When we start testing features around the addresses that are saved on the client side with Idb, we will need to fake Idb.
So, similarly as in NNS dapp, we can use `fake-indexeddb`
- `npm i fake-indexeddb -D`
- Add related import in vitest setup
=> build(test): import fake-indexeddb

src/frontend/src/btc/derived/has-pending-sent-transactions.derived.ts, src/frontend/src/btc/stores/btc-pending-sent-transactions.store.ts, src/frontend/src/tests/btc/derived/has-pending-sent-transactions.derived.spec.ts, src/frontend/src/tests/btc/stores/btc-pending-sent-transactions.store.spec.ts
As discussed in [this comment](https://github.com/dfinity/oisy-wallet/pull/2652#issuecomment-2393808608) this PR renames the BTC pending transactions to pending "sent" transactions.
* Rename file and store types and variables.
* Rename file and derived store.
* Rename test files and imports.
=> refactor(frontend): Rename btc pending transactions to "sent transactions"

src/frontend/src/lib/constants/app.constants.ts, src/frontend/src/lib/stores/auth.store.ts, src/frontend/src/tests/lib/stores/auth.store.spec.ts, vitest.config.ts
I'm not the fan numero uno of this pattern used in NNS dapp but, I have to admint that it is super handy for test purposes to be able to mock the `identity` in the `auth.store`. Given that I need to mock the identity in #2673, I guess to replicate the pattern.
- Add a flag `TEST` in `app.constant`
- Extend `auth.store` with `setForTesting` which set an identity only if `TEST` and `LOCAL` are `true`
=> feat(frontend): expose an imperative identity setter for test

Dockerfile.e2e
In `dfx.json` we are using the argument `init_arg_file` that was introduced in [v0.20.1](https://github.com/dfinity/sdk/releases/tag/0.20.1)
So, we bump to latest dfx version.
=> build(e2e): bump dfx version used for E2E env

src/frontend/src/btc/derived/has-pending-sent-transactions.derived.ts, src/frontend/src/btc/stores/btc-pending-sent-transactions.store.ts, src/frontend/src/tests/btc/derived/has-pending-sent-transactions.derived.spec.ts, src/frontend/src/tests/btc/stores/btc-pending-sent-transactions.store.spec.ts
We want to show a different message to the user if loading the pending sent transactions of bitcoin failed.
In this PR, I add the `null` type of the bitcoin pending sent transactions store.
* Add `null` in `BtcPendingSentTransactionsStoreData`.
* Add specific method to set it to `null`: `setPendingTransactionsError`. This should allow us to easily change the inner type.
* Support the new type in `initHasPendingSentTransactions` and return `"error"`. This will also allow us to easily change the implementation details of the error.
* Test the new type in `btcPendingSentTransactionsStore` tests.
* Test the new type in `initHasPendingSentTransactions` tests.
=> feat(frontend): Add support for error in btc pending sent txs

src/frontend/src/lib/utils/network.utils.ts, src/frontend/src/tests/lib/utils/network.utils.spec.ts
In the components I'll have a network id, but other levels need the `BitcoinNetwork`.
In this PR, I add an util to convert a network id into a `BitcoinNetwork` if it's one of the known bitcoin network ids.
* New util `mapNetworkIdToBitcoinNetwork`.
* Test new util `mapNetworkIdToBitcoinNetwork`.
=> feat(frontend): Add mapNetworkIdToBitcoinNetwork util

src/frontend/src/lib/components/ui/Copy.svelte, src/frontend/src/lib/components/ui/ExternalLink.svelte
We change the "blue" colors of `ExternalLink` component.
=> style(frontend): change colors of ExternalLink component

src/frontend/src/btc/services/btc-pending-sent-transactions.services.ts
We want to load the btc pending sent transactions when the user visits the form to send tokens.
In this PR, I introduce the service that will be used by the component to load it.
* New service `loadBtcPendingSentTransactions`.
Tested locally by loading them in the IcSendForm
=> feat(frontend): Service to load btc pending sent txs

src/frontend/src/btc/components/send/BtcSendForm.svelte, src/frontend/src/btc/services/btc-pending-sent-transactions.services.ts
We want to disable the review step if the user has pending sent transactions. Therefore, we load them in the form step so that they will be present in the review step.
* Use `loadBtcPendingSentTransactions` in `BtcSendForm`.
Tested manually that it does indeed load the data in the store.
=> feat(frontend): Load btc pending sent txs in BtcSendForm

src/frontend/src/btc/services/btc-pending-sent-transactions.services.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/btc/services/btc-pending-sent-transactions.services.spec.ts
Requested in comments:
* i18n in erros https://github.com/dfinity/oisy-wallet/pull/2721#discussion_r1791377537
* Add tests for services: https://github.com/dfinity/oisy-wallet/pull/2709#pullrequestreview-2352644773
* Use i18n for the errors in `loadBtcPendingSentTransactions`.
Add tests for `loadBtcPendingSentTransactions`
=> feat(frontend): Test and add i18n in errors in loadBtcPendingSentTransactions

canister_ids.json, dfx.json
`vite build` was broken with:
```
error during build:
[commonjs--resolver] Transform failed with 32 errors:
error: The define key "import.meta.env.VITE_TEST-FE-1_ICP_LEDGER_CANISTER_ID" contains invalid identifier "VITE_TEST-FE-1_ICP_LEDGER_CANISTER_ID"
error: The define key "import.meta.env.VITE_TEST-FE-1_BACKEND_CANISTER_ID" contains invalid identifier "VITE_TEST-FE-1_BACKEND_CANISTER_ID"
error: The define key "import.meta.env.VITE_TEST-FE-1_INTERNET_IDENTITY_CANISTER_ID" contains invalid identifier "VITE_TEST-FE-1_INTERNET_IDENTITY_CANISTER_ID"
error: The define key "import.meta.env.VITE_TEST-FE-2_CKBTC_MINTER_CANISTER_ID" contains invalid identifier "VITE_TEST-FE-2_CKBTC_MINTER_CANISTER_ID"
error: The define key "import.meta.env.VITE_TEST-FE-1_CYCLES_LEDGER_CANISTER_ID" contains …
```
=> fix(devops): Rename test-fe-X to test_fe_X

src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts, src/frontend/src/lib/types/post-message.ts
Another example of why we need to have zod for typing worker-client communication - there was an issue with the way of how BTC address was passed to the wallet worker.
=> fix(frontend): issue with loading BTC txs

src/frontend/src/lib/components/ui/RoundedIcon.svelte
As noted by @DenysKarmazynDFINITY , I forgot to adjust the contrast between the background and the icons in the transaction list.
=> fix(frontend): Add more contrast to the icons in the transaction list

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte
Extending BtcSendTokenWizard with an additional prop that tells component which button should it render - close or back.
=> feat(frontend): formCancelAction prop for BtcSendTokenWizard

src/frontend/src/btc/components/core/BtcWalletAddress.svelte
We now need to display a separate BTC address for regtest (previously, it was always the same with testnet).
=> feat(frontend): display regtest BTC address

src/frontend/src/tests/lib/actors/query.ic.spec.ts
As agreed with David offline, we want to keep unit tests log clean and therefore need to mock console.error for query.ic methods.
=> test(frontend): hide console.error logs for query.ic methods

src/frontend/src/lib/canisters/signer.canister.ts
The reason why the caller address is needed isn't clear.
- Explain why the caller principal is important when getting the user eth address.
N/A
=> docs(frontend): Comment on eth address derivation

scripts/deploy.args.sh, scripts/deploy.backend.sh, src/backend/backend.did, src/backend/tests/it/utils/pocketic.rs, src/declarations/backend/backend.did, src/declarations/backend/backend.did.d.ts, src/declarations/backend/backend.factory.certified.did.js, src/declarations/backend/backend.factory.did.js, src/shared/src/impls.rs, src/shared/src/types.rs
We want to remove the `address` parameter from the `SelectedUtxosFeeRequest` and derive it from the caller.
In this PR, I included the CFS canister id which will be used to fetch the ECDSA public key before deriving the address.
* New parameter `cfs_canister_id` in `Config` and `InitArg`.
* Add new parameter in deploy scripts `deploy.args.sh` and `deploy.backend.sh`.
* Add it to the move from init to the config.
Using `npm run generate`:
* Changes in candid files.
* Changes in declarations files.
* Add new `cfx_canister_id` as `None` in the integration tests. It's not yet used.
=> feat(devops): Add and include cfs_canister_id init

scripts/build.signer.sh, src/declarations/signer/signer.did, src/declarations/signer/signer.did.d.ts, src/declarations/signer/signer.factory.certified.did.js, src/declarations/signer/signer.factory.did.js, src/frontend/src/lib/canisters/signer.canister.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
A new version of the chain fusion signer is available.
- Update the chain fusion signer version to 0.2.5
- Update the frontend to use the new API
Existing CI should suffice.
=> chore(devops): Update the chain fusion signer version.

src/frontend/src/lib/canisters/signer.canister.ts, src/frontend/src/lib/canisters/signer.constants.ts, src/frontend/src/lib/constants/app.constants.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
The payment type is the same for every paid signer API call.
- Move the payment type into a constants file.
Existing CI should suffice.
=> refactor(frontend): Extract payment type as a constant

scripts/deploy.sh
The backend needs the CFS canister id.
In this PR, first signer is deployed and then the backend in the `deploy.sh`.
* Change order of scripts in `deploy.sh`
I tested with a clean dfx replica running `npm run deploy`.
=> fix(devops): Deploy signer before backend

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/lib/components/send/SendWizard.svelte
The `networkId` prop  that is passed down from `SendModal` is actually only defined when `targetNetwork` is there. Because of that, `BtcSendForm` was never receiving `networkId` even though it is relying on it to identify whether it's a regtest, testnet or mainnet btc.
=> fix(frontend): networkId always undefined in SendModal

src/frontend/src/lib/canisters/signer.constants.ts
The `SIGNER_PAYMENT_TYPE` inner value was fixed, but cleaner is simply to declare the type of the constant.
- Declare the type of `SIGNER_PAYMENT_TYPE` instead of coercing the inner.
Existing CI should suffice.
=> refactor(frontend): Provide type for payment type

src/frontend/src/btc/components/send/BtcSendHasPendingTransactions.svelte, src/frontend/src/btc/components/send/BtcSendReview.svelte, src/frontend/src/lib/components/send/SendReview.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
We want to avoid users double spending their utxos. Therefore, we disable sending Bitcoin if there is any pending sent transaction.
In this PR, we show a warning and disable the "Send" button in the review step.
* Use `initHasPendingSentTransactions` to get the state of the btc pending sent transactions, disable the button accordingly and show warning.
* Add a slot in `SendReview` that can be used to add feedback to the user.
* Add two new messages in i18n.
Tested locally by filling up the store with the different scenarios.
=> feat(frontend): Add warning if btc pending transactions

src/frontend/src/lib/canisters/signer.canister.ts, src/frontend/src/lib/types/api.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
For the consistency sake, let's keep hardcoded `adrdress_type` inside of `signer.canister` (same as it's done in `getBtcBalance`) instead of passing this value all the way down from the related service.
=> feat(frontend): do not pass address_type as a param

src/frontend/src/btc/constants/btc.constants.ts, src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
We want to show the latest balance.
In this PR, we change the requested balance to use only one confirmation.
* Create a new constant `BTC_BALANCE_MIN_CONFIRMATIONS`.
* Use the new constat in the btc wallet scheduler when getting the balance.
I deplyed the branch to test 2 and confirmed that the balance got updated when the transaction had 1 confirmation.
=> feat(frontend): Ask balance with 1 confirmations

src/frontend/src/btc/components/send/BtcSendHasPendingTransactions.svelte, src/frontend/src/btc/components/send/BtcSendReview.svelte, src/frontend/src/btc/derived/btc-pending-sent-transactions-status.derived.ts, src/frontend/src/tests/btc/derived/btc-pending-sent-transactions.derived.spec.ts
Rename entries for `BtcPendingSentTransactionsStatus` as suggested [here](https://github.com/dfinity/oisy-wallet/pull/2788#discussion_r1795448373) for readability purposes.
* Rename `PRESENT` to `SOME` and `EMPTY` to `NONE` in `BtcPendingSentTransactionsStatus` enum.
Everything still works.
=> refactor(frontend): Rename entries in BtcPendingSentTransactionsStatus

src/frontend/src/eth/providers/infura-erc20.providers.ts, src/frontend/src/eth/services/send.services.ts
A partner encountered an issue not specific to Oisy, but somehow can be food for thought for improvement.
It may happen that after the approval transaction is done, the transfer transaction may fail for whatever reasons. In this case, the next approval transaction will be rejected, since there is already an approved amount. So, the next transfer transaction will work only if the amount is below the one already approved. Otherwise, the user is blocked until it consumes all the approved amount.
1. The user wants to convert 10 USDT to ckUSDT:
1. `approve` transaction for 10 USDT --> _successful_
2. `transfer_from` transaction for 10 USDT --> _failed_ (for whatever reason)
2. The user wants to convert 20 USDT to ckUSDT:
1. `approve` transaction for 20 USDT --> _failed_ (the previous approved …
=> feat(frontend): Add allowance method to Send services

src/frontend/src/lib/styles/global/button.scss
Custom CSS classes `user` and `hero` for `button` are deprecated.
=> chore(frontend): remove deprecated custom CSS classes for buttons

src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte, src/frontend/src/icp/components/transactions/IcTransactionsBitcoinStatusBalance.svelte, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/tokens/TokensZeroBalance.svelte, src/frontend/src/lib/components/ui/ButtonMenu.svelte, src/frontend/src/lib/styles/global/button.scss
Using new primary color for text that were still using the old one. A few of them had that color on hovering.
=> style(frontend): adjust text elements to new color

src/frontend/src/btc/components/send/BtcSendReview.svelte, src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/btc/components/send/BtcUtxosFee.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
The goal of this PR is to use the btc-send service to get UTXOs fee and to display it on the review step. The PR could have been split into few pieces, but I think in this particular case it's useful to see the whole picture.
Loading state:
UTXOs fee has been fetched:
=> feat(frontend): fetch and display UTXOs fee on BTC send review step

.github/workflows/frontend-deploy-staging.yml
We want to enable bitcoin in Staging and other environments but bitcoin requires an extra env var apart from the flags that was missing in the current env vars: `VITE_BLOCKCHAIN_API_URL`.
* Add `VITE_BLOCKCHAIN_API_URL` in the GH workflow that deploys the frontend.
We will test when this PR is merged.
=> feat(devops): Add VITE_BLOCKCHAIN_API_URL to staging deploy

src/frontend/src/btc/components/send/BtcSendAmount.svelte
We want to give fast feedback to the user if a transaction can't be made.
In this PR, compare the amount that the user wants to send to the current balance and show an error is the amount is larger.
This doesn't consider the fee because the fee is calculated based on the amount, the utxos and the current fee of the network in the backend.
* Introduce a `customValidate` in `BtcSendAmount`.
=> feat(frontend): Disable if amount higher than balance

src/frontend/src/btc/services/worker.btc-wallet.services.ts
`triggerBtcWalletTimer` needs the same set of data as `startBtcWalletTimer`.
=> feat(frontend): pass required data on triggerBtcWalletTimer

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/btc/services/btc-send.services.ts
We need to send btc txId to BE after transaction send has succeeded.
=> feat(frontend): send btc txId to BE after transaction send has succeeded

src/frontend/src/lib/components/hero/HeroSignIn.svelte
The icons in the landing page bullet points were mixed up.
=> refactor(frontend): invert icons in landing page bullet points [GIX-3044]

src/frontend/src/eth/components/wallet-connect/WalletConnectButton.svelte, src/frontend/src/lib/styles/global/button.scss
The style of the WalletConnect disconnect button didn't fits the new design aynmore.
- Update style
- Remove custom button global style
Before:
After:
=> style(frontend): wallet connect disconnect button

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte
Use `nullishSignOut` in BTC send token wizard instead of just showing an error message.
=> feat(frontend): use nullishSignOut in BTC send token wizard

src/frontend/src/btc/components/send/BtcSendAmount.svelte
The goal is to add additional checks to validate the provided user amount in the BTC send flow.
=> feat(frontend): disable send BTC button for userAmount <= 0

src/frontend/src/lib/styles/global/button.scss
We adjust the colors of the `tertiary` button class to be consistent with the other classes.
=> style(frontend): set better disabled colors for tertiary button

src/frontend/src/btc/components/send/BtcSendAmount.svelte
Calculating the maximum amount to send for a bitcoin wallet takes some calculation.
For the MVP, we disable the max button that will be enabled once the calculation is added to the endpoint to select utxos and fee.
* Remove the function to calculate the bitcoin max amount which was anyway incorrect and that disables the Max button.
=> feat(frontend): Disable "Max" when sending btc

src/frontend/src/btc/constants/btc.constants.ts, src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts, src/frontend/src/btc/types/btc.ts, src/frontend/src/btc/utils/btc-transactions.utils.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts
In this PR, I fetch the current BTC block height to determine whether a transaction is confirmed, unconfirmed or pending. This will be used in:
1. Transaction list - an item will have a status displayed, plus pending txs will have "disabled" background.
2. The number of confirmations will be displayed in the tx detail view.
The UI PRs will be done separately.
=> feat(frontend): BTC transaction status based on current block height

src/frontend/src/lib/styles/global/button.scss
The sub-class `full` for buttons is deprecated, since it is now handled by tailwind into the `Button` component.
=> chore(frontend): deprecated button sub-class full

src/frontend/src/lib/components/navigation/NavigationMenu.svelte, src/frontend/src/lib/components/ui/SplitPane.svelte, src/frontend/src/routes/(app)/+layout.svelte
More width when we are on larger screens. Since the menu is in an `absolute` position, we cannot use `flex`, but `min-w-`.
=> style(frontend): Increase menu width for bigger screens [GIX-3045]

src/frontend/src/btc/utils/btc-transactions.utils.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts
The previous implementation didn't take utxos fee into account while calculating a transaction value for "send" txs. In this PR, I update the implementation in order to get complete numbers. The mapper is implemented the way that it loops through `inputs` and `out` just once to get all required vars.
Previous values:
Updated values:
Note: please ignore the UI, it will be tackled separately.
=> feat(frontend): take fees into account while calculating BTC tx value

src/frontend/src/btc/components/transactions/BtcTransaction.svelte, src/frontend/src/btc/types/btc.ts, src/frontend/src/lib/components/transactions/Transaction.svelte, src/frontend/src/lib/components/transactions/TransactionPending.svelte, src/frontend/src/lib/components/transactions/TransactionStatus.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/lib/types/transaction.ts
In this PR, "unconfirmed" transaction label is added to the `Transaction` component. The intermediate design as shown on the screenshot was agreed with Artem. 
Note: after ETH and IC Transaction components are refactored to use `lib/Transaction`, `TransactionPending` can be deleted in favour of `TransactionStatus`.
=> feat(frontend): "unconfirmed" BTC transaction UI

src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
Similar as with fetching BTC txs data, we don't want worker to fail if the latest block height cannot be fetched. If this value is not available, it also means that we cannot properly parse transactions response. For now, I added a simple check, but in the future we might want to handle this case more gracefully (e.g. we still display txs but mention to users that we cannot identify confirmations number and hence tx status).
=> feat(frontend): handle BTC latest block height endpoint error

src/frontend/src/lib/rest/blockchain.rest.ts, src/frontend/src/lib/types/blockchain.ts
Since we switched to Blockstream API, we can clean up `blockchain.rest` and related types.
=> feat(frontend): remove unused service from blockchain.rest

src/frontend/src/btc/constants/btc.constants.ts, src/frontend/src/btc/utils/btc-transactions.utils.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts, src/frontend/src/tests/mocks/btc.mock.ts
I realised I used incomplete formula to calculate BTC tx confirmations, it should be `confirmations = currentBlockHeight - transactionBlockHeight + 1`. Without adding +1, we didn't account for the block where the transaction was first included, which resulted in 0 confirmations immediately after the block is mined, which isn't correct.
=> fix(frontend): adjust BTC tx confirmations calculation

src/frontend/src/btc/components/transactions/BtcTransactionModal.svelte, src/frontend/src/lib/components/transactions/TransactionModal.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
The goal of this PR is to update BTC transaction modal with the following data:
1. Properly parse and display BTC tx status (previously, "unconfirmed" was missing).
2. Display number of confirmations if it's available.
=> feat(frontend): update BTC transaction modal

src/frontend/src/lib/components/ui/ButtonHero.svelte
Slightly increase mobile text dimension for the buttons in `Hero`.
=> style(frontend): Increase hero buttons text size for mobile [OISY-62]

src/frontend/src/app.html, src/frontend/src/lib/styles/global/body.scss
There should be no glitch given that the background is embeded in the html file but, just had this idea that we can maybe actually set the background color on the `:root` element.
- Move background color from background container to root.
- Remove `:root` specified as transparent background and black color. The first will be specifically set in the HTML page, the second is the default.
Before if I delete the background image:
After if I remove the bg image:
=> style(frontend): body background

src/frontend/src/lib/components/core/Footer.svelte, src/frontend/src/lib/components/ui/SplitPane.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, tailwind.config.js
The idea is to hide the "Developed with..." string for middle screens, leaving just the DFINITY logo. However, for narrower middle screen, hide the logo too.
- Make the entire string be an hyperlink.
- Modify the footer so that it is hidden on narrow middle screens, and only a logo on middle screens.
- The rest is unchanged.
https://github.com/user-attachments/assets/72d9e1b8-65c0-41f8-a0fc-c75f8886d0b5
=> refactor(frontend): hide partially the footer DFINITY string [OISY-62]

src/frontend/src/btc/derived/btc-transactions.derived.ts, src/frontend/src/btc/utils/btc-transactions.utils.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts
Sort BTC transactions with the following logic:
1. Pending status + timestamp.
2. Unconfirmed status + timestamp.
3. Confirmed status + timestamp.
=> feat(frontend): sort BTC transactions

src/frontend/src/lib/components/ui/ButtonAuthenticate.svelte
On the `/sign` route the `ButtonAuthenticate` requires to fit the full width according design.
- Add a `fullWidth` option.
=> feat(frontend): button authenticate fullWith option

src/frontend/src/routes/(sign)/sign/+page.svelte
At the top of the `/sign` route we want to initialize and reset the signer context.
- Subscribe to auth and destroy hook and init or reset the context.
=> feat(frontend): init and reset signer context on route sign

src/frontend/src/lib/components/signer/SignerCenteredContent.svelte, src/frontend/src/lib/components/signer/SignerLoading.svelte
I realized there is few screen that are all centered in the signer flow. Therefore I extracted a component from the "loading" component that places the content at the center of the signer article.
- Extract `SignerCenteredContent` component.
=> feat(frontend): signer centered content component

src/frontend/src/lib/styles/global/colors.scss, src/frontend/src/lib/styles/global/gix.scss, src/frontend/src/lib/styles/global/theme.scss, tailwind.config.js
Alas, the legacy color defined as `blue` (but more on the purple side) was being used still. This PR removes its references in favor of the new blue decided for the pallet.
=> style(frontend): Remove legacy blue color

src/frontend/src/lib/components/hero/HeroContent.svelte
The `HeroContent` component is using the `token` store. However it is not needed for its scope since it could directly use the `pageToken` store.
In fact, in this context, the token store is set as  such: `token.set($pageToken)`. We are not removing this, we are just substituting the store used to provide the same value.
Some of its sub-components use the `token` store too, but this PR change will not affect them, since we are just reading values that are equals.
We will analyze them in other PRs.
=> refactor(frontend): Remove token store from HeroContent

src/frontend/src/lib/components/hero/Header.svelte
In PR https://github.com/dfinity/oisy-wallet/pull/2959 I forgot to wrap the Alpha layout for signed out page.
=> fix(frontend): Alpha is wrongly set when logged out

HOW-TO.md, scripts/download.ckbtc.sh, scripts/download.cketh.sh, scripts/download.icp.sh
The `rosetta-api` path was renamed and restructured to `ledger_suite` in the IC main repo. Therefore we have to update the paths to download the ICP and ICRC ledger and index did files.
Detected in ic-js and fixed in PR https://github.com/dfinity/ic-js/pull/736
- Update path as in [https://github.com/dfinity/ic/tree/master/rs/ledger_suite](https://github.com/dfinity/ic/tree/master/rs/ledger_suite)
=> chore(download): update renamed ledger and index did source paths

src/frontend/src/app.html
Chrome is warning about the deprecation of `apple-mobile-web-app-capable` which should be replaced by `mobile-web-app-capable`.
> [!WARNING]  
> meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes"
A similar change was applied in Flutter. See https://github.com/flutter/flutter/issues/154596.
- https://web.dev/learn/pwa/web-app-manifest#designing_your_pwa_experience
> [!CAUTION]
> Warning: Before the web app manifest spec was defined, several browsers, including Safari on iOS/iPadOS and Chrome on Android, supported custom <meta> elements to describe the application experience, such as apple-mobile-web-app-capable. Do not use these <meta> elements today; it's no longer recommended, and may harm the …
=> feat(frontend): adapt deprecated meta-tag apple-mobile-web-app-capable

scripts/download.ckbtc.sh, scripts/download.cketh.sh, scripts/download.icp.sh
In #2996 I updated the new paths to match the IC main repo structure but, forgot to also update the commit version accordingly given that our scripts are pinned.
- Update version to https://github.com/dfinity/ic/commit/03dd6ee6de80c2202f66948692c69c61eb6af54d which introduced the folder refactoring.
=> chore(download): fix ic commit version for local deployement

scripts/download.icp.sh
In #2996 I updated the new paths to match the IC main repo structure but, turns out the IC main repo is organized differently for the ledger and index ICP. The first is at the root of `ledger_suite` while the second is in a subfolder.
- Correct `ledger.did` path for ICP
=> chore(download): fix icp ledger did path

src/frontend/src/lib/styles/global.scss
The syntax `@import` was deprecated in favor of `@use` and `@forward` (see [announcement](https://sass-lang.com/blog/import-is-deprecated/)). As per the latest versions of SASS, we are receiving deprecation warnings about it, for example:
```bash
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
╷
6 │ @import './global/fonts';
│         ^^^^^^^^^^^^^^^^
╵
src/frontend/src/lib/styles/global.scss 6:9  root stylesheet
```
So we adjust the only usages of `@import` left.
To do that I used directly the command suggested in the article:
`sass-migrator module --migrate-deps ./global.scss`
=> chore(frontend): Remove SASS deprecation warning for imports

src/frontend/src/lib/components/ui/Copy.svelte, src/frontend/src/lib/utils/clipboard.utils.ts
In #3013 we will need a specific copy button icon. I'm not sure if it will be use elsewhere, that's why instead of enhancing the existing `Copy` button, I rather like to create a specific "Receive related button". Also why it's handy to extract the "copy to clipboard" function to a module for reusability purposes.
- Move existing copy to clipboard function to a utils.
No particular tests.
=> refactor(frontend): extract copy to clipboard to a module

src/frontend/src/lib/components/receive/ReceiveCopy.svelte
For #3013 we need a new "Copy address" button. As explained in PR #3014, for now it just gonna be dedicated to the address and uses the existing function that was extracted in this related PR.
- Create a "Copy receive address" button component.
=> feat(frontend): receive address copy button

src/frontend/src/lib/components/ui/Logo.svelte
In #3013 we need a new logo size between "small" and "medium". I was not sure how to called it, so I named it "smallish". Open to better idea!
- Add `smallish` option to `Logo` for an icon of `36px`.
=> feat(frontend): smallish logo size

src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte, src/frontend/src/lib/components/receive/ReceiveAddressWithLogo.svelte, src/frontend/src/lib/components/tokens/HideTokenReview.svelte, src/frontend/src/lib/components/tokens/TokenLogo.svelte, src/frontend/src/lib/components/ui/Logo.svelte
Follow-up of #3015 in which we decided to adopt breakpoint prefix to describe the various sizes of the logo
- Replace `small | smallish | medium | big` by `xs | sm | md | lg`
=> feat(frontend): convert logo size to breakpoint prefix

src/frontend/src/eth/components/receive/EthReceiveMetamask.svelte, src/frontend/src/lib/components/icons/IconMetamask.svelte
The Metamask btn is currently displayed as a primary call to action which is incorrect.
This PR does not exactly style the button as in the last iteration of Figma which modified again the secondary button. Therefore it just set the button to secondary that way, when we modify again the buttons, it will inherit the style.
- Use secondary and reduce the size of the icon to make the button less big
Before:
After:
=> style(frontend): metamask secondary button

src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte, src/frontend/src/lib/components/receive/ReceiveAddressWithLogo.svelte, src/frontend/src/lib/components/tokens/HideTokenReview.svelte, src/frontend/src/lib/components/tokens/TokenLogo.svelte, src/frontend/src/lib/components/ui/Logo.svelte
In PR #3028 we are going to use an additional size for Logo, that is `42px`.
So, we "shift" all the sizes so that the new mapping is
```typescript
const sizes = {
xs: '22px',
sm: '36px',
md: '42px',
lg: '52px',
xl: '64px'
};
```
=> refactor(frontend): Introduce new size for Logo component

src/frontend/src/lib/components/receive/ReceiveAddress.svelte
The network icon displayed in the receive modals should be black and white according Figma.
=> feat(frontend): network icon black white for receive

src/frontend/src/lib/types/token.ts, src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
As discussed, the more obvious name for the variable should be `TokenUiGroup` since it represents a group of `TokenUi` types.
=> refactor(frontend): Rename type for token groups

src/frontend/src/lib/components/auth/AuthGuard.svelte, src/frontend/src/lib/components/core/Footer.svelte, src/frontend/src/lib/components/hero/Header.svelte, src/frontend/src/lib/components/navigation/NavigationMenu.svelte, src/frontend/src/lib/components/ui/SplitPane.svelte
As a recent feedback, we are increasing the breakpoint for the "mobile" view to be on `md` instead of `sm` (just for logged in).
https://github.com/user-attachments/assets/562c5f21-9f17-4bab-885d-6f122fcb3625
=> style(frontend): Increase breakpoint for mobile view

src/frontend/src/lib/components/dapps/DappPromoBanner.svelte
The buttons and text of the DappPromoBanner are not visible during loading of the image. Design-team wants a simple background to provide contrast during loading time.
- Add background
- improve backdrop
before: 
after:
=> style(frontend): add bg for loading phase of dapp promo banner

src/frontend/src/lib/utils/carousel.utils.ts, src/frontend/src/tests/lib/utils/carousel.utils.spec.ts
This PR includes utils needed for the Carousel component. The idea is to take provided to `Carousel` as children slides (can be any HTML elements, components, etc.) and to create a slider frame - a div that has `slidesNumber * slideWidth` width (only active slide is visible) and includes all slides with equal (percentage) size. The other 3 functions are small helpers to enable/disable (we need to disable animation when we do last-to-first and first-to-last switches) animation and to change a current slide by applying `transform` to the frame.   
Please let me know if you need more context to review this PR (e.g. you also want to include the UI component itself here).
https://github.com/user-attachments/assets/0cf5618b-1e26-45d2-8b9f-b2d1c3ce771c
=> feat(frontend): Carousel utils

src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte, src/frontend/src/lib/components/hero/HeroContent.svelte, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/receive/ReceiveQRCode.svelte, src/frontend/src/lib/components/send/SendTokensList.svelte, src/frontend/src/lib/components/tokens/TokenBalance.svelte, src/frontend/src/lib/components/tokens/TokenBalanceSkeleton.svelte, src/frontend/src/lib/components/tokens/TokenCard.svelte, src/frontend/src/lib/components/tokens/TokenCardContent.svelte, src/frontend/src/lib/components/tokens/TokenCardSignedOut.svelte, src/frontend/src/lib/components/tokens/TokenExchangeValueSkeleton.svelte, src/frontend/src/lib/components/tokens/TokenLogo.svelte, src/frontend/src/lib/components/tokens/TokenName.svelte, src/frontend/src/lib/components/tokens/TokenSymbol.svelte, src/frontend/src/lib/components/tokens/TokensSignedIn.svelte, src/frontend/src/lib/types/token-card.ts
We want to re-use TokenCard and its related components for the token groups. However, to abstract the data provided, instead of Token, we create a set of data that are common/required in both cases: single token or token group.
This is just a refactoring PR.
- Create type with common props required for the token card, called `CardData`
- Substitute the input types of all token card components from `Token`/`TokenUi` to `CardData`.
- Substitute the input name of all token card components from `token` to `data`.
=> refactor(frontend): Limit data provided to token cards

src/frontend/src/lib/components/tokens/TokenGroupCard.svelte
Not really sure how, but a missing commit was lacking in PR #3054 and it was merged even if the CI checks didn't pass.
So fixing it here
=> fix(frontend): Deprecated input for TokenGroupCard

src/frontend/src/env/dapp-descriptions.json, src/frontend/src/lib/types/oisyDappDescription.ts
We need to extend dApps description schema with data required for Carousel slides. Some fields (e.g. logo) is already present in the JSON, therefore I added only the missing ones. The fields are optional in case in the future not all dApps need to be showcased in the carousel.
=> feat(frontend): extend dApps description schema with data for carousel

src/frontend/src/tests/lib/utils/token-card.utils.spec.ts
Since ICP token name is the same as ICP network name, to be completely sure of the correct implementation of mapHeaderData, we use the Sepolia token, since the name of the token is slightly different than the name of the network.
=> test(frontend): Use Sepolia token for card tests

src/frontend/src/lib/components/tokens/TokenCardContent.svelte, src/frontend/src/lib/components/tokens/TokenGroupCard.svelte
To show the balance (and USD balance) of the summary of the token group, we need to use `TokenCardContent` instead of `TokenCard`.
=> fix(frontend): Show balance in Token Group Card

src/frontend/src/lib/components/core/Modals.svelte, src/frontend/src/lib/components/dapps/DappModalDetails.svelte, src/frontend/src/lib/components/dapps/DappsExplorerSignedIn.svelte
This PR is about moving `DappModal` from `DappsExplorerSignedIn` to global `Modals` so the modal can be opened from different places (e.g. list item on the explorer page, carousel slides on the token page). Also, to avoid having `selectedDapp` retrieval logic in the global component (`Modals`), I created `DappModalDetails` where all the checks will be placed.
=> feat(frontend): make DappModal accessible across all routes

src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte, src/frontend/src/lib/components/tokens/TokensSignedIn.svelte, src/frontend/src/lib/types/token.ts, src/frontend/src/lib/utils/token.utils.ts
We want to start grouping tokens that refers to the same underlying. For example `BTC` and `ckBTC`, or `ETH` and `ckETH`. Basically twin tokens, where the "native token" definition falls on the most mainstream one of the group (BTC, ETH, etc)
To do that we first group the sorted tokens and then we show single-tokens differently from the token groups (we use the `TokenCardGroup` component introduced recently).
- Modify function `isTokenUiGroup` to recognize the correct group type instead of the token type.
- Add an ID for the token group: this will be the same of the native token so that the animation can recognize it as the same element.
- Group tokens with function `groupTokensByTwin` in `TokenDisplayHandler`.
- In the token list, differentiate how we show a group from how we show a …
=> feat(frontend): Implement token groups in tokens list

src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
We need to re-use the sub-functions of `sumTokenBalances` and `sumTokenUsdBalances`, specifically to provide only the balances instead of the entire token object.
=> refactor(frontend): Extract sub-functions to sum balances

src/frontend/src/lib/components/carousel/Carousel.svelte
While implementing Carousel usages (2 instances rendered on the token page to comply with the provided design, one for XL screens, another one for smaller ones), I noticed that the frame and timers are being initialised even if one of carousel is not actually visible (display: none). In this PR, I add a check to avoid that. The check works and stops all processes both on mount and on resize.
=> feat(frontend): adjust Carousel initialisation function

src/frontend/src/lib/components/dapps/DappTags.svelte, src/frontend/src/lib/components/ui/Badge.svelte
Implement the reusable component 'Badge' from figma.
- Implement Badge
- Replace current concrete 'implementations' in DappTags with abstracted component
Looks same same:
new:
=> feat(frontend): add badge component

src/frontend/src/lib/utils/token.utils.ts
The svelte animation/transition bases itself on the "ID" given to  a specific component. For example, in the Tokens list, the "ID" in the `EACH` loop is given by the `token.id`:
``` svelte
{#each tokens ?? [] as token (token.id)}
```
That allows the `flip` animation, for example, to know exactly what is the component to "flip" even if it changes itself inside, or for the `fade` transition to "fade" always the same component.
So, if two components have the same ID, they will be treated as the same component for animation/transition.
However, for group cards, we have different IDs for the "native token" Token card and its Group card when one is created. Ideally, the transition between the two cards is none, meaning that a Native Token card becomes a group card if there are twin tokens. …
=> style(frontend): smooth transition between group card and token card

src/frontend/src/lib/components/tokens/TokenGroupCard.svelte, src/frontend/src/lib/stores/token-group.store.ts, src/frontend/src/lib/utils/token.utils.ts
Integrate group store with token group card to enable storing the isExpanded state of the card.
- Rename expanded to isExpanded for consistency
- use Symbol.for on group creation to prevent mismatch of logically same group
- Glue store and component
=> feat(frontend): integrate group store

src/frontend/src/routes/(public)/+layout.svelte, src/frontend/src/routes/(public)/terms-and-conditions/+page.svelte, src/frontend/src/routes/(public)/terms-and-conditions/+page.ts, tailwind.config.ts
We would like to have "public" routes in OISY, for example for Terms and Conditions. So, we set an independent page, agnostic to signed in or not.
=> feat(frontend): New public routes

src/frontend/src/lib/components/send/SendInputAmount.svelte, src/frontend/src/lib/components/ui/InputCurrency.svelte
Similarly to #3141, this PR extract a common input component for input of type currency.
- Create component and consume it.
=> feat(frontend): extract common input currency component

src/frontend/src/eth/components/tokens/AddTokenForm.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectForm.svelte, src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/send/SendInputDestination.svelte, src/frontend/src/lib/components/ui/InputText.svelte
I noticed that all input type `text` are similar. Given that I want to add a property to all of them, I thought that we can get started by extracting a common component.
- create `InputText` for all text inputs and consume it
=> feat(frontend): extract common input text component

src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte, src/frontend/src/lib/components/ui/ButtonBack.svelte
The "Back" button on the "How to convert..." modal does no inherits the secondary style of back button and is not fullwidth.
- Add `fullWidth` to `ButtonBack`
- Correct slot, style and width for the back button on the modal
Before:
After:
=> feat(frontend): how to convert back btn full width

.github/workflows/auto-format.yml
The dependabot workflows fail because of insufficient access rights. So we want to exclude the dependabot workflows.
- added condition to exclude dependabot workflows
=> fix(ci): fix dependabot issue

src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/lib/components/ui/SplitPane.svelte
To make it less dispersive, we reduce the padding on top of Hero, for the different brakpoints.
https://github.com/user-attachments/assets/5da80529-c68c-49f5-9c57-c8b57b53cc1e
=> style(frontend): Reduce padding of Hero

package-lock.json, package.json
We bump to the first `beta` version of OISY that is `v0.9.0`
=> chore(release): next version

src/frontend/src/env/oisy.metadata.json, src/frontend/src/env/types/env-oisy-metadata.ts, src/frontend/src/lib/constants/oisy.constants.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/lib/utils/i18n.utils.ts, src/frontend/src/tests/lib/utils/i18n.utils.spec.ts
We substitute the definition of the Alpha warning URL with the Repo status URL.
=> chore(frontend): Remove Alpha warning URL from metadata

README.md, src/frontend/src/lib/components/dapps/SubmitDappButton.svelte
When an user click to the "Submit your dApp" button it is redirected to the login page of Github, if it is not connected yet.
To avoid this disturbance, we redirect to a new section of the README file (that itself has the link to the submission form).
=> docs(frontend): Add description for submitting a dApp

src/frontend/src/lib/components/carousel/Carousel.svelte, src/frontend/src/routes/(app)/+layout.svelte, src/frontend/src/routes/(app)/+page.svelte
The idea is to disable Carousel slide animation on init (on back/load). Also, I added `out` animation to dapps carousel containers, similar as we had them for `in`.
=> feat(frontend): disable Carousel slide animation on init

src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
In this PR, BTC networks are filtered out from the selector in the Import modal. Also, an additional message is added in case user opens the modal while having an active BTC network.
=> feat(frontend): handle BTC in the Import modal

src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte
The "custom_tokens_not_supported" should be shown only if unsupported network is selected. In case, no network selected at all, it must be hidden.
=> fix(frontend): do not show token import text if no network selected

src/frontend/src/lib/components/dapps/DappModal.svelte
Fix a side effect of the new modal design #3171. The banner for the dapp modal should be outside of the card.
Incorrect:
After:
=> style(frontend): dapp modal banner outside card

src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/send/SendInputDestination.svelte, src/frontend/src/lib/components/ui/InputTextWithAction.svelte
I've been bothered for quite some time by input fields that lack a call to action yet don't use the full width for the input. The root cause of the issue is that the slot must be declared at the top, even if it's not used, which causes gix-cmp to assume that a slot is always in use.
To resolve this, I created a new component, `InputTextWithAction`. This allows us to choose either a simple input or an input with an action, as needed.
Before:
After:
=> feat(frontend): input text with action

src/frontend/src/lib/styles/global/gix.scss
Change the font-size of the titles in the modals. We were requested 20px, I think it's sosolala h3 but, let me know if not.
- Add global rule for title in modal
Before:
After:
=> style(frontend): modal title font-size

src/frontend/src/lib/components/send/SendTokensList.svelte
The "zero balance no send" message style got a bit off.
- Display list of tokens only if there are tokens
- Adapt padding
Before:
After:
=> feat(frontend): zero balance send message

src/frontend/src/lib/components/tokens/TokenCard.svelte, src/frontend/src/lib/components/tokens/TokenCardContent.svelte, src/frontend/src/lib/components/tokens/TokenGroupCard.svelte, src/frontend/src/lib/components/tokens/TokenSymbol.svelte
It was requested to hide the network logo for the Token Group card.
=> feat(frontend): Hide network logo for Token group

src/frontend/src/lib/components/dapps/DappCard.svelte, src/frontend/src/lib/components/dapps/DappModal.svelte, src/frontend/src/lib/components/dapps/DappPromoBanner.svelte, src/frontend/src/lib/components/dapps/DappTags.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte, src/frontend/src/lib/i18n/en.json
Small refactoring to change `dAppname` to `dAppName`, and to not use the `name` variable that it was giving a deprecation warning by the `dom`.
=> refactor(frontend): Rename dAppname to dAppName

src/frontend/src/env/networks.env.ts, src/frontend/src/lib/types/network.ts, src/frontend/src/lib/validation/network.validation.ts
We want to use Zod to safe parse the types of `Token`. Its interface uses the type `Network` too. So, we change type `NetworkId`, branding it specifically for NetworkId. This is similar to PR #3189 
- Create schema for `NetworkId`.
- Use it to define `NetworkId` type.
- Create util to parse `NetworkId` type.
- Adapt the code in each usage of `NetworkId`.
I didn't create a test for the util because I am not sure how to make it throw errors, but open to suggestions.
=> refactor(frontend): Use Zod for NetworkId

src/frontend/src/lib/types/token.ts
We create Zod schemas for a few interfaces of `Token` type.
Note: the types `TokenOisySymbol` and `TokenOisyName` were not used anymore, not even globally. So, we removed them.
=> refactor(frontend): Include Zod in Token interfaces

src/frontend/src/btc/convert/ConvertToCkBTC.svelte, src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Add the convert-to-ckBTC button for BTC mainnet transactions page.
=> feat(frontend): convert to ckBTC button for BTC mainnet

src/frontend/src/lib/types/network.ts
We change `Network` type to use Zod directly.
=> feat(frontend): Use Zod for Network type

src/frontend/src/lib/components/tokens/TokenGroupCard.svelte, src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte, src/frontend/src/lib/components/tokens/TokensSignedIn.svelte, src/frontend/src/lib/types/token-group.ts, src/frontend/src/lib/types/token.ts, src/frontend/src/lib/utils/token-card.utils.ts, src/frontend/src/lib/utils/token-group.utils.ts, src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token-group.utils.spec.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
We re-organize the `token-group` related functions in a separate file.
=> refactor(frontend): Separate module for token-group

src/frontend/src/lib/components/hero/HeroContent.svelte, src/frontend/src/lib/components/signer/SignerAlert.svelte, src/frontend/src/lib/components/signer/SignerAnimatedAstronaut.svelte, src/frontend/src/lib/components/signer/SignerLoading.svelte, src/frontend/src/lib/components/ui/ButtonAuthenticate.svelte, src/frontend/src/lib/components/ui/Info.svelte
Only for Tailwind, we want to replace the use of `blue-ribbon` (`primary`) with the new colors mapping.
=> refactor(frontend): Use colors mapping instead of blue-ribbon

src/frontend/src/lib/components/buy/BuyModal.svelte, src/frontend/src/lib/components/onramper/OnramperWidget.svelte, src/frontend/src/lib/styles/global/gix.scss
The Onramper widget was not scrollable for smaller screens, impeding the user to click the Buy button.
https://github.com/user-attachments/assets/ef40b4c9-cae5-4305-9dbb-239bf824c72c
=> fix(frontend): Onramper widget is scrollable now

src/frontend/src/lib/validation/utils.validation.ts
It slipped through my fingers that both imports from `zod` should be types. It changes nothing for the code, but it is the "correct" import consistency,
=> refactor(frontend): correct imports in safeParse

src/frontend/src/eth/constants/steps.constants.ts
The progression steps of the WalletConnect signing process were set incorrectly. I have a feeling they've always been incorrect; I just noticed it today. As a result, the progression of the `signMessage` service was not displayed visually. Feature itself was and is fine.
- Correct the enum value used to define the progression component
Before:
After:
=> fix(frontend): WalletConnect sign progression steps

src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte, src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte, src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte, src/frontend/src/icp/components/transactions/IcTransactionsBitcoinStatusBalance.svelte, src/frontend/src/lib/components/dapps/DappPromoBanner.svelte, src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/hero/HeroContent.svelte, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/navigation/NavigationItem.svelte, src/frontend/src/lib/components/receive/ReceiveAddress.svelte, src/frontend/src/lib/components/signer/SignerAlert.svelte, src/frontend/src/lib/components/signer/SignerAnimatedAstronaut.svelte, src/frontend/src/lib/components/signer/SignerLoading.svelte, src/frontend/src/lib/components/signer/SignerOrigin.svelte, src/frontend/src/lib/components/signer/SignerPermissions.svelte, src/frontend/src/lib/components/tokens/TokensZeroBalance.svelte, src/frontend/src/lib/components/ui/Badge.svelte, src/frontend/src/lib/components/ui/ButtonAuthenticate.svelte, src/frontend/src/lib/components/ui/ButtonControl.svelte, src/frontend/src/lib/components/ui/ButtonMenu.svelte, src/frontend/src/lib/components/ui/DropdownButton.svelte, src/frontend/src/lib/components/ui/ExternalLink.svelte, src/frontend/src/lib/components/ui/MessageBox.svelte, src/frontend/src/lib/components/ui/RoundedIcon.svelte, src/frontend/src/lib/components/ui/WarningBanner.svelte, src/frontend/src/lib/styles/global/button.scss, src/frontend/src/routes/(sign)/sign/+page.svelte, tailwind.config.ts
It is too verbose to have bg-background- or border-border- for the new color mapping. So, we simplify it extending the colors of specific scopes with the correct mapping:
1. Background: `bg-` and `gradient-`
2. Border: `border-` and `ring-`
3. Foreground: `text-`
Thanks @peterpeterparker for the suggestion!
=> refactor(frontend): remove prefix from new colors

src/frontend/src/lib/components/transactions/TransactionsPlaceholder.svelte
Resolve npm run check fails due to non-existent classname. https://github.com/dfinity/oisy-wallet/pull/3295/files caused and https://github.com/dfinity/oisy-wallet/pull/3242 caused this issue.
use new classnames
=> style(frontend): fix build

src/frontend/src/lib/utils/token-group.utils.ts, src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token-group.utils.spec.ts
We want to change the way we group tokens, to have more than two elements in the group, and to try and avoid repetitions/glitches when the order of the token list is not the usual one.
The "original" token of a certain group or of a certain other token; for example `BTC` is the "main token" of `ckBTC`, or `ETH` is the "main token" of `SepoliaETH`. Typically, a token and its "main token" should be 1:1.
A token that has a "main token", even if not present in the list. It is just to indicate that it should always be grouped if the latter is present.
To improve the grouping util, we first break it down into smaller utils: one for grouping a `main` token, and one to create a `secondary` token.
If the token has no "main token", it is either a "main token" for an existing group,
or a "main …
=> feat(frontend): Utils to group main and secondary tokens

src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte
Correcting color of information in the token form review for IC tokens.
=> style(frontend): change color of info in IcAddTokenForm

src/frontend/src/tests/btc/derived/btc-transactions.derived.spec.ts, src/frontend/src/tests/btc/stores/btc-pending-sent-transactions.store.spec.ts, src/frontend/src/tests/btc/utils/btc-send.utils.spec.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts, src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts, src/frontend/src/tests/eth/utils/transactions.utils.spec.ts, src/frontend/src/tests/icp/utils/cketh-memo.utils.spec.ts, src/frontend/src/tests/lib/canisters/backend.canister.spec.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts, src/frontend/src/tests/lib/components/guard/AddressGuard.spec.ts, src/frontend/src/tests/lib/components/send/SendInputAmount.spec.ts, src/frontend/src/tests/lib/services/loader.services.spec.ts, src/frontend/src/tests/lib/stores/balances.store.spec.ts, src/frontend/src/tests/lib/stores/signer.store.spec.ts, src/frontend/src/tests/lib/stores/token.store.spec.ts, src/frontend/src/tests/lib/stores/transactions.store.spec.ts, src/frontend/src/tests/lib/utils/auth.utils.spec.ts, src/frontend/src/tests/lib/utils/carousel.utils.spec.ts, src/frontend/src/tests/lib/utils/onramper.utils.spec.ts, src/frontend/src/tests/lib/utils/token-card.utils.spec.ts, src/frontend/src/tests/lib/utils/token-group.utils.spec.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts, src/frontend/src/tests/lib/utils/tokens.utils.spec.ts, src/frontend/src/tests/lib/utils/wizard-modal.utils.spec.ts
Just a bit of cleanup since most `vitest` imports can be spared as those are available globally.
=> chore(frontend): vitest is global - no import needed

package.json
There is no need to install `playwright` twice, we can do it once directly with deps.
=> ci(e2e): simplify script to install playwright

src/frontend/src/icp/components/transactions/IcTransactionsBitcoinStatusBalance.svelte
We adapt the refresh button to use the `brand-secondary` color for `hover` and `active`, as defined by the Design.
=> style(frontend): update Refresh button to current pallete

src/frontend/src/tests/lib/utils/credentials.spec.ts
Spotted mock data that were incomplete.
```
src/frontend/src/tests/lib/utils/credentials.spec.ts:14:6 - error TS2741: Property 'issuer' is missing in type '{ credential_type: { ProofOfUniqueness: null; }; verified_date_timestamp: [bigint]; }' but required in type 'UserCredential'.
14      {
~
15       credential_type: { ProofOfUniqueness: null },
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16       verified_date_timestamp: [123456n]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17      }
~~~~~~
src/declarations/backend/backend.did.d.ts:204:2
204  issuer: string;
~~~~~~
'issuer' is declared here.
```
=> chore(test): fix missing issuer mock data

src/frontend/src/lib/types/token.ts, src/frontend/src/lib/validation/token.validation.ts, src/frontend/src/tests/lib/validation/token.validation.spec.ts
Extract the token zod schemas and add test.
- Extract the `Token` zod from `types` to `validation`
- Add tests
- Comment about explicit type to avoid recursive import
- Add parameter validation in `parseTokenId`
=> feat(frontend): move and test token validation

src/frontend/src/icp/api/icrc-ledger.api.ts, src/frontend/src/tests/icp/api/icrc-ledger.api.spec.ts
We aim to support tokens without an index canister. This means that we want to support tokens without transactions, but we still want to fetch balances. These balances can be queried directly from the ledger.
- Add `balance` to `icrc-ledger.api`
- Comment and add todo for missing test to existing functions
=> feat(frontend): add balance to icrc-ledger.api

src/frontend/src/tests/mocks/identity.mock.ts
Spotted this check in NNS dapp which prevents the `mockIdentity` to be used without knowing. Thought it can be interesting for future proof to have it in OISY as well.
=> test(frontend): mockIdentity transformRequest

src/frontend/src/icp/types/ic-token.ts, src/frontend/src/icp/validation/ic-token.validation.ts, src/frontend/src/tests/icp/validation/ic-token.validation.spec.ts
This might not suffise but, it's a first step, type wise, to defined the "Index Canister" as optional.
I add to include comments because we cannot just set the index as optional. On the other side, I also need this new validation becase otherwise I cannot split PR  #3334 in smaller PRs.
- Provide validation and types `IcCanistersStrictSchema`
- Add TODO for making the Index Canister optional typewise
=> feat(frontend): IcCanistersStrict type and validation

src/frontend/src/lib/utils/nav.utils.ts, src/frontend/src/routes/(app)/activity/+page.ts, src/frontend/src/routes/(public)/license-agreement/+page.ts, src/frontend/src/routes/(sign)/sign/+page.ts, src/frontend/src/tests/lib/utils/nav.utils.spec.ts
We extract an util to reset the Route parameters, to be reused in the code.
=> refactor(frontend): extract util to reset route params

src/frontend/src/tests/icp/validation/ic-token.validation.spec.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts, src/frontend/src/tests/lib/utils/tokens.utils.spec.ts, src/frontend/src/tests/lib/validation/token.validation.spec.ts, src/frontend/src/tests/mocks/balances.mock.ts, src/frontend/src/tests/mocks/exchanges.mock.ts, src/frontend/src/tests/mocks/ic-tokens.mock.ts, src/frontend/src/tests/mocks/tokens.mock.ts
It's cleaner to prefix all mock values with `mock` to warn the developer that a value imported might comes from the tests.
=> test(frontend): cleanup mocks prefix

src/frontend/src/tests/lib/canisters/backend.canister.spec.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts, src/frontend/src/tests/mocks/agents.mock.ts
A bit opiniated but, I feel like it's cleaner to not have the `mock<HttpAgent>()` provided as a global mock module. Feel like it's particular to every test suite. Hence, removing the existing mock use in two tests.
=> test(frontend): remove mockedAgent

src/frontend/src/icp/components/transactions/IcTransaction.svelte
We rename the prop `transactionType` to `type`, for consistency.
Furthermore, elsewhere in the code, in the util `mapIcrcTransaction`, the type is defined as
```typescript
const type: IcTransactionType = nonNullish(fromNullable(approve))
? 'approve'
: nonNullish(fromNullable(burn))
? 'burn'
: isMint
? 'mint'
: source.incoming === false
? 'send'
: 'receive';
```
Meaning that we can simply use `type === 'send'` in the same way that we use `incoming === false`
=> refactor(frontend): rename prop of IcTransaction

vitest.config.ts
We exclude some folders from the coverage analysis, since there is nothing we can do to improve those (those are not project folders).
=> test(frontend): exclude folders from coverage analysis

src/frontend/src/tests/lib/stores/balances.store.spec.ts, src/frontend/src/tests/lib/stores/token.store.spec.ts, src/frontend/src/tests/mocks/page.store.mock.ts, vitest.setup.ts
Inspired by [NNS Dapp codebase](https://github.com/dfinity/nns-dapp/blob/95d58213187190f606cffe7b43e6fc857d50528d/frontend/__mocks__/%24app/stores.ts#L40), we create a mock for the `page` store at the base of the vitest configs.
- Create `page` store mock similar to NNS Dapp.
- Include it in `vitest.setup`.
- Adapt the tests. 
All tests still works.
=> test(frontend): create global mock for page store

.github/workflows/frontend-checks.yml, src/frontend/src/routes/(app)/+layout.svelte
As spotted by @loki344 , once again we were able to merge in `main` a PR that did not passed the frontend CI checks: latest example is PR #3410 at last commit https://github.com/dfinity/oisy-wallet/pull/3410/commits/090e14577f7f6730a02ab29a6eea79072bdaa0bf where [the frontend CI checks failed](https://github.com/dfinity/oisy-wallet/actions/runs/11738140030/job/32700102628).
The issue surges because, even if one the sub-steps of the check fail, the `may-merge` step is not marked as failed, but simply as "skipped". And that is considered by Github in the same way as "passed", or "ignored".
This PR aims to have a more explicit "fail" status for the status check `may-merge`, that is present in `frontend-checks` workflow.
We tried to solve the issue with PR #3233 but it. did not solved the …
=> fix(ci): frontend checks are not blocking merging

src/frontend/src/lib/styles/global/gix.scss
Since most of the GIX UI components use the same CSS classes namings (.content, .header, .container, .etc), the styles, that were supposed to be applied to the Modal component, affect all other GIX components inside a modal (e.g. in case token conversion flow I use `Collapsible`). This PR fixes it by applying the global styles from gix.scss only to direct children of the specified selectors.
=> fix(frontend): global GIX styles

src/frontend/src/icp/components/fee/BitcoinFeeContext.svelte, src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
To re-use `BitcoinFeeContext` in the BTC -> ckBTC flow, we need to accept `token` as a prop.
=> feat(frontend): accept token as a prop in BitcoinFeeContext

src/frontend/src/lib/components/transactions/TransactionsPlaceholder.svelte
We are using `scss` as CSS processor. In PR https://github.com/dfinity/oisy-wallet/pull/3451#discussion_r1837930148 we discussed `postcss` and noticed similar Tailwind imports can be resolved with our standard approach, therefore this PR removes an inconsistency.
=> style(frontend): use scss instead of postcss

src/frontend/src/lib/components/convert/ConvertValue.svelte
Desktop (1 row = 1 ConvertValue component):
Mobile Desktop (1 row = 1 ConvertValue component):
=> feat(frontend): ConvertValue component

src/frontend/src/lib/components/convert/ConvertInputAmount.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/convert.ts, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/convert/ConvertInputAmount.spec.ts
In this PR, `ConvertInputAmount` component is implemented. Note: unfortunately, I needed to "hack" some internal GIX Input styles in order to match the design from Figma. 
Empty state:
Normal state:
Disabled state:
Error state:
=> feat(frontend): ConvertInputAmount component

canister_ids.json, dfx.json
We have lots of test frontend canisters (test-fe-{1..4}) but no similar backend canisters.
- Added a test canister for pure-backend testing.
- Added the canister to cycleops
- Added the same controllers as for the staging backend
- I have used this test canister for testing automated cycles ledger top-up.
=> chore(devops): Add backend test canister

src/backend/backend.did, src/backend/src/lib.rs, src/backend/src/signer.rs, src/backend/tests/it/main.rs, src/backend/tests/it/signer.rs, src/declarations/backend/backend.did, src/declarations/backend/backend.did.d.ts, src/declarations/backend/backend.factory.certified.did.js, src/declarations/backend/backend.factory.did.js, src/shared/src/types.rs
We need to automatically top up the oisy cycles ledger account.
We do this by having an API method on the backend canister that tops up the account.  The method can be called by canister controllers or automatically on a timer.
- Define (but do not implement) an API method to  top up the ledger canister.
- Implementation is omitted to keep the PRs small.
- Update the candid file and bindings.
CI has an existing test to verify that the bindings are up to date.
=> feat(backend): Add topping up API

src/frontend/src/eth/components/transactions/EthTransaction.svelte, src/frontend/src/eth/components/transactions/EthTransactions.svelte, src/frontend/src/lib/components/transactions/AllTransactionsList.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
For consistency, we rename all variables related to Ethereum transaction modal store.
=> refactor(frontend): rename ETH transaction modal store

src/frontend/src/lib/components/ui/RoundedIcon.svelte
Maybe this PR is not required, but I wanted to check if there are any objections when removing some props from `RoundedIcon`. 
Being a UI component, maybe it is good to have customizable props, but they are really not used for now.
Additionally, we replace `style` with Tailwind classes.
=> refactor(frontend): simplify component RoundedIcon

src/frontend/src/eth/components/wallet-connect/WalletConnectButton.svelte, src/frontend/src/lib/components/about/AboutItem.svelte, src/frontend/src/lib/components/common/MaxButton.svelte, src/frontend/src/lib/components/common/QRButton.svelte, src/frontend/src/lib/components/core/Back.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte, src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/components/icons/IconAstronautHelmet.svelte, src/frontend/src/lib/components/ui/Copy.svelte, src/frontend/src/lib/components/ui/ExternalLink.svelte, src/frontend/src/lib/styles/global/text.scss
The custom CSS class `text-primary` was still using the definition of primary color that was not the one according to new mapping colors. We replace it.
=> refactor(frontend): replace CSS class text primary with mapped colors

src/frontend/src/tests/icp/workers/ic-wallet-transactions.worker.spec.ts
- Rename the test name because it covers the "transactions" worker and we are about to add "balance"
- Correct a leftover - i.e. use the Icrc scheduler for testing error as well
=> test(frontend): rename and leftover in ic-wallet.worker

src/frontend/src/icp/workers/icp-wallet.worker.ts, src/frontend/src/tests/icp/workers/ic-wallet.worker.spec.ts
Even though we won't support "balance" only for ICP, let's rename the init scheduler with "transactions" anyway.
=> refactor(frontend): rename fn to initIcpWalletTransactionsScheduler

src/frontend/src/btc/components/send/BtcSendReview.svelte, src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/btc/components/send/BtcUtxosFee.svelte, src/frontend/src/btc/services/btc-send.services.ts
"progress" was required but never used in that service. This popped up when I started reusing this method in the conversion flow.
=> feat(frontend): remove unnecessary param from the utxos service

src/frontend/src/lib/components/convert/ConvertNetwork.svelte
`ConvertNetwork` component in action for both source and destination tokens:
=> feat(frontend): ConvertNetwork component

src/frontend/src/lib/components/convert/ConvertAmountExchange.svelte, src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
The goal is to create a util for finding a twin token that can be reused in token-grouping.util as well as in the upcoming `convert.store`.
=> feat(frontend): findTwinToken util

src/frontend/src/lib/components/convert/ConvertAmountExchange.svelte, src/frontend/src/tests/lib/components/convert/ConvertAmountExchange.spec.ts
`ConvertAmountExchange` component in action (when some of the values is undefined, just a regular skeleton will be shown):
=> feat(frontend): ConvertAmountExchange component

src/frontend/src/icp/utils/icrc.utils.ts, src/frontend/src/lib/utils/token-group.utils.ts, src/frontend/src/tests/lib/utils/token-group.utils.spec.ts
There was a duplicated `isIcCkToken` function that not really fits the correct validation. So we replace with the correct one that uses zod.
=> refactor(frontend): use correct Ck token validation util

src/frontend/src/env/types/env-icrc-token.ts, src/frontend/src/env/types/env-sns-token.ts, src/frontend/src/icp/services/icrc-custom-tokens.services.ts, src/frontend/src/icp/types/icrc-custom-token.ts
On one hand, we will extend the environment with some "additional icrc tokens" #3506, on the other, existing "sns env tokens" are not solely "icrc tokens" because they contains addition information such as the root canister.
To clean up a bit the naming and data inconsistency, this PR move and rename the sns related env types to a particular module and also add the "Schema" suffix we have started to use for our zod schema.
Skipped.
=> refactor(frontend): rename icrc env tokens specific for sns

src/frontend/src/env/schema/env-oisy-metadata.schema.ts, src/frontend/src/lib/constants/oisy.constants.ts
Use our naming and structure convention for `OisyMetadataSchema`.
Skipped.
=> refactor(frontend): oisy metadata schema

src/frontend/src/env/schema/env-additional-icrc-token.schema.ts, src/frontend/src/env/tokens.icrc.env.ts, src/frontend/src/env/tokens.icrc.json, src/frontend/src/env/types/env-icrc-additional-token.ts, src/frontend/src/env/types/env-icrc-token.ts
We want to load a selection of additional icrc tokens. This prepares the json data structure with zod parsing and typing.
- Add types with zod
- Add parsing
- add empty json structure
=> feat(frontend): add json import for additional icrc env tokens

src/frontend/src/lib/stores/convert.store.ts, src/frontend/src/tests/lib/stores/convert.store.spec.ts
In this PR, a new store is created. It will be used across the conversion flow files. According to the new designs, we need to display data about both source and destination tokens, therefore the store contains the same set of info for both provided tokens.
=> feat(frontend): convert store

src/frontend/src/icp/services/ic-listener.services.ts, src/frontend/src/tests/icp/services/ic-listener.services.spec.ts
When the IC web worker scheduler runs without index canister to solely fetch the balance from the ledger, the related ic transactions store entry for the token should be nullified.
- `nullify` ic transactions store if undefined transactions is received (no matter what - i.e. regardless if there were transactions in memory)
=> feat(frontend): nullify ic transactions store on post message

src/frontend/src/lib/components/convert/ConvertAmountDisplay.svelte, src/frontend/src/tests/lib/components/convert/ConvertAmountDisplay.spec.ts
=> feat(frontend): ConvertAmountDisplay component

src/frontend/src/icp/components/tokens/IcHideTokenModal.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Now that we support custom tokens without an Index canister, it should also be possible to hide them. However, this is not yet the case, as the hide function currently requires an Index canister to be provided.
- Handle nullable Index canister ID in "Hide" component.
- Remove unused label key.
Manually tested.
=> feat(frontend): hide custom token without Index canister

src/frontend/src/eth/stores/eth-transactions.store.ts
Renaming Ethereum transactions store types.
=> refactor(frontend): rename types of Ethereum transactions store

src/frontend/src/lib/utils/format.utils.ts
I missed a commit: the docstring for `formatSecondsToNormalizedDate`.
=> chore(frontend): missing docstring for formatSecondsToNormalizedDate

src/frontend/src/lib/config/convert.config.ts, src/frontend/src/lib/config/send.config.ts, src/frontend/src/lib/enums/wizard-steps.ts, src/frontend/src/lib/types/steps.ts
This PR includes convert wizard steps for the swap flow. It also shares a common interface `WizardStepsParams` between send and convert flows.
=> feat(frontend): convert wizard steps

.github/workflows/deploy-to-environment.yml, scripts/deploy.backend.sh
If an API changes, dfx will typically ask the user whether they really want to deploy.  In CI, we need a way of saying "yes", but probably don't want this to be the default.
There is an existing checkbox for forcing the backend deployment to take place, no matter what.  It seems reasonable to use `--yes` when that is selected, so we do not need a new input.
- If `force-backend` is selected in the CI deployment task, deploy with `--yes` and `--upgrade-unchanged`.
Executed the action by:
- Disabling the check that allows deploying only from main.
- Running the action with: `gh workflow run deploy-to-environment.yml --ref "yes" --field network=staging --field canister=backend --field force-backend=true`
- Re-enabling the main check.
=> feat(devops): Manually deploy breaking changes via CI

src/frontend/src/btc/services/btc-send.services.ts, src/frontend/src/tests/btc/services/btc-send.services.spec.ts
As agreed, before adding changes to a function, I'm covering existing functionality with tests. In this case, it's about `sendBtc` of `btc-send.services`.
=> test(frontend): add sendBtc tests

src/frontend/src/lib/utils/transactions.utils.ts, src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
I thought a lot about what would be the best way to reduce loops for the unified transaction list, but the only flow that I was able to reach and respect the requirements is:
- First loop --> unify the transactions looping the enabled tokens
- Second loop --> sort the transactions
- Third loop --> group by date (that gives automatically the correct sorting)
I verified if performance was better when the sorting would happen after, for dates and for each date group, but it was not better.
Furthermore there would be another method, but it would create the date groups directly when rendering inside the component. We yield the "latest date" and every-time it changes, we add a title with the new date, so we don't need to group anymore, just an if condition inside the component rendering. …
=> feat(frontend): util to sort unified transaction list

src/frontend/src/icp/utils/icp-transactions.utils.ts, src/frontend/src/icp/utils/icrc-transactions.utils.ts, src/frontend/src/lib/canisters/signer.errors.ts
The PR fixes one of the issues reported in https://github.com/dfinity/oisy-wallet/issues/3480. Also, I noticed a few more places where the same kinda of error could have appeared.
=> fix(frontend): use jsonReplacer to stringify bigints

src/frontend/src/btc/components/transactions/BtcTransaction.svelte, src/frontend/src/eth/components/transactions/EthTransaction.svelte, src/frontend/src/eth/components/transactions/EthTransactions.svelte, src/frontend/src/lib/components/transactions/AllTransactionsList.svelte, src/frontend/src/lib/components/transactions/Transaction.svelte, src/frontend/src/lib/types/transaction.ts, src/frontend/src/lib/utils/transactions.utils.ts, src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
After PR #3537 , we can provide the token to the Transaction card components, to show the Token logo in the unified transaction list.
- Make prop `token` for `EthTransaction` and adapt the usage, removing the derived store and providing the input from its parents, like `EthTransactions`.
- Map `token` for all the UI transactions.
- Adapt `AllTransactionsList`.
Test adapted and here results.
=> feat(frontend): add token prop to transaction card components

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/btc/services/btc-send.services.ts, src/frontend/src/tests/btc/services/btc-send.services.spec.ts
The idea is to decouple btc-send.services from the send flow so the service can be re-used by the conversion wizard too.
=> feat(frontend): onSend callbacks in btc-send.services

src/frontend/src/lib/components/convert/ConvertFee.svelte
A small wrapper around `ConvertAmountDisplay` to display provided `feeAmount` (or `zeroAmountLabel` if fee is zero and the label is there).
Small heads up: total fee will have a separate component, since it should be displayed differently.
P.S.: I haven't added unit tests for this one as the child component as well as all used here utils are tested separately.
=> feat(frontend): ConvertFee component

src/frontend/src/lib/components/convert/ConvertFeeTotal.svelte
A component for displaying total fee value. The difference with `ConvertFee` component is that total fee should only display a dollar value, and this value should be passed as `main-value` slot (in order to have `font-bold`).
P.S.: same as with `TotalFee`, I think this component is too simple to have its own unit tests. Let me know if you still want to have some tests.
=> feat(frontend): ConvertFeeTotal component

src/frontend/src/lib/components/convert/ConvertFee.svelte, src/frontend/src/lib/components/convert/ConvertFeeTotal.svelte, src/frontend/src/lib/utils/format.utils.ts, src/frontend/src/tests/lib/utils/format.utils.spec.ts
Before I start introducing new places with the similar formatting, creating the util that we discussed with @AntonioVentilii .
=> feat(frontend): formatTokenBigintToNumber util

src/frontend/src/lib/components/transactions/AllTransactionsList.svelte, src/frontend/src/tests/lib/components/transactions/AllTransactionsList.spec.ts, src/frontend/src/tests/mocks/ic-transactions.mock.ts
After PR #3568, we add the IC transactions in the UI.
=> feat(frontend): add IC transactions in AllTransactionsList

src/frontend/src/env/tokens.btc.env.ts, src/frontend/src/lib/constants/tokens.constants.ts
We move `SUPPORTED_BITCOIN_TOKENS` since it was giving circular reference on initiation.
=> fix(frontend): remove circular reference in tokens env file

src/frontend/src/lib/components/transactions/Transaction.svelte, src/frontend/src/lib/components/ui/RoundedIcon.svelte, src/frontend/src/tests/btc/components/fee/UtxosFeeContext.spec.ts, src/frontend/src/tests/btc/derived/tokens.derived.spec.ts, src/frontend/src/tests/eth/components/loaders/LoaderEthTransactions.spec.ts, src/frontend/src/tests/eth/derived/tokens.derived.spec.ts, src/frontend/src/tests/icp-eth/services/custom-token.services.spec.ts, src/frontend/src/tests/icp/components/transactions/IcTransactions.spec.ts, src/frontend/src/tests/icp/services/icrc.services.spec.ts, src/frontend/src/tests/icp/utils/cketh-transactions.utils.spec.ts, src/frontend/src/tests/lib/derived/exchange.derived.spec.ts, src/frontend/src/tests/lib/derived/tokens.derived.spec.ts, src/frontend/src/tests/lib/utils/format.utils.spec.ts, src/frontend/src/tests/lib/utils/nav.utils.spec.ts, src/frontend/src/tests/lib/utils/token-toggle.utils.spec.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts, src/frontend/src/tests/lib/validation/coingecko.validation.spec.ts, src/frontend/src/tests/lib/validation/token.validation.spec.ts
The prop iconStyleClass seemed unnecessary for just opacity. So we substitute with a direct boolean prop (reference https://github.com/dfinity/oisy-wallet/pull/3537#discussion_r1842195829).
=> refactor(frontend): remove custom class prop from RoundedIcon

src/frontend/src/lib/components/transactions/TransactionsDateGroup.svelte, src/frontend/src/lib/types/transaction.ts, src/frontend/src/tests/lib/components/transactions/TransactionsDateGroup.spec.ts
As suggested in https://github.com/dfinity/oisy-wallet/pull/3601#pullrequestreview-2440325251 , we rename type`AllTransactionsUi` for readability reasons.
=> refactor(frontend): rename AllTransactionsUi type

src/shared/src/types.rs
The 10T cycles ledger balance has proven itself insufficient for usage spikes.
- Increase the cycles ledger topping-up threshold to 50T.
N/A
=> chore(backend): Increase the topping-up threshold to 50T

src/frontend/src/lib/utils/convert.utils.ts, src/frontend/src/tests/lib/utils/convert.utils.spec.ts
The util that will be used in `ConvertAmountSource` as `customValidate` function for the input. I extracted it from the component for the unit testing purposes.
=> feat(frontend): validateConvertAmount util

src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/tests/lib/components/convert/ConvertAmountSource.spec.ts
Component for handling source token amount input and all related information appearance.
Desktop:
Mobile:
=> feat(frontend): ConvertAmountSource component

src/frontend/src/eth/components/loaders/LoaderEthTransactions.svelte, src/frontend/src/eth/components/loaders/LoaderMultipleEthTransactions.svelte, src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/tests/eth/components/loaders/LoaderEthTransactions.spec.ts, src/frontend/src/tests/eth/components/loaders/LoaderMultipleEthTransactions.spec.ts
It seems more consistent to rename `loadTransactions` to `loadEthereumTransactions` (both ETH and ERC20). Note that `loadEthTransactions` already exists in the same module.
=> refactor(frontend): rename services for Ethereum transactions

src/frontend/src/lib/stores/modal.store.ts, src/frontend/src/tests/lib/stores/modal.store.spec.ts
As discussed offline and in https://github.com/dfinity/oisy-wallet/pull/3608#discussion_r1845974057 , it does not make really sense to export `initModalStore` to test it, when we can test directly the initiated store modalStore.
In this PR we replace it.
=> test(frontend): test modal store directly

src/frontend/src/lib/utils/transactions.utils.ts, src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
For now, we will put the missing timestamps (local replica transctions for example) at the bottom of the unified transaction list.
=> refactor(frontend): missing timestamps at the bottom of transactions list

src/frontend/src/icp/components/transactions/IcTransaction.svelte, src/frontend/src/icp/components/transactions/IcTransactionModal.svelte, src/frontend/src/icp/components/transactions/IcTransactions.svelte, src/frontend/src/lib/components/transactions/AllTransactionsList.svelte, src/frontend/src/lib/utils/transaction.utils.ts, src/frontend/src/tests/lib/utils/transaction.utils.spec.ts
The component `IcTransactionModal` was using the token store to define the token to which the transaction refers too.
That means that in the unified transaction list, we will have an issue when opening the modal, specifically, the amount is not calculated.
We remove this dependency making it a prop.
An alternative could be to create a context for the transaction modal.
- Add prop token to `IcTransactionModal`.
- Make the `modalStore` call pass not only the transaction but the token too.
- Create function to "extract" the transaction data from the modal store. Plus tests.
- Adapt both `IcTransactions` and `AllTransactionsList`.
=> feat(frontend): remove token store from IcTransactionModal

src/frontend/src/btc/components/convert/BtcConvertProgress.svelte, src/frontend/src/lib/enums/progress-steps.ts
This PR contains a basic version of the BtcConvertProgress component. There is already a new, much fancier designs in Figma for this modal, therefore I kept it simple in the first iteration.
=> feat(frontend): BtcConvertProgress component

scripts/check.unused.mjs
The script `check.unused.mjs` was mistakenly pointing out some components that were actually used inside an util. For example, the icons used by `mapTransactionIcon`:
```bash
antonio.ventilii@Antonio-Ventilii-W0LHX2LX6V oisy-wallet % ./scripts/check.unused.sh
Scanning src/frontend/src folder to find all .svelte files
Found 5 unused component(s).
Unused Svelte file: /Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/btc/components/convert/BtcConvertTokenWizard.svelte
Unused Svelte file: /Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/lib/components/icons/IconConvert.svelte
Unused Svelte file: /Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/lib/components/icons/IconConvertFrom.svelte
Unused Svelte file: …
```
=> fix(build): search for unused svelte files in TS modules too

.github/workflows/update-snapshots.yml
The CI workflow that updates the snapshots is giving the error of not being on a branch.
See https://github.com/dfinity/oisy-wallet/actions/runs/11929888449/job/33249595587?pr=3673
This is caused by the trigger on Pull request introduced in PR #3614 
We fix it here differentiating the checkouts.
=> ci(e2e): solve checkout error for pull request

src/frontend/src/lib/components/convert/ConvertReview.svelte, src/frontend/src/lib/components/receive/ReceiveAddressQRCode.svelte, src/frontend/src/lib/components/ui/ContentWithToolbar.svelte
Adding `flex` to `ContentWithToolbar` introduced in some particular cases some unwanted spacings between elements. Solution - make the component accept `styleClass` to allow consumers adjust the styling as needed. Having both `styleClass` and `minHeight` doesn't make too much sense, therefore I removed the latter.
=> fix(frontend): modal styling issue

src/frontend/src/lib/utils/format.utils.ts
To properly decide whether "today" or "yesterday" label should be displayed, `daysDifference` needs to be calculated with vars in dates-only format.
=> feat(frontend): adjust day difference calculation

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
A small clean up of unused strings, given by script `check.i18n.sh` :
```bash
Unused keys: [
'core.text.more',
'auth.alt.sign_in',
'init.error.no_infura_ckerc20_provider',
'settings.text.sign_in',
'networks.show_testnets',
'tokens.import.error.missing_index_id',
'transaction.status.included',
'transaction.status.safe',
'transaction.status.finalised',
'about.text.title'
]
```
The following are being flagged because they are used dynamically
```
'transaction.status.included',
'transaction.status.safe',
'transaction.status.finalised',
```
`<span in:fade>{$i18n.transaction.status[status]}</span>`
=> chore(frontend): clean up unused i18n strings

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/lib/utils/transaction.utils.ts, src/frontend/src/tests/lib/utils/transaction.utils.spec.ts
Instead of showing `Undefined` for missing timestamps, we show `No Date Available`.
=> style(frontend): modify string for missing date of date group

scripts/deploy.backend.sh, src/backend/backend.did, src/backend/tests/it/utils/pocketic.rs, src/declarations/backend/backend.did, src/declarations/backend/backend.did.d.ts, src/declarations/backend/backend.factory.certified.did.js, src/declarations/backend/backend.factory.did.js, src/shared/src/impls.rs, src/shared/src/types.rs
We want to validate the new field "derivationOrigin" in the id alias credential.
Before we can do that, the backend needs to know the derivation origin.
This PR, adds the derivation origin to the configuration parameter of the backend.
* Add a new field `derivation_origin` in InitArg and Config struts.
* Add new field in `deploy.backend.sh` script.
* `.did` and related file changes after running `npm run generate`.
* Add a `derivation_origin` in the pocket ic init args of the backend canister.
=> feat(backend): Add derivation_origin to backend config

e2e/transactions-page.spec.ts
The test that we decided to skip for now seems to be flaky (fails in ~50% of times).
=> test(frontend): skip ETH transactions page test

src/frontend/src/lib/components/loaders/Loader.svelte
#3240 broke the spacing around the banner displayed in the login modal.
- Redo div around banner and absolute image
Note against better idea.
Issue:
Fix:
=> fix(frontend): login banner spacing

src/frontend/src/lib/components/tokens/Tokens.svelte
Not sure exactly why but the navigation between pages from assets to other pages become glitchy again.
- Use an animation to display the "Manage tokens" button only on enter
Before:
After:
=> fix(frontend): glitchy navigation between pages

e2e/utils/pages/activity.page.ts, e2e/utils/pages/homepage.page.ts, e2e/utils/pages/transactions.page.ts
Following @peterpeterparker 's suggestion (https://github.com/dfinity/oisy-wallet/pull/3666#pullrequestreview-2447431986) , we make `extendWaitForReady` an `abstract` function.
=> refactor(e2e): make extendWaitForReady function abstract

src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/tests/lib/components/convert/ConvertAmountSource.spec.ts
The convert max button format was using only 4 decimals which doesn't match with value format we display in `sendAmount` input.
=> feat(frontend): convert max button format

src/frontend/src/btc/components/fee/UtxosFeeContext.svelte
Make sure `amount` is `number` before using it.
=> feat(frontend): parse "amount" before using it in UtxosFeeContext

scripts/add.tokens.erc20.mjs, scripts/build.tokens.ckerc20.mjs, scripts/build.tokens.sns.mjs, scripts/check.tokens.erc20.ts, scripts/constants.mjs, scripts/utils.mjs
To have better control on them, we extract and centralize some variables that points to the tokens CkERC20 and SNS JSON files in a new file called `constants.mjs`
UNRELATED: there was a non-alias import in one of the scripts.
=> refactor(build): centralize variables for tokens JSON files

src/frontend/src/btc/utils/btc-send.utils.ts, src/frontend/src/tests/btc/utils/btc-send.utils.spec.ts
I noticed that for some numbers the `convertNumberToSatoshis` was throwing `cannot be converted to a BigInt because it is not an integer` error. This PR fixes it as well as adds some explanations to the code.
=> fix(frontend): issue with converting very low numbers to satoshis

src/frontend/src/icp/utils/map-icrc-data.ts, src/frontend/src/tests/icp/utils/map-icrc-data.spec.ts
IcrcData from the json is wrongly mapped with an exchangeCoinId hardcoded to internet-computer. This is wrong and causes the fallback logic of exchange balance to default to the ICP price.
remove hardcoded value
=> fix(frontend): fix hardcoded exchangecoinid

src/frontend/src/lib/components/networks/NetworksTestnetsToggle.svelte
Since ,with PR #3734, we want to persist the selected network during navigation, it makes sense to reset the network param when the network selector is disabled. That means, when the testnets are disabled.
- Delete NETWORK_PARAM when toggle is turned off.
- Replace state.
- Add TODO for future tests.
https://github.com/user-attachments/assets/5ad53784-3c69-4e49-9dba-f6bf3639cdcd
=> feat(frontend): reset network param when turning testnets off

src/frontend/src/btc/components/convert/BtcConvertForm.svelte, src/frontend/src/lib/components/fee/InsufficientFundsForFee.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/btc/components/convert/BtcConvertForm.spec.ts
The same UI component can be re-used in both convert and send flow. In this PR, I'm extracting the code as well as using the new component in BtcConvertForm.
=> feat(frontend): create and use InsufficientFundsForFee component

src/frontend/src/tests/btc/components/send/BtcSendReview.spec.ts
As agreed, before implementing updates to a component, covering it with unit tests first. In this case, it's about BtcSendReview component. In the next PRs, I will be adding an additional check for the "insufficient-fund-for-fee" error.
=> test(frontend): add tests for BtcSendReview components

src/frontend/src/tests/lib/services/load-user-profile.spec.ts, src/frontend/src/tests/lib/services/request-pouh-credential.services.spec.ts, src/frontend/src/tests/lib/utils/credentials.spec.ts, src/frontend/src/tests/mocks/user-profile.mock.ts
For reusability, we extract the user profile mock and we use it in the relevant tests.
=> refactor(frontend): extract mock user profile

src/frontend/src/tests/btc/workers/btc-wallet.worker.spec.ts
As I'm going to introduce "queryAndUpdate" approach in the btc-wallet worker in the next PR, we need to add some tests for it beforehand. The test structure is similar to what we have in the other wallet test file.
=> test(frontend): add tests for btc-wallet worker

src/frontend/src/icp/components/transactions/IcNoIndexPlaceholder.svelte, src/frontend/src/lib/components/dapps/DappsExplorerSignedOut.svelte, src/frontend/src/lib/components/receive/ReceiveAddresses.svelte, src/frontend/src/lib/components/send/SendTokensList.svelte, src/frontend/src/lib/components/settings/SettingsVersion.svelte, src/frontend/src/lib/components/tokens/NoTokensPlaceholder.svelte, src/frontend/src/lib/components/tokens/TokenLogo.svelte, src/frontend/src/lib/components/transactions/TransactionsPlaceholder.svelte, src/frontend/src/lib/components/ui/DropdownButton.svelte, src/frontend/src/lib/styles/global/colors.scss, src/frontend/src/lib/styles/global/text.scss
We need to introduce the real foreground color secondary. But before that we remove the custom class text-secondary that is really not necessary, and that is actually black.
=> refactor(frontend): replace text-secondary with black

src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/navigation/NavigationMenu.svelte, src/frontend/src/lib/utils/nav.utils.ts, src/frontend/src/tests/lib/utils/nav.utils.spec.ts
As suggested by @peterpeterparker  in https://github.com/dfinity/oisy-wallet/pull/3734#discussion_r1856973090 , we rename variable `isTransactionsRoute` in function `networkUrl`, to make it more generic.
=> refactor(frontend): change variable name of networkUrl input

src/frontend/src/lib/components/ui/ButtonCloseModal.svelte
Use the paddingSmall prop for ButtonCloseModal
- add paddingSmall
before:
after:
=> style(frontend): use paddingSmall for ButtonCloseModal

src/frontend/src/btc/components/core/BtcLoaderWallets.svelte, src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts, src/frontend/src/btc/schema/btc-post-message.schema.ts, src/frontend/src/btc/services/btc-listener.services.ts, src/frontend/src/btc/services/worker.btc-wallet.services.ts, src/frontend/src/icp/api/bitcoin.api.ts, src/frontend/src/lib/schema/post-message.schema.ts, src/frontend/src/tests/btc/workers/btc-wallet.worker.spec.ts
In this PR, the "query and update" strategy is implemented in the BTC wallet worker. Important notes:
* "Querying" balance only available for BTC mainnet
* At the moment, we don't have a way of certifying BTC transactions, therefore they are fetched only on `query`
P.S: the UI part of the feature can be found here - https://github.com/dfinity/oisy-wallet/pull/3806
=> feat(frontend): query and update BTC wallet

src/frontend/src/lib/components/send/SendTokensList.svelte
Uniform layout of modals, use btn close modal in sendTokensList
- replace btn with buttonCloseModal
before:
after:
=> style(frontend): use btn close modal in sendTokensList

package-lock.json, package.json
vitest cannot be bumped automatically by bot PR #3814 because it requires the vitest coverage library to be bumped as well.
- `npm rm vitest @vitest/coverage-v8 && npm i vitest @vitest/coverage-v8 -D`
=> build(frontend): bump vitest

src/frontend/src/lib/services/load-user-profile.services.ts, src/frontend/src/tests/lib/services/load-user-profile.spec.ts
We want to provide the choice of not reloading the user profile if not necessary.
- Add optional prop `reload` to `loadUserProfile`
- Default to `true`, since it is the current behavior
Included tests.
=> feat(frontend): optional reload prop in loadUserProfile

src/frontend/src/lib/components/about/AboutWhyOisyModal.svelte
Uniform display of Modals. Preparation for future MR where ContentWithToolbar will be styled as sticky footer.
Use ContentWithToolbar in AboutWhyOisyModal.
before:
https://github.com/user-attachments/assets/2383be01-13ae-4032-89c6-82f6517ec898
after:
https://github.com/user-attachments/assets/84a1e736-7f20-448a-ae89-e0c53ce85b89
=> style(frontend): add ContentWithToolbar to AboutWhyOisyModal.svelte

src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/lib/components/convert/ConvertAmountDestination.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/convert/ConvertAmountDestination.spec.ts
This PR updates the logic of how `receiveAmount` is calculated - it should be equal to `sendAmount` unless there are some fees that are gonna be payed by receiver (not the case for BTC -> ckBTC). Also, I updated a translation key related to that component.
=> feat(frontend): don't deduct fee from receiveAmount on convert

src/frontend/src/btc/components/convert/BtcConvertForm.svelte
We now fetch utxos even if no amount is provided by the user, so it's possible that the no-utxos warning message is shown before user actually types something. To avoid that, we add a small check. 
P.S.: pending-tx message will still be shown on `hasPendingTransactionsStore` availability.
=> feat(frontend): do not show Utxos warning if no amount provided

src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/convert/ConvertInputAmount.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/convert/ConvertAmountSource.spec.ts
In this PR, I'm updating the max button behavior in the Conversion flow - it is now working similar to the ETH send flow, where it considers the fee and also updates input value automatically if fees got changed after the max button was clicked. Also, according the UX team suggestion, we need to display "Calculating..." label until all fees are known. The tests are updated accordingly.
Total fee is not available:
Total fee is available:
=> feat(frontend): convert max button update

src/frontend/src/lib/derived/user-profile.derived.ts, src/frontend/src/tests/lib/derived/user-profile.derived.spec.ts, src/frontend/src/tests/mocks/user-profile.mock.ts
We create a derived store for the user settings, so that we can handle eventual `nullable` values.
=> feat(frontend): derived store for user settings

src/frontend/src/lib/styles/global/links.scss
There was a warning given by a Sass deprecation:
Fixed using `sass-migrator` as suggested by the [documentation](https://sass-lang.com/blog/import-is-deprecated/).
=> chore(frontend): adapt to new SASS rules

src/frontend/src/lib/schema/network.schema.ts, src/frontend/src/tests/lib/schema/network.schema.spec.ts
As suggested in the past, we should refine the schema of network type to be more specific for the icons.
=> refactor(frontend): add SVG schema to network schema

src/frontend/src/btc/components/transactions/BtcTransaction.svelte, src/frontend/src/tests/btc/components/transactions/BtcTransaction.spec.ts
On the transactions page the BTC send transactions are displayed as if the user is receiving tokens instead of sending them. The amount of a `send` transaction should be displayed with a leading `-` (minus) and the text should be black.
- fixes calculation
**before:**
**after:**
=> style(frontend): calculates amount for btc transactions correctly

src/frontend/src/lib/schema/network.schema.ts, src/frontend/src/tests/lib/schema/network.schema.spec.ts
In PR #3875 , I introduced the IconSchema, considering only the environments where the local files were passed as string path. However, in production, staging, and in general in any non-local deployed environment, the element is the SVG file content.
That is why we fix the schema here.
=> fix(frontend): correct IconSchema

src/frontend/src/lib/components/auth/ButtonAuthenticateWithLicense.svelte
Centering the license agreement in the Sign page. No changes for the other screens.
=> style(frontend): center license in Sign screen

src/frontend/src/lib/components/carousel/Carousel.svelte, src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte, src/frontend/src/lib/components/icons/lucide/IconClose.svelte
We add a close button to the carousel slides to hide them.
This affects only current navigation. Persisting that will be applied in another PR, using the backend method `add_hidden_dapp_id` introduced with PR #3777  
- Add button close to component `DappsCarouselSlide`.
- Bubble event `icCloseCarouselSlide` that provides the dApp that is being closed.
- Create function in `DappsCarousel` to manage the event and remove the correspondent slide.
- Adjust `Carousel` function removeSlide to refresh all needed variables.
- Add transitions.
https://github.com/user-attachments/assets/873fa742-5307-48a2-b81a-2276e54afdc7
=> feat(frontend): add close button to carousel slides

src/frontend/src/lib/utils/carousel.utils.ts, src/frontend/src/tests/lib/utils/carousel.utils.spec.ts
It makes sense to return immediately if the `slides` array is empty in `extendCarouselSliderFrame`.
=> feat(frontend): do nothing if slides are empty in extendCarouselSliderFrame

.github/actions/oisy-backend/action.yml, .github/workflows/e2e-tests.yml, .github/workflows/update-snapshots.yml
Our E2E Tests are failing due to wasm not being built on macOS. This PR will fix this issue in a stable manner.
adjusted workflows to build the wasm only on ubuntu but download it as artifact on macOS.
ran on different branch with success
=> fix(e2e): fixing e2e wasm failure

src/frontend/src/btc/services/btc-listener.services.ts
Fix for incorrect `hideToast` param handling in `btc-listener.services`.
=> fix(frontend): btc wallet error hideToast option

src/frontend/src/btc/services/worker.btc-wallet.services.ts, src/frontend/src/tests/btc/services/btc-listener.services.spec.ts
Since BTC testnet is not working at the moment, we want to avoid showing toast for all the users that have "testnet" setting on. We will remove it after it is fixed on the canister side.
=> feat(frontend): avoid showing toast on errors with BTC testnet

Dockerfile
Fix a typo similar to the one spotted by @goodactive in a comment on the Dockerfile of  [Juno](https://github.com/junobuild/juno/pull/891).
- `dependecies` -> `dependencies`
=> docs(config): fix typo in Dockerfile comment

src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/derived/user-profile.derived.ts, src/frontend/src/tests/lib/components/dapps/DappsCarousel.spec.ts, src/frontend/src/tests/lib/derived/user-profile.derived.spec.ts
The carousel was not being loaded for old accounts, because `userSettings` was always `undefined`.
However, we should distinguish between not having loaded the user profile (from which `userSettings` derives), and having a missing field `settings` in the user profile (it happens for old accounts, since we introduced the field recently).
- Improve `userSettings` derived store to set `null` when the user profile exists but it is missing the `settings` field.
- Adapt tests.
- Adapt `DapsCarousel`.
Provided.
=> fix(frontend): load Carousel when missing settings in user profile

src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/derived/user-profile.derived.ts, src/frontend/src/tests/lib/derived/user-profile.derived.spec.ts
According to @peterpeterparker 's suggestion in https://github.com/dfinity/oisy-wallet/pull/3893#pullrequestreview-2486419830 , we find a better way to distinguish if the user settings are not available because the user profile is not loaded, or if they are missing (old accounts for example).
The base difference is simply if the user profile is not `nullish`: if it is not `nullish` and the settings are nullish, we are sure that the `settings` are missing.
- Create derived store `userProfileLoaded`.
- Use new store in `DappsCarousel`.
Test created and adjusted.
=> feat(frontend): derived store userProfileLoaded

src/frontend/src/lib/components/carousel/Carousel.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte, src/frontend/src/lib/constants/analytics.contants.ts
We would like to monitor the conversion rate of the carousel.
- Add tracking constants.
- Add tracking events to `Carousel` control buttons.
- Add tracking event to close button.
- Create function to open the modal and track the event.
=> feat(frontend): track carousel events

src/frontend/src/lib/utils/onramper.utils.ts, src/frontend/src/tests/lib/utils/onramper.utils.spec.ts
The function `mapOnramperWallets` was deprecated in the past, but never ultimately removed.
=> chore(frontend): remove unused function mapOnramperWallets

src/frontend/src/lib/components/dapps/DappModal.svelte, src/frontend/src/lib/components/ui/ExternalLink.svelte, src/frontend/src/lib/constants/analytics.contants.ts, src/frontend/src/lib/services/analytics.services.ts, src/frontend/src/lib/types/analytics.ts
We start tracking the click on the hyperlink of the dApp modal.
- Add tracking constants.
- Add `on:click` event in `ExternalLink` that uses a new prop `trackEventParams`.
- Add `trackEventParams` in `DappModal`.
=> feat(frontend): track dApp modal clicks

src/frontend/src/lib/components/hero/Actions.svelte
As a part of Swap feature, we need to make some adjustments to the Actions component - "Send" as well as future "Swap" buttons will always be visible and enabled on the tokens page. 
Message that is shown to a user with zero balance:
=> feat(frontend): always show Send button

src/frontend/src/eth/components/send/SendNetwork.svelte, src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte
It's probably a warning currently but, following becomes an error when migrating to Svelte v5 in #3929:
> `<span>` cannot be a child of `<option>`. `<option>` only allows these children: `<#text>`. The browser will 'repair' the HTML (by moving, removing, or inserting elements) which breaks Svelte's assumptions about the structure of your components.
- Remove `span` in `option`.
=> fix(frontend): span cannot be a child of option

src/frontend/src/lib/components/core/Listener.svelte, src/frontend/src/lib/components/core/NoListener.svelte
Migration to Svelte v5 (#3929) involves replacing the ComponentType. While updating the Listener, a minor TypeScript issue was identified. We use a `svelte:component` that maps a token property, which may or may not be present, and can sometimes be set or unset. This approach works because the component is assigned to a state variable, but it is not fully TypeScript-compliant. To address this, we can leverage the template to correctly mount the listener.
=> feat(frontend): listener templating

.gitignore
We started doing E2E Playwright tests for MacOS too, so we shouldn't ignore the `*-darwin` screenshots anymore.
=> chore(e2e): do not ignore mac screenshots

src/frontend/src/lib/styles/global/gix.scss
Removing SASS warning:
```bash
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
╷
148 │ ┌         @screen sm {
149 │ │             --dialog-padding-y: 1.5rem;
150 │ │             --padding-3x: 1rem;
151 │ │         }
│ └─── nested rule
... │
153 │           --color-grey: rgba(0, 0, 0, 0.05);
│           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
╵
src/frontend/src/lib/styles/global/gix.scss 153:3  load-css()
src/frontend/src/lib/styles/global.scss 16:1       root stylesheet
```
=> chore(frontend): solve SASS warning

scripts/deploy.sh
An attempt to fix `InsufficientAllowance` error while fetching BTC addresses in the E2E environment.
=> test(e2e): increase ledger cycles amount

src/frontend/src/eth/services/eth-balance.services.ts, src/frontend/src/eth/services/eth-listener.services.ts, src/frontend/src/eth/services/eth-transaction.services.ts, src/frontend/src/eth/services/send.services.ts, src/frontend/src/icp-eth/components/core/LoaderBalances.svelte
Renaming some Ethereum services for balance and transactions with the prefix `eth-`.
=> refactor(frontend): rename Ethereum services for balance

src/frontend/src/tests/lib/components/core/Listener.spec.ts, src/frontend/src/tests/lib/components/dapps/DappsCarousel.spec.ts
Svelte v5 #3929 wraps rendered elements with `` around it. If we use `.innerHTML` for comparison purpose we would need to amend those comments or trim those, which isn't nice. Therefore, instead of it, we can use `.textContent` for comparison purposes.
=> test(frontend): use .textContent instead of .innerHTML

src/frontend/src/lib/derived/testnets.derived.ts, src/frontend/src/tests/btc/components/tokens/BtcTokenMenu.spec.ts, src/frontend/src/tests/eth/derived/tokens.derived.spec.ts, src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts, src/frontend/src/tests/lib/components/hero/ContextMenu.spec.ts
Currently, we force `testnets` store to be always on locally. On one hand, it's kinda convenient to have it always enabled there, but on the other hand, it's a bit confusing that the related toggle has absolutely no effect locally. Since `LOCAL` is also `true` in the e2e environment, it also affects the tests and makes it impossible to validate the setting toggle functionality.
=> feat(frontend): align testnets behaviour between envs

.github/repo_policies/BOT_APPROVED_FILES
According to recent changes in the DFINITY repo policies, we require to add a list of files that can be changed by the a bot, for security reasons.
=> chore(ci): add list of Bot approved files

src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
There is a new utility `isEmptyString` in `@dfinity/utils` which can be use instead of `!notEmptyString`. So this PR replace the one occurence of such code we have in our code base.
- Replace function usage
=> feat(frontend): use utility isEmptyString

src/frontend/src/icp/utils/icrc.utils.ts
The `@dfinity/ledger-icrc` now implements a function `mapTokenMetadata` which is equals to our `mapOptionalToken` function (it was copied from there, see PR [#798](https://github.com/dfinity/ic-js/pull/798)), therefore we can use this utility.
Maybe I should have marked the type of the function as generic in ic-js since we basically duplicates the same type with zod but TypeScript is able to understand both types are equals it seems.
- Replace function
=> feat(frontend): use ledger-icrc mapTokenMetadata

src/frontend/src/tests/lib/utils/format.utils.spec.ts
Fix unit tests that rely on hardcoded year values.
=> test(frontend): fix tests that use hardcoded 2024 year

src/frontend/src/lib/components/convert/ConvertReview.svelte
I just noticed in prod that after the recent changes in the Modals-related code the appearance of outer-content slot (ConvertReview modal) is a bit off. 
Before:
After:
=> fix(frontend): outer-content slot appearance in ConvertReview modal

src/frontend/src/sol/providers/sol-rpc.providers.ts
Via sol-wallet.worker.ts there was a reference to svelte. This broke the build via sol-wallet.worker.ts as sveltekit is not available there (see vite config).
Remove assertion as it's unnecessary anyway, it's already secured via TS that there cannot be passed another network.
=> fix(frontend): remove reference to svelte in sol-rpc.providers.ts

scripts/did.update.types.mjs
Currently, the certified candid generation script does not handle correctly the case when `['query'] parameter is placed on the new line. It wasn't noticed before since such a case only present in the frontend candid for which we do not generate a certified file.
This code
```
get_txs: IDL.Func(
[IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat32), IDL.Opt(IDL.Nat16)],
[TxsResult],
['query']
),
```
is parsed into
```
'get_txs' : IDL.Func(
[
IDL.Opt(IDL.Nat64),
IDL.Opt(IDL.Nat64),
IDL.Opt(IDL.Nat32),
IDL.Opt(IDL.Nat16),
],
[TxsResult],
,
),
```
With this fix, that code will be correctly compiled into:
```
get_txs: IDL.Func(
[IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat32), IDL.Opt(IDL.Nat16)],
[TxsResult]
),
```
=> fix(scripts): issue with generating certified candid

dfx.json, scripts/build.kong_backend.sh, scripts/deploy.kong_backend.sh, scripts/deploy.sh, scripts/did.delete.types.mjs, scripts/generate.sh, src/declarations/kong_backend/index.d.ts, src/declarations/kong_backend/kong_backend.did, src/declarations/kong_backend/kong_backend.did.d.ts, src/declarations/kong_backend/kong_backend.factory.certified.did.js, src/declarations/kong_backend/kong_backend.factory.did.js
This PR includes all the necessary steps for the integration of the kong_backend canister. Note: it's implemented the same way it's done for signer. 
1. Script for building kong_backend by using the respective WASM and candid files available in the KongSwap repo.
2. Script for deploying kong_backend locally.
3. Script for generating, updating and deleting declaration files (src/declarations/kong_backend/*).
4. Dfx config update with the kong_swap canister.
=> feat(backend): integrate kong_backend

scripts/build.csp.mjs
Since we are going to use Coingecko API outside of worker (to fetch exchange rates for disabled tokens when opening the Swap modal), we need to whitelist it.
=> chore(frontend): add Coingecko API URL to CSP header

src/frontend/src/lib/api/kong_backend.api.ts, src/frontend/src/lib/canisters/kong_backend.canister.ts, src/frontend/src/lib/canisters/kong_backend.errors.ts, src/frontend/src/lib/constants/app.constants.ts, src/frontend/src/lib/types/api.ts, src/frontend/src/tests/lib/canisters/kong_backend.canister.spec.ts
In this PR, we are exposing to frontend required for the Swap functionality kong_backend services: `swap_amounts` and `swap_async`. The PR includes:
1. `kong_backend` canister class and related tests.
2. `KONG_BACKEND_CANISTER_ID` app constant.
3. `kong_backend` API methods.
=> feat(frontend): expose kong_backend API to FE

src/frontend/src/lib/services/reward-code.services.ts
Alessandro noticed that we can actually not use `ResultSuccess<VipReward>` because that would be a misuage of `ResultSuccess`. Something I mislead the type and thought about ` {result: T, err?: Err} ` or `{result: T, err?: Err}` but, we do not have those patterns. So, for pragamatical reason, we decided to remove the TODO.
As a nipick, since I removed the TODO, I added an explicit `return undefined` for the function.
=> feat(frontend): remove todo and explicit undefined return

src/frontend/src/icp-eth/components/info/InfoEthereum.svelte, src/frontend/src/lib/components/info/InfoBox.svelte
Replaced leagacy stylings and colors for the "Convert to ckXXX" token helper info boxes 
These boxes used old styles which are differrent from what we have now. 
1. Removed border 
2. Smaller close button (same that we use for info boxes on Activity page)
3. Changed description text to match new colors 
**Before**
**After**
=> style(frontend): Updated styles for large info boxes

scripts/build.csp.mjs
Fixes [https://github.com/dfinity/oisy-wallet/security/code-scanning/1](https://github.com/dfinity/oisy-wallet/security/code-scanning/1)
To fix the problem, we need to modify the regular expression to be case-insensitive. This can be achieved by adding the `i` flag to the regular expression. This change ensures that the regular expression will match `<script>`, `<SCRIPT>`, `<Script>`, and other case variations.
The best way to fix the problem without changing existing functionality is to update the regular expression on line 97 to include the `i` flag. This change will ensure that the regular expression matches script tags regardless of their case.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> fix(build): Fix code scanning alert no. 1: Bad HTML filtering regexp

src/frontend/src/btc/services/worker.btc-wallet.services.ts, src/frontend/src/btc/workers/btc-wallet.worker.ts, src/frontend/src/icp/services/worker.btc-statuses.services.ts, src/frontend/src/icp/services/worker.ck-minter-info.services.ts, src/frontend/src/icp/services/worker.ckbtc-update-balance.services.ts, src/frontend/src/icp/services/worker.icp-wallet.services.ts, src/frontend/src/icp/services/worker.icrc-wallet.services.ts, src/frontend/src/icp/workers/btc-statuses.worker.ts, src/frontend/src/icp/workers/ckbtc-minter-info.worker.ts, src/frontend/src/icp/workers/ckbtc-update-balance.worker.ts, src/frontend/src/icp/workers/cketh-minter-info.worker.ts, src/frontend/src/icp/workers/icp-wallet.worker.ts, src/frontend/src/icp/workers/icrc-wallet.worker.ts, src/frontend/src/lib/services/worker.auth.services.ts, src/frontend/src/lib/services/worker.exchange.services.ts, src/frontend/src/lib/workers/auth.worker.ts, src/frontend/src/lib/workers/exchange.worker.ts, src/frontend/src/lib/workers/workers.ts, src/frontend/src/sol/services/worker.sol-wallet.services.ts, src/frontend/src/sol/workers/sol-wallet.worker.ts
Copied from @peterpeterparker 's PR https://github.com/junobuild/juno/pull/1035 . The motivation below is the same as the Juno's PR, written by @peterpeterparker .
I don't know why I didn't realize this earlier, but each worker in our setup is bundled by vite and rollup into a standalone chunk without reusing chunks across workers. As a result, we are shipping quite a bit of redundant code since almost every worker includes both Buffer, agent-js and other inherited stuffs.
I couldn't find any non-hacky bundling option to improve this. However, I did come up with a potential solution: using a single worker entry point.
Since we are already splitting each worker into different modules, we can easily integrate a single worker entry point that dispatches messages to the appropriate modules. …
=> feat(frontend): use a single web worker

src/frontend/src/lib/components/convert/ConvertToken.svelte, src/frontend/src/lib/components/networks/NetworkLogo.svelte, src/frontend/src/lib/components/ui/Logo.svelte, src/frontend/src/lib/constants/components.constants.ts, src/frontend/src/lib/types/components.ts
In this PR, I'm introducing a new Logo size, which is an intermediate value between previous `sm` (36px) and `xs` (22px). 
Old values:
```
const logoSizes = {
xs: '22px',
sm: '36px',
md: '42px',
lg: '52px',
xl: '64px'
};
```
New values:
```
const logoSizes = {
xxs: '22px',
xs: '30px',
sm: '36px',
md: '42px',
lg: '52px',
xl: '64px'
};
```
Also, moved the const to a separate file since the sizes are gonna be reused in the Swap components.
=> feat(frontend): introduce new Logo size

.github/repo_policies/BOT_APPROVED_FILES
The CI that updates the SNS tokens requires to act on the icons folder too.
=> fix(ci): add SNS icons folder to BOT approved files

src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/sol/components/send/SolSendAmount.svelte, src/frontend/src/tests/lib/utils/token.utils.spec.ts
Similar to the other networks, we enable the Max button using the `calculateMax` function.
=> feat(frontend): add Max button for Solana

src/frontend/src/lib/canisters/kong_backend.canister.ts, src/frontend/src/lib/types/api.ts, src/frontend/src/tests/lib/canisters/kong_backend.canister.spec.ts
There was an incorrectly named kong_backend API param - it should have been `receiveAddress` instead of `destinationAddress`.
=> fix(frontend): rename kong_backend API param

src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/ui/InputSearch.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Since Tokens list view is now gonna be available within the Swap feature, the idea is to re-use as match things from ManageTokens component as possible. One of such things - `InputSearch`.
=> feat(frontend): extract InputSearch component

src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/utils/tokens.utils.ts
The idea is to re-use the filterTokens functionality between ManageTokens and SwapTokensList.
=> refactor(frontend): extract filterTokens util

src/frontend/src/eth/components/wallet-connect/WalletConnectSession.svelte, src/frontend/src/eth/constants/wallet-connect.constants.ts, src/frontend/src/eth/providers/wallet-connect.providers.ts
It seems coherent to rename `SESSION_REQUEST_SEND_TRANSACTION` to `SESSION_REQUEST_ETH_SEND_TRANSACTION`, since we will integrate Solana too.
=> refactor(frontend): rename SESSION_REQUEST_ETH_SEND_TRANSACTION

src/frontend/src/lib/derived/all-tokens.derived.ts
This PR includes:
1. Expose `allIcrcTokens` store to be used in SwapTokensList.
2. Create a new `allDisabledIcrcTokens` store in order to have all disabled icrc tokens for which we need to fetch balances and USD rates.
=> feat(frontend): allDisabledIcrcTokens derived

src/frontend/src/icp/services/ic-send.services.ts, src/frontend/src/lib/types/utils.ts
We need to expose sendIcp and sendIcrc methods in order to initiate transactions and get their block indexes before calling the swap API method of kong_backend.
=> feat(frontend): expose sendIcp and sendIcrc methods

src/frontend/src/lib/components/swap/SwapInputCurrency.svelte, src/frontend/src/lib/components/ui/InputCurrency.svelte
SwapInputCurrency - a small wrapper around existing InputCurrency, adds styling according to the design specs.
=> feat(frontend): SwapInputCurrency component

src/frontend/src/env/tokens/tokens-spl/tokens.usdt.env.ts
Mistypo in Solana USDT symbol: corrected to USDT.
=> fix(frontend): correct symbol for Solana USDT

src/frontend/src/env/tokens/tokens-spl/tokens.eurc.env.ts, src/frontend/src/env/tokens/tokens-spl/tokens.usdc.env.ts, src/frontend/src/env/tokens/tokens-spl/tokens.usdt.env.ts, src/frontend/src/sol/types/spl.ts
Similar to CK Tokens, we add the `twinToken` property to SPL tokens, to group them together.
=> feat(frontend): add Twin Tokens to Solana SPL

src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSignModal.svelte, src/frontend/src/eth/services/wallet-connect.services.ts, src/frontend/src/lib/services/wallet-connect.services.ts
The `reject` function and its sub-function `execute` will be used for more networks than Ethereum, so we move them to `lib`.
=> refactor(frontend): move WalletConnect reject function to lib

src/frontend/src/lib/utils/token-group.utils.ts, src/frontend/src/tests/lib/utils/token-group.utils.spec.ts
We built the util `groupTokens` in the past, to group more than 2 tokens that are twins, and we finally use it for the main function `groupTokensByTwin`.
=> refactor(frontend): use new util groupTokens inside groupTokensByTwin

src/frontend/src/icp/services/worker.ck-minter-info.services.ts, src/frontend/src/icp/workers/ckbtc-minter-info.worker.ts, src/frontend/src/icp/workers/cketh-minter-info.worker.ts, src/frontend/src/lib/schema/post-message.schema.ts, src/frontend/src/tests/lib/schema/post-message.schema.spec.ts
We merged the workers into a single entry in #4180, which is great for performance reasons but implies that messages should be unique. It turns out this is not the case when loading the minter info—for example, the same messages were used for ckBTC and ckETH. As a result, when a user navigates to a ck token, the page attempts to load information for both ckETH and ckBTC. Given that their APIs are different, the responses cannot be decoded correctly for one or the other.
There might be better solutions; this is just a quick fix.
- Duplicated the messages to ensure uniqueness.
- Added a `postMessage` key to interact with the worker, as the UI-side code is shared.
- Moved the code to load the worker, making it more explicit that there is a single entry.
No tests or debugging were performed.
=> fix(frontend): ckBTC minter info loaded on ckETH (and the contrary)

src/frontend/src/lib/components/core/Menu.svelte
In https://github.com/dfinity/oisy-wallet/pull/4280 I forgot to remove the existing icon of `ExternalLink` component.
=> fix(frontend): forgot to remove default icon of Support

src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/components/swap/SwapInputCurrency.svelte, src/frontend/src/lib/components/swap/SwapSelectToken.svelte
One of the feature feedbacks was that we need to disable Swap button if a new quote is loading (e.g. when user typed a new swapAmount). This PR implements this suggestion. Also, I added a small pulse effect to the receive input to highlight that there is an ongoing loading.
=> feat(frontend): disable Swap button if new quote is loading

src/frontend/src/lib/components/tokens/TokenLogo.svelte
The props in TokenLogo were extracted from `data` in non-reactive way. This PR fixes it.
=> fix(frontend): TokenLogo props reactivity

src/frontend/src/sol/services/sol-send.services.ts, src/frontend/src/sol/types/sol-transaction.ts, src/frontend/src/tests/sol/services/sol-send.services.spec.ts
To make the code more manageable, we create two functions: one that signs a Solana transactions and one that sends a Solana signed transaction.
=> refactor(frontend): extract functions to sign and send Solana transactions

src/frontend/src/lib/constants/routes.constants.ts, src/frontend/src/lib/utils/nav.utils.ts, src/frontend/src/tests/lib/utils/nav.utils.spec.ts
The route that opens when an user is redirected by WalletConnect should be the same of the main page (the Tokens List). However there are some checks that are managed by the util `isRouteTokens`, for example showing or not the `Hero`.
To make it the same for the two routes, we include the check for Wallet Connect route inside `isRouteTokens`.
=> fix(frontend): show Tokens page when in WalletConnect link page

dfx.json
The staging kong_backend canister is not very stable, has very limited amount of pools and some broken endpoints (e.g. `tokens`). Therefore, it makes sense for us to use the prod canister in all testing and staging envs (same as we do with II). Beta and prod already use the correct one.
=> feat(frontend): use prod kong_backend in all envs

src/frontend/src/icp/services/icrc.services.ts, src/frontend/src/lib/components/swap/Swap.svelte, src/frontend/src/tests/icp/services/icrc.services.spec.ts
This PR refactors the Swap component by moving icrc-related services into the dedicated to them file. Also, some unit tests have been added.
=> refactor(frontend): move icrc services from Swap component

src/frontend/src/lib/constants/exchange.constants.ts
To cope with the limits of our Coingecko subscription, and with the expansion of the user base, it was requested that we increase the exchange worker interval to refresh the exchange rates.
=> feat(frontend): increase exchange refresh to 2 minutes

src/frontend/src/eth/constants/steps.constants.ts, src/frontend/src/eth/services/wallet-connect.services.ts, src/frontend/src/lib/enums/progress-steps.ts
For consistency, we add the `APPROVE_WALLET_CONNECT` to the steps of signing a WalletConnect transaction.
=> refactor(frontend): create approve step for WalletConnect

src/frontend/src/lib/components/swap/Swap.svelte, src/frontend/src/lib/components/swap/SwapTokensList.svelte, src/frontend/src/lib/derived/all-tokens.derived.ts, src/frontend/src/tests/lib/derived/all-tokens.derived.spec.ts
In this PR, instead of using the store with all disabled ICRC tokens, we filter all uncompatible with kong_backend entries to avoid fetching unnecessary balances and exchanges, as well as not to render them in the tokens list. Data for kong-swap-tokens store will be fetched only on the first open of the Swap modal.
=> feat(frontend): use kong-swap-tokens store

.github/repo_policies/BOT_APPROVED_FILES
The CIs for the BOT Repo Policies are failing at https://github.com/dfinity/oisy-wallet/pull/4361 most probably because we are missing a wildcard in the SNS icon folder path.
=> fix(ci): correct BOT policies wildcard

.github/workflows/binding-checks.yml, .github/workflows/formatting-checks.yml, Dockerfile, dev-tools.json, docker/bootstrap
Tools are currently installed inconsistently, making it easy for tool sets to get out of sync.
- Add more tool sets to `dev-tools.json`
- Use the setup command to install these tools, consistently throughout the codebase. (With a few exceptions, that will be dealt with in another PR as those changes are a bit more complicated.)
- See CI
- Additionally, as some of these changes affect the backend Docker build, I have run a docker build locally.
=> refactor(devops): Install tools consistently

src/frontend/src/lib/derived/page-token.derived.ts, src/frontend/src/sol/derived/spl.derived.ts, src/frontend/src/tests/lib/derived/page-token.derived.spec.ts
Since we now have the same structure of default tokens and user tokens for SPL tokens, as we have in ERC20, we adapt the derived stores to avoid duplicates, and to have all of them, in preparation for the backend to be able to save them too.
It is basically a copy of the module `erc20.derived` (removing the unused ones).
=> feat(frontend): adapt SPL derived stores to user tokens

src/frontend/src/lib/components/manage/ManageTokensModal.svelte
We can now use the `saveSplUserTokens` service in `ManageTokensModal`.
=> feat(frontend): use saveSplUserTokens in ManageTokensModal

.github/workflows/bump-version.yml
We have workflows for tagging.  We would like to test that without having to affect production release numbers.
- Support pre-release version bumps.  So we get e.g. 1.2.3-4 .  See: https://docs.npmjs.com/cli/v8/commands/npm-version
=> feat(devops): Support prerelease version bumps for testing

.github/workflows/deploy-to-environment.yml, .github/workflows/release-notes.yml
Some workflows are meant to be triggered when a tag is pushed.
But GitHub has a policy of not letting workflows trigger workflows, except in a few very specific ways.
So we have a few options:
- Put code in actions
- Use the (limited)  explicit "trigger this workflow when that one has finished" functionality.
The latter a has strong limitations, but in this case the triggered events are simple and few, so as long as we don't add fancy chains this is probably the simpler option.
- Trigger workflows when we create a tag in CI.
Hard to test workflows triggering workflows when this is not in main.  But once merged, we can trigger some patch updates.  Note: Factoring code into actions is more testable, even in brances.
- Note: The tagging workflow has a very long name, so I have tried using …
=> feat(ci): Explicitly trigger tagging workflows

.github/workflows/deploy-to-environment.yml, .github/workflows/release-notes.yml, .github/workflows/tag-release.yml
Triggering releases on tag did not work.  Presumably that is because the workflow filename name was used instead of the human readable name.
- Make the name more accurate - the triggering workflow tags but does not create a release.
- In the triggered workflows, use the name not the filename.
Can only be tested properly in main.
=> fix(ci): Use workflow name rather than filename

src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
For mobile version, the label "Available balance" in the `Hero` was not centered. Now it is.
=> style(frontend): Center available balance label

src/frontend/src/lib/utils/tokens.utils.ts, src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
We would like to search the tokens not only by name, but by network too, so that all the tokens for example of Solana will appear if we write "solana".
=> feat(frontend): search tokens by network too

src/frontend/src/env/networks/networks.sol.env.ts
The websocket URL for Solana mainet was wrong: it was pointing at devnet. It is now fixed.
=> fix(frontend): wrong WebSocket address for Solana Mainnet

src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/constants/analytics.contants.ts
Add missing tracking for the swap feature.
=> feat(frontend): add tracking for kong swap

src/frontend/src/lib/enums/progress-steps.ts, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte, src/frontend/src/sol/constants/steps.constants.ts, src/frontend/src/sol/services/sol-send.services.ts, src/frontend/src/tests/sol/services/sol-send.services.spec.ts
To provide a better feedback to the user, we add a step to the Solana send flow: `SIGN`.
=> refactor(frontend): add Sign step to Solana transaction flow

src/frontend/src/icp-eth/types/add-token.ts, src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte, src/frontend/src/lib/components/manage/ManageTokensModal.svelte
For more clarity, we specify that the prop `contractAddress` is for ERC20, when adding a new token. It will be useful since Solana uses a similar nomenclature.
=> refactor(frontend): rename prop regarding ERC20 in Manage Tokens modal

src/frontend/src/eth/services/fee.services.ts
A user complained that OISY fails to send one particular erc20 token - [ResearchCoin (RSC)](https://coinmarketcap.com/currencies/researchcoin/). Our internal tests confirmed it - [RSC transactions](https://etherscan.io/advanced-filter?tadd=0xD101dCC414F310268c37eEb4cD376CcFA507F571&qt=1&fadd=0x2Eb29A5553bBc0066bA3ce9Ad4e95C10ab040806) fail in 100% of cases because of the out of gas error. After comparing [a failed OISY tx](https://etherscan.io/tx/0xf9e308c90a93ed388a9cd1df484ee73b4b21ccfa38becf359a6c979a9052635a) and [some random successful RSC tx](https://etherscan.io/tx/0x1c40d707f63ae7b02f56e77cd75c673e545713a284b01921a8771c1e4196b408) on Etherscan (both were done almost at the same time), I can indeed see that OISY sets a low gas limit (82,434 gas, 100% of which is used), when all …
=> feat(frontend): increase estimated max gas fee for RSC token

src/frontend/src/sol/components/fee/SolFeeContext.svelte, src/frontend/src/sol/components/fee/SolFeeDisplay.svelte, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte, src/frontend/src/sol/stores/sol-fee.store.ts, src/frontend/src/tests/sol/components/send/SolSendForm.spec.ts
We will need to have the Solana fee through a few other components, especially to freeze it when sending the transaction.
So, we move the fee calculation (with the prioritization fee), in a separate component that defines the context. It is very similar to what it is done with Ethereum.
- Create fee store and fee context: this is basically a simplified version of the Ethereum one.
- Move `prioritizationFee` calculation to another component `SolFeeContext`.
- Modify the functions to update the context instead of local variables.
- Wrap the components in `SolSendTokenWizard`.
- Initialize the context in `SolSendTokenWizard`.
- Adapt `SolFeeDisplay` to call the context.
No changes to the replica:
=> refactor(frontend): create Solana Fee context

src/backend/tests/it/custom_token.rs
When tests assert that something `.is_ok()` the error message gives no information about what went wrong.
- Use `assert_eq` instead of `assert!(x.is_ok())`, as this displays the error.
This is part of a test.  The change has been useful locally.
=> chore(backend): Better test error messages

src/backend/src/assertions.rs, src/backend/src/lib.rs, src/shared/src/types.rs
It would be useful to have the max symbol length available in the shared crate.  Technically, the maximum symbol length is also part of the public interface, so the shared crate is a more appropriate location anyway.
- Move the definition of `MAX_SYMBOL_LENGTH` to the shared crate.
Existing CI should suffice.
=> refactor(backend): Move the maximum symbol length

src/frontend/src/btc/services/worker.btc-wallet.services.ts
Update BTC balance still sometimes throws "ingress_expiry" issue. Previously, there was a problem with busy subnets (https://forum.dfinity.org/t/subnets-with-heavy-compute-load-what-can-you-do-now-next-steps/35762/19), but it is supposed to be fixed some time ago. 
For the time being, we were asked to hide related error toasts (same as in the Solana wallet worker). I added a TODO comment to remove this change after a proper investigation is completed and the error is fixed. For the debugging purposes, we will still show toast in staging env.
=> feat(frontend): hide error toasts on BTC balance update

vite.config.ts, vite.utils.ts, vitest.config.ts
To resolve the following tests warning we want to use the CSS `modern-compiler` for testing purpose as well:
> Deprecation Warning [user-authored]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
>
> More info: https://sass-lang.com/d/legacy-js-api
- Extract vite CSS options to a constant utils
- Use constant for vitest config
=> chore(test): use scss modern-compiler for tests

src/frontend/src/sol/services/spl.services.ts
Awaiting for the backend methods to be completed, to show better the SPL tokens that the user added manually, we can now split the loaded user tokens between the ones that we have hard-coded and the ones that require to load the metadata. 
- Split loaded token addresses between existing tokens in the `SPL_TOKENS` list and addresses without matching token.
- Map the unmatched addresses using method `getSplMetadata`: this is very similar to how we map the ERC20 tokens.
https://github.com/user-attachments/assets/82e913d0-9733-4268-b83a-07d8e08856e7
=> feat(frontend): load Solana user tokens that were included manually

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/sol/services/spl.services.ts
It is more consistent to call the SPL contracts as SPL tokens.
=> chore(frontend): SPL contracts --> SPL tokens

src/frontend/src/eth/services/erc20.services.ts, src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/lib/stores/toasts.store.ts, src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
The idea is to make ETH txs and erc20 tokens error messages user-friendlier by removing the "err" part from the error toasts. The `err` object will be logged in the console instead.
=> feat(frontend): update ETH txs and erc20 tokens error messages

src/frontend/src/sol/rest/quicknode.rest.ts, src/frontend/src/sol/services/spl.services.ts
Some tokens provide an image URL to the icon in their metadata.
- Adapt type of response of Quicknode metadata.
- Adapt service that fetches metadata.
I manually added PENGU:
=> feat(frontend): try and fetch SPL icon in metadata

src/frontend/src/lib/components/swap/SwapInputCurrencyUsd.svelte, src/frontend/src/tests/lib/components/swap/SwapInputCurrencyUsd.test.ts
The USD input field in the swap formats values unexpectedly and breaks the usage.
Replace formatUSD with toFixed(2)
Unit tests added
Additionally
https://github.com/user-attachments/assets/4c32a2c8-f2af-461a-bc11-b857d644c1bf
=> fix(frontend): do not format usd

.github/workflows/deploy-to-environment.yml
The step "Deploy Frontend to Environment" deploys `$CANISTER` but it looks as if it may be possible for that not to be the frontend.  This is _probably_ not intentional, and if it is, it should be documented.
- Deploy `frontend` instead of `$CANISTER` in the "Deploy Frontend to Environment" step.
=> fix(devops): Deploy only frontend in frontend step

src/frontend/src/tests/btc/components/convert/BtcConvertTokenWizard.spec.ts
When we run the tests for BtcConvertTokenWizard there is a warning:
> ```bash
> stderr | src/frontend/src/tests/btc/components/convert/BtcConvertTokenWizard.spec.ts
> It looks like the agent is trying to make a request that should have been mocked at Error: 
>     at Object.transformRequest (/Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/tests/mocks/identity.mock.ts:11:3)
>     at HttpAgent.createReadStateRequest (/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1042:27)
>     at HttpAgent.readState (/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1048:21)
>     at /Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/canisterStatus/index.ts:152:12
> …
```
=> test(frontend): mock utxos fee in BtcConvertTokenWizard

src/frontend/src/lib/components/swap/SwapFees.svelte, src/frontend/src/lib/components/ui/ModalExpandableValues.svelte
The next step of aligning Convert and Swap flow is to extract ModalExpandableValues into a separate component. The convert form usage will be added in the following PR.
=> refactor(frontend): re-use ExpandableValues between swap and convert

src/frontend/src/btc/components/convert/BtcConvertFees.svelte, src/frontend/src/btc/components/convert/BtcConvertForm.svelte, src/frontend/src/btc/components/convert/BtcConvertReview.svelte
In this PR, I'm updating the BtcConvertFees component to be aligned with SwapFees.
=> feat(frontend): update BtcConvertFees component

src/frontend/src/icp/components/core/CkBTCUpdateBalanceListener.svelte, src/frontend/src/lib/components/loaders/Loaders.svelte
The idea is to separate ckBTC update balance listener from other loaders to prevent very slow page loading on localhost/e2e.
=> fix(frontend): separate ckBTC update balance listener from other loaders

scripts/build.icp_ledger.args.sh
The recent changes in the backend deployment introduced an error with the PEM of the minter. 
when creating the minter identity we use plaintext so it does not ask for an encrypted PEM
=> feat(devops): fix minter PEM issue

.github/repo_policies/BOT_APPROVED_FILES
Same as with Svelte components, we need to allow bot to remove .spec.ts files.
=> feat(ci): include test files among bot policies

src/frontend/src/icp/services/ic-custom-tokens.services.ts, src/frontend/src/lib/types/custom-token.ts, src/frontend/src/lib/utils/custom-token.utils.ts, src/frontend/src/tests/lib/utils/custom-token.utils.spec.ts, src/frontend/src/tests/mocks/ic-tokens.mock.ts
Including the SPL parser for util `toCustomToken`.
- Create types and interfaces for the SPL custom tokens, similar to ICRC.
- Create sub-util to parse.
Added tests.
=> feat(frontend): add SPL parser to Custom Token parser

src/frontend/src/sol/services/spl.services.ts
Before starting to use the SPL Custom tokens backed, we first need to save the current browser-cached SPL tokens to the backend, to avoid any any disruptions to the user experience, as the user tokens are not yet stored in the backend.
However, it is acceptable to remove it after a certain amount of time, since we expect that most of the users that consider this part relevant will log in before that time.
So, as timeline, we define a period of 1 month, more or less, to remove this function and its usage. That is enough time for the users to log in and have their tokens saved in the backend.
- Create temporary util to load the SPL cached in the browser (this part of code was already there, just moved) and upload them to the backend (this is a copy of how we do for ICRC Custom tokens).
- …
=> feat(frontend): save cached SPL tokens to backend

src/frontend/src/lib/components/manage/ManageTokensModal.svelte, src/frontend/src/sol/services/spl-user-tokens.services.ts
Since we can now save SPL tokens in the backend, we use the common service `setManyCustomTokens` to set SPL Custom tokens.
=> feat(frontend): save SPL custom tokens to backend

src/frontend/src/btc/components/convert/BtcConvertForm.svelte, src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/tests/btc/components/convert/BtcConvertForm.spec.ts
In the new flow, the error state is integrated directly into input components. Therefore, we need to adjust the BtcConvertForm component.
=> feat(frontend): update BtcConvertForm component

src/frontend/src/tests/lib/utils/auth.utils.spec.ts
With https://github.com/dfinity/oisy-wallet/pull/4142 I forgot to remove the mocked `VITE_AUTH_DERIVATION_ORIGIN` from the tests.
=> chore(frontend): remove unused env var VITE_AUTH_DERIVATION_ORIGIN

.github/actions/release-notes/action.yml, .github/workflows/release-notes.yml, .github/workflows/tag-release.yml
Chaining workflows is flaky and hard to test.  It looks as if we have our first casualty in the form of `main` tags being created due to the `ref_name` in the downstream workflow being unexpected. Time to pay down the technical debt and do this properly....
- Move the release notes code into an action.
- Call the action directly from the release workflow.
- Call the action from "release notes on tag"
Expected behaviours & tests:
The action is called in two places.  We will cover each separately.
Here we use `ref_name` as the release tag, but check that the `ref_type` is tag.
To demonstrate, we will run the workflow explicitly on a branch:
```
gh workflow run --ref refs/heads/release-notes-action release-notes.yml
```
The workflow is skipped: …
=> refactor(devops): Move release notes code into an action

src/frontend/src/lib/components/tokens/TokenInput.svelte, src/frontend/src/lib/components/tokens/TokenInputAmountExchange.svelte, src/frontend/src/lib/components/tokens/TokenInputCurrency.svelte, src/frontend/src/lib/components/tokens/TokenInputCurrencyUsd.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Refactoring PR to rename some "swap" leftovers after moving related components from `/swap/*` to `/tokens/*`.
=> refactor(frontend): clean up "swap" vars in tokens components

src/frontend/src/sol/services/spl-user-tokens.services.ts, src/frontend/src/sol/services/spl.services.ts
Just to have a clean and smooth cache, we will be saving in the browser cache only SPL mainnet tokens, since the devnet and the testnet are not really relevant for the user experience, so they can be "lost" in the token list when the new version is released.
=> refactor(frontend): keep caching only SPL mainnet tokens

src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/tests/mocks/sol-signatures.mock.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
After PR https://github.com/dfinity/oisy-wallet/pull/4565 , we can create a service to fetch the transactions related to a specific signature and map them to `SolTransactionUi` type.
- Create service `fetchSolTransactionsForSignature` that first fetches the transaction details to a signature.
- Break down the details into instructions and parse them back to transaction list.
Included tests.
=> feat(frontend): service to fetch Solana transaction and map them

src/frontend/src/sol/api/solana.api.ts, src/frontend/src/sol/schedulers/sol-wallet.scheduler.ts, src/frontend/src/sol/services/sol-signatures.services.ts, src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/tests/sol/api/solana.api.spec.ts, src/frontend/src/tests/sol/schedulers/sol-wallet.scheduler.spec.ts, src/frontend/src/tests/sol/services/sol-signatures.services.spec.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
It makes more sense that the method `getSolTransactions` is a service instead of being inside the API module.
=> refactor(frontend): move getSolTransactions to services

.github/workflows/e2e-tests.yml
There was an issue in the e2e test workflow, where the backend wasm was downloaded to the wrong location.
Fixed the location path for the wasm download.
=> fix(e2e): correct the download path of the backend wasm

src/frontend/src/icp-eth/utils/token.utils.ts, src/frontend/src/lib/components/hero/HeroContent.svelte, tailwind.config.ts
We want to display a special gradient for GLDT token Hero.
* new theme colors
* new `isGLDTToken` util
* set `via-bright-gold`,  `to-golden-sap` and `bg-gradient-to-r` for the HeroContent component if it's GLDT token page
=> feat(frontend): special gradient for GLDT token Hero

src/frontend/src/lib/derived/all-tokens.derived.ts
Just to have more manageability, we explicitly set the types of a few derived stores on ICRC tokens that pertains to Kong swap
=> chore(frontend): add types to derived stores of Kong swap ICRC tokens

src/frontend/src/lib/components/swap/SwapModal.svelte, src/frontend/src/lib/components/swap/SwapTokensList.svelte, src/frontend/src/lib/derived/all-tokens.derived.ts, src/frontend/src/lib/derived/swap.derived.ts, src/frontend/src/lib/stores/swap.store.ts, src/frontend/src/tests/lib/components/swap/SwapForm.test.ts, src/frontend/src/tests/lib/derived/swap.derived.spec.ts, src/frontend/src/tests/lib/stores/swap.store.spec.ts
In all the Swap components, the correct type for the destination tokens and the source token is `IcTokenToggleable`.
=> chore(frontend): specify type of tokens in swap context

scripts/build.tokens.sns.ts, src/frontend/src/env/schema/env-icrc-token.schema.ts, src/frontend/src/env/tokens/tokens.sns.json, src/frontend/src/env/types/env-icrc-token.ts, src/frontend/src/env/types/env-sns-token.ts
In script `build.tokens.sns` there are a few redundancies with the types: we can use some that already exists in folder $`env`, or a derived version of them.
- Create type `EnvIcrcTokenIcon` that is just the optional `icon` prop used in the script.
- Create type `EnvIcrcTokenMetadataWithIcon` as union of `EnvIcrcTokenMetadata` and `EnvIcrcTokenIcon`.
- Replace `SnsMetadata` with `EnvIcrcTokenMetadataWithIcon`, and `OptionalSnsMetadata` with a `Partial` version of it.
- Created type `EnvSnsTokenWithIcon` that add the `icon` prop to `metadata` in `EnvSnsToken`.
- Replace `SnsToken` with `EnvSnsTokenWithIcon`.
- Adjusted `SnsTokenWithOptionalMetadata` to use be `EnvSnsTokenWithIcon` but with optional `metadata`.
- Remove unused `EnvSnsTokens` type.
I injected a missing SNS token in this PR …
=> refactor(frontend): re-use existing Env ICRC types for SNS script

src/frontend/src/lib/components/core/Footer.svelte
On mobile – OISY footer is a bit cluttered, especially on secondary pages when they are empty. We'd like to hide social icons and beta badge on all pages on mobile except the "home screen" (footer is not that visible and located below the tokens) 
Hiding block with buttons in <Footer.svelte> for all screens where sidebar is not visible. 
Home screen: 
Token screen:
=> fix(frontend): Hide social media icons and beta badge on mobile on "secondary" pages

src/frontend/src/sol/services/sol-signatures.services.ts, src/frontend/src/tests/mocks/sol-signatures.mock.ts, src/frontend/src/tests/sol/services/sol-signatures.services.spec.ts
In Solana, some signatures may be associated ONLY to the main wallet address, some others to ONLY the ATA address, and ultimately some with both. To include them all in our view, we merge them removing the duplicates one.
=> feat(frontend): merge Solana wallet signatures with ATA signatures

src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/stores/swap.store.ts
In order to re-use the `isSourceTokenIcrc2` const, we need to move it up to the Swap context.
=> refactor(frontend): move isSourceTokenIcrc2 to context

package.json
To keep it more organized and help us out, we split the scripts to update `@dfinity` packages (and their `next` versions).
NOTE: we can now split the `agent` from `ic-js` packages.
- Script for `ic-js`
- Script for `agent`
- Script for `oisy-wallet-signer`
Tested manually since we will provide the PRs for each bump separately.
=> build(frontend): separate scripts for Dfinity-packages updates

package-lock.json, package.json
Using the scripts provided in https://github.com/dfinity/oisy-wallet/pull/4653 , we bump `oisy-wallet-signer` to the `next` version. This will allow us to avoid conflicts with `ic-js` packages.
=> chore(frontend): bump oisy-wallet-signer to next

src/frontend/src/eth/components/send/ConvertToCkERC20.svelte, src/frontend/src/eth/components/send/ConvertToCkETH.svelte, src/frontend/src/icp-eth/components/convert/ConvertETH.svelte, src/frontend/src/icp/components/convert/ConvertToEthereum.svelte
The idea is to move ConvertETH component to `.../convert/` folder since we now distinguish between send and convert flows, and therefore this component belongs to the convert folder.
=> refactor(frontend): move ConvertETH component to convert folder

src/frontend/src/lib/components/tokens/TokenInputCurrencyToken.svelte, src/frontend/src/lib/components/tokens/TokenInputCurrencyUsd.svelte
While working on the conversion flows, I noticed that `nnsInput` event bubbling was not properly working after the latest changes in TokenInput components.
=> fix(frontend): event bubbling in TokenInput

src/frontend/src/eth/components/fee/FeeContext.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
To re-use FeeContext in the conversion flow, we need to pass all required params as props instead of using the send context.
=> refactor(frontend): use FeeContext outside of the send flow

src/frontend/src/icp/api/icrc-ledger.api.ts, src/frontend/src/tests/icp/api/icrc-ledger.api.spec.ts
To always use the latest icrc token fee, we are going to fetch this info from the ledgers in the Swap flow.
=> feat(frontend): ledger transactionFee

src/frontend/src/lib/components/swap/Swap.svelte, src/frontend/src/lib/components/swap/SwapFee.svelte, src/frontend/src/lib/components/swap/SwapFees.svelte, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/components/swap/SwapMaxBalanceButton.svelte, src/frontend/src/lib/components/swap/SwapReview.svelte, src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/services/swap.services.ts, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/swap/SwapForm.test.ts
In this PR, we start using the IcTokenFee store in the Swap flow, as well as update SwapFees component UI with the skeleton loading indicator and additional entry for the approval fee.
=> feat(frontend): Swap fee logic update

src/frontend/src/eth/components/wallet-connect/WalletConnectSignReview.svelte, src/frontend/src/lib/components/carousel/Indicator.svelte, src/frontend/src/lib/components/ui/Badge.svelte, src/frontend/src/lib/components/wallet-connect/WalletConnectReview.svelte
It makes more sense that we use `bg-disabled` instead of `bg-dust` in all its usages. Apart from `bg-dust/30` that is `bg-secondary`.
=> refactor(frontend): bg-dust --> bg-disabled

src/frontend/src/lib/constants/themes.constants.ts, src/frontend/src/lib/enums/themes.ts
In https://github.com/dfinity/oisy-wallet/pull/4669 I forgot to remove the unused variables once imported inside the component.
=> chore(frontend): remove unused theme constants

src/frontend/src/btc/components/core/BtcWalletAddress.svelte, src/frontend/src/eth/components/core/EthWalletAddress.svelte, src/frontend/src/icp/components/core/IcWalletAddress.svelte, src/frontend/src/sol/components/core/SolWalletAddress.svelte
We want to put a bit more space in the address shown for the single network in the menu.
=> style(frontend): add padding to single addresses in menu

src/frontend/src/eth/components/convert/EthConvertForm.svelte, src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/convert/ConvertForm.svelte
In case of ETH -> ckETH conversion, we need to operate with total (max) and min gas fee: the total fee needs to be used for calculating max transaction amount and the min fee - for validating user input. For the reference, this is how it currently works in the old conversion flow (https://github.com/dfinity/oisy-wallet/blob/main/src/frontend/src/eth/components/send/EthSendAmount.svelte#L52).
=> feat(frontend): adjust Convert components for ETH fees case

src/frontend/src/lib/components/signer/SignerPermissions.svelte, src/frontend/src/lib/components/tokens/TokenInput.svelte, src/frontend/src/lib/components/ui/Logo.svelte, src/frontend/src/lib/components/ui/RoundedIcon.svelte, src/frontend/src/lib/components/ui/WarningBanner.svelte, src/frontend/src/lib/styles/tailwind/theme-variables.ts, src/frontend/src/routes/(sign)/sign/+page.svelte
As part of the new theme refactoring https://github.com/dfinity/oisy-wallet/pull/4686 , we rename a few bordr-* and ring-* (because ring classes reference border colors) colors that were hardcoded colors and map them to theme variables.
=> refactor(frontend): rename tailwind border color classes

src/frontend/src/lib/canisters/kong_backend.canister.ts
After the recent changes in kong_backend code, the update calls to their `token` and `swap_amount` endpoints are protected with a guard. The solution is to query them instead.
=> feat(frontend): query calls to kong_backend token and swap_amount

src/frontend/src/lib/components/airdrops/AirdropCard.svelte, src/frontend/src/lib/schedulers/user-snapshot.scheduler.ts, src/frontend/src/lib/workers/workers.ts
We left a `text-misty-rose` class to be replaced by `text-tertiary`.
=> chore(frontend): remove leftover misty-rose class

package.json
We already use `elliptic` version `v6.1.1` (see [package-lock.json](https://github.com/dfinity/oisy-wallet/blob/2879a6d2599a34c046ac08c84d4d9f2f3258a661/package-lock.json#L6712)) since November 2024, therefore we are safe. However, given that three days ago a critival CVE rated 9/10 was published ([GHSA-vjh7-7g9h-fjfh](https://github.com/indutny/elliptic/security/advisories/GHSA-vjh7-7g9h-fjfh)) I was thinking it's probably best if we also align the reference in `package.json` instead of a less strict reference than `^6.5.7`.
- Set `"elliptic": "^6.6.1"` in `package.json`
=> chore(frontend): explicitly overrides elliptic v6.6.1

package-lock.json, package.json
Version compatible with Agent-js v2.3.0 which was bumped in #4756.
- Bump oisy-wallet-signer next build at the top of https://github.com/dfinity/oisy-wallet-signer/releases/tag/v0.1.6. Next because we use ic-js next.
=> build(frontend): bump oisy-wallet-signer

src/frontend/src/lib/components/swap/SwapFees.svelte, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/components/swap/SwapReview.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
The next iteration of SwapFee changes - we remove the LP and gas fees from being displayed and assumed while calculating the total fee amount as they are both already included into a swap deal. In the next step, we will start showing them again but we'll update UI the way it's clear those fees are not to be paid once again.
=> feat(frontend): remove swap LP and gas fees from calculations

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
Since we are starting to support Solana Token-2022, we map the instructions too.We now map `transfer` that is basically the same as the "old" Token.
=> feat(frontend): map Solana Token-2022 transfer instruction

src/frontend/src/lib/schema/post-message.schema.ts, src/frontend/src/sol/schedulers/sol-wallet.scheduler.ts, src/frontend/src/sol/services/sol-signatures.services.ts, src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/tests/sol/services/sol-signatures.services.spec.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
We need to use the token's owner address to fetch Solana transactions, since now we have Token-2022 that use different Token Program address.
=> feat(frontend): adapt Solana transaciton loader to Token-2022

src/frontend/src/lib/components/swap/SwapMaxBalanceButton.svelte
Similar as in the other Swap fees-related places, we need to multiply `sourceTokenFee` by two if it's an icrc2 token to cover transfer and approval fees while calculation the max available balance.
=> feat(frontend): update Swap max button calculation

src/frontend/src/lib/components/swap/SwapForm.svelte
The last place where the double-fee on icrc2 token operations must be considered - SwapForm.
=> feat(frontend): update SwapForm input validation

scripts/add.tokens.erc20.mjs, src/frontend/src/eth/services/wallet-connect.services.ts, src/frontend/src/icp/components/fee/IcTokenFeeContext.svelte, src/frontend/src/icp/services/ic-add-custom-tokens.service.ts, src/frontend/src/lib/components/dapps/DappModal.svelte, src/frontend/src/lib/components/send/SendDataAmount.svelte, src/frontend/src/lib/components/swap/SwapAmountsContext.svelte, src/frontend/src/lib/components/swap/SwapProvider.svelte, src/frontend/src/lib/services/address.services.ts, src/frontend/src/lib/services/loader.services.ts
Few unused errors were not prefixed with `_`.
I also added two TODOs. Unrelated to the change but close to it and easy to resolve.
=> chore(frontend): fix no-unused-vars

scripts/test.frontend.reproducibility.sh
Some libraries might generate and reuse a cache saved under `node_modules`, which could result in different bundles, so in the reproducibility script it's better to always reinstall the lib before building.
=> chore(frontend): npm ci in reproducibility test

src/frontend/src/lib/components/swap/Swap.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
After recent incidents with kong_backend, we need to improve the swap modal opening behavior to avoid app being stuck if the dapp canister is not responsive.
The updated implementation of Swap component handles the following cases when user clicks the swap button:
1. If `loadKongSwapTokens` succeeds within 10s - show modal.
2. If `loadKongSwapTokens` does not succeed within 10s - show toast, do not show modal.
3. If `loadKongSwapTokens` throws - show toast, do not show modal.
=> feat(frontend): abort opening Swap modal if kong_backend is down

src/frontend/src/lib/styles/global.scss
After migrating to Tailwind 4, building OISY via Docker was no longer possible due to the issue on the screenshot below. Investigation showed that there was a problem with transforming files that contain tailwind classes. [The function that was throwing the error](https://github.com/tailwindlabs/tailwindcss/blob/main/crates/oxide/src/scanner/allowed_paths.rs#L111) implied that we somehow try to parse some unexpected by tailwind files. Also, there were [some complains](https://github.com/tailwindlabs/tailwindcss/issues/15987) on the exact same issue recently.
Apparently, the previous way of specifying content for parsing in Tailwind.config file doesn't work in the 4th version. Instead, we need to set [the base path](https://tailwindcss.com/docs/detecting-classes-in-source-files#setting-your …
=> fix(build): issue with processing files with Tailwind via Docker

package-lock.json, package.json
We want to embed the latest version of gix-cmp which contains a patch in dompurify.
- Bump [v5.1.0](https://github.com/dfinity/gix-components/releases/tag/v5.1.0)
=> build(frontend): bump gix-cmp v5.1.0

src/frontend/src/lib/styles/global/gix.scss
Since we styled toasts like alerts and alerts use alpha background colors, it can be very hard to see the text in some cases. After checking with Dan, we switch to using error/warning/success-secondary background color for toasts.
Changed colors for toast bg
Before:
After:
=> style(frontend): Fix transparent toasts

src/frontend/src/env/airdrop-campaigns.json
The shown end date of the first campaign was not correct.
before:
after:
=> feat(frontend): updates airdrop end date

src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/i18n/en.json
Pierre requested the message shown when an in-wallet fails due to exceeded slippage is more user frfiendly.
before:
after:
=> feat(frontend): changes swap slippage exceeded message

src/frontend/src/lib/components/ui/Share.svelte
The text of the share button should be displayed in a bolder style.
before:
after:
=> feat(frontend): fixes share button styling

src/frontend/src/lib/i18n/en.json
The text on the `reward received modal` still refers to `airdrops`, but it should say `rewards` instead.
**before:**
reward:
jackpot:
**after:**
reward:
jackpot:
=> feat(frontend): updates the rewards texts

src/frontend/src/lib/services/user-snapshot.services.ts
I noticed that for accounts with ckBTC txs the register snapshot function throws an error. Most likely, it was related to some leftovers from the previous implementations where we were asserting `to` and `from` addresses for icrc txs.
=> fix(frontend): remove asserts from toIcrcTransaction method

src/frontend/src/lib/components/tokens/TokenInput.svelte
The `TokenInput` field should also be used in the `SendForms`. Since the custom validation for the `SendAmount` components works with `errors` instead of `errorTypes`, the `TokenInput` should support this as well.
- adds support for errors
=> feat(frontend): updates TokenInput.svelte

src/frontend/src/lib/components/common/MaxBalanceButton.svelte, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
The `SwapMaxBalanceButton` component should be more generic so that it can also be used in the `SendForms`. Since the custom validation for the `SendAmount` components works with `errors` instead of `errorTypes`, the `MaxBalanceButton` should support this as well.
- renames SwapMaxBalanceButton to MaxBalanceButton
- makes component more generic
=> feat(frontend): updates SwapMaxBalanceButton.svelte

src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/utils/convert.utils.ts, src/frontend/src/tests/lib/utils/convert.utils.spec.ts
This is the first step of preparing EthConvertTokenWizard to handle ERC20 conversions - convert utils should be updated to tackle ERC20 case where the fee is always paid in ETH.
=> feat(frontend): adjust convert utils for ERC20 case

README.md
Removing the status `beta` from the README file for version 1.
=> chore(docs): remove beta status from README

src/frontend/src/eth/components/convert/EthConvertForm.svelte, src/frontend/src/eth/components/convert/EthConvertReview.svelte, src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte, src/frontend/src/eth/components/fee/EthFeeDisplay.svelte, src/frontend/src/eth/components/send/ConvertToCkERC20.svelte, src/frontend/src/eth/stores/fee.store.ts, src/frontend/src/tests/eth/components/convert/EthConvertForm.spec.ts
In this PR, the new conversion flow is enabled for the erc20 tokens. To do that, we needed to update EthConvertTokenForm to cover both ETH and ERC20 cases (similar as it was before with EthSendTokenForm).
=> feat(frontend): update ERC20 conversion flow

src/frontend/src/lib/components/core/Menu.svelte
On settings page, the main page links disappear which is a problem on mobile, since the main navigation to the left disappears. Theres then no way for a mobile user to navigate away from the settings page except clicking on the logo, which might not be clear for all users.
Removed conditions that hide the links if youre on the settings page.
Also changed the order of Airdrops menu item and explore dapps menu item so it is the same as on the desktop only navigation to the left.
=> fix(frontend): Navigation consistency

src/frontend/src/lib/services/user-snapshot.services.ts
The IC `approve` transactions are already filtered out by the `from` and `to` props. However, we explicitly filter them out for clarity.
=> feat(frontend): explicit filter out IC approve transactions in snapshot

src/frontend/src/sol/services/sol-signatures.services.ts, src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/sol/types/sol-api.ts
To avoid repetition of code we unify the params passed to get Solana transactions, that basically mean adding `tokenAddress` and `tokenOwnerAddress` (as options) to `GetSolTransactionsParams`.
UNRELATED: remove unused type `GetSplTransactionsParams`
=> refactor(frontend): unify Sol-get-transactions params

src/frontend/src/lib/styles/global/links.scss
It does not affect the color (since it is the same), but it seems more correct to use `--color-foreground-brand-primary` instead of the background one for the `blue-link` class of hyperlinks.
=> refactor(frontend): use foreground color for blue link class

scripts/build.backend.args.ic.did, scripts/build.backend.args.sh
This change allows a specific user (in this case @AntonioVentilii ) to access some data and endpoint of the OISY backend. Specifically all the endpoints with guard `caller_is_allowed`, and among them the `update` endpoints are:
- `bulk_up`
- `migrate_user_data_to`
- `migration_stop_timer`
- `set_guards`
- `step_migration`
- `top_up_cycles_ledger`
As recent requirement, we would like to quickly check the user statistics of OISY, such as endpoint `stats`. The quickest way is to allow some user. In this case, we will allow me.
We should have a different list of allowed users (or a different guard) for the less sensitive endpoints, that are useful to the OISY devs team.
=> feat(backend): add Antonio's principal to the allowed callers

src/frontend/src/lib/constants/exchange.constants.ts
To reduce the number of calls to CoinGecko, we increase the interval of requesting exchange rates to 5 minutes. It is not so necessary for the user to have a very frequent rate.
=> feat(frontend): increase exchange load interval to 5 minutes

src/frontend/src/eth/components/fee/FeeDisplay.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp-eth/components/fee/FeeAmountDisplay.svelte, src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte, src/frontend/src/lib/components/exchange/ExchangeAmountDisplay.svelte
This PR fixes a few related things:
1. ckERC20 tokens conversion forms (both send and review) are now properly calculating USD values using the ETH exchange rate. 
2. Same issue fixed for the ERC20 tokens send flow.
3. Added back the animation of the ETH fee value.
=> fix(frontend): issues with ETH fees on send/convert

src/frontend/src/env/networks/networks.cketh.env.ts, src/frontend/src/icp-eth/utils/cketh.utils.ts
It seems that the fallback for the ckETH helper contract is not needed anymore. It was introduced in PR https://github.com/dfinity/oisy-wallet/pull/1231 as safe measure. But currently both ckETH minters ([prod](https://dashboard.internetcomputer.org/canister/sv3dd-oaaaa-aaaar-qacoa-cai#get_minter_info) and [staging](https://dashboard.internetcomputer.org/canister/jzenf-aiaaa-aaaar-qaa7q-cai#get_minter_info)) provide the `eth_helper_contract_address`.
=> feat(frontend): remove fallback from ckETH Helper Contract address

src/frontend/src/lib/components/exchange/ExchangeAmountDisplay.svelte
We got an unexpected behaviour of the Send modal after adding `global` Svelte transition to the ETH fee component. It appeared that the `if` statement is not needed, which simplifies everything.
=> fix(frontend): avoid using "global" transition

src/frontend/src/icp/components/fee/BitcoinEstimatedFee.svelte
Instead ckBTC token data, the estimated Bitcoin network fee should use BTC symbol, decimals and exchange rate.
=> fix(frontend): wrong token symbol and exchange in ckBTC convert

src/frontend/src/tests/lib/utils/network.utils.spec.ts
Some tests for util `filterTokensForSelectedNetwork`. Note that a few cases are not practical since inputs `$selectedNetwork` and `$pseudoNetworkChainFusion` are linked between them.
=> test(frontend): util filterTokensForSelectedNetwork

src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte
Small refactoring that it will come in handy when we will brand the type of addresses. Note that we remove the fallback to empty string that it was not really necessary
=> refactor(frontend): use deconstruction of token data in AddTokenByNetwork

HACKING.md, package.json, scripts/build.tokens.ckerc20.ts, src/frontend/src/env/schema/env-token-ckerc20.schema.ts, src/frontend/src/env/tokens/tokens.ckerc20.json, src/frontend/src/env/types/env-token-ckerc20.ts
To be consistent we transform the `build.tokens.ckerc20` script in Typescript.
- Add more schemas and types for the script.
- Rename the script to `.ts`
- Apply typing throughout the script.
I removed some ckERC2 tokens from the JSON file and modified others. Then I ran the script and it was reverted. Both commits are included in this PR.
=> refactor(scripts): build ckErc20 tokens to Typescript

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
We want to include the nICP token.
```
Ledger Canister: buwm7-7yaaa-aaaar-qagva-cai
Index Canister: btxkl-saaaa-aaaar-qagvq-cai
```
(see https://docs.waterneuron.fi/more/canisters)
=> feat(frontend): add nICP token

package-lock.json, package.json
This PR prepares the release of version v1.2.1. It is a patch to include `nICP` token.
=> chore(release): v1.2.1

src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
As pointed out by PRODSEC, we should reverse the list of mapped transactions ONLY after the mapping, to avoid mixing the indexes that match the inner instructions.
=> feat(frontend): reverse Solana transactions only after mapping

src/frontend/src/lib/types/convert.ts, src/frontend/src/lib/utils/assert-amount.utils.ts, src/frontend/src/tests/lib/utils/assert-amount.utils.spec.ts
The idea is to create utils for validating user amount that can be re-used in both convert and send flow. Some of the utils take into account tokens-specific conditions. The whole list of added functions:
* `assertAmount` - common for BTC and ETH
* `assertCkBtcAmount` - specific for ckBTC
* `assertCkErc20Amount` - specific for ckERC20 tokens
* `assertCkEthAmount` - specific for ckETH
* `assertErc20Amount` - specific for ERC20 tokens
=> feat(frontend): assert-amount utils

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
Under PRODSEC suggestion: we will show the original addresses of a Solana transaction instead of their owner when we are parsing transactions
=> fix(frontend): show ATA addresses as destination and sources

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
The redeemed value of a SOlana closeAccount transaction is not explicitly indicated in the transaction data. So it must be inferred/calculated from the latest balance of the ATA that is being closed.
- Provide new prop cumulativeBalances to the mapper of Solana Token program transactions.
- The map will be a list of addresses with their cumulative balance up until that point.
- Use the cumulated balance of the ATA address as value for the mapper.
Adapted tests.
=> feat(frontend): add code to calculate a Solana closeAccount redeemed value

src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
Just to be more correct, we put the inner instructions right after the instruction they refer to: this will allow to have a proper cumulative balance during the parsing.
=> refactor(frontend): put Sol inner instructions at the respective index

.github/workflows/deploy-to-environment.yml, scripts/build.utils.mjs, src/frontend/src/lib/constants/app.constants.ts
The newly created `audit` environment should replicate the `staging` settings.
=> feat(build): treat audit ENV as staging

.github/workflows/deploy-to-environment.yml
There is a new network called "audit".  This PR adds it to the list of networks that can be deployed with CI.
- Add audit to the list of networks in `deploy-to-environment.yml`
=> feat(devops): Add audit to the list of networks

src/frontend/src/lib/stores/convert.store.ts, src/frontend/src/tests/lib/stores/convert.store.spec.ts
In this PR, I'm extending the Convert store with some data needed for ckERC/ckBTC/ckETH conversions.
1. Add `balanceForFee` to the store.
2. Add `minterInfo` to the store.
Tests are updated.
=> feat(frontend): extend convert store

src/frontend/src/lib/constants/app.constants.ts, src/frontend/src/sol/schedulers/sol-wallet.scheduler.ts, src/frontend/src/tests/sol/schedulers/sol-wallet.scheduler.spec.ts
We pay the calls of the Solana RPC provider, and they are proportional to the number. It is becoming too unscalable.
So, as a temporary measure, we delay the calls of the Solana wallet scheduler to one minute (double the other wallets).
This solution should be removed when we have a better one. For example, if we have a Solana RPC canister (similar to the EVM one), or when we change the code to not re-load the same transactions twice but guarantee that the data are correct.
=> feat(frontend): reduce the number of calls of the Solana wallet

src/frontend/src/sol/types/sol-transaction.ts, src/frontend/src/sol/utils/sol-instructions.utils.ts
It is useful to have a fallback for the token address when mapping a Token program instruction. So we use the `destination` mint info as fallback, in the same way we use the `source` one.
=> feat(frontend): fallback of token address for mapping Solana instructions

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
We want to map directly the createAccount transaction from the Solana RPC.
=> feat(frontend): map Solana transaction createAccount directly

.github/workflows/frontend-checks.yml
The `config` step was missing int the `may-merge` status check.
=> feat(ci): include config result in may-merge status check

src/frontend/src/lib/utils/user-amount.utils.ts, src/frontend/src/tests/lib/utils/user-amount.utils.spec.ts
In this PR, the user-amount utils are created. They are gonna replace the existing `convert.utils`. `validateUserAmount` is implemented the way that it can be used in swap, send and convert flow. 
In the next PR, I will remove the old file and update SwapForm and ConvertAmountSource to start using this method.
New util is created.
Provided.
=> feat(frontend): user-amount utils

src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
The inner instructions are being already treated as the other instructions, since we merge them together and pass to the mapper.
So we remove them from the usage as additional parsable transaction.
=> feat(frontend): remove recursive usage of inner instructions

src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/lib/components/convert/ConvertForm.svelte
Following the previous PR, we now need to update the existing convert components accordingly. Mostly, it's about passing the props down (the ones, that cannot be put in the context).
=> feat(frontend): update convert components

src/frontend/src/icp/types/ic-transaction.ts, src/frontend/src/icp/utils/icp-transactions.utils.ts, src/frontend/src/icp/utils/icrc-transactions.utils.ts
As further step to standardize the UI transactions (and their store), we use common type `TransactionId` for `IcTransactionUi`.
- Adjust `IcTransactionUi`.
- Adjust utils.
Current tests are sufficient.
=> feat(frontend): use common ID type for IcTransactionUi

dfx.json, scripts/build.cketh_minter.args.sh, scripts/build.cketh_minter.sh, scripts/deploy.cketh.sh
`dfx deploy X` should work out of the box for all canisters.  This implements that for `cketh_minter`.
- Define a build command for `cketh_minter` that downloads the Wasm and generates the default arguments.
- Delete unneeded arguments and variables.
Existing e2e tests should suffice.
Additionally, here is a manual test:
```
$ dfx start --clean --background
$ dfx canister create --all
$ dfx deploy cketh_minter
...
Installing code for canister cketh_minter, with canister ID jzenf-aiaaa-aaaar-qaa7q-cai
Deployed canisters.
```
Checking the arguments:
```
$ cat target/ic/cketh_minter.args.did 
(variant {
InitArg = record {
ethereum_network = variant {Sepolia};
ecdsa_key_name = "dfx_test_key";
ethereum_contract_address = opt "0xb44B5e756A894775FC32EDdf3314Bb1B1944dC34";
ledger_id = principal …
```
=> refactor(devops): dfx deploy cketh_minter works out of the box

src/frontend/src/lib/components/send/SendInputDestination.svelte, src/frontend/src/lib/components/ui/Value.svelte, src/frontend/src/lib/i18n/en.json
The titles on the send and review form are written with a trailing colon, which should be removed.
- removes colons
**before:**
**after:**
=> feat(frontend): removes colons

src/frontend/src/lib/styles/theme/base-colors.scss, src/frontend/src/lib/styles/theme/dark-theme.scss
Current yellow warning color in the dark theme is too active - suggestion is to dim it down a little bit
Before: 
After:
=> fix(frontend): updated toast warning color in the dark theme

src/frontend/src/lib/components/airdrops/AirdropEarnings.svelte, src/frontend/src/lib/services/reward-code.services.ts, src/frontend/src/tests/lib/services/reward-code.services.spec.ts
Currently we hardcoded to display 3 sprinkles in the `<AirdropEarnings/>` component. This PR implements displaying the correct amount of airdrops received.
- Updated `getUserRewardsTokenAmounts` to return amount of airdrops
- Updated AirdropEarnings component to display amount of airdrops
- Updated tests
Tests have been updated to also check for the amount of airdrops received
=> fix(frontend): Display correct sprinkle amount

.github/workflows/deploy-to-environment.yml
Just to organize better the logic of deploying, we put the general check of the canister directly in the step that sets the deployment network.
This avoids doubling the code too.
=> refactor(devops): simplify checks for deployment CI

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/sol/components/send/SolSendDestination.svelte, src/frontend/src/tests/sol/components/send/SolSendForm.spec.ts
The PRODSEC review suggested that we warn/inform the user when the destination input for Solana is not an ATA address, since we will derive it in our code.
This information can happen either in the form or in the confirmation review, or both, or in whichever form it is acceptable to have the user aware.
However, we are going to revisit how to show this information further on. For the current release we temporarily remove it.
=> feat(frontend): remove the warning for non-ATA destination address

src/frontend/src/sol/components/receive/SolReceive.svelte
The PRODSEC review suggested that we show the ATA address to the user for the specific token when needed, for example, when opening the receive modal.
However, we are going to revisit how to show this information further on. For the current release we temporarily remove it.
=> feat(frontend): replace the ATA address with the main Solana address in the receive modal

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
We extend the Solana mapper to `MintTo` and `Burn` transactions (and their `Checked` version) of the Token Program.
Practical examples used to map them:
- [Burn](https://solscan.io/tx/4RqjWLda38NSUmk88MYoq5AT2p6gcDfY73D4aZ6oKuaaeapshuM3SUsRsQpDKPdEB3zZkZeQLYo8tLDDcQWsdWyX)
- [MintTo](https://solscan.io/tx/5cFKsXTRLCQbmouPPLaYsMdVd137eTkm4nPxpxpnJ8qMQ17qVuXeyWtaNujJM6bSKczATsGcH7jBKNKCFj5uMRwE)
- [BurnChecked](https://solscan.io/tx/328K81kSv6bCMatwHs7HJYgJNm5SCEfKAqfYVYwuJEHcsXnWDxEhKvbbRFCrM3wzVkN7Spusjb3FWbC4N2RwNuBL)
- [MintToChecked](https://solscan.io/tx/2aeZQGnQxpCziLcCFRd1Nay4wTcHBH3TEKRRymTcSnZMnn9FcjhdzqrmcUmDU9eZcRuEH3SBbgxnRiyonphmA7yP)
- Add mapper for `MintTo` and `MintToChecked`.
- Add mapper for `Burn` and `BurnChecked`.
Added new tests.
=> feat(frontend): map MintTo and Burn transactions in Solana mapper

src/frontend/src/eth/services/eth-transaction.services.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
There is an issue caused by a wrong data in the ERC20 transactions details: after the transaction is `mined`, we process it again from `pending`. However, we use an endpoint that returns the wrong source and/or destination: specifically, it shows the token address, that is the smart contract that was interacted with.
The endpoint we are using is [eth_getTransactionByHash](https://www.quicknode.com/docs/ethereum/eth_getTransactionByHash): for an ERC20 `transfer` transaction, it correctly returns the token address in the `to` field, and in the `input` field we could extract/parse the real destination.
However, we alreaady use another provider to list the correct parsed data of ERC20 transactions. So, to fix it, we decide to reload the transactions from the provider that returns the correct …
=> feat(frontend): refresh ERC20 mined transaction details

src/frontend/src/eth/services/eth-transaction.services.ts, src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
The service `loadEthereumTransactions` typically re-set the transactions, using the method `set` of the transaction store: it ignores the existing transactions and overrwrites everything with the new ones.
However, we prefer to have a "refresh" when using such a service in processing mined transaction (function `processMinedTransaction`), using method `update` of the transaction store. There is no practical difference, but it allows to just refresh the data of the pending transactions, instead of completing removing it and add the respective mined ones.
It seems more correct/coherent this way.
- Add prop `updateOnly` to `loadEthereumTransactions` (defaults to `false`): it will use method `update` for each transaction, instead of `set` for all.
- Create new service …
=> feat(frontend): service loadEthereumTransactions can be update only

src/frontend/src/eth/components/transactions/EthTransactionModal.svelte, src/frontend/src/eth/utils/transactions.utils.ts, src/frontend/src/tests/eth/utils/transactions.utils.spec.ts
This PR is just to extract an util that maps an Ethereum address to a known name (if found). And to add tests.
=> refactor(frontend): extract util to map an ETH address to a known name

src/frontend/src/eth/components/transactions/EthTransactionModal.svelte, src/frontend/src/eth/utils/transactions.utils.ts, src/frontend/src/icp-eth/utils/cketh.utils.ts, src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts, src/frontend/src/tests/eth/utils/transactions.utils.spec.ts, src/frontend/src/tests/icp/components/convert/IcConvertTokenWizard.spec.ts, src/frontend/src/tests/mocks/ck-minter.mock.ts
We are already mapping the known ERC20 token names to display instead of their addresses in a transaction detail. A further step is to map the CK Minter too: if we know their address, we can map it and display a better name instead of the address.
- Export util `toCkMinterAddress`
- Add mapping of relevant CK minter addresses in util `mapAddressToName`.
- Provide CK Minter Info to the caller of `mapAddressToName` in component `EthTransactionModal`.
Added tests.
=> feat(frontend): map CK minter contract name for ERC20 transactions

src/frontend/src/eth/components/loaders/LoaderEthTransactions.svelte, src/frontend/src/tests/eth/components/loaders/LoaderEthTransactions.spec.ts
When we are in an Ethereum transaction page, we are not refreshing the transaction list. We just listen to new transactions, but ideally we should have a timer to refresh every certain amount of time.
- Create functions to reload transactions.
- Create timer utils to start and stop.
- Assign `onMount` and `onDestroy`.
Added tests.
=> feat(frontend): add timer to Ethereum transactions loader

tailwind.config.ts
Since we changed the default viewport sizes to be imported from tailwind itself, it broke our custom viewports leading to the missing footer issue.
Specified viewports in rem instead of px to be able to use defaultTheme.screens since the newer tailwind versions at some point started using rem, and mixing units breaks the custom viewports
=> fix(frontend): Fix tailwind screen size definitions

scripts/build.tokens.icrc.ts
We check if the Ledger canister ID saved in the JSON file is different from the one fetched with the metadata. However, it does not really make sense to check since the metadata are fetched using the saved Ledger canister ID. It will always match with the returned value.
=> refactor(frontend): remove unnecessary check in building ICRC

src/frontend/src/lib/styles/global/gix.scss
On some display, text inside of modals with scrollable content can look blurry. Discovered on Mac OS
Added a `border-radius: 0` to the content element solves it, even though its a slightly different problem than the one described below:
https://stackoverflow.com/questions/54667653/text-blur-after-scroll-bar-hide-with-webkit
In the below screenshots in one of the affected display we can see that adding the `border-radius: 0` hack seems to work to solve the blurry text issue.
We can also observe that the scrollbar is not anymore cut off in the top right side because of the border radius change, which fits perfectly now.
Before:
After:
=> fix(frontend): Fix blurry text on modals with scrollable content

src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/lib/components/convert/ConvertAmountDestination.svelte, src/frontend/src/lib/components/convert/ConvertForm.svelte, src/frontend/src/lib/components/convert/ConvertReview.svelte, src/frontend/src/tests/lib/components/convert/ConvertAmountDestination.spec.ts
This PR includes some small updates of the shared Convert components.
1. Update `receiveAmount` calculation - it now should deduct the amount needed for destination token fees (e.g. in case of ckBTC -> BTC conversion).
2. Add `destination` address slot to ConvertForm and ConvertReview components.
Existing tests updated.
=> feat(frontend): update shared Convert components

src/frontend/src/icp/components/send/IcSendDestination.svelte, src/frontend/src/icp/components/send/IcSendForm.svelte, src/frontend/src/lib/components/send/SendInputDestination.svelte
This PR includes a refactoring of the IcSendDestination component - this component should be reusable between send and convert flows.
1. Switch from context usage to props.
2. Make label optional for now (it will be gone with the redesign of the send flow).
=> refactor(frontend): generalize IcSendDestination component

src/frontend/src/lib/components/address/DestinationValue.svelte
A small UI component for displaying either a label for default address or a custom address string. The "change" button can be optionally displayed via slots (the following PRs).
Default address:
Custom address:
=> feat(frontend): DestinationValue component

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
Solana program [Token-2022](https://spl.solana.com/token-2022) is a superset of the functionality provided by the [Token Program](https://spl.solana.com/token).
So, it makes sense (according to PRODSEC's suggestion too) that we map the Token-2022 instructions exactly as the legacy Token program, at least for the ones that are in common.
This will even help with avoiding duplicated code.
=> feat(frontend): map Solana program Token2022 as legacy Token program

src/frontend/src/icp/components/convert/IcConvertForm.svelte, src/frontend/src/icp/components/convert/IcConvertReview.svelte, src/frontend/src/icp/components/convert/IcConvertTokenWizard.svelte, src/frontend/src/icp/components/fee/IcTokenFees.svelte, src/frontend/src/lib/config/convert.config.ts, src/frontend/src/lib/enums/wizard-steps.ts, src/frontend/src/tests/icp/components/convert/IcConvertTokenWizard.spec.ts
As the next step of the preparation for ckBTC -> BTC conversion, we need to update IC convert form components.
1. Display destination address in both convert and review steps forms.
2. Pass `destinationTokenFee` to update `receiveAmount` accordingly.
=> feat(frontend): IC convert forms update

src/frontend/src/tests/lib/services/address.services.spec.ts, src/frontend/src/tests/lib/services/manage-tokens.services.spec.ts, src/frontend/src/tests/lib/utils/info.utils.spec.ts, src/frontend/src/tests/sol/services/sol-signatures.services.spec.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
We are mocking the console directly in the `vitest.setup` file. So, we need to avoid resetting it when we have tests that could raise a console log.
=> test(frontend): do not reset console mock

src/frontend/src/icp/components/convert/IcConvertForm.svelte
This PR fixes a problem I just noticed on staging: the balance in the error message is calculated with incorrect decimals.
=> fix(frontend): display correct balance on ckERC20 conversions

src/frontend/src/lib/components/icons/IconCheck.svelte, src/frontend/src/lib/components/signer/SignerAlert.svelte
In order to repurpose the check icon, we refactor it a bit to reuse it in upcoming PRs regarding the Settings page refactoring.
- Changed fixed white color for check icon to `currentColor` so we can dynamically set color
- Added `text-white` to only current occurrence of the icon so the color doesn't change there
=> fix(frontend): Check icon fixes

src/frontend/src/lib/components/convert/ConvertAmountDisplay.svelte, src/frontend/src/lib/components/fee/FeeDisplay.svelte
This PR fixes the way of how a very low amounts (e.g. BTC fees) are displayed in the conversion flows. 
Before:
After:
=> fix(frontend): format of the BTC fees

src/frontend/src/tests/btc/components/send/BtcSendReview.spec.ts
There is a small unsafe type in the tests for `BtcSendReview`.
=> test(frontend): convert balance input to string in BtcSendReview tests

src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts, src/frontend/src/lib/types/transaction.ts
We want to migrate to `ethers` v6. However, the `Transaction` type changes quite a bit, so we first define exactly what type of interface we need from `ethers.Transaction`
=> refactor(frontend): extract specific type for ethers transaction

.github/workflows/backend-checks.yml, .github/workflows/backend-tests.yml, .github/workflows/binding-checks.yml, .github/workflows/e2e-tests.yml
Many of our workflows have a final job that checks whether all the other jobs succeeded.  This makes it much easier to manage which workflows need to pass for a PR to merge, than if all the individual jobs need to be listed in the ruleset.
However I noticed that many of the workflows omit the `always()` conditional on this final job.  Omitting always will make that final step pointless: If a job dependency, listed in `needs`, is skipped or fails, the dependent job will be skipped, and a skipped job is considered as not applicable when considering a merge rule.
Having PRs mergeable when required jobs fail is of course a bug.
- Add `always()` as a conditional for all the final steps.
=> fix(devops): Always run final jobs

src/frontend/src/lib/i18n/en.json
There was a typo on the conversion info box.
- resolves typo
**before:**
**after:**
=> fix(frontend): fixes conversion info box typo

src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/components/tokens/TokenInput.svelte, src/frontend/src/lib/types/token-action.ts, src/frontend/src/lib/utils/assert-amount.utils.ts, src/frontend/src/lib/utils/user-amount.utils.ts
The first step of creating a context for validation errors in send/convert/swap flows is to generalize convert-related type.
=> refactor(frontend): generalize convert-related type

src/frontend/src/lib/stores/token-action-validation-errors.store.ts, src/frontend/src/tests/lib/stores/token-action-validation-errors.store.spec.ts
The next step of creating a context for validation errors in send/convert/swap flows is to actually create all required stores and context.
=> feat(frontend): new context for validation errors on token action

src/frontend/src/lib/components/convert/ConvertAmountDisplay.svelte, src/frontend/src/lib/components/ui/ModalValue.svelte
This PR fixes the issue that recently happened in ConvertAmountDisplay - the USD values stoped being displayed in the convert modal. It is now properly working in both Swap modal only token values does not need to be displayed, as well as in the Convert flow.
=> fix(frontend): issue with USD value not being displayed on convert

src/frontend/src/lib/utils/user-amount.utils.ts
We need to migrate to `ethers` v6: one of the biggest change was the deprecation of `BigNumber` in favour of built-in `bigint` (see [documentation](https://docs.ethers.org/v6/migrating/#migrate-bigint)).
To smooth the migration, we replace `BigNumber` with `bigint` in the util `validateUserAmount` and its sub-functions.
- Make util `validateUserAmount` accept `amount` as `bigint` instead of `BigNumber`.
- Adapt the rest of the usages.
Existing tests were adapted and they works.
=> feat(frontend): util validateUserAmount will use bigint instead of BigNumber

src/frontend/src/lib/components/carousel/Carousel.svelte
Under certain screen sizes, it was possible for the next card to show up slightly. This is due to the introduction of the scroll bar in the main nav.
Before carousel initialisation:
After initialisation the scroll bar disappears as the carousel receives its final height, the calculations are still done with the scroll bar included:
If we can get the carousel to have the same height as when the dimensions have calculated and applied, the scrollbar would be included in the calculations only when it should. To do this, we added a starting width style of 9999px to the frame slider container, which after the carousel gets initialized will receive its correct width.
=> fix(frontend): Carousel incorrect width display next card

src/frontend/src/lib/canisters/kong_backend.canister.ts, src/frontend/src/lib/utils/swap.utils.ts, src/frontend/src/tests/lib/canisters/kong_backend.canister.spec.ts, src/frontend/src/tests/lib/utils/swap.utils.spec.ts
As suggested by the Kong team, we need to use ledger ids (prefixed with `IC.`) instead of token symbols for communicating with their endpoints.
=> feat(frontend): switch to ledger ids instead of symbols on kong swap

src/frontend/src/sol/api/solana.api.ts, src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/sol/types/sol-transaction.ts, src/frontend/src/tests/mocks/sol-transactions.mock.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
We want to have a more explicit type for the getTransaction method of Solana RPC.
However, according to [Solana dev forum](https://solana.stackexchange.com/questions/17643/how-to-infer-or-find-basic-types-for-return-values-in-solana-web3-js-v2-library/17673#17673), exporting ‘result types’ from `@solana/kit` is impractical, because the RPC is fluid to the point where its result types change depending on the particular inputs to the calls themselves.
So, we must first create a sub-function and extract the type from there, in a more fluid way.
- Create function that just wraps the `getTransaction` method of the Solana RPC.
- Extract the type for such type.
- Use it in the code.
Adapted a few mock, the rest is sufficient.
=> feat(frontend): explicit type of method getTransaction of Solana RPC

src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/sol/types/sol-transaction.ts, src/frontend/src/tests/mocks/sol.mock.ts
According to [Solana documentation](https://solana.com/docs/core/fees#base-transaction-fee), the first signer is the fee payer. So we set the fee in a `SolTransactionUi` only if the user is the fee payer.
- Create small function to extract the fee payer from `accountKeys`: it filters all the signers and returns the first.
- Use the fee payer to set the fee prop in `fetchSolTransactionsForSignature`.
Current tests are sufficient and works.
=> fix(frontend): Solana fees are set only if user is payer

src/frontend/src/eth/services/send.services.ts, src/frontend/src/icp/components/fee/EthereumFeeContext.svelte, src/frontend/src/icp/services/ic-add-custom-tokens.service.ts, src/frontend/src/icp/utils/ckbtc.utils.ts, src/frontend/src/icp/utils/cketh.utils.ts, src/frontend/src/icp/utils/icp-transactions.utils.ts, src/frontend/src/icp/utils/icrc-transactions.utils.ts, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/services/reward-code.services.ts, src/frontend/src/lib/services/user-snapshot.services.ts, src/frontend/src/lib/utils/assert-amount.utils.ts, src/frontend/src/lib/utils/token-group.utils.ts, src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte, src/frontend/src/sol/services/sol-send.services.ts, src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/sol/services/spl-accounts.services.ts, src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/sol/utils/sol-transactions.utils.ts, src/frontend/src/tests/icp-eth/services/custom-token.services.spec.ts, src/frontend/src/tests/icp/services/ic-add-custom-tokens.service.spec.ts, src/frontend/src/tests/icp/workers/ic-wallet-transactions.worker.spec.ts, src/frontend/src/tests/lib/canisters/backend.canister.spec.ts, src/frontend/src/tests/lib/services/reward-code.services.spec.ts, src/frontend/src/tests/lib/services/user-snapshot.services.spec.ts, src/frontend/src/tests/lib/utils/format.utils.spec.ts, src/frontend/src/tests/mocks/sol-transactions.mock.ts, src/frontend/src/tests/sol/api/solana.api.spec.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
Replacing instances of `0n` with `ZERO_BI`.
=> refactor(frontend): use ZERO_BI instead of 0n

src/frontend/src/btc/components/convert/BtcConvertForm.svelte, src/frontend/src/eth/components/convert/EthConvertForm.svelte, src/frontend/src/icp/components/convert/IcConvertForm.svelte, src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/convert/ConvertForm.svelte, src/frontend/src/lib/components/convert/ConvertModal.svelte, src/frontend/src/tests/btc/components/convert/BtcConvertForm.spec.ts, src/frontend/src/tests/btc/components/convert/BtcConvertTokenWizard.spec.ts, src/frontend/src/tests/eth/components/convert/EthConvertForm.spec.ts, src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts, src/frontend/src/tests/icp/components/convert/IcConvertForm.spec.ts, src/frontend/src/tests/icp/components/convert/IcConvertTokenWizard.spec.ts, src/frontend/src/tests/lib/components/convert/ConvertAmountSource.spec.ts, src/frontend/src/tests/lib/components/convert/ConvertWizard.spec.ts
In this PR, all convert flows are updated to use the TokenActionValidationErrors context.
1. Start using the TokenActionValidationErrors context in all convert flows.
2. Remove outdated props.
Existing tests have been adjusted.
=> feat(frontend): use errors context in ETH/IC/BTC convert flows

src/frontend/src/btc/components/convert/BtcConvertForm.svelte, src/frontend/src/eth/components/convert/EthConvertForm.svelte, src/frontend/src/icp/components/convert/IcConvertForm.svelte, src/frontend/src/lib/components/convert/ConvertForm.svelte, src/frontend/src/lib/components/ui/ContentWithToolbar.svelte, src/frontend/src/lib/constants/test-ids.constants.ts, src/frontend/src/tests/lib/components/convert/ConvertWizard.spec.ts
While working on another PR, I noticed that ConvertWizard.spec is missing some test suites.
=> test(frontend): add missing ConvertWizard tests

src/frontend/src/tests/eth/stores/eth-transactions.store.spec.ts, src/frontend/src/tests/lib/utils/tokens.utils.spec.ts, src/frontend/src/tests/mocks/balances.mock.ts, src/frontend/src/tests/mocks/eth-transactions.mock.ts
We have a few constants that are mocked balances as `BigNumber`. However, we are deprecating them in favour of `bigint`, for the coming upgrade to `ethers` v6.
=> feat(frontend): use bigint mocked balance instead of BigNumber

src/frontend/src/lib/components/about/AboutWhyOisyModal.svelte, src/frontend/src/lib/components/carousel/Indicators.svelte, src/frontend/src/lib/components/core/MultipleListeners.svelte, src/frontend/src/lib/components/dapps/DappTags.svelte, src/frontend/src/lib/components/dapps/DappsExplorerSignedIn.svelte, src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/components/license-agreement/LicenseAgreement.svelte, src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte, src/frontend/src/lib/components/networks/NetworksSwitcher.svelte, src/frontend/src/lib/components/rewards/RewardsGroup.svelte, src/frontend/src/lib/components/rewards/RewardsRequirements.svelte, src/frontend/src/lib/components/settings/ThemeSelector.svelte, src/frontend/src/lib/components/signer/SignerPermissions.svelte, src/frontend/src/lib/components/swap/SwapLiquidityFees.svelte, src/frontend/src/lib/components/swap/SwapRoute.svelte, src/frontend/src/lib/components/swap/SwapSlippage.svelte, src/frontend/src/lib/components/ui/Json.svelte, src/frontend/src/lib/components/ui/SkeletonCards.svelte, src/frontend/src/lib/components/ui/StaticSteps.svelte, src/frontend/src/lib/components/wallet-connect/WalletConnectReview.svelte
We want to bump library @dfinity/eslint-config-oisy-wallet (PR https://github.com/dfinity/oisy-wallet/pull/5418).
However, that causes some Svelte lint issues linked to new enabled rules.
In this PR, we tackle [require-each-key](https://sveltejs.github.io/eslint-plugin-svelte/rules/require-each-key/) :  
> This rule reports {#each} block without key.
Add a specific key to each loop in the Svelte component.
Existing tests will suffice.
=> chore(frontend): add key to Svelte loops

src/frontend/src/btc/components/send/BtcSendAmount.svelte, src/frontend/src/btc/components/send/BtcSendDestination.svelte, src/frontend/src/eth/components/send/EthSendAmount.svelte, src/frontend/src/eth/components/send/EthSendDestination.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp/components/send/IcSendAmount.svelte, src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/sol/components/send/SolSendAmount.svelte, src/frontend/src/sol/components/send/SolSendDestination.svelte
We want to bump library @dfinity/eslint-config-oisy-wallet (PR https://github.com/dfinity/oisy-wallet/pull/5418).
However, that causes some Svelte lint issues linked to new enabled rules.
In this PR, we tackle [no-reactive-functions](https://sveltejs.github.io/eslint-plugin-svelte/rules/no-reactive-functions/) :  
> This rule reports whenever a function is defined in a reactive statement. This isn’t necessary, as each time the function is executed it’ll already have access to the latest values necessary. Redefining the function in the reactive statement is just a waste of CPU cycles.
Replace all reactive-declared functions with constants. 
Existing tests will suffice.
=> feat(frontend): remove unnecessary reactive declarations for functions

src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/eth/components/send/SendInfo.svelte, src/frontend/src/icp/components/send/IcSendTokenWizard.svelte, src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/components/onramper/OnramperWidget.svelte, src/frontend/src/lib/components/rewards/AllRewardsList.svelte, src/frontend/src/lib/components/rewards/RewardEarnings.svelte, src/frontend/src/lib/components/rewards/RewardStateModal.svelte, src/frontend/src/lib/components/swap/SwapProvider.svelte, src/frontend/src/sol/components/send/SolSendReview.svelte
We want to bump library @dfinity/eslint-config-oisy-wallet (PR https://github.com/dfinity/oisy-wallet/pull/5418).
However, that causes some Svelte lint issues linked to new enabled rules.
In this PR, we tackle [no-reactive-literals](https://sveltejs.github.io/eslint-plugin-svelte/rules/no-reactive-literals/) :  
> This rule reports on any assignment of a static, unchanging value within a reactive statement because it’s not necessary.
Replace all reactive-declared variables with mutable (or constants when possible) declarations.
Existing tests will suffice.
=> refactor(frontend): remove unnecessary reactive statement

src/frontend/src/icp/components/info/InfoBitcoin.svelte, src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/rewards/RewardModal.svelte, src/frontend/src/lib/components/rewards/Rewards.svelte
We want to bump library @dfinity/eslint-config-oisy-wallet (PR https://github.com/dfinity/oisy-wallet/pull/5418).
However, that causes some Svelte lint issues linked to new enabled rules.
In this PR, we tackle [no-useless-mustaches](https://sveltejs.github.io/eslint-plugin-svelte/rules/no-useless-mustaches/) :  
> This rule reports mustache interpolation with a string literal value.
The mustache interpolation with a string literal value can be changed to a static contents.
Remove all unnecessary brackets in Svelte components and replace with string literals.
Existing tests will suffice.
=> chore(frontend): remove unnecessary declaration brackets in Svelte components

src/frontend/src/eth/components/send/EthSendForm.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp/components/send/IcSendForm.svelte, src/frontend/src/lib/components/send/SendForm.svelte, src/frontend/src/tests/eth/components/send/EthSendForm.spec.ts
ETH is the last Send flow where common send form components are not used. In this PR, updating the EthSendForm component. 
`EthSendForm` is now aligned with the other send flows.
Existing tests should be enough. Additionaly, tested the send process manually.
=> refactor(frontend): use SendForm in EthSendForm

src/frontend/src/lib/i18n/en.json
To save space in the redesigned network switcher we change the chain fusion text slightly.
Changed text from `Chain Fusion (all networks)` to `All networks`
Before:
After:
=> refactor(frontend): Remove chain fusion text just all networks

src/frontend/src/lib/components/networks/NetworkButton.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
We want to display a badge on th network buttons inside of the network switcher.
- Added prop `isTestnet`
- Added testnet badge
- Added testnet translation
=> feat(frontend): Add testnet badge for network button

src/frontend/src/env/reward-campaigns.json
Current end date shows March 27.
We need a bit more time to have the next episode ready.
Change March 27 to April 7
=> feat(frontend): Update rewards campaign end date

src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte, src/frontend/src/lib/services/exchange.services.ts, src/frontend/src/tests/lib/services/exchange.services.spec.ts
Some ICRC tokens are not available via our primary price provider (CoinGecko). To ensure complete price coverage, we need to support a fallback data source.
Implemented fallback logic in the exchangeRateICRCToUsd service to fetch missing token prices from KongSwap when not available via CoinGecko.
Added test coverage for new utility methods.
=> feat(frontend): implemented fallback logic for icrcUsdPrices

src/frontend/src/lib/styles/global/gix.scss
Debugging showed that the align-items rule is not really necessary for NetworksSelector. Additionally, it was causing issue for other modals. The solution is to remove it completely.
=> fix(frontend): issue with modal content

src/frontend/src/lib/components/tokens/ModalTokensList.svelte
I noticed today that on some screen sizes the TokensList modal displays with unwanted scrollbar. It appeared to be an issue with the `stretch` class that was giving this unexpected effect to the list. The solution is to not use `ContentWithToolbar` in this particular case. Also, I cleaned up the component by removing some unnecessary HTML/CSS.
=> fix(frontend): scrollable content of ModalTokensList

src/frontend/src/lib/components/loaders/Loaders.svelte
We move the component `LoaderUserProfile` before the other loaders: we are going to user the enabled networks that are saved in the user profile in the backed. That will affect the rest: loading address, transactions, prices, and so forth.
=> refactor(frontend): move User profile loader to top level

src/frontend/src/lib/derived/page-token.derived.ts, src/frontend/src/tests/lib/derived/page-token.derived.spec.ts
In store `pageToken`, the native Ethereum tokens were hardcoded, but it makes sense that they are used with store `enabledEthereumTokens` (like the rest).
=> refactor(frontend): store pageToken should use enabledEthereumTokens

src/frontend/src/lib/derived/testnets.derived.ts, src/frontend/src/lib/derived/user-networks.derived.ts, src/frontend/src/lib/derived/user-profile.derived.ts, src/frontend/src/tests/lib/derived/user-networks.derived.spec.ts, src/frontend/src/tests/lib/derived/user-profile.derived.spec.ts
Since we are going to use the `userSettingsNetworks` store in other modules and we risk to cross-import, it is better to move it to the user-profile module.
=> refactor(frontend): move store userSettingsNetworks

src/frontend/src/env/networks/networks.env.ts, src/frontend/src/lib/derived/user-networks.derived.ts, src/frontend/src/tests/lib/derived/user-networks.derived.spec.ts
The `userNetworks` store should consider if `testnets` are enabled or not. So that the default (in case nothing is set in the backend for the user's profile) will include both mainnets and testnets.
- Create list of testnet networks IDs (similar to mainnets).
- Include `testnets` in the default response of the store `userNetworks` (basically when there are no settings about networks in thew user profile).
Included tests.
=> feat(frontend): include testnets in default of userNetworks

src/frontend/src/btc/derived/btc-pending-sent-transactions-status.derived.ts, src/frontend/src/btc/derived/networks.derived.ts, src/frontend/src/btc/derived/tokens.derived.ts, src/frontend/src/eth/derived/networks.derived.ts, src/frontend/src/eth/derived/tokens.derived.ts, src/frontend/src/icp/derived/icrc.derived.ts, src/frontend/src/lib/components/loaders/Loader.svelte, src/frontend/src/lib/components/networks/NetworksDropdown.svelte, src/frontend/src/lib/components/networks/NetworksTestnetsToggle.svelte, src/frontend/src/lib/components/receive/ReceiveAddresses.svelte, src/frontend/src/lib/derived/testnets.derived.ts, src/frontend/src/lib/derived/user-networks.derived.ts, src/frontend/src/sol/derived/networks.derived.ts, src/frontend/src/sol/derived/tokens.derived.ts, src/frontend/src/tests/lib/derived/page-token.derived.spec.ts, src/frontend/src/tests/lib/derived/testnets.derived.spec.ts, src/frontend/src/tests/utils/derived.test-utils.ts
It makes more sense that the derived store `testnets` is renamed `testnetsEnabled`.
=> refactor(frontend): rename store testnets to testnetsEnabled

.github/workflows/e2e-tests.yml
In PR https://github.com/dfinity/oisy-wallet/pull/5045 , I need to change the final step to resolve the `merge-e2e` check to positive if there are no changes in the E2E files. This is the case for PRs that do not require E2E tests, otherwise it will not pass the CI checks (see https://github.com/dfinity/oisy-wallet/actions/runs/14154886004/job/39652848558?pr=5504).
=> fix(e2e): merge-e2e tag must resolve to true when no changes

src/frontend/src/lib/components/receive/ReceiveAddresses.svelte, src/frontend/src/lib/derived/networks.derived.ts
We will start to enable and disable network according to the user preference. That means that we could have the Solana networks disabled.
To that scope we need to turn off some features that would not be possible if the networks are turned off.
- Create derived stores to check if Solana networks are enabled: Mainnet, Testnet, Devnet and Local.
- Use the stores to hide the Solana addresses.
- Use the store to hide the Solana tokens.
I simulated the Solana disabled network:
=> feat(frontend): stores to check if Solana networks are enabled

src/frontend/src/lib/components/tokens/TokenLogo.svelte, src/frontend/src/sol/components/send/SolSendDestination.svelte, src/frontend/src/sol/components/wallet-connect/SolWalletConnectSignReview.svelte
In library eslint-config-oisy-wallet we are adding rule [svelte/spaced-html-comment](https://sveltejs.github.io/eslint-plugin-svelte/rules/spaced-html-comment/) (PR https://github.com/dfinity/eslint-config-oisy-wallet/pull/57).
So we apply the rule formatting here first, adding whitespaces in the comments, where needed.
=> chore(frontend): apply Svelte rule spaced-html-comment

src/frontend/src/lib/components/networks/MainnetNetwork.svelte, src/frontend/src/lib/components/networks/Network.svelte, src/frontend/src/lib/components/networks/NetworkButton.svelte, src/frontend/src/lib/components/networks/NetworkSwitcherList.svelte, src/frontend/src/lib/components/networks/NetworkSwitcherLogo.svelte, src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
After some iterations, we finally landed on how do we want to re-use NetworksSwitch in the ModalTokensList component - we only re-use particular parts of it. This PR extract them into their own components.
=> refactor(frontend): extract parts of NetworksSwitcher into components

src/frontend/src/lib/components/settings/Settings.svelte, src/frontend/src/lib/components/settings/SettingsModalEnabledNetworks.svelte, src/frontend/src/lib/constants/test-ids.constants.ts
We need to adjust the e2e tests to work with the adjusted testnet toggler (its a checkbox now which opens in the active networks settings modal)
- Added test id for edit button in settings
- Added test id for enable testnet checkbox
=> fix(frontend): Add test ids for new testnet toggler in network settings

src/frontend/src/lib/components/swap/SwapModal.svelte, src/frontend/src/lib/components/swap/SwapTokensList.svelte
Similar to the send flow, we are introducing the new token selector into the Swap flow. The network filter in this case is view-only since all the swap tokens are from one single network.
=> feat(frontend): update Swap flow with the new token selector

src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendTokensList.svelte, src/frontend/src/lib/components/swap/SwapModal.svelte, src/frontend/src/lib/components/swap/SwapTokensList.svelte, src/frontend/src/lib/components/tokens/ModalTokensList.svelte, src/frontend/src/lib/config/send.config.ts, src/frontend/src/lib/enums/wizard-steps.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
This PR integrates the new token selector into the send and swap flow. In the send flow, it also adds an additional wizard step for selecting a network filter. And in the swap flow, the network selector button is view-only since all tokens belong to a single network (ICP).
=> feat(frontend): use the new token selector in Send and Swap flows

.github/workflows/e2e-tests.yml
The E2E tests are running only for changes in E2e-related files. But we need it to always run on `main`, for each new push.
=> fix(e2e): snapshots tests should run on main

.github/workflows/backend-checks.yml, .github/workflows/backend-tests.yml, .github/workflows/binding-checks.yml, .github/workflows/devops-checks.yml, .github/workflows/formatting-checks.yml, .github/workflows/release.yml, .github/workflows/update-rust.yml
After PR https://github.com/dfinity/oisy-wallet/pull/5542 , since we keep improving our security liabilities in the Github CI folder, we start by restricting the permissions at the jobs level for the majority of the CIs.
=> feat(devops): restrict permissions to Backend Github CI Actions

src/frontend/src/lib/components/tokens/ModalTokensList.svelte
Similar to the global NetworksSwitcher, we'd like to hide the label on smaller screens in the ModalTokensList component.
=> style(frontend): hide ModalTokensList network label on small screens

.github/workflows/e2e-tests.yml
To trigger the CI that does the E2E tests for the label, we need to specify the types in the trigger for the pull requests.
=> ci(e2e): E2E tests should be triggered when labelling a PR

src/frontend/src/lib/components/networks/MainnetNetwork.svelte, src/frontend/src/lib/components/networks/Network.svelte, src/frontend/src/lib/components/networks/NetworkButton.svelte, src/frontend/src/lib/components/networks/NetworkSwitcherList.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendTokensList.svelte, src/frontend/src/lib/components/tokens/ModalNetworksFilter.svelte
This PR implements some adjustments and improvements that were found during the testing session:
1. The network selector modal should only be closable by clicking the "Back" button.
2. The synthetic delay on network select should not be used when NetworksSwitcherList in rendered as a modal.
3. If $selectedNetwork is preselected by the user before opening the send modal, we should disable the Network filter button.
=> fix(frontend): tokens list adjustments and fixes

src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/tokens/ModalTokensList.svelte, src/frontend/src/lib/components/ui/InputSearch.svelte
We need to show the reset button when user start typing something and not only when there are no matching tokens found.
1. Rename the input prop.
2. Adjust its usage in ManageTokens and ModalTokensList.
No tests affected.
=> fix(frontend): tokens filter input reset button

.github/workflows/backend-tests.yml, .github/workflows/e2e-tests.yml, .github/workflows/release.yml
Third party GitHub actions should be pinned as part of security hardening.
- Pin download-artifact
See CI
=> chore(devops): Pin download-artifact

scripts/lint.github.sh
During the audit, it was noted that we used third party GitHub actions pinned toa version, rather than a commit, thereby making it possible for an attacker to move the tag to a different commit and so exploit our CI.
This is detected by our GitHub linter, but only in pedantic mode: https://woodruffw.github.io/zizmor/audits/#unpinned-uses
- Run zizmor in pedantic mode.
See CI
=> chore(devops): Use zizmor in pedantic mode

.npmrc
The experimental `resolution-mode` was deprecated in recent versions of `npm`, so we remove it from `.npmrc`.
There is no difference, since we were already using it with the default value of getting the highest version.
=> chore(build): remove deprecated resolution-mode in npmrc

src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
If we have no testnets enabled, we shouldnt show n of 10 networks enabled, but consider the total to be only the amount of mainnets.
Only if testnets and at least one of the them is enabled, we display n of 10 (all supported) networks.
Also, if all are selected we dont display the count at all.
Changes logic on when and how to display.
Case 1 - testnets disabled, all mainnets enabled
Case 2 - testnets disabled, 3/4 mainnets enabled
Case 3 - testnets enabled, but not individual testnets enabled:
Case 4 - testnets enabled, a few individual testnets enabled as well:
Case 5 - testnets enabled, all individual testnets enabled:
=> refactor(frontend): Network switcher should display enabled networks depending on if testnets are enabled

src/frontend/src/lib/components/networks/MainnetNetwork.svelte, src/frontend/src/lib/components/networks/Network.svelte, src/frontend/src/lib/components/networks/NetworkButton.svelte, src/frontend/src/lib/components/networks/NetworkSwitcherList.svelte, src/frontend/src/lib/components/tokens/ModalNetworksFilter.svelte, src/frontend/src/lib/types/components.ts
As requested by the design team, we need to increate some fonts in the ModalNetworksFilter component. The global NetworksSwitcher should stay unaffected.
=> style(frontend): increase fonts for Network filter labels

src/frontend/src/eth/rest/etherscan.rest.ts, src/frontend/src/tests/eth/rest/etherscan.rest.spec.ts
To be more type-safe, we explicitly set the type of the mapper in method `transactions` of class `EtherscanRest`, and clean the unnecessary values.
=> refactor(frontend): explicit type for method transactions of class EtherscanRest

src/frontend/src/lib/components/fee/FeeDisplay.svelte, src/frontend/src/lib/components/swap/SwapFees.svelte, src/frontend/src/lib/utils/format.utils.ts
Util `formatTokenAmount` is a duplicated of `formatToken`, so we replace the first with the latter.
=> refactor(frontend): replace duplicated util formatTokenAmount

src/frontend/src/lib/components/loaders/Loader.svelte, src/frontend/src/tests/lib/components/loaders/Loader.spec.ts
The `Loader` component should await initialization before running the reactive statement. Otherwise there will be a race condition where the component is trying to load the addresses but the signer allowance is not initialized yet:
=> fix(frontend): remove race condition from Loader component

src/frontend/src/env/plausible.env.ts, src/frontend/src/lib/services/analytics.services.ts, src/frontend/src/tests/lib/services/analytics.service.spec.ts
We aim to track analytics using Plausible. The goal is to ensure that pageviews and custom events are tracked correctly across the app.
Integrated plausible-tracker
Added unit tests for initPlausibleAnalytics and trackEvent
=> feat(frontend): added plausible service

src/frontend/src/lib/components/transactions/TransactionAddress.svelte, src/frontend/src/lib/components/transactions/TransactionModal.svelte
As a preparation for handling multiple recipients addresses in the BtcTransactionModal component, we need to extract some logic into a separate component. Also, we add additional `transaction-custom-to` slot for displaying a custom recipient information (BTC case).
=> feat(frontend): TransactionRecipient component

src/frontend/src/lib/services/analytics.services.ts, src/frontend/src/tests/lib/services/analytics.service.spec.ts
We aim to track analytics using Plausible. The goal is to ensure that pageviews and custom events are tracked correctly across the app.
Added try-catch block to prevent app initialization from breaking if Plausible fails to load
Covered new logic with the tests.
=> feat(frontend): added try/catch for plausible init

src/frontend/src/btc/components/transactions/BtcTransactionModal.svelte, src/frontend/src/btc/types/btc.ts, src/frontend/src/btc/utils/btc-transactions.utils.ts, src/frontend/src/lib/services/user-snapshot.services.ts, src/frontend/src/tests/btc/derived/btc-transactions.derived.spec.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts, src/frontend/src/tests/mocks/btc-transactions.mock.ts
As suggested by the external audit, we need to properly handle BTC transactions with multiple valid outputs. This case is not reproducible via OISY at the moment, but we might extend the BTC functionality in the future. 
1. Instead of using the first valid output to get a value, we calculate a sum from all the valid entries.
2. Instead of using the first valid output to get a recipient address, we collect all valid entries as an array.
3. Update UI to display all the recipients as a list of address. The UI can be improved later, if and when this case becomes real.
Existing tests adjusted.
=> feat(frontend): handle BTC tx multiple recipients case

src/frontend/src/lib/types/transaction.ts
Furthermore we explicitly specify props `hash`, `from` and `to` in interface `EthersTransaction`, and props `blockNumber` and `timestamp` in interface `Transaction`.
It does not change anything, since the new definitions are the same as the imbedded ones. However, in `ethers` v6 they will change to be null instead of undefined, so this helps us with maintaining the behaviours during migration.
=> refactor(frontend): explicitly set props of Ethers transaction interface
