src/airdrop/src/lib.rs, src/airdrop/src/utils.rs
=> fix(airdrop): fix already borrowed: BorrowMutError

canister_ids.json, dfx.json
https://dashboard.internetcomputer.org/canister/grghe-syaaa-aaaar-qabyq-cai
=> chore: move the backend canister to the tECDSA subnet

src/airdrop/src/guards.rs, src/airdrop/src/lib.rs, src/airdrop/src/state.rs, src/airdrop/src/utils.rs
Change some parts of the code to be more idiomatic.
=> chore(airdrop): satisfy `clippy`

src/frontend/src/lib/components/send/SendDestination.svelte, src/frontend/src/lib/components/send/SendForm.svelte
In case use paste an address not prefixed with 0x
=> feat(frontend): map address with 0x

src/frontend/src/lib/components/airdrop/AirdropModal.svelte
=> fix(frontend): display status when airdrop over without children

README.md, oisy-comparison.svg
=> Minor readme edits

src/frontend/src/lib/api/airdrop.api.ts, src/frontend/src/lib/components/airdrop/AirdropModal.svelte, src/frontend/src/lib/components/airdrop/AirdropWorker.svelte, src/frontend/src/lib/constants/app.constants.ts, src/frontend/src/lib/types/post-message.ts, src/frontend/src/lib/utils/actor.utils.ts, src/frontend/src/lib/utils/airdrop.utils.ts, src/frontend/src/lib/workers/auth.worker.ts, src/frontend/src/lib/workers/code.worker.ts, src/frontend/src/routes/(app)/+layout.svelte
Every 10sec get the airdrop code
=> feat(frontend): periodically refresh the airdrop code

.env.example, src/frontend/src/lib/components/airdrop/AirdropCompleted.svelte, src/frontend/src/lib/components/airdrop/AirdropModal.svelte, src/frontend/src/lib/components/airdrop/AirdropOngoing.svelte, src/frontend/src/lib/components/ui/InProgress.svelte, src/frontend/src/lib/components/ui/StaticSteps.svelte, src/frontend/src/lib/constants/airdrop.constants.ts, src/frontend/src/lib/types/steps.ts, src/frontend/src/lib/utils/airdrop.utils.ts
=> feat(frontend): display status as readonly once airdrop completed

src/frontend/src/lib/components/wallet-connect/WalletConnectReview.svelte, src/frontend/src/lib/components/wallet-connect/WalletConnectSession.svelte
With Uniswap noticed that this sometimes happens.
=> feat(frontend): add a cancel button if WalletConnection proposal get stuck

src/frontend/src/lib/utils/nav.utils.ts
=> fix(frontend): url to transactions was invalid when landing on the page dedicated to WalletConnect URI login

src/frontend/src/lib/api/backend.api.ts
Way better for the DX, that way one can click on the function in the IDE to access directly the definition.
=> refactor(frontend): destruct actor

src/frontend/src/lib/components/tokens/AddTokenReview.svelte, src/frontend/src/lib/components/ui/Warning.svelte
=> feat(frontend): enhance warning text to add token and link to metamask

package-lock.json, package.json
Let's just tag a release for the state of the art.
=> build: bump v0.0.2

src/frontend/src/lib/components/hero/Balance.svelte
=> style(frontend): font-bold for balance

src/frontend/src/lib/services/worker.exchange.services.ts, src/frontend/src/lib/types/post-message.ts, src/frontend/src/lib/workers/exchange.worker.ts
=> feat: display a toast if there is an error while fetching the exchange usd<>eth

src/frontend/src/lib/components/tokens/AddTokenModal.svelte, src/frontend/src/lib/components/tokens/TokensSkeletons.svelte, src/frontend/src/lib/constants/erc20.constants.ts, src/frontend/src/lib/providers/infura-erc20.providers.ts, src/frontend/src/lib/services/erc20.services.ts, src/frontend/src/lib/services/exchange.services.ts, src/frontend/src/lib/types/coingecko.ts, src/frontend/src/lib/types/erc20.ts, src/frontend/src/lib/types/exchange.ts, src/frontend/src/lib/types/post-message.ts, src/frontend/src/lib/utils/erc20.utils.ts, src/frontend/src/lib/workers/exchange.worker.ts
Display value instead of $- because exchange does not know the contract.
=> feat: use ICP usd exchange for ICP on ETH

src/frontend/src/lib/components/networks/Network.svelte, src/frontend/src/lib/utils/nav.utils.ts, src/frontend/src/lib/utils/network.utils.ts, src/frontend/src/routes/(app)/transactions/+page.svelte
=> feat: use goto to switchNetwork

src/frontend/src/lib/styles/global/variables.scss
=> style: fix base z-index for gix-cmp

src/frontend/src/eth/components/fee/FeeDisplay.svelte, src/frontend/src/eth/components/send/SendAmount.svelte, src/frontend/src/eth/components/send/SendForm.svelte, src/frontend/src/eth/utils/fee.utils.ts
=> feat: check for insufficient funds for gas on eth amount input

src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/routes/(app)/+layout.svelte
=> style: hero background according network

src/frontend/src/lib/components/receive/Receive.svelte, src/frontend/src/lib/components/ui/Busy.svelte, src/frontend/src/lib/stores/busy.store.ts
=> feat: receive button enabled but use a guard to open action

src/frontend/src/eth/receive/ReceiveModal.svelte, src/frontend/src/eth/receive/ReceiveQRCode.svelte, src/frontend/src/lib/derived/network.derived.ts
Receive modal for IC will be implemented afterwards.
=> feat: remove network address derived

src/frontend/src/eth/receive/ReceiveModal.svelte, src/frontend/src/eth/receive/ReceiveQRCode.svelte, src/frontend/src/lib/derived/network.derived.ts
=> Revert "feat: remove network address derived"

src/frontend/src/eth/components/transactions/Transactions.svelte, src/frontend/src/icp/components/receive/ReceiveBitcoin.svelte, src/frontend/src/icp/components/transactions/IcTransactions.svelte, src/frontend/src/routes/(app)/transactions/+page.svelte
That way we can add the "Receive BTC" actions on token ckBTC.
=> feat: duplicate transactions title per network and add slot

src/frontend/src/icp/components/transactions/IcTransactionModal.svelte, src/frontend/src/icp/components/transactions/IcTransactions.svelte, src/frontend/src/icp/derived/ckbtc-transactions.derived.ts, src/frontend/src/icp/derived/ic-transactions.derived.ts, src/frontend/src/icp/services/ckbtc-listener.services.ts, src/frontend/src/icp/stores/ckbtc.store.ts, src/frontend/src/icp/types/ic.ts, src/frontend/src/icp/utils/ckbtc-transactions.utils.ts
Even more mumbo jumbo for ckBTC...
=> feat: display ckBTC pending utxos as transactions

src/frontend/src/icp/constants/ckbtc.constants.ts
The process is so sloooow that it almost takes a minute so make no sense to refresh every minute.
=> feat: update balancer timer set to 5min

src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/constants/networks.constants.ts
=> feat: enable support for ICP, ckBTC and ckETH on production

src/frontend/src/eth/components/send/SendTokenModal.svelte, src/frontend/src/icp/components/convert/HowToConvertETHModal.svelte, src/frontend/src/icp/components/receive/IcReceiveCkETHModal.svelte, src/frontend/src/icp/components/send/IcSendModal.svelte, src/frontend/src/lib/utils/modal.utils.ts
=> fix: close wizard modal UI glitch

src/frontend/static/manifest.webmanifest
Read this blog post yesterday evening: https://webkit.org/blog/15063/webkit-features-in-safari-17-4/
=> feat: add a categories to manifest

HACKING.md, README.md
Correct typos as provided in PR #896 by @omahs
=> docs: typos

package-lock.json, package.json
=> build: bump alchemy-sdk to inherit follow-redirects update

src/frontend/src/eth/services/metamask.services.ts
> MetaMask - RPC Error: Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'
=> fix: switch metamask chain id

src/frontend/src/eth/components/send/SendReview.svelte, src/frontend/src/eth/components/send/SendReviewNetwork.svelte, src/frontend/src/eth/components/send/SendTokenWizard.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSend.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendModal.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendReview.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
One might initiate a Sepolia transaction from Uniswap while Oisy is currently on ETH network.
=> feat: network resolution for wallet connect

Dockerfile, docker/bootstrap, docker/build
Similar to Internet Identity and Juno.
=> build: docker build for backend

.gitignore, scripts/test.backend.sh, src/backend/tests/upgrade_test.rs, src/backend/tests/utils.rs
I've got "upgrade trust issue" 😉.
=> test: upgrade backend

src/backend/tests/it/main.rs, src/backend/tests/it/sign.rs, src/backend/tests/it/token.rs, src/backend/tests/it/upgrade.rs, src/backend/tests/it/utils/mock.rs
I opened a TODO task to improve test with meaningful data.
=> test: sign transaction

package-lock.json, package.json
It can be upgraded as #1033 is resolved.
=> build: bump walletconnect

.github/workflows/update-sns-tokens.yml
> If no paths are specified, all new and modified files are added.
=> build: fix commit add and check

src/frontend/src/lib/styles/global/gix.scss
So let's use a small value (previously 460px)
=> style: fit-content makes opening modal a bit glitchy

src/frontend/src/icp/components/tokens/IcManageTokenToggle.svelte
Toggle looked disabled but, was enabled underneath.
=> feat: disable toggle in manage token

src/frontend/src/lib/constants/analytics.contants.ts, src/frontend/src/lib/services/analytics.services.ts, src/frontend/src/lib/services/auth.services.ts, src/frontend/src/routes/+layout.svelte
Anonyoums and count only.
e.g. "how many times sign-in was successful today?"
=> feat: track few anonymous events about auth in analytics

src/frontend/src/eth/components/send/SendTokenWizard.svelte, src/frontend/src/eth/services/wallet-connect.services.ts, src/frontend/src/icp/components/send/IcSendModal.svelte, src/frontend/src/lib/constants/analytics.contants.ts
Anonyoums and count only.
e.g. "how many times send icp was successful today?"
=> feat: track anonymous transfer count in analytics

src/frontend/src/app.d.ts, src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte, src/frontend/src/icp-eth/services/eth.services.ts, src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts, src/frontend/src/icp/components/receive/IcReceiveEthereum.svelte, src/frontend/src/icp/components/transactions/IcTransactionsCkEthereumListeners.svelte, src/frontend/src/icp/derived/cketh-transactions.derived.ts, src/frontend/src/icp/stores/ic-pending-transactions.store.ts
Not functional but, it introduces and refactor functions in the right direction. I'll follow up with other PR(s).
=> feat: display pending erc20 -> ckErc20 (init)

src/frontend/src/env/tokens.btc.env.ts, src/frontend/src/icp/components/tokens/IcTokenModal.svelte
Revert https://github.com/dfinity/oisy-wallet/pull/1246 and just fix Bitcoin twin token logo
=> fix: twin token bitcoin logo

.github/workflows/update-rust.yml
Copied from II. Added manual workflow to start it once merge.
=> build: GH to provide Rust update

.github/pull_request_template.md
Provide a template for PRs. Similar to what we do in other repo.
=> chore: template for PRs

package-lock.json, package.json
There is a breaking changes in last release of Juno (v0.0.30).
=> build: bump Juno analytics lib

src/frontend/src/lib/components/common/MaxButton.svelte, src/frontend/src/lib/components/send/SendInputAmount.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/components/send/SendInputAmount.spec.ts, src/frontend/src/tests/mocks/i18n.mock.ts
Introduce a central `SendInputAmount` component for enhanced reuse and feature integration, such as the "Max" button functionality.
- Created the `SendInputAmount` component.
- Created the `MaxButton` sub-component.
- Created unittest for `SendInputAmount`.
The test `SendInputAmount.spec.ts` was run successfully.
=> feat: created custom component SendInputAmount that has an optional Max button

src/frontend/src/eth/components/send/ConvertToCkERC20.svelte, src/frontend/src/eth/components/send/ConvertToCkETH.svelte, src/frontend/src/icp-eth/components/send/ConvertETH.svelte, src/frontend/src/icp/components/convert/ConvertToEthereum.svelte, src/frontend/src/icp/components/info/InfoEthereum.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
Resolves a TODO.
- Rename ckEth <> Eth used by both Eth and Erc20 modals' events and derived values.
=> refactor: rename modal events and derived values

src/frontend/src/eth/components/fee/FeeDisplay.svelte
The UI feels a bit smoother by animating the in and out.
=> style: smooth the maximum fee animation

src/frontend/src/env/tokens.ckerc20.json
Modifications have been made to the list of ckErc20 tokens deployed by the Orchestrator.
=> build: Update ckErc20 Tokens

package-lock.json, package.json
=> chore: set next version for release

src/frontend/src/lib/types/qr-code.ts, src/frontend/src/lib/utils/qr-code.utils.ts, src/frontend/src/tests/lib/utils/qr-code.utils.spec.ts, src/frontend/src/tests/mocks/tokens.mock.ts
As first step to creating the QR code modal, we need to set up a function that decode a possible correct QR code and manages each case.
- New `decodeQrCode` function in utils that checks for possible errors and token compatibility.
- Tests of such function that include the creation of a mock Token object.
Test `qr-code.utils.spec.ts` was correctly completed.
**Note**: we mock the return of third-party function `decodePayment` of library [@dfinity/ledger-icrc](https://github.com/dfinity/ic-js/tree/main/packages/ledger-icrc), since the testing of such function is already done there.
=> feat: created utility function to decode QR code

package-lock.json, package.json
Release a version with the USDC $ fix and the improvements of the fees for ckUSDC.
=> chore: next release

src/frontend/src/env/networks.ircrc.env.ts, src/frontend/src/env/tokens.erc20.env.ts, src/frontend/src/env/tokens.usdc.env.ts
- extract USDC env information to separate module
=> refactor: extract USDC env

src/frontend/src/env/networks.ircrc.env.ts, src/frontend/src/icp/types/env-token-ckerc20.ts
There will be more ckErc20 tokens to set up. While we cannot make the process fully automated, this PR introduces a mapper which can help avoid some code duplication when we add new tokens.
=> feat: map ckErc20 tokens env

src/frontend/src/lib/derived/tokens.derived.ts
Review tokens order as currently in production.
- Eth
- ICP
- Bitcoin (new)
- Erc20
- Icrc
=> feat: tokens order

package-lock.json
=> build: bump ws

src/frontend/src/lib/stores/token.store.ts
Sorry forgot to add the `TODO` before merge. Good idea!
=> docs: token store todo

src/frontend/src/lib/components/tokens/Tokens.svelte, src/frontend/src/lib/components/ui/Card.svelte, src/frontend/src/lib/components/ui/CardAmount.svelte
=> feat: align vertically amount in tokens list

src/frontend/src/lib/components/tokens/TokenReceiveSend.svelte
=> style: align send button in list of tokens

src/frontend/src/icp/components/fee/EthereumFeeContext.svelte, src/frontend/src/icp/components/receive/IcReceiveCkBTC.svelte
Cleanup an empty comment and a cast not needed.
=> chore: no dev (cleanup)

src/frontend/src/icp-eth/assets/chainlink.svg
We were asked to use the same logo for LINK as ckLINK.
=> feat: update LINK logo with same asset as ckLINK

src/frontend/src/lib/components/tokens/TokensMenu.svelte
The item in the overflow menu is now the same for all the networks.
Removed IF statement from the tokens menu.
=> feat: removed conditional network-related choice for the managing modal

src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte, src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte, src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte
First round of reviewing spacing in manage tokens modal.
=> style: manage tokens first round of spacing

src/frontend/src/eth/components/tokens/AddTokenForm.svelte, src/frontend/src/icp-eth/components/tokens/AddTokenByNetwork.svelte, src/frontend/src/icp-eth/components/tokens/AddTokenByNetworkToolbar.svelte, src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte
This PR reduce the duplication of the form which per extension also fixes the spacing between the form and the buttons. It also improves the spacing and removes the duplication of the call to actions (toolbar).
=> feat: add token modal common form and spacing

src/frontend/src/icp/components/fee/IcTokenFee.svelte, src/frontend/src/icp/components/receive/IcReceiveWalletAddress.svelte, src/frontend/src/icp/components/transactions/IcTransactionModal.svelte, src/frontend/src/lib/components/core/Modals.svelte, src/frontend/src/lib/components/tokens/AddTokenWarning.svelte, src/frontend/src/lib/components/tokens/Token.svelte
Fix probable Webstorm auto-import issues.
=> chore: remove .js in imports

src/frontend/src/lib/i18n/en.json
"Manage tokens" and "Select the network" are used in the Figma design for manage tokens feature.
=> feat: align text to Figma design

src/frontend/src/lib/components/tokens/HideTokenReview.svelte, src/frontend/src/lib/i18n/en.json
Adding custom token is always through the same cta now.
=> feat: simplify i18n key

package.json
I'm use to run `npm run clippy` in my projects so it's handy to have the shorthand here as well ;)
=> chore: npm run clippy

.github/workflows/frontend-checks.yml
We have `backend-tests` and `frontend-tests` so it makes sense to be consistent.
=> refactor: rename frontend checks action

src/frontend/src/lib/derived/tokens.derived.ts
Product want ICP token to be listed first on Chain Fusion and generally speaking.
=> feat: icp token first in list

src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte
The list of tokens displayed in the "Manage tokens" modal was not correct anymore due to all the changes that have been developed this week.
=> fix: list tokens in manage tokens modal

src/frontend/src/eth/services/erc20.services.ts, src/frontend/src/lib/components/core/Loader.svelte
Rename the loader functions for consistency reason.
=> refactor: rename erc20 load functions

src/frontend/src/env/tokens.erc20.env.ts, src/frontend/src/eth/derived/erc20.derived.ts, src/frontend/src/eth/services/erc20.services.ts
Product want to allow users to disable default tokens. Therefore we have to compare default and user tokens when we derive those to figure out which tokens are enabled and which are disabled while avoiding duplication.
=> feat: derive ERC20 tokens with user disabled tokens

src/frontend/src/eth/components/tokens/TokenMenu.svelte, src/frontend/src/eth/components/transactions/TransactionsSkeletons.svelte, src/frontend/src/eth/derived/erc20.derived.ts, src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/components/hero/Balance.svelte, src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/lib/components/tokens/TokenMenu.svelte, src/frontend/src/lib/components/tokens/TokensMenu.svelte, src/frontend/src/lib/components/tokens/TokensSkeletons.svelte
There was some changes in the naming of the stores, renaming the derived stores for the initialization for erc20 follow those changes.
=> refactor: rename init erc20 user derive stores

src/frontend/src/env/networks.icrc.env.ts, src/frontend/src/env/tokens.pepe.env.ts
ckPEPE proposal has been adopted on mainnet.
=> feat: integrate ckPEPE

src/frontend/src/eth/derived/erc20.derived.ts
There was a typo in the comment.
=> docs: review comment

src/frontend/src/eth/services/erc20.services.ts, src/frontend/src/eth/types/erc20-token-toggleable.ts, src/frontend/src/eth/utils/erc20.utils.ts, src/frontend/src/lib/types/token-toggleable.ts
We will need the same "toggleable" type for Icrc.
=> feat: extract a generic token toggleable type

src/frontend/src/eth/derived/erc20.derived.ts
Few erc20 derived stores do not need to be exposed globally.
=> feat: review erc20 derived stores export

src/frontend/src/eth/derived/erc20.derived.ts, src/frontend/src/lib/utils/token.utils.ts
We gonna need similar mapping for icrc.
=> feat: extract toggleable token mapper function

src/frontend/src/icp/derived/icrc.derived.ts, src/frontend/src/lib/derived/tokens.derived.ts
Follow-up #1615 and rename also sorted enabled icrc tokens.
=> refactor: rename sorted icrc tokens

src/frontend/src/icp-eth/components/tokens/ManageTokens.svelte, src/frontend/src/icp/derived/icrc.derived.ts, src/frontend/src/icp/services/icrc-custom-tokens.services.ts
Product want to allow user to disable or enable any Icrc tokens including those default provided by Oisy.
=> feat: enabled and disable all icrc tokens

src/frontend/src/eth/components/send/SendReviewNetwork.svelte, src/frontend/src/icp/components/send/IcReviewNetwork.svelte, src/frontend/src/lib/components/networks/NetworkButton.svelte, src/frontend/src/lib/components/ui/TextWithLogo.svelte
Useful to display network information as we display the logo next to it.
=> feat: component to display text and logo

src/frontend/src/icp/components/tokens/IcManageTokenToggle.svelte
Product want default icrc to be toggleable. The dapp has been adapted but the UI component, the toggle, still needed to be made editable.
=> feat: default icrc token toggleable

package-lock.json, package.json, src/frontend/src/lib/styles/global/gix.scss
Update next version of gix-cmp.
- Bump dependency.
- Update CSS to match renamed CSS variables.
=> feat: upgrade gix-cmp

src/frontend/src/eth/components/receive/EthReceive.svelte, src/frontend/src/icp/components/receive/IcReceiveICP.svelte, src/frontend/src/lib/stores/modal.store.ts
Follow-up of #1634. I should have renamed the function as well which I do in this PR.
=> refactor: rename open receive eth modal

src/frontend/src/eth/components/receive/EthReceive.svelte, src/frontend/src/lib/derived/modal.derived.ts
It's embarassing....follow-up of follow-up of #1635. I should have renamed the derived store as well.
=> refactor: rename open receive eth modal derived store

src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/lib/components/receive/Receive.svelte, src/frontend/src/lib/components/receive/ReceiveActions.svelte, src/frontend/src/lib/components/receive/ReceiveAddress.svelte, src/frontend/src/lib/components/receive/ReceiveAddressWithLogo.svelte, src/frontend/src/lib/components/receive/ReceiveAddresses.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/stores/modal.store.ts, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/routes/(app)/+layout.svelte
Product want to redo the call to action "Receive" on Chain Fusion and display a particular list of addresses for that pseudo network.
=> feat: receive information on chain fusion

package-lock.json, package.json, src/frontend/src/icp/api/cketh-minter.api.ts
A type was not exposed in `@dfinity/cketh`. This is now solved.
=> chore: import exposed type of cketh lib

src/frontend/src/icp/components/transactions/IcTransaction.svelte, src/frontend/src/lib/components/tokens/Token.svelte
It's probably a side effect of having updated Tailwind recently.
=> style(frontend): fix missing first-letter capitalize

src/frontend/src/app.d.ts, src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/core/WalletAddresses.svelte, src/frontend/src/lib/components/receive/Receive.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Artem want to add a call to action "Your addresses" in the menu that has to be displayed if pseudo network Chain Fusion is selected and which open the "Receive" modal that presents the various addresses (cross-network).
=> feat(frontend): "your addresses" cta

.github/actions/docker-build-e2e/action.yml
Fix https://github.com/dfinity/oisy-wallet/actions/runs/9763172478/job/26948399245
=> fix(ci): save docker image

.github/workflows/e2e-tests.yml
Just to make it clear it uses the Docker image for E2E.
=> chore(ci): add some prefix in labels

.github/actions/docker-build-e2e/action.yml
I missed few prefix in my last PR.
=> chore(ci): add some more prefix in labels

.github/workflows/e2e-tests.yml
Almost there, now run the e2e tests in CI and save output in case of failure.
=> chore(ci): run e2e

src/frontend/src/lib/components/tokens/TokenReceiveSend.svelte, src/frontend/src/lib/components/tokens/Tokens.svelte, src/frontend/src/lib/components/ui/Card.svelte
Review the "Token" card for mobile. Better spacing and a bit less line height for the title of the token.
=> style(frontend): token card review for mobile

src/frontend/src/env/tokens.sns.json
Modifications have been made to the icons and metadata of the Icrc tokens known to the Sns-Aggregator.
=> feat(frontend): Update Sns Tokens

package-lock.json, package.json
We want to release next version.
=> chore(release): bump version number

package-lock.json, package.json
Bump version number for release.
=> chore(frontend): release

src/frontend/src/env/tokens.ckerc20.json
Modifications have been made to the list of ckErc20 tokens deployed by the Orchestrator.
=> feat(frontend): Update ckErc20 Tokens

src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/hero/Balance.svelte, src/frontend/src/lib/components/hero/HeroSignIn.svelte
A bit smaller titles in the hero as discussed with Artem.
=> style(frontend): hero title size

src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/lib/styles/global/button.scss
A bit more padding at the bottom of the hero as discussed with Artem.
=> style(frontend): hero padding bottom

src/frontend/src/lib/components/hero/Hero.svelte
=> style(frontend): fix text overflow over button in header

src/frontend/src/env/tokens-erc20/tokens.shib.env.ts, src/frontend/src/env/tokens.erc20.env.ts
Since `ckSHIB` was approved in production, we add Shiba Inu token (mainnet) to the list.
=> feat(frontend): add Ethereum Mainnet Shiba Inu token

package-lock.json, package.json
=> chore(release): next version

src/frontend/src/lib/components/hero/About.svelte, src/frontend/src/lib/components/hero/AboutModal.svelte, src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/stores/modal.store.ts, src/frontend/src/lib/types/i18n.d.ts
We were asked to add some "About" information within Oisy.
- Make existing info text become a button
- Add new modal type
- Implement modal (static text only)
=> feat(frontend): about Oisy

package.json
- Set engine >= Node LTS in packages.json
=> chore(dev): require Node LTS

.gitignore, src/backend/backend.did, src/backend/src/lib.rs, src/backend/tests/it/user_profile.rs, src/shared/src/types.rs
We want Oisy to become a relying party and store credentials for users.
In this PR, I introduce the new endpoints needed for the new functionality along with the new Rust and Candid types.
* Add endpoints and types to candid interface.
* Add endpoints to the backend returning mock data.
* Add types to the types file.
No new functionality was added yet. Therefore, no new tests were a
=> feat(backend): Add types to Rust and Candid

src/frontend/src/env/networks.icrc.env.ts
=> fix(frontend): missing ckWBTC

src/backend/backend.did, src/shared/src/types.rs
There are issues in the candid file. Fix them
* Add `record` in new candid types.
* Rename struct UserProfileStorage to StoredUserProfile.
Not necessary.
=> refactor(backend): Fix Candid file

src/backend/backend.did, src/shared/src/types.rs
Rewards canister will also need the updated timestamp for each user.
* Add "updated_timestamp" to OisyUser.
* Add new field in candid file.
Not necessary.
=> feat(backend): Add updated_timestamp to OisyUser

src/frontend/src/lib/components/icons/OisyWalletLogo.svelte
=> style(frontend): update main logo

src/frontend/src/lib/components/hero/Hero.svelte
Update banner background using an ellipse element:
=> style(frontend): change banner background

src/frontend/src/lib/components/tokens/Tokens.svelte
While the user in logged out we blur the token list:
=> style(frontend): blur token list when is logged out

src/frontend/src/lib/components/hero/Header.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
We want to include the subtitle "NEVER DOWNLOAD AN APP" under the Oisy logo when the user is not logged in.
**It will not be shown in the mobile version.**
The objective is:
P.S. it is a little too close to the "Alpha" warning, but since this new branch implies the removal of such a warning, I will ignore it.
=> style(frontend): add subtitle to Oisy logo when logged out

package-lock.json, package.json
We have released gix-cmp so we can include this version instead of a pinned next version.
=> build(frontend): update gix component

src/frontend/src/lib/components/core/Menu.svelte
New style for `Menu` button using `ButtonHero` component.
=> style(frontend): change style of Menu button to use ButtonHero

src/frontend/src/lib/styles/global/button.scss
I forgot to remove the border from primary buttons.
=> style(frontend): remove border from primary buttons

src/frontend/src/lib/styles/global/button.scss
The CSS class `user` is deprecated.
=> chore(frontend): remove class 'user' that is deprecated

scripts/build.utils.mjs, scripts/check.unused.mjs, scripts/check.unused.sh, scripts/utils.mjs
The new script will check for unused `svelte` components (excluding `/routes` folder).
=> feat(ci): script to check unused components

src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/components/icons/IconArrowAstronaut.svelte, src/frontend/src/lib/components/ui/ButtonAuthenticate.svelte, src/frontend/src/lib/styles/global/colors.scss, tailwind.config.js
New authenticate button with animated icon:
https://github.com/user-attachments/assets/51a921f1-d0d5-4ea8-90cc-cb53af06ea8d
=> feat(frontend): new authenticate button with animation

src/frontend/src/eth/components/wallet-connect/WalletConnectForm.svelte, src/frontend/src/lib/components/core/MenuWallet.svelte, src/frontend/src/lib/constants/analytics.contants.ts
Collect few anonymous (count) metrics to get to know if user connect WalletConnect "manually" in the UI.
=> feat(frontend): WalletConnect anonymous connect count

src/frontend/src/lib/derived/network-tokens.derived.ts
Removing sorting function from network tokens store.
=> fix(frontend): remove sorting function from global store

src/frontend/src/eth/components/tokens/HideTokenModal.svelte, src/frontend/src/eth/services/balance.services.ts, src/frontend/src/eth/services/erc20-user-tokens-services.ts, src/frontend/src/eth/services/erc20.services.ts, src/frontend/src/icp-eth/services/user-token.services.ts
Add the TODOS we have to resolve to reduce the numbers of calls to Infura.
- Add few `TODO(GIX-2740)` (Jira task number).
=> chore(frontend): add todos to cache ERC20 metadata

src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/lib/components/hero/HeroContent.svelte, src/frontend/src/routes/(app)/+layout.svelte
Removing deprecated `send` prop from `Actions` component.
=> chore(frontend): remove deprecated 'send' prop from Actions

src/frontend/src/lib/i18n/en.json
Updated title in header when logged out
=> refactor(frontend): update header title

src/frontend/src/eth/components/wallet-connect/WalletConnectForm.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Change WalletConnect text for the URI link.
=> refactor(frontend): change WalletConnect key for uri

src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
We include the links to the Oisy Roadmap and the Issue report into the `Menu` component. Furthermore, we re-arrange the order so that the source code is after the new items.
=> feat(frontend): include roadmap and ticket report in Menu

package-lock.json, package.json
We want to release the next version after having merged:
- PR #1799
=> chore(frontend): next version

src/frontend/src/env/tokens.env.ts, src/frontend/src/eth/types/erc20.ts, src/frontend/src/lib/types/token.ts, src/frontend/src/lib/types/utils.ts
Create utility function `RequiredExcept` to be used for required tokens that still retain the state of specific props..
=> refactor(frontend): create RequiredExcept function for types

scripts/deploy.sh
Added 2 missing dfx command so the deploy.sh script works locally and in e2e tests CI.
=> build(deploy): update deploy script with missing dfx commands

src/frontend/src/lib/types/idb.ts
I forgot to push the last commit before merging from PR #2034 referring to the [last modification](https://github.com/dfinity/oisy-wallet/pull/2034#discussion_r1720038318).
=> feat(frontend): IDB functions for Bitcoin address PR #2034 - missing commit

src/frontend/src/env/networks.icrc.env.ts, src/frontend/src/env/tokens-erc20/tokens.eurc.env.ts, src/frontend/src/env/tokens.erc20.env.ts
Intregrate ckEURC that was executed on mainnet.
- run `./scripts/add.tokens.erc20.sh`
- add new token to `networks.icrc.env` and `tokens.erc20.env`
=> feat(frontend): add support for ckEURC

.github/dependabot.yml
We would like to automatically bump the Cargo dependencies weekly.
=> feat(ci): add dependabot for Cargo

src/frontend/src/lib/services/auth.services.ts
Similar to ETH, we create functions to clean the BTC IDB storage.
=> feat(frontend): add BTC IDB cleaning function

src/frontend/src/eth/components/send/ConvertToCkERC20.svelte, src/frontend/src/eth/components/send/ConvertToCkETH.svelte, src/frontend/src/icp/components/convert/ConvertToBTC.svelte, src/frontend/src/icp/components/convert/ConvertToEthereum.svelte, src/frontend/src/lib/components/icons/IconBurn.svelte, src/frontend/src/lib/components/icons/IconConvert.svelte
=> style(frontend): change conversion icon

HACKING.md
Add a bitcoin faucets to the list of faucets.
=> docs(hacking): list bitcoin faucets

src/frontend/src/lib/components/pages/SettingsVersion.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Follow-up of #2084. We want to link the displayed version with the release notes.
=> feat(frontend): link version with release

src/frontend/src/icp-eth/services/eth.services.ts
Reverts dfinity/oisy-wallet#2069
It causes an issue:
=> fix(frontend): revert PR #2069

HACKING.md
Add LINK faucet to the list of, well, faucets.
=> docs(hacking): list link faucet

src/frontend/src/icp/components/info/InfoBitcoin.svelte, src/frontend/src/icp/components/info/InfoEthereum.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
As per requested we update the texts of the info boxes for ck-conversions.
=> refactor(frontend): update info box for ck-conversions

src/frontend/src/lib/components/core/Loader.svelte, src/frontend/src/lib/enums/progress-steps.ts, src/frontend/src/lib/i18n/en.json
Generic text when loading addresses from backend.
=> refactor(frontend): generalize text when loading addresses from backend

src/frontend/src/lib/i18n/en.json
Request to change the message.
=> style(frontend): change ERC20 ck conversion message

src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
Just for consistency, the name of the variable is corrected.
=> refactor(frontend): rename ckErc20 variable

e2e/about-how-modal.spec.ts, e2e/about-what-modal.spec.ts, e2e/utils/constants/e2e.constants.ts
Make the renamed const re-usable for all modals.
=> refactor(e2e): rename modal viewport width const

e2e/about-how-modal.spec.ts, e2e/about-what-modal.spec.ts, e2e/utils/pages/homepage.page.ts
1. Add re-usable helper methods to Homepage parent class.
2. Make the way viewport is set more general.
3. Add possibility to hide some locators before taking modal snapshot.
=> test(e2e): add additional functionality to Homepage class

src/frontend/src/lib/components/send/SendTokensList.svelte
In component `SendTokensList` we use the `balance` prop of `TokenUi` introduced in PR #2150.
=> refactor(frontend): use balance prop in send tokens list

e2e/about-how-modal.spec.ts, e2e/about-what-modal.spec.ts
Fix issue with viewportSize setting in both About modals.
=> test(e2e): fix issue with about modals

src/frontend/src/icp/components/fee/EthereumFeeContext.svelte
Just to simplify the code, we invert the condition in `updateContext` function of `EthereumFeeContext` component.
=> refactor(frontend): invert update condition in EthereumFeeContext

src/frontend/src/lib/i18n/en.json
We change the main header title when signed out.
=> style(frontend): update header title string

src/frontend/src/eth/components/send/EthSend.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectButton.svelte, src/frontend/src/icp-eth/components/send/ConvertETH.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/derived/address.derived.ts
We rename the derived store specific for ETH address not loaded.
=> refactor(frontend): rename ETH address store

.eslintrc.cjs, scripts/add.tokens.erc20.mjs, scripts/utils.mjs, src/frontend/src/lib/components/icons/IconRandom.svelte
We include the rule [prefer-template](https://eslint.org/docs/latest/rules/prefer-template) to avoid string concatenations,  and we fix issues found.
=> feat(lint): add rule prefer-template

src/frontend/src/lib/components/guard/AddressGuard.svelte, src/frontend/src/lib/services/address.services.ts
We include the BTC address verification in the `AddressGuard` component.
=> feat(frontend): add BTC verification to AddressGuard

.eslintrc.cjs, src/frontend/src/eth/components/send/ConvertToCkERC20.svelte, src/frontend/src/eth/components/send/ConvertToCkETH.svelte, src/frontend/src/eth/components/send/EthSend.svelte, src/frontend/src/eth/components/send/EthSendTokenModal.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/eth/components/send/SendAmount.svelte, src/frontend/src/eth/components/send/SendDestination.svelte, src/frontend/src/eth/components/send/SendForm.svelte, src/frontend/src/eth/components/send/SendInfo.svelte, src/frontend/src/eth/components/send/SendNetwork.svelte, src/frontend/src/eth/components/send/SendNetworkICP.svelte, src/frontend/src/eth/components/send/SendReview.svelte, src/frontend/src/eth/components/send/SendReviewNetwork.svelte, src/frontend/src/eth/components/send/SendTokenContext.svelte
=> feat(lint): sort svelte imports

src/frontend/src/lib/utils/tokens.utils.ts, src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
The idea is to re-use code needed to calculate token USD balance.
=> feat(tokens): re-use code needed to calculate token USD balance

src/frontend/src/lib/utils/tokens.utils.ts
Improve `sumMainnetTokensUsdBalance` by checking if required data is available before looping through tokens list.
=> feat(tokens): improve sumMainnetTokensUsdBalance

src/frontend/src/lib/derived/tokens.derived.ts, src/frontend/src/lib/types/token-balance.ts, src/frontend/src/lib/types/token.ts, src/frontend/src/lib/utils/tokens.utils.ts, src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
The idea is to create derived stores for tokens total USD balance.
=> feat(tokens): create derived stores for tokens total USD balance

src/frontend/src/lib/utils/tokens.utils.ts
We aim to make util function `pinTokensWithBalanceAtTop` more functional.
=> refactor(frontend): make pinTokensWithBalanceAtTop more functional

src/frontend/src/lib/components/networks/NetworksSwitcher.svelte, src/frontend/src/lib/components/networks/NetworksTestnetsToggle.svelte, src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte, src/frontend/src/lib/components/tokens/TokensZeroBalanceToggle.svelte, src/frontend/src/lib/derived/settings.derived.ts
To avoid repetition of code, we create derived stores for the cached settings.
=> feat(frontend): derived stores for settings

src/frontend/src/lib/utils/exchange.utils.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
There is no need to calculate the USD value if the balance store is nullish.
=> feat(frontend): avoid calculating USD value if no balance store

src/frontend/src/lib/styles/global/gix.scss
Modal style updated as per requirements.
=> style(frontend): update modals style

scripts/send.tokens.sh
The amount of ckSepoliaETH sent by default was very small to be used for testing.
=> test(frontend): increase fake ck Sepolia ETH sent to local replica

src/frontend/src/eth/components/transactions/Transaction.svelte, src/frontend/src/eth/components/transactions/TransactionModal.svelte, src/frontend/src/eth/types/eth-transaction.ts, src/frontend/src/icp/types/ic.ts, src/frontend/src/lib/types/transaction.ts
Created common type for Transaction type.
=> refactor(frontend): create type for Transaction type

dfx.json
A newer version of dfx is available.
- Update the dfx version.
See CI
=> chore(devops): Update dfx to 0.23.0

.eslintrc.cjs, src/frontend/src/icp/schedulers/btc-statuses.scheduler.ts, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/derived/networks.derived.ts
We include the rule [prefer-reduce-type-parameter](https://typescript-eslint.io/rules/prefer-reduce-type-parameter) for `.reduce`,  and we fix issues found.
=> feat(lint): add rule prefer-reduce-type-parameter

src/frontend/src/env/onramper.env.ts
We will start adding features to buy from OnRamper. So, until it is finished, we will use the env flag `VITE_ONRAMPER_ENABLED` to show/hide such feature, for development scopes.
=> feat(frontend): create env flag for OnRamper features

src/frontend/src/eth/components/receive/EthReceiveModal.svelte, src/frontend/src/eth/components/send/SendForm.svelte, src/frontend/src/eth/components/send/SendReview.svelte, src/frontend/src/eth/components/tokens/AddTokenReview.svelte, src/frontend/src/eth/components/tokens/TokenModal.svelte, src/frontend/src/eth/components/transactions/TransactionModal.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectForm.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendReview.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSignReview.svelte, src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte, src/frontend/src/icp/components/receive/IcReceiveInfoCkBTC.svelte, src/frontend/src/icp/components/receive/IcReceiveInfoCkEthereum.svelte, src/frontend/src/icp/components/receive/IcReceiveInfoICP.svelte, src/frontend/src/icp/components/receive/IcReceiveInfoIcrc.svelte, src/frontend/src/icp/components/send/IcSendForm.svelte, src/frontend/src/icp/components/send/IcSendReview.svelte, src/frontend/src/icp/components/tokens/IcTokenModal.svelte, src/frontend/src/icp/components/transactions/IcTransactionModal.svelte, src/frontend/src/lib/components/receive/ReceiveAddresses.svelte, src/frontend/src/lib/components/tokens/HideTokenReview.svelte, src/frontend/src/lib/components/ui/ContentWithButtons.svelte, src/frontend/src/lib/components/ui/ContentWithToolbar.svelte
We create an UI component that organize the content of the modals that have a button at the end, to concentrate the code.
=> feat(frontend): UI component for content with buttons

src/frontend/src/lib/styles/global/button.scss
Button class `token` was not used so we remove it.
=> chore(frontend): remove unused button class

e2e/receive-tokens-modal.spec.ts, e2e/utils/pages/homepage.page.ts, e2e/utils/selectors.utils.ts, src/frontend/src/lib/components/receive/ReceiveActions.svelte, src/frontend/src/lib/components/receive/ReceiveAddressQRCode.svelte, src/frontend/src/lib/constants/test-ids.constants.ts
Test that QR code from the image matches with the addresses we display in the receive-tokens modal.
=> test(e2e): QR code tests for the receive-tokens modal

.prettierrc, package-lock.json, package.json, src/frontend/src/lib/components/common/MaxButton.svelte, src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/info/InfoBox.svelte
The idea is to gradually introduce https://github.com/tailwindlabs/prettier-plugin-tailwindcss into the codebase.
=> feat(lint): sort tailwind classes

src/frontend/src/lib/styles/global/gix.scss
There are some missing fixes that appears only during building, due to the bumped sass (PR #2394 ).
=> fix(frontend): missing fixes after bumping sass

src/frontend/src/lib/components/ui/ButtonSwitcher.svelte
Update color of component `NetworksSwitcher`.
=> style(frontend): change color of NetworksSwitcher [GIX-2980]

src/frontend/src/icp/components/core/IcLoaderWallets.svelte, src/frontend/src/lib/components/core/LoaderWallets.svelte
The idea is to make LoaderWallets component reusable for BTC.
=> feat(frontend): make LoaderWallets component reusable

e2e/utils/pages/homepage.page.ts, src/frontend/src/lib/components/tokens/TokenCard.svelte, src/frontend/src/lib/components/tokens/TokensSkeletons.svelte, src/frontend/src/lib/components/ui/Card.svelte, src/frontend/src/lib/constants/test-ids.constants.ts
After the tokens list implementation changed, we need to adjust the way of how we wait for its initialisation.
=> test(e2e): update waitForTokensInitialization implementation

src/frontend/src/lib/components/core/Back.svelte, src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/components/hero/Header.svelte, src/frontend/src/lib/components/hero/Hero.svelte, src/frontend/src/lib/components/hero/HeroContent.svelte, src/frontend/src/lib/components/tokens/TokenMenu.svelte, src/frontend/src/lib/components/ui/ButtonIcon.svelte, src/frontend/src/lib/styles/global/layout.scss, src/frontend/src/routes/(app)/+layout.svelte
The spacing was a bit odd with the new UI, so we adjust the margins and the padding according to design. Furthermore, we limit the header width to a maximum, to avoid expanding too much on larger screens.
=> style(frontend): adjust spacing in layout

src/frontend/src/lib/api/signer.api.ts, src/frontend/src/lib/canisters/signer.canister.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
Implement a function for getting certified BTC balance. The implementation on the Signer side - https://github.com/dfinity/chain-fusion-signer/blob/0d611dd8e18d2d83a6e8ae1577ba762cc500c081/src/signer/canister/src/lib.rs#L140
=> feat(frontend): add updateBtcBalance function

src/frontend/src/env/networks.env.ts, src/frontend/src/lib/types/network.ts, src/frontend/src/lib/types/onramper.ts
The correct name is `Onramper` and not `OnRamper`.
=> refactor(frontend): write Onramper with correct case

src/frontend/src/icp/api/icp-index.api.ts, src/frontend/src/icp/api/icrc-index-ng.api.ts, src/frontend/src/icp/components/transactions/IcTransactions.svelte, src/frontend/src/icp/constants/ic.constants.ts, src/frontend/src/icp/schedulers/wallet.scheduler.ts, src/frontend/src/lib/constants/app.constants.ts
The idea is to move wallet constants to lib so they can be reused for BTC wallet worker.
=> feat(frontend): move wallet constants to lib

src/frontend/src/icp/utils/ic-send.utils.ts
Implement isNetworkIdBTCTestnet util.
=> feat(frontend): isNetworkIdBTCTestnet util

src/frontend/src/btc/types/btc.ts, src/frontend/src/lib/derived/tokens.derived.ts
Implement enabledBtcTokens derived store.
=> feat(frontend): enabledBtcTokens derived store

package.json, vite.config.ts
There were still remains of three that I forgot to remove with PR #2462 :
- types package
- optimization
=> chore(build): clean three package leftover

src/frontend/src/lib/components/hero/Header.svelte
The header had disabled pointer events (PR #121 ), however it seems like now we can enable again. This even fixes the issue that the Alpha warning was not clickable.
=> feat(frontend): enable pointer events in header

src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts, src/frontend/src/btc/schedulers/wallet.scheduler.ts, src/frontend/src/btc/workers/btc-wallet.worker.ts, src/frontend/src/lib/types/post-message.ts
PR with the BTC wallet scheduler and worker. Services will be merged separately.
=> feat(frontend): BTC wallet scheduler + worker

src/frontend/src/btc/services/btc-listener.services.ts, src/frontend/src/btc/services/worker.btc-wallet.services.ts, src/frontend/src/icp/utils/ic-send.utils.ts
The goal is to implement BTC wallet services. Worker and scheduler will be merged in a separate PR. 
In the final PR of this feature, `BtcLoaderWallets` will be added to the list of all loaders.
=> feat(frontend): BTC wallet services

src/frontend/src/lib/styles/global/colors.scss, src/frontend/src/lib/styles/global/theme.scss, tailwind.config.js
New scrollbar style.
https://github.com/user-attachments/assets/87c7491b-c779-49bf-aec7-a4bfee3d656f
https://github.com/user-attachments/assets/343a5994-41ac-4b1b-a95b-86f5f6c2cfbe
=> style(frontend): change scrollbar style [GIX-3019]

src/frontend/src/btc/components/core/BtcLoaderWallets.svelte, src/frontend/src/lib/components/core/Loaders.svelte
The goal of this PR is to initialise BTC wallet workers. Should be merged after https://github.com/dfinity/oisy-wallet/pull/2489.
=> feat(frontend): BTC loader wallets component

.env.example, .env.test, src/frontend/src/lib/rest/blockchain.rest.ts, src/frontend/src/lib/types/blockchain.ts
The goal is to implement service for communicating with Blockchain API. Initially, it will be used for fetching uncertified BTC transactions.
=> feat(frontend): implement service for communicating with Blockchain API

src/frontend/src/lib/rest/blockchain.rest.ts
Remove unnecessary slash from `btcAddressData`.
=> fix(frontend): fix btcAddressData function

src/frontend/src/lib/assets/chain_fusion.svg
New icon for Chain Fusion  inside the network switcher.
=> style(frontend): change icon for Chain Fusion in network switcher [GIX-3015]

src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/i18n/en.json
New header title when the user is not signed in.
=> style(frontend): new header title when signed off [GIX-3015]

src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
=> feat(frontend): add BTC transaction modal to the stores

src/frontend/src/btc/types/btc.ts, src/frontend/src/btc/utils/btc-transactions.utils.ts, src/frontend/src/lib/types/blockchain.ts, src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts, src/frontend/src/tests/mocks/btc.mock.ts
A parser for BTC transactions. It will later extended with additional field: "confirmations".
=> feat(frontend): util for parsing BTC transactions

package-lock.json, package.json
Bumping `gix-components` to next version for PR #2583
=> build(frontend): bump gix-components

src/frontend/src/eth/components/transactions/TransactionStatus.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Create and use "status" transaltion.
=> feat(frontend): create and use "status" translation in txs modals

src/frontend/src/lib/components/transactions/Transaction.svelte
There should an onclick handler in the Transaction component' button.
=> fix(frontend): add missing on:click handler

src/frontend/src/btc/components/core/BtcLoaderWallets.svelte, src/frontend/src/btc/components/core/BtcWalletAddress.svelte, src/frontend/src/btc/components/receive/BtcReceive.svelte, src/frontend/src/btc/components/transactions/BtcTransactionModal.svelte, src/frontend/src/btc/services/worker.btc-wallet.services.ts, src/frontend/src/icp/components/info/Info.svelte, src/frontend/src/icp/services/worker.ckbtc-update-balance.services.ts, src/frontend/src/icp/utils/ic-send.utils.ts, src/frontend/src/lib/utils/network.utils.ts
Just one of the steps to move shared between BTC and IC code to $lib.
=> refactor(frontend): move BTC network utils to lib

src/frontend/src/icp/utils/ic-send.utils.ts, src/frontend/src/lib/utils/send.utils.ts
Implement shared `isInvalidDestinationBtc` util that will be used by both IC and BTC.
=> feat(frontend): implement isInvalidDestinationBtc util

src/frontend/src/btc/components/send/BtcSendDestination.svelte
Implement `BtcSendDestination` that will be used in the BTC-send flow.
=> feat(frontend): BtcSendDestination component

src/frontend/src/btc/components/core/BtcLoaderWallets.svelte, src/frontend/src/icp/components/core/IcLoaderWallets.svelte, src/frontend/src/lib/components/core/LoaderWallets.svelte, src/frontend/src/lib/components/core/Loaders.svelte, src/frontend/src/lib/components/core/WalletWorkers.svelte
Create a core component for all wallet loaders (refactoring that we discussed with David some time ago in one of my PRs).
=> refactor(frontend): core component for all wallet loaders

package-lock.json, package.json
We release `eslint-config-oisy-wallet` v0.0.4.
https://github.com/dfinity/eslint-config-oisy-wallet/releases/tag/v0.0.4
=> build(frontend): bump eslint lib

package-lock.json, package.json
We have new code that we would like to deploy to production.
- Update the package version from 0.0.40 to 0.0.41
No code changes, see CI for any dev-ops issues.
=> chore(devops): Bump release version to 0.0.41

src/frontend/src/app.html
The background should no scroll.
https://github.com/user-attachments/assets/dbf5968f-47c7-497d-b071-cba1214330c5
=> style(frontend): make the background fixed

src/frontend/src/btc/components/send/BtcReviewNetwork.svelte
Implement BtcReviewNetwork component.
=> feat(frontend): BtcReviewNetwork component

src/frontend/src/icp/components/send/IcReviewNetwork.svelte
Refactor IcReviewNetwork component to use the shared `ReviewNetwork`.
=> feat(frontend): refactor IcReviewNetwork component

src/frontend/src/tests/lib/canisters/backend.canister.spec.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts, src/frontend/src/tests/mocks/agents.mock.ts
As noticed by @peterpeterparker, there were some warning thrown inside canister tests. This PR fixes them.
=> test(frontend): Fix canister tests warnings

src/frontend/src/lib/components/send/SendReview.svelte
Implement a shared `SendReview` component.
=> feat(frontend): SendReview component

src/frontend/src/btc/components/send/BtcSendReview.svelte
The next step is to implement `BtcSendReview`.
=> feat(frontend): BtcSendReview component

src/frontend/src/lib/constants/app.constants.ts
The test environment will be treated as Staging.
=> feat(frontend): consider the test environment the same as Staging

src/frontend/src/btc/components/send/BtcSendProgress.svelte, src/frontend/src/lib/enums/progress-steps.ts
The next step is to implement BtcSendProgress component. 
Note: for now, I only used the very basic progress steps, I will update them when creating related services.
=> feat(frontend): implement BtcSendProgress component

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte
Create BtcSendTokenWizard component.
=> feat(frontend): BtcSendTokenWizard component

src/frontend/src/btc/components/send/BtcSendReview.svelte, src/frontend/src/icp/components/send/IcSendReview.svelte
Fix issue with send modal introduced after creating a shared component.
=> fix(frontend): issue with send modal

src/frontend/src/btc/components/send/BtcSendForm.svelte
There was another event missing in BtcSendForm, fixing it.
=> fix(frontend): add missing event to BtcSendForm

src/frontend/src/btc/components/send/BtcSendAmount.svelte
Calculate max BTC amount on send, for now without fees.
=> feat(frontend): calculate max BTC amount on send

src/frontend/src/btc/components/send/BtcSendForm.svelte
We need to disable send BTC button if conditions are not met.
=> feat(frontend): disable send BTC button if conditions are not met

.github/workflows/frontend-deploy-staging.yml
Based on previous workflow, but with fixed envvars
using echo instead of export
=> ci(frontend): workflow-to-auto-deploy-in-environments

src/frontend/src/btc/utils/btc-send.utils.ts, src/frontend/src/tests/btc/utils/btc-send.utils.spec.ts
Since it will be used in a few places (btc-send.services), I makde this small function available as a util.
=> feat(frontend): converNumberToSatoshis util

src/frontend/src/btc/services/btc-send.services.ts, src/frontend/src/btc/types/btc-send.ts
A service to get utxos fee for the provided BTC amount.
=> feat(frontend): btc-send.service - selectUtxosFee

src/frontend/src/lib/canisters/signer.canister.ts, src/frontend/src/lib/canisters/signer.constants.ts, src/frontend/src/tests/lib/canisters/signer.canister.spec.ts
Extract a constant for `P2WPKH` address type.
- Create a constant
- Use it
=> refactor(frontend): P2WPKH constant

src/frontend/src/btc/services/btc-send.services.ts
One more service required to send BTC.
=> feat(frontend): btc-send.service - sendBtc

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/lib/enums/progress-steps.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Use sendBtc service if all conditions are met.
=> feat(frontend): use sendBtc service

src/frontend/src/btc/services/btc-send.services.ts
Fix incorrect @dfinity/utils path that was autocompleted by WebStorm.
=> fix(frontend): incorrect @dfinity/utils path

.github/workflows/frontend-deploy-staging.yml
Just adapting the PROD name to IC
=> refactor(ci): adjust name from PROD to IC

.github/workflows/frontend-deploy-staging.yml
It may happen that we want to force the re-deployment of the backend.
=> feat(ci): add optionality to force backend deployment

src/frontend/src/lib/components/ui/ButtonIcon.svelte
Make `ButtonIcon` always sqaure.
Before:
After:
=> style(frontend): make button icon square

scripts/build.csp.mjs
In PR #2827, I forgot to put the Onramper Frame CSP policy in `frame-src`.
=> fix(build): Put Onramper CSP policy in frames [GIX-3024]

src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
Do not disrupt the whole BTC experience if fetching the transactions fails.
* Wrap getting btc transactions with a try/catch
Not tested.
=> feat(frontend): Load btc balance if tx fetch fails

src/frontend/src/btc/schedulers/btc-wallet.scheduler.ts
Use blockstream API to get latest block height.
=> feat(frontend): use blockstream API to get latest block height

src/frontend/src/lib/components/ui/ExternalLink.svelte
The component `ExternalLink` should be updated with the new color pallets when hovered/active.
=> style(frontend): Update ExtrenalLink hover state color [OISY-62]

src/frontend/src/lib/components/core/Footer.svelte
The transition is not needed for mobile.
=> style(frontend): Transition DFINITY Logo just on middle screens

src/frontend/src/lib/components/core/Footer.svelte
Bigger spacing for the footer.
=> style(frontend): Increase top spacing of footer

package-lock.json, package.json
We would like to make a release.
- Update version to the meaning of life.
=> chore(devops): Update version to 0.0.42

scripts/build.csp.mjs
Missing Onramper prod in the CSP allowed sites.
=> fix(frontend): Enable CSP for Onramper Prod

.github/workflows/deploy-to-environment.yml
The deployment workflow has a faulty run-name and needs caching to reduce runtime
fixed run-name depending on input variables
added caching
=> chore(ci): update deployment workflow

tailwind.config.js
Adding missing `black` color, will be later used in the Carousel indicators component.
=> feat(frontend): new tailwind color

.github/workflows/deploy-to-environment.yml
run-name needs to be executed after the on: block
put run-name after the on: block
=> chore(ci): fixed deployment task

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
i18n keys/types for the Carousel components.
=> feat(frontend): i18n for the Carousel component

src/frontend/src/lib/components/carousel/Indicator.svelte, src/frontend/src/lib/components/carousel/Indicators.svelte
This PR includes Carousel Indicator components. 
https://github.com/user-attachments/assets/5545fc0c-b7ca-4368-a1cc-c4fffb3b3718
=> feat(frontend): Carousel Indicator components

src/frontend/src/lib/components/carousel/Controls.svelte, src/frontend/src/lib/components/ui/ButtonControl.svelte
This PR includes Carousel Controls component.
https://github.com/user-attachments/assets/f5705783-55df-4dfa-b6cb-f784c5f17da5
=> feat(frontend): Carousel Controls components

.github/workflows/deploy-to-environment.yml
We don't need the workflow to deploy to ic, since we do that with orbit. Additionally we set defaults so the run-name will be fixed.
- remove ic related code
- add default choices
=> fix(ci): fix run-name and remove ic

src/frontend/src/lib/components/carousel/Carousel.svelte, src/frontend/src/lib/utils/carousel.utils.ts
This PR includes the main Carousel component. It is based on the Carouse-utils branch, it will be switched to `main` after that PR is merged.
https://github.com/user-attachments/assets/1fd6da41-1da1-4ad4-b6ba-0672942006d6
=> feat(frontend): Carousel component

src/frontend/src/lib/components/carousel/Indicator.svelte, src/frontend/src/lib/components/carousel/Indicators.svelte
We need to update `isActive` logic of the Indicator component to smoothly animate on last-to-first and first-to-last transitions.
=> feat(frontend): update isActive login of Indicator component

src/frontend/src/lib/types/token.ts, src/frontend/src/lib/utils/token-card.utils.ts, src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token-card.utils.spec.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
We remove the props that are not needed from `TokenUiGroup` and we keep only the needed ones.
=> chore(frontend): Remove unused prop of TokenUiGroup

.github/workflows/auto-update-i18n.yml
Fix the issue from the last run 
- removed caching
- removed pull/push on add-and-commit
=> fix(ci): npm i18n adjustments

src/frontend/src/lib/components/carousel/Carousel.svelte
The PR has small styling updates of the Carousel component (mostly, padding values).
=> feat(frontend): update Carousel styling

src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte
This PR includes DappsCarousel components.
https://github.com/user-attachments/assets/3a474efe-4a3b-45c7-895f-02591836f3ed
=> feat(frontend): DappsCarousel components

src/frontend/src/lib/components/carousel/Carousel.svelte, src/frontend/src/lib/components/carousel/Controls.svelte, src/frontend/src/lib/components/carousel/Indicators.svelte, src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte, src/frontend/src/lib/components/ui/SplitPane.svelte, src/frontend/src/routes/(app)/+layout.svelte, tailwind.config.ts
The final approved design:
https://github.com/user-attachments/assets/cb25e5b5-3ef6-47e6-9a24-75b38226d7bd
Approved by Artem ✅
=> feat(frontend): dApps carousel styling adjustments

src/frontend/src/lib/components/send/SendInputAmount.svelte, src/frontend/src/lib/components/ui/InputCurrency.svelte
Similarly to #3143, disable autocomplete for input type currency.
=> feat(frontend): input currency autocomplete off

src/frontend/src/lib/components/core/Loader.svelte, src/frontend/src/lib/components/guard/AddressGuard.svelte, src/frontend/src/lib/components/onramper/OnramperWidget.svelte, src/frontend/src/lib/components/receive/ReceiveAddresses.svelte, src/frontend/src/tests/lib/components/guard/AddressGuard.spec.ts
Remove BTC feature flag from components.
=> feat(frontend): remove BTC flag from components

src/frontend/src/btc/derived/networks.derived.ts, src/frontend/src/btc/derived/tokens.derived.ts, src/frontend/src/lib/services/address.services.ts
Remove BTC feature flag from stores and services.
=> feat(frontend): remove BTC flag from stores and services

README.md
With the release of beta version, we update the status in the README file to make notice that we are almost "ready for production".
=> docs(release): Update status paragraph

src/frontend/src/env/oisy.metadata.json, src/frontend/src/env/types/env-oisy-metadata.ts, src/frontend/src/lib/components/core/Footer.svelte, src/frontend/src/lib/constants/oisy.constants.ts, src/frontend/src/lib/utils/i18n.utils.ts, src/frontend/src/tests/lib/utils/i18n.utils.spec.ts
We update the OISY twitter URL and make it part of the metadata file.
=> chore(frontend): update Twitter URL

src/frontend/src/lib/components/dapps/DappCard.svelte, src/frontend/src/lib/components/dapps/DappModal.svelte, src/frontend/src/lib/components/dapps/DappModalDetails.svelte, src/frontend/src/lib/components/dapps/DappPromoBanner.svelte, src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte, src/frontend/src/lib/components/dapps/DappsExplorerSignedIn.svelte, src/frontend/src/lib/types/dapp-description.ts
Consistency.
- Rename module
- Upper case for schema
- Add toto to move constants which should not find place in types
=> chore(frontend): cleanup dapp description types

src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
A new modal for the BTC <-> ckBTC exchange.
=> feat(frontend): modal for BTC <-> ckBTC exchange

src/frontend/src/lib/components/receive/ReceiveAddress.svelte
Auto-merge #3207 bypassed the lint error.
- Remove unused import.
=> chore(frontend): clean-up unused import

src/frontend/src/env/dapp-descriptions.json
We need to remove the Signer Standart tag from KongSwap.
=> feat(frontend): remove tag from KongSwap dApp

src/frontend/src/lib/i18n/en.json
=> feat(frontend): update landing page text item

package-lock.json, package.json
This PR prepares the release of version v0.9.2.
Last minute small adjustments.
=> chore(release): v0.9.2

src/frontend/src/tests/icp/derived/ckbtc-transactions.derived.spec.ts
Some bare minimum tests for `ckBtcPendingUtxoTransactions`.
=> test(frontend): ckBtcPendingUtxoTransactions

package-lock.json, package.json
This PR prepares the release of version v0.9.3.
=> chore(release): v0.9.3

src/frontend/src/tests/lib/stores/transactions.store.spec.ts
As discussed on- and offline, `transactionsStore.append` should not deduplicate transactions with same ID.
Follow-up of PR: https://github.com/dfinity/oisy-wallet/pull/3300#discussion_r1827906055
- Add a test which duplicate ID
=> test(frontend): should duplicate transactions with same id

src/frontend/src/tests/lib/utils/token-card.utils.spec.ts
I forgot to update the `TokenUiGroup` import for test of `mapHeaderData` util.
=> fix(test): wrong import in test for mapHeaderData

src/frontend/src/tests/icp/derived/ckbtc-transactions.derived.spec.ts, src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts, src/frontend/src/tests/lib/stores/transactions.store.spec.ts, src/frontend/src/tests/mocks/ckbtc.mock.ts, src/frontend/src/tests/utils/ckbtc-stores.test-utils.ts, src/frontend/src/tests/utils/transactions-stores.test-utils.ts
Some bare minimum tests for `icTransactions`.
- Refactor some existing mocks and utils for test to avoid duplicating code.
- Create bare minimum tests.
=> test(frontend): icTransactions store

src/frontend/src/env/tokens-erc20/tokens.eurc.env.ts, src/frontend/src/env/tokens-erc20/tokens.link.env.ts, src/frontend/src/env/tokens-erc20/tokens.oct.env.ts, src/frontend/src/env/tokens-erc20/tokens.shib.env.ts, src/frontend/src/env/tokens-erc20/tokens.uni.env.ts, src/frontend/src/env/tokens-erc20/tokens.usdc.env.ts, src/frontend/src/env/tokens-erc20/tokens.usdt.env.ts, src/frontend/src/env/tokens-erc20/tokens.wbtc.env.ts, src/frontend/src/env/tokens-erc20/tokens.wsteth.env.ts, src/frontend/src/env/tokens-erc20/tokens.xaut.env.ts, src/frontend/src/env/tokens.btc.env.ts, src/frontend/src/env/tokens.env.ts
Webstorm....
Follow-up of https://github.com/dfinity/oisy-wallet/pull/3360#pullrequestreview-2415976919
- Remove blank lines
=> chore(frontend): remove blank lines

src/frontend/src/lib/validation/token.validation.ts, src/frontend/src/tests/icp/validation/ic-token.validation.spec.ts, src/frontend/src/tests/lib/validation/token.validation.spec.ts, src/frontend/src/tests/mocks/ic-tokens.mock.ts, src/frontend/src/tests/mocks/tokens.mock.ts
An useful util to find out when an object is a Token type.
Tests included.
=> feat(frontend): create util isToken

src/frontend/src/tests/btc/derived/tokens.derived.spec.ts
Some tests for derived `enabledBitcoinTokens`.
=> test(frontend): Test derived enabledBitcoinTokens

src/frontend/src/tests/eth/derived/tokens.derived.spec.ts
Some tests for derived `enabledEthereumTokens`.
=> test(frontend): Test derived enabledEthereumTokens

src/frontend/src/lib/utils/nav.utils.ts
Small refactoring to use variable keys in navigation utils.
=> refactor(frontend): use variable keys in nav utils

src/frontend/src/tests/lib/derived/tokens.derived.spec.ts, src/frontend/src/tests/mocks/erc20-tokens.mock.ts
Some tests for the derived store `tokens`.
=> test(frontend): Derived store tokens list

src/frontend/src/lib/components/icons/lucide/IconMoveDown.svelte, src/frontend/src/lib/components/icons/lucide/IconMoveRight.svelte
Add 2 new icons that are gonna be used in the token conversion flow.
=> feat(frontend): add new icons

src/frontend/src/lib/components/ui/Hr.svelte
Additional spacing prop for the Hr component.
=> feat(frontend): add additional spacing to the Hr component

src/frontend/src/lib/components/ui/InputCurrency.svelte
Additional prop for InputCurrenct.
=> feat(frontend): add "disabled" prop to InputCurrency

src/frontend/src/lib/components/ui/MessageBox.svelte
Add new level to the MessageBox component.
=> feat(frontend): new MessageBox level

src/frontend/src/eth/components/transactions/EthTransactions.svelte, src/frontend/src/eth/utils/transactions.utils.ts, src/frontend/src/tests/eth/utils/transactions.utils.spec.ts
Renaming `mapTransactionUi` to `mapEthTransactionUi`.
=> refactor(frontend): rename Ethereum mapping function

src/frontend/src/tests/eth/components/loaders/LoaderEthTransactions.spec.ts
We add an important test for component `LoaderEthTransactions`: when the load transactions function fails, the component should understand that it should re-load if necessary, instead of considering a token that was already processed.
=> test(frontend): Missing test for component LoaderEthTransactions

src/frontend/src/lib/components/convert/ConvertInputsContainer.svelte
Component that will be re-used for Source and Destination tokens inputs.
=> feat(frontend): ConvertInputsContainer component

src/frontend/src/lib/components/convert/ConvertToken.svelte
=> feat(frontend): ConvertToken component

src/frontend/src/env/schema/env-icrc-token.schema.ts, src/frontend/src/env/types/env-icrc-token.ts, src/frontend/src/env/types/env-sns-token.ts, src/frontend/src/env/types/env-token-ckerc20.ts
Continuing with some cleanup of our env tokens by splitting schema and types (as we newly do) and using suffix Schema.
Follow-up of #3514.
Skipped.
=> feat(frontend): env icrc token schema suffix and module

src/frontend/src/env/schema/env-token-ckerc20.schema.ts, src/frontend/src/env/tokens.ckerc20.env.ts, src/frontend/src/env/types/env-token-ckerc20.ts
Use our naming and structure convention for ckErc20 env tokens.
Skipped.
=> refactor(frontend): ckErc20 env token schema

src/frontend/src/lib/components/transactions/TransactionsPlaceholder.svelte, src/frontend/src/lib/components/ui/RoundedIcon.svelte
- Align design to Figma by use white background.
- Remove custom code and unique usage of `postCSS`.
- Be consistent.
Before:
After:
=> style(frontend): review rounded icon

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
This PR includes all i18n strings I have at the moment.
=> feat(frontend): Conversion flow i18n

src/frontend/src/lib/components/convert/ConvertReviewNetworks.svelte
=> feat(frontend): ConvertReviewNetworks component

src/frontend/src/lib/components/convert/ConvertReviewAmount.svelte
=> feat(frontend): ConvertReviewAmount component

src/frontend/src/lib/utils/network.utils.ts, src/frontend/src/tests/lib/utils/network.utils.spec.ts
Splitting PR #3547 , we use this one to create a small util to check it a network is Sepolia.
=> feat(frontend): util to check for Sepolia network

src/frontend/src/lib/components/transactions/AllTransactionsList.svelte, src/frontend/src/tests/lib/components/transactions/AllTransactionsList.spec.ts
As last part of splitting #3547 , we add the Ethereum transactions in the UI.
Note that UI wise, there will be other PRs
=> feat(frontend): add Ethereum transactions in AllTransactionsList

src/frontend/src/lib/components/transactions/AllTransactionsList.svelte
As mentioned in PR #3565 , we will be add another loop to the `AllTransactionsList`, sorting the entire list of transactions by timestamp.
=> feat(frontend): add sorting in AllTransactionsList

src/frontend/src/tests/lib/utils/nav.utils.spec.ts
More tests for `nav.utils` module.
=> test(frontend): more tests for nav.utils

src/frontend/src/lib/components/convert/ConvertAmountDestination.svelte, src/frontend/src/tests/lib/components/convert/ConvertAmountDestination.spec.ts
Component for handling destination amount calculation and appearance.
Desktop:
Mobile:
=> feat(frontend): ConvertAmountDestination component

src/frontend/src/lib/components/convert/ConvertInputsContainer.svelte
After switching to the colors from theme file, the input started to have a blueish color when it should be light grey. Fixed it.
=> fix(frontend): ConvertInputsContainer border color

src/frontend/src/btc/components/convert/BtcConvertFeeTotal.svelte, src/frontend/src/tests/btc/components/convert/BtcConvertFeeTotal.spec.ts
A component to sum and display all related to the BTC  -> ckBTC conversion fees.
=> feat(frontend): BtcConvertTotalFee component

src/frontend/src/lib/components/convert/ConvertForm.svelte
A container component for the first step of the conversion flow.
=> feat(frontend): ConvertForm component

src/frontend/src/icp/utils/map-icrc-data.ts, src/frontend/src/tests/icp/utils/map-icrc-data.spec.ts
We would like to have BURN in all envs minus LOCAL.
=> feat(frontend): show BURN in staging too

src/frontend/src/btc/components/convert/BtcConvertReview.svelte
A component for displaying BTC-related conversion info on the review step.
=> feat(frontend): BtcConvertReview component

src/frontend/src/lib/components/convert/ConvertAmount.svelte, src/frontend/src/lib/components/convert/ConvertAmountDestination.svelte, src/frontend/src/lib/components/convert/ConvertAmountSource.svelte, src/frontend/src/lib/components/convert/ConvertForm.svelte
In this PR, except a new component, I also updated related prop types according to the latest change from main.
Desktop:
Mobile:
=> feat(frontend): ConvertAmount component

src/frontend/src/env/tokens.icrc.json
In PR #3646 , I forgot to include the modifications of the JSON file that gives the default ICRC tokens.
=> fix(frontend): adjust input JSON for ICRC default tokens

src/frontend/src/lib/utils/balances.utils.ts
Removing a paragraph that was bothering me.
=> chore(frontend): remove paragraph

src/frontend/src/lib/components/core/Menu.svelte
We don't want to show "Your Addresses" in the Activity page.
=> feat(frontend): do not show Your Addresses in Activity

src/frontend/src/lib/components/convert/ConvertWizard.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/convert/ConvertWizard.spec.ts
`ConvertWizard` - semi-last component in the Conversion flow tree.
=> feat(frontend): ConvertWizard component

src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/lib/services/rest.services.ts, src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
We use new util retry for the function loadErc20Transactions.
Provided a few tests.
=> feat(frontend): use retry for loadErc20Transactions

src/frontend/src/lib/components/convert/ConvertModal.svelte, src/frontend/src/tests/lib/components/convert/ConvertModal.spec.ts
The top-level conversion modal component.
=> feat(frontend): ConvertModal component

src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/lib/utils/time.utils.ts, src/frontend/src/tests/lib/utils/time.utils.spec.ts
Simple util for random waiting to be re-used.
=> feat(frontend): extract util for random waiting

package-lock.json, package.json
This PR prepares the release of version v0.9.4.
=> chore(release): v0.9.4

src/frontend/src/btc/components/convert/ConvertToCkBTC.svelte, src/frontend/src/lib/components/convert/ConvertModal.svelte, src/frontend/src/tests/btc/components/convert/ConvertToCkBTC.spec.ts, src/frontend/src/tests/lib/components/convert/ConvertModal.spec.ts
The last piece of the puzzle - updating ConvertToCkBTC component.
=> feat(frontend): update ConvertToCkBTC component

src/frontend/src/btc/components/fee/UtxosFeeContext.svelte
Forgot to add in https://github.com/dfinity/oisy-wallet/pull/3717 `amountError` to the vars to listen to in UtxosFeeContext.
=> feat(frontend): UtxosFeeContext - listen for amountError updates

src/frontend/src/icp/services/icrc.services.ts
Removing unused function `unsafeLoadDefaultPublicIcrcTokens`.
=> chore(frontend): remove unused function

package-lock.json, package.json
=> chore(release): v0.9.6

src/frontend/src/lib/components/dapps/DappModal.svelte
Uniform layout for Modals.
- Use ContentWithToolbar in DappModals
before:
after:
=> style(frontend): use ContentWithToolbar in DappModal

svelte.config.js, vitest.config.ts
Including aliases for Solana directory.
=> feat(frontend): add aliases for Solana

src/frontend/src/env/networks.sol.env.ts, src/frontend/src/sol/schema/network.schema.ts, src/frontend/src/sol/types/network.ts, tsconfig.spec.json
We create a new type for Solana networks that include the RPC API URL.
=> feat(frontend): add RPC URLs to Solana Networks

package-lock.json, package.json
We install Solana SDK that will come useful for the integration.
Documentation at: https://solana.com/docs/clients/javascript
=> feat(frontend): installing Solana SDK

scripts/build.csp.mjs
As per @peterpeterparker suggestion, we need to whitelist BTC-related APIs.
=> feat(frontend): whitelist BTC-related APIs

src/frontend/src/lib/derived/networks.derived.ts, src/frontend/src/sol/schema/network.derived.ts, src/frontend/src/tests/sol/derived/network.derived.spec.ts
Including the Solana networks in the dropdown
=> feat(frontend): add Solana network to list

src/frontend/src/env/networks.sol.env.ts, src/frontend/src/lib/api/idb.api.ts, src/frontend/src/lib/api/signer.api.ts, src/frontend/src/lib/canisters/signer.canister.ts, src/frontend/src/lib/services/address.services.ts, src/frontend/src/lib/stores/address.store.ts, src/frontend/src/sol/services/sol-address.services.ts
=> feat(frontend): load Solana addresses

package-lock.json, package.json
Prodsec inquiry related to [security vulnerability in nanoid](https://github.com/advisories/GHSA-mwcw-c2x4-8c55).
- `npm audit fix` for nanoid 3.3.8
- bump `@junobuild/analytics` for nanoid 5.0.9
=> fix(frontend): low security vulnerability in nanoid

HACKING.md
=> chore(doc): correct Regtest

src/frontend/src/lib/derived/page-token.derived.ts, src/frontend/src/tests/lib/derived/page-token.derived.spec.ts
add solana to the page-token.dervied.ts
- add solana
Unit testing added
=> feat(frontend): add solana to page-token.derived.ts

src/frontend/src/env/tokens/tokens.sns.json
We cannot merge automatic PR #4025 because the CTS case has still not being handled. This PR handpick the changes that have to be integrated.
=> feat(frontend): handpick update Sns tokens

src/frontend/src/env/tokens/tokens.sol.env.ts, src/frontend/src/lib/components/onramper/OnramperWidget.svelte, src/frontend/src/lib/types/onramper.ts
Add sol as a token to onramper.
Integrating SOL into the onramper feature.
VITE_SOLANA_NETWORK_ENABLED=true
https://github.com/user-attachments/assets/aae56749-c271-4fa4-8d73-2d89fe42e0c5
VITE_SOLANA_NETWORK_ENABLED=false
https://github.com/user-attachments/assets/415c2954-53d7-4f18-a569-63a7f6c7f473
=> feat(frontend): add sol to onramper

src/frontend/src/lib/derived/exchange.derived.ts, src/frontend/src/lib/schema/post-message.schema.ts, src/frontend/src/lib/services/exchange.services.ts, src/frontend/src/lib/validation/coingecko.validation.ts, src/frontend/src/lib/workers/exchange.worker.ts
Have a usd price for all SOL tokens.
Integrate SOL into exchange feature.
local: 
devnet:
testnet:
mainnet:
=> feat(frontend): add sol to exchange feature

package-lock.json, package.json
Bumping version for release that removes Holiday theme and adds POPEYE token.
=> chore(release): v0.12.0

src/frontend/src/env/networks/networks.icrc.env.ts
In PR https://github.com/dfinity/oisy-wallet/pull/4088 I forgot to add the changes of the file that lists the POPEYE token data.
=> fix(frontend): missing POPEYE data in token list

src/frontend/src/tests/btc/components/convert/ConvertToCkBTC.spec.ts, src/frontend/src/tests/btc/workers/btc-wallet.worker.spec.ts, src/frontend/src/tests/eth/stores/eth-transactions.store.spec.ts, src/frontend/src/tests/icp/services/ic-transactions.services.spec.ts, src/frontend/src/tests/icp/services/icrc.services.spec.ts, src/frontend/src/tests/lib/api/idb.api.spec.ts, src/frontend/src/tests/lib/derived/all-tokens.derived.spec.ts, src/frontend/src/tests/lib/derived/network.derived.spec.ts, src/frontend/src/tests/lib/derived/token.derived.spec.ts, src/frontend/src/tests/lib/services/auth.services.spec.ts, src/frontend/src/tests/lib/services/batch.services.spec.ts, src/frontend/src/tests/lib/services/rest.services.spec.ts, src/frontend/src/tests/lib/services/reward-code.services.spec.ts, src/frontend/src/tests/lib/utils/convert.utils.spec.ts, src/frontend/src/tests/lib/utils/nav.utils.spec.ts, src/frontend/src/tests/lib/utils/onramper.utils.spec.ts
As discussed in https://github.com/dfinity/oisy-wallet/pull/4087#discussion_r1905053812, those `vi` imports are not necessary.
=> chore(frontend): import vi clean-up

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
We add CLOUD ICRC token:
- Ledger Canister: pcj6u-uaaaa-aaaak-aewnq-cai
- Index Canister: 72uqs-pqaaa-aaaak-aes7a-cai
=> feat(frontend): add CLOUD ICRC token

LICENSE
=> chore(frontend): update copyright

src/frontend/src/lib/components/icons/lucide/IconArrowUpDown.svelte, src/frontend/src/lib/components/icons/lucide/IconCircleArrowDown.svelte
In this PR, 2 new icons have been added, as well as an existing got an additional `size` prop.
=> feat(frontend): icons update

src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
We include the service `sendSol` in the component that collects the wizard to send Solana.
=> feat(frontend): include SOL send service in wizard component

package-lock.json, package.json
We want to embed the last improvement of the `@dfinity/oisy-wallet-signer` library.
- Bump release [v0.1.2](https://github.com/dfinity/oisy-wallet-signer/releases/tag/v0.1.2)
=> build(frontend): update oisy-wallet-signer

src/frontend/src/sol/components/core/SolLoaderWallets.svelte
Including SPL tokens in the component that initialize the wallet workers: `SolLoaderWallets`
=> feat(frontend): start wallet workers for SPL tokens

src/frontend/src/lib/derived/all-tokens.derived.ts, src/frontend/src/sol/utils/token.utils.ts, src/frontend/src/tests/lib/derived/all-tokens.derived.spec.ts
Including SPL token in the manage tokens list.
=> feat(frontend): include SPL tokens in manage list

src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
This PR includes all i18n related to the Swap feature.
=> feat(frontend): Swap i18n

src/frontend/src/lib/components/swap/SwapTokenBalance.svelte
=> feat(frontend): SwapTokenBalance component

src/frontend/src/lib/stores/swap.store.ts, src/frontend/src/tests/lib/stores/swap.store.spec.ts
This PR includes the Swap store and related tests.
=> feat(frontend): swap store

src/frontend/src/lib/enums/progress-steps.ts, src/frontend/src/lib/services/swap.services.ts, src/frontend/src/lib/types/api.ts
This PR includes a service for starting a swap operation.
=> feat(frontend): swap service

src/frontend/src/lib/components/swap/SwapInputContainer.svelte
=> feat(frontend): SwapInputContainer component

src/frontend/src/lib/components/swap/SwapAmountExchange.svelte
The PR includes the SwapAmountExchange component.
=> feat(frontend): SwapAmountExchange component

src/frontend/src/lib/components/swap/SwapInputCurrency.svelte, src/frontend/src/lib/components/swap/SwapValue.svelte
SwapValue component:
P.S.: I also used this PR to fix a small issue with SwapInputCurrency.
=> feat(frontend): SwapValue component

src/frontend/src/lib/components/swap/SwapAmountsContext.svelte, src/frontend/src/lib/stores/swap-amounts.store.ts
This PR includes store and context files for the swap amounts data.
=> feat(frontend): swap amounts store and context

src/frontend/src/lib/components/swap/SwapMaxBalanceButton.svelte
SwapMaxBalanceButton component:
=> feat(frontend): SwapMaxBalanceButton component

src/frontend/src/lib/components/swap/SwapButton.svelte, src/frontend/src/lib/components/swap/SwapButtonWithModal.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
This PR includes the swap modal store additions + button components to work with it.
=> feat(frontend): swap modal store and button

src/frontend/src/lib/components/swap/SwapProgress.svelte
This PR includes a basic progress component - SwapProgress.
=> feat(frontend): SwapProgress component

src/frontend/src/env/caip10-chains.env.ts, src/frontend/src/env/networks/networks.sol.env.ts, src/frontend/src/eth/services/eth-listener.services.ts, src/frontend/src/lib/components/wallet-connect/WalletConnectSession.svelte, src/frontend/src/lib/providers/wallet-connect.providers.ts, src/frontend/src/sol/schema/network.schema.ts, src/frontend/src/sol/types/network.ts
we want to include solana mainnet in the wallet connect listener if the feature flag is on.
add namespace for solana mainnet, other will follow.
https://github.com/user-attachments/assets/97636e32-584d-4e16-a033-0a2e2c95e9f0
=> feat(frontend): extend wallet connect listener with sol

src/frontend/src/lib/components/swap/SwapTokensList.svelte
=> feat(frontend): SwapTokensList component

src/frontend/src/lib/components/swap/SwapSelectToken.svelte
=> feat(frontend): SwapSelectToken component

src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/components/swap/SwapSwitchTokensButton.svelte
This PR includes the SwapForm component and related to it SwapSwitchTokensButton component.
=> feat(frontend): SwapForm component

src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/enums/wizard-steps.ts
This PR includes the SwapWizard component.
=> feat(frontend): SwapWizard component

src/frontend/src/lib/components/swap/SwapModal.svelte, src/frontend/src/lib/config/swap.config.ts, src/frontend/src/lib/types/swap.ts
This PR includes the SwapModal component.
=> feat(frontend): SwapModal component

src/frontend/src/env/networks/networks.sol.env.ts, src/frontend/src/env/tokens/tokens-spl/tokens.bonk.env.ts, src/frontend/src/env/tokens/tokens-spl/tokens.ray.env.ts, src/frontend/src/env/tokens/tokens-spl/tokens.usdc.env.ts, src/frontend/src/env/tokens/tokens-spl/tokens.usdt.env.ts
Include the Onramper IDs for Solana SPL tokens.
=> feat(frontend): add Onramper IDs for SPL tokens

src/frontend/src/lib/components/hero/Actions.svelte, src/frontend/src/lib/components/swap/Swap.svelte, src/frontend/src/lib/derived/exchange.derived.ts
This is the last step of the Swap feature - Swap component + its usage.
=> feat(frontend): implement Swap component and use it in Actions

package-lock.json, package.json
This PR prepares the release of version v0.20.0.
=> chore(release): v0.20.0

src/frontend/src/lib/components/swap/SwapTokensList.svelte
The idea is to apply to SwapTokensList the same sorting as we have in the main tokens list (tokens with balance should be pinned to the top).
=> feat(frontend): sort SwapTokensList

e2e/utils/pages/homepage.page.ts, src/frontend/src/lib/components/networks/NetworksTestnetsToggle.svelte, src/frontend/src/lib/constants/test-ids.constants.ts
Just to be more generic, the test ID for the testnet toggle should not have token references.
=> refactor(frontend): BTC_TESTNET_TOGGLE --> TESTNET_TOGGLE

src/frontend/src/lib/providers/wallet-connect.providers.ts, src/frontend/src/sol/constants/wallet-connect.constants.ts
To be consistent, we extract the Solana methods that concerns WalletConnect in separate variables.
=> refactor(frontend): extract constants for WalletConnect Solana methods

package-lock.json, package.json
This PR prepares the release of version v0.20.2
=> chore(release): v0.20.2

src/frontend/src/sol/services/sol-send.services.ts
Just to be more clear, we extract the common part of creating the default transaction for Solana, where:
1. the version is defined;
2. the payer is specified;
3. it is decided that the lifetime is based on the blockhash.
=> refactor(frontend): Extract function to create default transaction in Solana

src/declarations/kong_backend/kong_backend.did, src/declarations/kong_backend/kong_backend.did.d.ts, src/declarations/kong_backend/kong_backend.factory.certified.did.js, src/declarations/kong_backend/kong_backend.factory.did.js
This PR updates kong_backend declarations according to the new WASM and candid files the kong team released today.
=> chore(backend): update kong_backend declarations

src/frontend/src/lib/api/kong_backend.api.ts, src/frontend/src/lib/canisters/kong_backend.canister.ts, src/frontend/src/tests/lib/canisters/kong_backend.canister.spec.ts, src/frontend/src/tests/mocks/kong_backend.mock.ts
This PR includes a new kong_backend endpoint exposed. It will be used in the next PRs.
=> feat(frontend): expose tokens endpoint of kong_backend

src/frontend/src/eth/components/wallet-connect/WalletConnectSignModal.svelte
Small chore for consistency renaming the component InProgressWizard with its correct name.
=> chore(frontend): correct component name in WalletConnectSignModal

src/frontend/src/lib/components/swap/Swap.svelte, src/frontend/src/lib/components/swap/SwapTokensList.svelte, src/frontend/src/lib/derived/all-tokens.derived.ts, src/frontend/src/lib/services/swap.services.ts, src/frontend/src/lib/stores/kong-swap-tokens.store.ts, src/frontend/src/tests/lib/derived/all-tokens.derived.spec.ts, src/frontend/src/tests/lib/services/swap.services.spec.ts, src/frontend/src/tests/mocks/kong_backend.mock.ts
In this PR, a service and a store for using kong_backend tokens endpoint is created.
=> feat(frontend): kong_backend tokens service and store

src/frontend/src/lib/utils/network.utils.ts, src/frontend/src/sol/components/transactions/SolTransactionModal.svelte, src/frontend/src/tests/lib/utils/network.utils.spec.ts
We create a small util to verify if a possible network is a Solana network. This is useful to define its type too. It will be used especially for the explorer URL prop.
=> feat(frontend): util to check if network is Solana

.github/workflows/deploy-to-environment.yml, .github/workflows/release-notes.yml
We would like to automate more of releases.
The flow in the last PR was not quite right, so this aims to correct that.
- Change which workflow triggers which.
- For deploy to network, deploy to beta
This can only be tested when merged.
=> fix(devops): More accurate triggers

src/frontend/src/tests/lib/utils/format.utils.spec.ts
The tests for `formatSecondsToNormalizedDate` were failing because we were simulating a date that it is actually today. So we generalize them.
=> test(frontend): fix test for date formatter

src/frontend/src/sol/services/sol-send.services.ts
Similar to the other networks, we await for the Solana transactions to be sent (NOT CONFIRMED, just sent).
=> feat(frontend): await the Solana transaction to be sent

src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte
We can add `SolAddTokenForm` among the choices that the user have when one wants to add manually a new token, so that they can decide to add SPL tokens.
https://github.com/user-attachments/assets/187cc664-5951-40b1-817e-3cbccc4b1082
=> feat(frontend): let user manually add SPL tokens

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
We add GLDT ICRC token (https://docs.gold-dao.org/other/key-canisters#gldt)
Ledger Canister: 6c7su-kiaaa-aaaar-qaira-cai
Index Canister: oo6x4-xiaaa-aaaap-abrza-cai
=> feat(frontend): add GLDT ICRC token

dfx.json
A more recent version of `dfx` is available
- Bump `dfx` to the latest version.
Existing CI should suffice
=> chore(devops): Bump dfx version

HACKING.md
=> chore(docs): typo in Solana faucet

src/frontend/src/sol/components/send/SolSendAmount.svelte
We have a Solana fee context, so it makes sense to use such a store to validate the balance.
=> refactor(frontend): use Solana fee context for validation

src/frontend/src/lib/components/tokens/TokenInput.svelte
TokenInput component should have an option of hiding the Dropdown icon.
=> feat(frontend): add isSelectable prop to TokenInput

src/frontend/src/sol/services/spl.services.ts
We can switch to using the SPL custom tokens loaded from the backend instead of using the browser-cached one. However we keep loading them to save them with the temporary solution provided in https://github.com/dfinity/oisy-wallet/pull/4545
- Loop through `splCustomTokens` loaded from backed.
- Split them into existing tokens (the ones hard-coded in our codebase) and non-existing one (the ones that the user add manually).
- Refresh the metadata of the second group, for insurance.
Current tests are sufficient, but we will provide a more comprehensive one, once removed the temporary solution.
=> feat(frontend): use SPL custom tokens from backend instead of the cached ones

scripts/build.tokens.sns.mjs
Deprecating the CTS project (#4331) led to skipping the fetching of icons for governance if no ledger icon was available in the SNS script. This is why we removed the fallback (see #4523). However, as discussed today in the [forum](https://forum.dfinity.org/t/icrc-metadata-inconsistency/40793/5?u=peterparker) post, while there might be an issue in the tooling, older SNSes (OC, Ghost, Yarl, Kinic, Yuku, Motoko, Alice, Gold, Catalyze, and Boom) do not have effectively logos in their ledger for historical reasons. Therefore, we should redo the fallback.
- If no icon and not a deprecated SNS, then use the SNS (root) project logo
=> fix(script): redo fallback SNS governance logo if no ledger logo

src/frontend/src/env/rest/quicknode.env.ts, src/frontend/src/sol/rest/quicknode.rest.ts, src/frontend/src/sol/services/spl.services.ts
We will fetch SPL token data for Solana devnet and testnet tokens too.
=> feat(frontend): fetch metadata for SPL devnet/testnet tokens too

src/frontend/src/env/tokens/tokens-spl/tokens.trump.env.ts
Adding TRUMP to the list of Onramper tokens.
=> feat(frontend): add TRUMP Onramper ID

src/frontend/src/lib/components/swap/SwapForm.svelte, src/frontend/src/lib/components/swap/SwapReview.svelte, src/frontend/src/lib/components/tokens/TokensReview.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
In this PR, TokensReview component is prepared to be re-used by both Swap and Conversion flows.
=> refactor(frontend): re-use TokensReview component

SECURITY.md
The "Important" block is not displayed properly.
Adds a line-break to fix the formatting.
Not needed. It only changes the documentation.
=> docs(security): updates formatting of the security policy

e2e/utils/pages/homepage.page.ts
Splitting from @inc-man 's https://github.com/dfinity/oisy-wallet/pull/4613 :  useful method to wait for an element by test ID.
=> feat(e2e): create internal method to wait for by test ID

src/frontend/src/icp/components/receive/IcReceiveInfoICP.svelte, src/frontend/src/lib/components/hero/Balance.svelte, src/frontend/src/lib/components/send/SendInputAmount.svelte, src/frontend/src/lib/components/send/SendInputDestination.svelte, src/frontend/src/lib/components/transactions/Transaction.svelte, src/frontend/src/lib/components/ui/InProgressWizard.svelte, src/frontend/src/lib/constants/test-ids.constants.ts
for the upcoming new test we need testIds
added all the necessary testIds on the component and in the constants library.
=> test(e2e): added testIds for upcoming test

src/frontend/src/icp/services/icrc-custom-tokens.services.ts, src/frontend/src/icp/utils/icrc.utils.ts, src/frontend/src/tests/icp/utils/icrc.utils.spec.ts
Follow-up of [comment](https://github.com/dfinity/oisy-wallet/pull/4628#discussion_r1946602370) as discussed offline.
- `isNotDeprecated` -> `isNotDeprecatedSns`
=> refactor(frontend): isNotDeprecatedSns

package-lock.json, package.json
Bumping `@dfinity/gix-components` because we would like to use the theme features exposed in:
- https://github.com/dfinity/gix-components/pull/578
=> build(frontend): bump gix-cmp next

src/frontend/src/lib/components/ui/ModalValue.svelte
Just a small UI improvement for the ModalValue component.
https://github.com/user-attachments/assets/81e4810e-5d76-4014-9f27-19b676659e3a
=> feat(frontend): add "in" effect to ModalValue

package-lock.json, package.json
Bumping `gix-components` to include new improvements of the themeStore from https://github.com/dfinity/gix-components/pull/585
=> build(frontend): bump gix-cmp to next

src/frontend/src/tests/lib/services/reward-code.services.spec.ts
The usage of `Date.now()` in several places caused the test to fail sometimes, but this should not happen. The test needs to run exactly the same every time.
- fixes test case
=> fix(frontend): fixes test case

src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte, src/frontend/src/icp/components/tokens/IcAddTokenReview.svelte, src/frontend/src/lib/components/dapps/DappPromoBanner.svelte, src/frontend/src/lib/components/navigation/NavigationItem.svelte, src/frontend/src/lib/components/qr/VipQrCodeModal.svelte, src/frontend/src/lib/components/receive/ReceiveAddress.svelte, src/frontend/src/lib/components/signer/SignerPermissions.svelte, src/frontend/src/lib/components/swap/SwapSlippage.svelte, src/frontend/src/lib/components/tokens/TokenInput.svelte, src/frontend/src/lib/components/ui/Badge.svelte, src/frontend/src/lib/components/ui/MessageBox.svelte, src/frontend/src/lib/styles/global/button.scss, src/frontend/src/lib/styles/tailwind/theme-variables.ts
As part of the new theme refactoring done by @daviddecentage 's  https://github.com/dfinity/oisy-wallet/pull/4686 , we start with the background colors.
=> refactor(frontend): rename background tailwind colors

src/frontend/src/eth/components/convert/EthConvertReview.svelte
In this PR, a new EthConvertReview component is implemented.
No extra tests needed.
=> feat(frontend): EthConvertReview component

src/frontend/src/eth/components/convert/EthConvertForm.svelte, src/frontend/src/tests/eth/components/convert/EthConvertForm.spec.ts
This PR includes the new EthConvertForm and its tests.
=> feat(frontend): EthConvertForm component

src/frontend/src/icp-eth/components/info/InfoEthereum.svelte
Changing the text color of `InfoEthereum` component.
=> style(frontend): change color of text of InfoEthereum

src/frontend/src/lib/components/loaders/Loader.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
The `initialization modal` should display a third step 'Enjoy OISY' and the step descriptions should be updated.
- adds third step
- update step descriptions
**before:**
**after:**
=> feat(frontend): improves initialization modal

package-lock.json, package.json
OISY is using Node LTS not v20.
=> build(frontend): bump @types/node

postcss.config.js, postcss.config.mjs, tsconfig.eslint.json
Configuring postcss with ESM is a bit more handy.
- Convert `postcss.config.js` to `.mjs`
- Update reference in eslint tsconfig
=> chore(frontend): postcss config to esm

src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte, src/frontend/src/lib/constants/analytics.contants.ts, src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
This PR includes a new `EthConvertTokenWizard` component as well as all related tests.
=> feat(frontend): EthConvertTokenWizard component

src/frontend/src/eth/components/convert/ConvertToCkETH.svelte, src/frontend/src/lib/components/convert/ConvertWizard.svelte, src/frontend/src/lib/components/hero/Actions.svelte
The last PR to enable the new ETH -> ckETH conversion flow.
=> feat(frontend): enable new ETH -> ckETH conversion flow

package-lock.json, package.json
This PR makes the `main` version even with the hotfix branch. Doing it manually in order not to trigger release CI (it would fail anyway).
=> chore(build): update version in main to v0.25.0

package.json
Useful script to update GIX components.
=> feat(build): add script to update GIX components

src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/i18n/en.json
According to task, changing the landing page main title.
=> style(frontend): change title text of landing page

src/frontend/src/sol/services/sol-transactions.services.ts
We refactor the `reduce` function inside `fetchSolTransactionsForSignature` to return an object, so that we can prepare for further calculation: we will calculate the cumulative balance in another PR, to pass it to the mapping and calculate the `closeAccount` value (from PR https://github.com/dfinity/oisy-wallet/pull/5056).
Instead of returning an array of parsed transactions `SolTransactionUi`, the reduce function returns an object that is `{ parsedTransactions: SolTransactionUi[] }`.
Nothing changed in the implementation of the functions.
Current tests are enough.
=> refactor(frontend): make object for internal reduce of fetchSolTransactionsForSignature

src/frontend/src/icp/components/fee/BitcoinEstimatedFee.svelte, src/frontend/src/icp/components/fee/BitcoinKYTFee.svelte, src/frontend/src/icp/components/fee/EthereumEstimatedFee.svelte, src/frontend/src/icp/components/fee/IcTokenFee.svelte, src/frontend/src/icp/components/fee/IcTokenFees.svelte
In this PR, I'm adding a new component for displaying all IC-tokens related fees. It will be used in both Convert and Send flows. After we updated the Send flow, we will remove the old fee components (for now, I added TODO comments there).
=> feat(frontend): IcTokenFees component

src/frontend/src/icp/components/convert/IcConvertProgress.svelte, src/frontend/src/icp/constants/steps.constants.ts
This PR include the new `IcConvertProgress` component. It is very similar to `IcSendProgress` at the moment, but may receive some changes later, therefore I kept them separate but re-used the main functionality.
=> feat(frontend): IcConvertProgress component

src/frontend/src/icp/components/convert/IcConvertReview.svelte
This PR includes the new `IcConvertReview` component.
=> feat(frontend): IcConvertReview component

src/frontend/src/env/airdrop-campaigns.json, src/frontend/src/lib/i18n/en.json
Updates texts for redesigned airdrops campaign
Text changes
=> refactor(frontend): Update airdrop camapign texts

src/frontend/src/lib/components/airdrops/AirdropCard.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Updates the text for the "button" on airdrop cards
Updated text
=> refactor(frontend): Updated check status text on airdrop cards

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
We add the RUGGY ICRC token
- Ledger Canister: `icaf7-3aaaa-aaaam-qcx3q-cai`
- Index Canister: `qiu4p-taaaa-aaaal-qsi4a-cai`
=> feat(frontend): add RUGGY ICRC token

src/frontend/src/lib/components/airdrops/AirdropEarnings.svelte
=> style(frontend): remove excessive divider

src/frontend/src/icp/components/convert/IcConvertForm.svelte
This PR adds missing gas fee error message to the new Convert flow.
=> feat(frontend): add missing gas fee error message

.github/workflows/deploy-to-environment.yml
In PR https://github.com/dfinity/oisy-wallet/pull/5160 , I put the wrong quotes for the title check.
=> fix(ci): incorrect quotes in deploy CI

.github/workflows/deploy-to-environment.yml
In PR https://github.com/dfinity/oisy-wallet/pull/5160 , I repeated twice `.event`
=> fix(ci): repeated prop in deployment CI

src/frontend/src/lib/components/convert/ConvertAmount.svelte
The padding between the two input fields on the convert form is missing and should be added.
- fixes padding
**before:**
**after:**
=> fix(frontend): fixes padding

.github/workflows/deploy-to-environment.yml
I forgot to close the IF condition.
=> fix(devops): missing end of IF in deployment CI

src/frontend/src/eth/components/transactions/EthTransactionModal.svelte
When we show the transactions details of an Ethereum transaction, if `from` and/or `to` are token addresses, it would be better to show it, instead of its address. This is to avoid possible confusions on what that address refers too.
- Create the `from` and `to` strings by searching among the known tokens.
=> feat(frontend): show token name in transaction detail instead of addrress

src/frontend/src/eth/services/eth-transaction.services.ts
When we have a pending ERC20 transaction, we typically receive an "not-totally-correct" information in the `to` field: it shows the ERC20 token (smart contract) address.
This could lead to confusions on the user side. For example the user could copy such an address thinking it was the original destination address, and re-use the copied address in a new transaction.
So, we avoid showing the `to` address for ERC20 pending transactions.  
Unchanged for ETH native token.
=> feat(frontend): hide the destination for pending ERC20 transactions

package-lock.json, package.json
This PR prepares the release of version v1.3.1.
=> chore(release): v1.3.1

scripts/add.tokens.erc20.mjs, scripts/build.utils.mjs, scripts/check.i18n.mjs
Fix a lint error detected in Svelte v5 [branch](https://github.com/dfinity/oisy-wallet/pull/3929).
- Prefer `??`
=> chore(scripts): lint prefer nullish coalescing

src/frontend/src/lib/components/tokens/TokenInput.svelte, src/frontend/src/lib/components/tokens/TokensReview.svelte
Fix lint errors detected in Svelte v5 [branch](https://github.com/dfinity/oisy-wallet/pull/3929).
- Prefer `<div></div>` instead of `</div>`
=> chore(frontend): lint self closing tag

src/frontend/src/icp/components/convert/ConvertToBTC.svelte, src/frontend/src/lib/components/convert/ConvertModal.svelte, src/frontend/src/lib/components/convert/ConvertWizard.svelte, src/frontend/src/lib/utils/wizard-modal.utils.ts
The last step of enabling the new ckBTC -> BTC conversion flow
1. Update ConvertToBTC component to use ConvertModal.
2. Update ConvertModal and ConvertWizard with a few additional vars and events needed for the ckBTC -> BTC conversion feature.
=> feat(frontend): enable the new ckBTC -> BTC conversion flow

src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
The tests for `EthConvertTokenWizard` are flaky, because sometimes they raise a console log for missing data (that is correct, since the tests is done exactly for that).
However, we don't want console logs, we mock them before each test. So, we do not reset the mocks but only clear them. And refactor the code to make this work.
- Move custom mocks in `beforeEach`.
- Substitute `resetAllMocks` with `clearAllMocks`.
Current tests worked.
=> test(frontend): simplify EthConvertTokenWizard tests

src/frontend/src/lib/components/dapps/DappsCarousel.svelte, src/frontend/src/lib/components/navigation/NavigationMenuMainItems.svelte, src/frontend/src/lib/components/rewards/RewardEarningsCard.svelte, src/frontend/src/lib/components/rewards/RewardStateModal.svelte
Just a small cleaning: we remove the unnecessary `.js` extensions from the TS imports.
=> chore(frontend): remove unnecessary .js extension from imports

.github/actions/needs_success/action.yaml, .github/workflows/backend-checks.yml, .github/workflows/backend-tests.yml, .github/workflows/binding-checks.yml, .github/workflows/frontend-checks.yml
There is a GitHub action that checks that all required jobs succeeded.
- Vendor & use the action.
This action is used extensively in the nns-dapp and other repos.
=> fix(devops): Require jobs to succeed

src/frontend/src/lib/components/swap/SwapTokensList.svelte, src/frontend/src/lib/components/ui/ButtonCancel.svelte
This is the next step of aligning tokens list view - we start using it in the Swap flow.
=> feat(frontend): use ModalTokensList in the Swap flow

src/frontend/src/lib/components/send/SendTokensList.svelte
This is the next step of aligning tokens list view - we start using it in the Send flow.
=> feat(frontend): use ModalTokensList in the Send flow

src/frontend/src/env/networks/networks.btc.env.ts, src/frontend/src/env/networks/networks.env.ts
After refactoring and cleaning up the network env files, we now add a full list of all supported networks.
- Added full supported networks list
- Exported supported btc networks to use it in the networks list
=> feat(frontend): Full network list of supported networks

src/frontend/src/lib/components/ui/LogoButton.svelte
The logo button needs a test id if we want to use it for the network switcher
Added test id prop
=> refactor(frontend): Logo button test id

src/frontend/src/lib/api/backend.api.ts
Creating open API function for backend method `updateUserNetworkSettings`.
=> feat(frontend): open function for backend method updateUserNetworkSettings

src/frontend/src/env/tokens/tokens-erc20/tokens.pepe.env.ts
Unnecessary whitespace in imports.
=> chore(frontend): remove unnecessary whitespace

src/frontend/src/lib/canisters/reward.canister.ts, src/frontend/src/tests/lib/canisters/reward.canister.spec.ts
As a user i want to be abel to use the referral feature specific functions from the `reward canister`.
- canister implementation update
=> feat(frontend): implements canster functions

src/frontend/src/btc/components/transactions/BtcTransactionModal.svelte, src/frontend/src/lib/components/dapps/DappModal.svelte, src/frontend/src/lib/components/loaders/Loader.svelte, src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte, src/frontend/src/lib/components/swap/SwapProvider.svelte
There is no need for curly brackets in some reactive statement.
=> chore(frontend): removing unnecessary reactive curly brackets

src/frontend/src/lib/stores/modal-tokens-list.store.ts
In this PR, the modal-tokens-list store is a bit refactored. Also, it now exposes the `setTokens` method - it will be needed for the Swap flow where tokens are not available initially on the modal open.
=> feat(frontend): update modal-tokens-list store

src/frontend/src/lib/components/tokens/ModalNetworksFilter.svelte
This PR includes a new component for displaying networks list within a modal.
=> feat(frontend): ModalNetworksFilter component

src/frontend/src/icp/components/send/IcSendTokenWizard.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendTokensList.svelte, src/frontend/src/lib/components/send/SendWizard.svelte
This PR fixes 2 issues related to dispatching events in the Send flow:
1. Correct event is now dispatched on selecting tokens to send.
2. Back button is now aligned and correctly behaving in all the send flows.
=> fix(frontend): dispatch correct events in the send flow

src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/core/Modals.svelte, src/frontend/src/lib/constants/test-ids.constants.ts, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/stores/modal.store.ts, src/frontend/src/lib/types/i18n.d.ts
As a user i want to be able to see a menu item that allows me to open the referral modal.
- add referral menu item
=> feat(frontend): implements referral menu item

src/frontend/src/lib/components/guard/RewardGuard.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts, src/frontend/src/lib/types/reward.ts, src/frontend/src/lib/utils/rewards.utils.ts, src/frontend/src/tests/lib/utils/rewards.utils.spec.ts
When a user receives a referral reward the referral state modal should be opened.
- displays referral state modal
https://github.com/user-attachments/assets/87374257-c892-436a-a55e-5ecb136d8719
=> feat(frontend): uses referral state modal

.github/actions/release-notes/action.yml, .github/workflows/auto-update-i18n.yml, .github/workflows/binding-checks.yml, .github/workflows/bump-version.yml, .github/workflows/e2e-tests.yml, .github/workflows/formatting-checks.yml, .github/workflows/frontend-checks.yml, .github/workflows/frontend-remove-unused-components.yml, .github/workflows/update-next.yml, .github/workflows/update-rust.yml, .github/workflows/update-tokens.yml
Github actions should be pinned for security hardening.
- Pin create-github-app-token
See CI
=> chore(devops): Pin create-github-app-token

.github/workflows/e2e-tests.yml, src/frontend/src/lib/utils/input.utils.ts
The type definition of util `isNullishOrEmpty` should be an optional empty string instead of just a nullish value.
=> refactor(frontend): define output type of util isNullishOrEmpty

src/frontend/src/tests/lib/components/guard/UrlGuard.spec.ts
We want to be sure that the `UrlGuard` component does what it is supposed to do. That's why additional tests are provieded.
- implements some tests
=> feat(frontend): implements url guard tests

scripts/build.csp.mjs, src/frontend/src/env/plausible.env.ts
We aim to track analytics using Plausible. The goal is to ensure that pageviews and custom events are tracked correctly across the app.
Added plausible to csp scripts and created .env file for it.
=> feat(frontend): added plausible to csp and created .env file

svelte.config.js, tsconfig.spec.json
We need to cover the routes with tests, so I added a new alias for the route paths.
Added a new alias for the route paths.
=> feat(frontend): added new alias for routes

src/frontend/src/lib/utils/token.utils.ts, src/frontend/src/tests/lib/utils/token.utils.spec.ts
Util `sumTokenBalances` is not used anymore, so we remove it.
=> chore(frontend): remove unused util sumTokenBalances

src/frontend/src/eth/components/convert/EthConvertForm.svelte
EthConvertForm was not using one of the error context values correctly.
=> fix(frontend): issue with EthConvertForm

src/frontend/src/env/reward-campaigns.json
The `endDate` of the reward campaign should be changed to `2025.04.09`.
- updates date
=> fix(frontend): updates reward campaign date

package-lock.json, package.json
This PR prepares the release of version `v1.3.4`.
=> chore(release): v1.3.4

src/frontend/src/lib/components/tokens/TokenCard.svelte, src/frontend/src/lib/types/transaction.ts, src/frontend/src/routes/(app)/transactions/+layout.svelte
New lint rules to be applied according to PR https://github.com/dfinity/oisy-wallet/pull/5701
=> chore(frontend): apply new lint rules

src/frontend/src/lib/components/ui/ButtonBack.svelte
We want to be able to set a `testId` on the `ButtonBack`.
- adds testId
=> feat(frontend): updates ButtonBack

src/frontend/src/lib/components/auth/AuthGuard.svelte, src/frontend/src/lib/components/hero/HeroSignIn.svelte, src/frontend/src/lib/components/signer/SignerSignIn.svelte
The `Need help signingIn?` should also work on the `SignerSignIn`.
https://github.com/user-attachments/assets/aac68bbc-75d3-43e5-834d-5a96a95375dd
=> feat(frontend): improves need help signIn

scripts/build.csp.mjs
We need to update the CSP to allow the Kongswap API, so it can make requests without triggering a CSP error.
=> fix(frontend): added kongswap to csp

scripts/build.backend.args.ic.did, scripts/build.backend.args.sh, scripts/deploy.args.sh, src/backend/tests/it/utils/mock.rs, src/frontend/src/lib/constants/app.constants.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/stores/auth.store.ts
We revert PR #5737 : we will tackle it again in the next release.
=> feat(frontend): REVERT PR #5737: switch from ic0 to internetcomputer

dfx.json, scripts/build.ckbtc_index.args.sh, scripts/build.ckbtc_index.sh, scripts/deploy.ckbtc.sh
`dfx deploy` should just work
- Set default arguments for `ckbtc-index`, so that `dfx deploy ckbtc-index` works by default.
Existing CI should suffice
=> chore(devops): Deploy ckbtc index

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
Add the vCHF ICRC token
- Ledger: ly36x-wiaaa-aaaai-aqj7q-cai
- Index: 4cx56-naaaa-aaaai-aqkaa-cai
=> feat(frontend): add VCHF ICRC token

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
Add VEUR ICRC token
- ledger: `wu6g4-6qaaa-aaaan-qmrza-cai`
- index: `wi24n-jqaaa-aaaan-qmr3a-cai`
=> feat(frontend): add VEUR ICRC token

package-lock.json, package.json
This PR prepares the release of version `v1.3.8`.
=> chore(release): v1.3.8

src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/core/MenuAddresses.svelte, src/frontend/src/lib/components/icons/lucide/IconUserSquare.svelte, src/frontend/src/lib/constants/test-ids.constants.ts, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/core/Menu.spec.ts
Adds a menu entry to be able to open the address book
Adds the entry to the menu with translations and a new lucide icon.
=> feat(frontend): add address book menu entry

src/frontend/src/env/tokens/tokens-evm/tokens-base/tokens.eth.env.ts
Including ETH and Sepolia ETH as native tokens for Base network.
=> feat(frontend): add Ethereum native tokens for Base network

src/backend/tests/it/pow.rs
This PR refactors the test setup to eliminate the use of the auto-progress function, replacing it with direct configuration on the Pocket instance. It also updates assertions and test logic to enhance maintainability and ensure consistent behavior.
- Removed unused thread imports and sleep_test function.
- Renamed setup_cycles_ledger_with_progress() to setup_with_cycles_ledger() for clarity.
- Adjusted test cases to use setup() or setup_with_cycles_ledger() consistently.
- Replaced manual thread sleeping with advance_time() for precise time simulation in tests.
- Updated an assertion to adjust allowed_cycles from 1,000,000,000 to 7,000,000,000.
No new tests were added, but existing tests were refactored for clarity and to align with new function names and logic. All changes focus on test …
=> feat(backend): add backend integration test for pow

package-lock.json, package.json
Release of the hotfix (pending ck tokens transactions).
=> chore(release): v1.3.9

src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte, src/frontend/src/icp/components/convert/HowToConvertEthereumWizardSteps.svelte, src/frontend/src/lib/components/receive/ReceiveAddressQRCode.svelte, src/frontend/src/lib/constants/test-ids.constants.ts, src/frontend/src/tests/icp/components/convert/HowToConvertEthereumWizardSteps.spec.ts
Adding missing tests for HowToConvertEthereumWizardSteps to increase an overall test coverage.
=> test(frontend): add tests for HowToConvertEthereumWizardSteps

src/frontend/src/tests/icp/components/info/Info.spec.ts
Adding tests for Info component. Note: 2 suites are skipped for now as they cover some future cases, it will be cleaned up in the following PRs.
=> test(frontend): add tests for Info component

src/frontend/src/tests/icp-eth/components/info/InfoEthereum.spec.ts
Adding tests for InfoEthereum component.
=> test(frontend): add tests for InfoEthereum component

src/frontend/src/tests/icp/components/receive/IcReceiveCkEthereumModal.spec.ts
Adding tests for IcReceiveCkEthereumModal component to increase the overall test coverage percentage.
=> test(frontend): add tests for IcReceiveCkEthereumModal component

src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte
Migrate `HowToConvertEthereumInfo` to Svelte 5.
=> refactor(frontend): migrate HowToConvertEthereumInfo to Svelte 5

src/frontend/src/icp/components/info/Info.svelte
=> refactor(frontend): migrate Info to Svelte 5

src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
Migrate `IcReceiveCkEthereum` to Svelte 5
=> refactor(frontend): migrate IcReceiveCkEthereum to Svelte 5

src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
Migrate `IcReceiveCkEthereumModal` to Svelte 5.
=> refactor(frontend): migrate IcReceiveCkEthereumModal to Svelte 5

src/frontend/src/tests/icp/workers/ic-wallet-balance-and-transactions.worker.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few warnings. So, in preparation, for now we apply the rule [vitest/no-duplicate-hooks](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-duplicate-hooks.md) on the ic-wallet-balance-and-transactions worker tests.
We put the common tests into a single callable function.
=> refactor(frontend): use test util for common tests in ic-wallet worker

package-lock.json, package.json
This PR prepares the release of version `v1.3.10`.
=> chore(release): v1.3.10

src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/core/Modals.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
Since the VIP QR code modal accepts a `codeType` parameter, we want to set this parameter when opening the modal.
- sets `codeType` parameter when opening modal
=> feat(frontend): uses new modal param on opening modal

package-lock.json, package.json
This PR prepares the release of version `v1.3.11`.
=> chore(release): v1.3.11

src/frontend/src/icp/components/transactions/IcTransactionsScroll.svelte
Migrating component `IcTransactionsScroll` to Svelte v5.
=> refactor(frontend): component `IcTransactionsScroll` to Svelte v5

src/frontend/src/env/tokens/tokens-spl/tokens.eurc.env.ts
According to [Onramper documentation](https://docs.onramper.com/docs/crypto-asset-support), EURC has an ID on Solana.
=> feat(frontend): add Onramper ID to Solana EURC

src/frontend/src/eth/components/fee/FeeContext.svelte, src/frontend/src/eth/components/send/EthSendAmount.svelte, src/frontend/src/eth/services/eth-balance.services.ts, src/frontend/src/eth/services/eth-listener.services.ts, src/frontend/src/eth/services/eth-transaction.services.ts, src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/eth/services/send.services.ts
In all the same situations where the code checks if a token is an Ethereum native token, we need to add the check for EVM native tokens.
=> feat(frontend): check if a token is an EVM native token

src/frontend/src/eth/providers/etherscan.providers.ts, src/frontend/src/tests/eth/providers/etherscan.providers.spec.ts
Including EVM networks in the Etherscan providers.
=> feat(frontend): add EVM networks in Etherscan provider

src/frontend/src/env/networks/networks-evm/networks.evm.env.ts, src/frontend/src/eth/services/erc20.services.ts
Including EVM tokens in the filter and network map of service `loadUserTokens`.
=> feat(frontend): add EVM tokens to network map of ERC20 user tokens

src/frontend/src/lib/utils/transactions.utils.ts, src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
We need to start displaying EVM transactions on the Activities page.
Transactions mapper is updated.
Adjusted.
=> feat(frontend): display base and bnb transactions on the activities page

src/frontend/src/env/networks/networks.eth.env.ts
Two Etherscan API variables are not used anymore.
=> chore(frontend): remove unused variables for Etherscan API

src/frontend/src/eth/components/loaders/LoaderMultipleEthTransactions.svelte, src/frontend/src/tests/eth/components/loaders/LoaderMultipleEthTransactions.spec.ts
As a follow-up of https://github.com/dfinity/oisy-wallet/pull/6160, we also need to load Base and BNB transactions on the Activity page.
=> feat(frontend): load base and bnb transactions on the activities page

src/frontend/src/lib/components/qr/VipQrCodeModal.svelte
=> refactor(frontend): upgrades VipQrCodeModal to svelte 5

src/frontend/src/lib/components/rewards/RewardCard.svelte, src/frontend/src/lib/components/rewards/RewardsGroup.svelte
=> refactor(frontend): upgrades RewardCard to svelte 5

src/frontend/src/routes/(app)/rewards/+page.svelte
The name of the imported component should match the name of the component being imported.
- changes name of imported component
=> refactor(frontend): renames component usage

src/frontend/src/env/networks/networks-evm/networks.evm.bsc.env.ts, src/frontend/src/lib/components/hero/HeroContent.svelte, src/frontend/src/lib/derived/network.derived.ts, src/frontend/src/lib/styles/tailwind/theme-variables.ts, src/frontend/src/lib/utils/network.utils.ts, src/frontend/src/tests/lib/utils/network.utils.spec.ts
According to design, we define a specific `Hero` background for BNB Smart Chain (BSC) networks:
=> style(frontend): add specific `Hero` background for BSC networks

src/frontend/src/lib/components/sprinkles/Sprinkles.svelte
=> refactor(frontend): upgrades Sprinkles to svelte5

src/frontend/src/lib/components/rewards/RewardModal.svelte
=> refactor(frontend): upgrades RewardModal to svelte5

src/frontend/src/lib/components/hero/HeroContent.svelte
According to design, we rotate the `Hero` gradient of GLDT token and BNB Smart Chain (BSC) networks.
=> style(frontend): rotate `Hero` gradient for GLDT token and BSC network

HACKING.md
Refactoring the list of faucets to include EVM networks.
=> chore(docs): expand list of Ethereum and EVM faucets

src/frontend/src/env/eip155-chains.env.ts, src/frontend/src/eth/components/wallet-connect/WalletConnectSend.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendModal.svelte
Adding EVM networks to EIP-155 networks, used by WalletConnect.
=> feat(frontend): add EVM networks to EIP-155 chains

src/frontend/src/btc/components/convert/ConvertToCkBTC.svelte, src/frontend/src/icp-eth/components/convert/ConvertETH.svelte, src/frontend/src/icp/components/convert/ConvertToBTC.svelte, src/frontend/src/lib/components/buy/BuyButton.svelte, src/frontend/src/lib/components/hero/ButtonHero.svelte, src/frontend/src/lib/components/receive/ReceiveButton.svelte, src/frontend/src/lib/components/send/SendButton.svelte, src/frontend/src/lib/components/swap/SwapButton.svelte
When upgrading the `ButtonHero` component to svelte5 i forgot to also update the slot implementation of the component.
- Updates slot implementation
=> fix(frontend): fixes slot implementation of ButtonHero

src/frontend/src/lib/components/rewards/RewardEarningsCard.svelte
- Upgrades `RewardEarningsCard`
=> refactor(frontend): upgrades RewardEarningsCard to svelte 5

package-lock.json, package.json
This PR prepares the release of version v1.4.1.
=> chore(release): v1.4.1

src/frontend/src/lib/components/auth/AuthGuard.svelte
=> refactor(frontend): upgrades AuthGuard to svelte 5

src/frontend/src/lib/components/hero/HeroSignIn.svelte
=> refactor(frontend): upgrades HeroSignIn to svelte 5

src/frontend/src/lib/components/ui/ButtonGroup.svelte
=> refactor(frontend): upgrades ButtonGroup to svelte 5

src/frontend/src/lib/components/guard/RewardGuard.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
As we do now, we want to use an own derived function to access the modal data. We don't want to handle the `modal store` data in the component itself anymore.
- implements new derived function
=> feat(frontend): improves RewardStateModal data handling

src/frontend/src/icp/stores/ckbtc-utxos.store.ts, src/frontend/src/tests/icp/stores/ckbtc-utxos.store.spec.ts
Adding tests for store `ckBtcPendingUtxosStore`.
=> test(frontend): tests for store `ckBtcPendingUtxosStore`

src/frontend/src/tests/icp/stores/ic-pending-transactions.store.spec.ts
Adding tests for store `icPendingTransactionsStore`.
=> test(frontend): tests for store `icPendingTransactionsStore`

src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte
Same as with the Send flow, removing fallback value from the selectedEthereumNetwork store affected the modal functionality - in the Receive and HowToConvert flows, the store is undefined, therefore the modals did not render any content due to nonNullish check.
=> fix(frontend): selectedEthereumNetwork not defined in Receive/HowTo

src/frontend/src/tests/lib/config/auth-help.config.spec.ts, src/frontend/src/tests/lib/config/convert.config.spec.ts, src/frontend/src/tests/lib/config/send.config.spec.ts, src/frontend/src/tests/lib/config/swap.config.spec.ts
Adding tests for all the files in `lib/config` folder: mostly those are steps configurations.
=> test(frontend): add tests for steps configs

src/frontend/src/lib/components/ui/Badge.svelte, src/frontend/src/lib/types/style.ts
We need a new `disabled` state for the Badge.
- adds new state
=> feat(frontend): implements disabled badge state

src/frontend/src/lib/components/icons/lucide/IconShare.svelte
=> refactor(frontend): upgrades IconShare to svelte 5

src/frontend/src/env/reward-campaigns.json
Current end date shows May 7.
We need a bit more time to have the next episode ready.
Change May 7 to May 21
=> feat(frontend): Update rewards campaign end date

scripts/build.kong_backend.sh
Updated the KongSwap build script's repository URL to correctly retrieve the Candid file and Wasm, as the KongSwap team has changed the file paths.
Updated KONGSWAP_REPO_URL to a valid link
=> feat(frontend): updated kongSwap build script Repo URL

src/frontend/src/lib/components/send/KnownDestinations.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/send/KnownDestinations.spec.ts
To display recent destinations, we need to add a new component.
=> feat(frontend): implement KnownDestinations component

src/frontend/src/icp/derived/ic-transactions.derived.ts, src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts
We need to implement a new store for keeping information about known IC destinations.
=> feat(frontend): icKnownDestinations derived

src/frontend/src/btc/components/send/BtcSendForm.svelte, src/frontend/src/eth/components/send/EthSendForm.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp/components/send/IcSendForm.svelte, src/frontend/src/lib/components/send/SendDestination.svelte, src/frontend/src/lib/components/send/SendForm.svelte, src/frontend/src/lib/constants/test-ids.constants.ts, src/frontend/src/sol/components/send/SolSendForm.svelte, src/frontend/src/tests/btc/components/send/BtcSendForm.spec.ts, src/frontend/src/tests/eth/components/send/EthSendForm.spec.ts, src/frontend/src/tests/icp/components/send/IcSendForm.spec.ts, src/frontend/src/tests/lib/utils/send.utils.spec.ts, src/frontend/src/tests/sol/components/send/SolSendForm.spec.ts, vitest.config.ts
The next step is to update all the Send forms.
=> feat(frontend): updated Send forms for all networks

src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/eth/components/send/EthSendForm.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp/components/send/IcSendTokenWizard.svelte, src/frontend/src/lib/components/send/SendWizard.svelte, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
The next step is to update Send token wizard components.
=> feat(frontend): update Send token wizards

src/frontend/src/eth/derived/eth-transactions.derived.ts, src/frontend/src/lib/components/send/SendWizard.svelte, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte, src/frontend/src/tests/eth/derived/eth-transactions.derived.spec.ts
While breaking the feature PRs into smaller chunks, some leftovers were not cleaned up correctly.
=> feat(frontend): Send flow adjustments

src/frontend/src/tests/sol/utils/spl.utils.spec.ts
Created tests for SPL util `isTokenSplToggleable`.
=> test(frontend): add tests for `isTokenSplToggleable`

package-lock.json, package.json, src/frontend/src/tests/lib/components/tokens/ModalTokensList.spec.ts, src/frontend/src/tests/routes/layout.spec.ts, src/frontend/src/tests/utils/console.test-utils.ts
We want to pull in the latest changes for the `eslint-config-oisy-wallet` package.
* Ran `npm run update:oisy-eslint`
* CI should pass
* The pulled in changes should have been tested before being committed to their repositories.
=> build(frontend): Bump eslint-config-oisy-wallet

src/frontend/src/tests/sol/utils/sol-send.utils.spec.ts
Created some tests for the Solana send utils.
=> test(frontend): test suite for Solana send utils

src/frontend/src/tests/sol/utils/token.utils.spec.ts
Created some tests for the Solana token utils.
=> test(frontend): test suite for Solana token utils

src/frontend/src/tests/btc/utils/btc-transactions.utils.spec.ts
Including one more test for util `mapBtcTransaction`.
=> test(frontend): one more test for util `mapBtcTransaction`

src/frontend/src/eth/utils/erc20.utils.ts, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/derived/token.derived.ts, src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
Created some tests for the ERC20 utils. Furthermore there is a small typo in two functions names:
`icTokenEthereumUserToken` --> `isTokenEthereumUserToken`
`icTokenErc20UserToken` --> `isTokenErc20UserToken`
=> test(frontend): test suite for ERC20 utils

src/frontend/src/tests/btc/utils/token.utils.spec.ts
Some tests for the Bitcoin token utils.
=> test(frontend): test suite for Bitcoin token utils

src/frontend/src/tests/icp-eth/utils/token.utils.spec.ts
Created some tests for the ICP-ETH token utils.
=> test(frontend): test suite for ICP-ETH token utils

src/frontend/src/tests/icp/services/ic-transactions.services.spec.ts
Created tests for service `onTransactionsCleanUp`.
=> test(frontend): service `onTransactionsCleanUp`

src/frontend/src/tests/lib/constants/steps.constants.spec.ts
Small test for `addTokenSteps` to increase coverage.
=> test(frontend): add tests for `addTokenSteps`

src/frontend/src/tests/lib/utils/user-amount.utils.spec.ts
To complete the test coverage of util `validateUserAmount`, we add a few test cases with balance not provided.
=> test(frontend): add assertions cases for user-amount util `validateUserAmount`

src/frontend/src/lib/schema/post-message.schema.ts, src/frontend/src/tests/lib/workers/workers.spec.ts, src/frontend/src/tests/mocks/workers.mock.ts
We create small simple tests for the `onmessage` function of the workers.
=> test(frontend): simple tests for `onmessage` worker

src/frontend/src/tests/lib/canisters/backend.canister.spec.ts
A few cases were missing when mocking the backend canister interface to run the unittests. We add them in this PR.
=> test(frontend): complete error-testing of backend canister interface

src/frontend/src/lib/components/ui/ButtonIcon.svelte, src/frontend/src/lib/components/ui/CollapsibleBottomSheet.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
We need to integrate a new UI component and align existing components with the design specifications for consistency
- Updated styles for `ModalValue` and `CollapsibleBottomSheet` components
=> feat(frontend): adjusted modal value and collapsible bottom sheet

package-lock.json, package.json
This PR prepares the release of version `v1.4.5`.
=> chore(release): v1.4.5

src/frontend/src/btc/components/send/BtcUtxosFee.svelte, src/frontend/src/tests/btc/components/send/BtcUtxosFee.spec.ts
Updating `BtcUtxosFee` according to the new design. Also, adding missing tests.
=> feat(frontend): update BtcUtxosFee component

src/frontend/src/lib/components/manage/ManageTokens.svelte
We include DIP-20 tokens in the flow to save tokens.
=> feat(frontend): add DIP-20 tokens in flow for manage tokens

.github/workflows/update-next.yml
The phrasing of workflow update-next is a bit confusing.
=> chore(devops): improve phrasing of update-next

src/frontend/src/lib/components/swap/SwapDetailsKongSwap.svelte, src/frontend/src/tests/lib/components/swap/SwapDetailsKongSwap.spec.ts
Add a component to display details related to KongSwap providers to improve modularity and reuse.
Created new component for rendering KongSwap provider details
Covered new component with the tests
=> feat(frontend): added new kongSwap Provider details component

src/frontend/src/icp/components/send/IcSendReview.svelte, src/frontend/src/icp/components/send/IcSendTokenWizard.svelte, src/frontend/src/tests/icp/components/send/IcSendReview.spec.ts
Same as with the other networks, we need to update the Send review components.
=> feat(frontend): update IcSendReview components

src/frontend/src/lib/types/reward.ts, src/frontend/src/lib/utils/rewards.utils.ts, src/frontend/src/tests/lib/utils/rewards.utils.spec.ts
We want the ability to map the received eligibility data from the rewards canister into a data structure usable in our components.
- implements `EligibilityReport` mapping function
=> feat(frontend): implements mapping for EligibilityReport

src/frontend/src/lib/components/rewards/AllRewardsList.svelte, src/frontend/src/lib/components/rewards/RewardCard.svelte, src/frontend/src/lib/stores/reward.store.ts, src/frontend/src/tests/lib/components/rewards/RewardCard.spec.ts, src/frontend/src/tests/lib/components/rewards/RewardsGroup.spec.ts
To get a better reusablity we add a new `getCampaignEligibility` function to the `reward store`.
- adds `getCampaignEligibility` function
=> feat(frontend): adds getCampaignEligibility function to reward store

src/frontend/src/sol/services/sol-transactions.services.ts, src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
Preparing for PR https://github.com/dfinity/oisy-wallet/pull/6438, we need a service that will load the next Solana transactions based on the oldest timestamp. This will simplify the component. 
- Created wrapper around `loadNextSolTransactions` to include checks based on a minimum timestamp.
Added tests.
=> feat(frontend): service to load next Solana transactions by oldest

src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte, src/frontend/src/lib/components/send/SendModal.svelte
As the preparation for displaying known addresses based on network, we need to load all txs if Send token network is ETH.
=> feat(frontend): load all txs if Send token network is ETH

src/frontend/src/btc/derived/btc-transactions.derived.ts, src/frontend/src/eth/derived/eth-transactions.derived.ts, src/frontend/src/icp/derived/ic-transactions.derived.ts, src/frontend/src/lib/components/send/KnownDestination.svelte, src/frontend/src/lib/components/send/KnownDestinations.svelte, src/frontend/src/lib/types/transaction.ts, src/frontend/src/lib/types/transactions.ts, src/frontend/src/lib/utils/transactions.utils.ts, src/frontend/src/sol/derived/sol-transactions.derived.ts, src/frontend/src/tests/btc/derived/btc-transactions.derived.spec.ts, src/frontend/src/tests/eth/derived/eth-transactions.derived.spec.ts, src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts, src/frontend/src/tests/lib/components/send/KnownDestination.spec.ts, src/frontend/src/tests/lib/components/send/KnownDestinations.spec.ts, src/frontend/src/tests/lib/utils/transactions.utils.spec.ts, src/frontend/src/tests/sol/derived/sol-transactions.derived.spec.ts
We need to update the KnownDestinations components according to the new types.
=> feat(frontend): update KnownDestinations components

src/frontend/src/lib/components/swap/SwapWizard.svelte
Updated swap context types
Imported real Context Types for icTokenFeeStore and swapAmountsStore
=> fix(frontend): updated swap context types

src/frontend/src/evm/derived/networks.derived.ts, src/frontend/src/evm/polygon/derived/networks.derived.ts
Similar to the other networks, we create a derived store with all the enabled Polygon networks.
=> feat(frontend): create derived store for enabled Polygon networks

scripts/build.csp.mjs
Including Polygon providers URLs to the Content Security Policy.
=> build(frontend): add Polygon URLs to CSP

src/frontend/src/env/tokens/tokens-evm/tokens-polygon/tokens-erc20/tokens.usdt.env.ts
I forgot to update the network for USDT in Polygon.
=> fix(frontend): Correct network for USDT in Polygon

scripts/build.csp.mjs
For polygon we inquiry the [official gas station](https://docs.polygon.technology/tools/gas/polygon-gas-station/) for the fee. So we need to clear it in the CSP.
=> fix(build): add Polygon gas station to Content Security Policy

package-lock.json, package.json, scripts/add.tokens.erc20.mjs, scripts/build.metadata.mjs, src/frontend/src/eth/components/core/EthWalletAddress.svelte, src/frontend/src/eth/components/fee/FeeStoreContext.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte, src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/settings/SettingsModalEnabledNetworks.svelte, src/frontend/src/lib/components/transactions/AllTransactions.svelte, src/frontend/src/lib/components/ui/Responsive.svelte, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
Bump `@dfinity/eslint-config-oisy-wallet` to next and auto-fixing new lint rules.
=> chore(frontend): Bump lint library to next

src/frontend/src/lib/components/send/SendInputDestination.svelte, src/frontend/src/tests/lib/components/tokens/ModalTokensList.spec.ts, vitest.setup.ts
We need to set focus on the input on desktop when user opens the destination wizard step.
=> feat(frontend): autofocus on desktop for SendInputDestination

src/frontend/src/lib/i18n/en.json
Adding Polygon to the initial loader modal.
=> style(frontend): Add Polygon to initial modal steps

package-lock.json, package.json
This PR prepares the release of version `v1.4.7`.
=> chore(release): v1.4.7

src/frontend/src/lib/components/address/IconAddressType.svelte, src/frontend/src/lib/components/contact/AddressesBadge.svelte
Adds a badge component to show either the address type or the amount of addresses
=> feat(frontend): Adds AddressesBadge to be used in contact card later

src/frontend/src/env/tokens/tokens-erc20/tokens.dai.env.ts, src/frontend/src/env/tokens/tokens.erc20.env.ts, src/frontend/src/eth/utils/erc20.utils.ts, src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
Similar to others ERC20 tokens, we move the DAI token to the list of additional ERC20 tokens.
=> refactor(frontend): Move DAI token to additional ERC20 tokens

dfx.json, src/declarations/rewards/rewards.did, src/declarations/rewards/rewards.did.d.ts, src/declarations/rewards/rewards.factory.certified.did.js, src/declarations/rewards/rewards.factory.did.js
A newer version of the rewards canister is available that supports amounts larger than u64.
- Update the rewards canister version.
=> chore(rewards): Bump rewards canister version

src/frontend/src/icp/components/send/IcSendForm.svelte, src/frontend/src/icp/components/send/IcSendTokenWizard.svelte, src/frontend/src/lib/components/send/SendForm.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendWizard.svelte
We now can remove convert-related code from all IC send components.
=> refactor(frontend): remove convert-related code from IC send components

src/frontend/src/lib/components/address-book/EditContactNameStep.svelte
One more step towards removing non-null assertions: refactoring `EditContactNameStep` to adapt to nullish values of contact name.
=> refactor(frontend): remove non-null assertion from `EditContactNameStep`

src/frontend/src/eth/components/fee/FeeContext.svelte
One more step towards removing non-null assertions: refactoring `FeeContext` to adapt to nullish values of ETH address.
=> refactor(frontend): remove non-null assertion from `FeeContext`

src/frontend/src/lib/components/address-book/AddressBookModal.svelte
One more step towards removing non-null assertions: refactoring `AddressBookModal` to adapt to nullish values of `currentContact`.
=> refactor(frontend): remove non-null assertion from `AddressBookModal`

src/frontend/src/lib/components/networks/NetworkButton.svelte
Migrating component `NetworkButton `to Svelte 5.
Migrated the `NetworkButton `component to Svelte 5.
=> feat(frontend): migrate NetworkButton to Svelte 5

src/frontend/src/lib/components/address-book/AddressBookModal.svelte
One more step towards removing non-null assertions: more refactoring `AddressBookModal` to adapt to nullish values of `currentContact`.
=> refactor(frontend): remove more non-null assertion from `AddressBookModal`

.github/workflows/update-tokens.yml
It makes sense that the workflow that updates the tokens is triggered by changes on the tokens JSON files.
So that any PR that changes it will be updated accordingly.
=> feat(devops): Trigger update tokens workflow on files changes

src/frontend/src/lib/components/contact/ContactCard.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/contact/ContactCard.spec.ts, src/frontend/src/tests/mocks/contacts.mock.ts
Adds contact card component to displaying contacts in the address book
[vokoscreenNG-2025-05-21_17-33-04.webm](https://github.com/user-attachments/assets/ab7d1f2c-40b1-43aa-b107-26145100f538)
=> feat(frontend): Add contact card

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
Add WindogeXP token
Add the WindogeXP ICRC token
- Ledger: `wqihv-qyaaa-aaaak-afjoa-cai`
- Index: `7hwgv-uaaaa-aaaao-qjv7q-cai`
=> feat(frontend): add XP ICRC token

src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp-eth/services/cketh.services.ts, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendWizard.svelte
Finally, the last step of the refactoring is to remove unused props from SendModal.
=> refactor(frontend): remove unused props from the Send components

src/frontend/src/env/networks/networks.icrc.env.ts, src/frontend/src/env/tokens/tokens.icrc.json
Add Windoge98 (EXE) token
Add the Windoge98 (EXE) ICRC token
- Ledger: `rh2pm-ryaaa-aaaan-qeniq-cai`
=> feat(frontend): add EXE ICRC token

src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/tokens/TokenCard.svelte
Enabling usage of `oisySymbol` prop in components.
=> feat(frontend): Show Oisy Custom Symbol in frontend

src/frontend/src/lib/components/address-book/AddressBookModal.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/types/i18n.d.ts
Adds missing address book title
- Add edit contact title
- Reuse edit contact title for edit address book (should display the same)
=> feat(frontend): Cleanup address book titles

src/frontend/src/lib/utils/contact.utils.ts, src/frontend/src/tests/lib/utils/contact.utils.spec.ts
We need to create a mapper for Address -> ContactAddressUi.
=> feat(frontend): mapAddressToContactAddressUi util

src/frontend/src/lib/components/address-book/SaveAddressStep.svelte
For testing purposes a handler has been added to onClick, but it should be empty as the behavior is broken now.
See: https://github.com/dfinity/oisy-wallet/pull/7000#discussion_r2111968875
Revert back to empty onClick handler
=> fix(frontend): Include suggested changes SaveAddressStep

src/frontend/src/lib/components/address-book/AddressBookModal.svelte, src/frontend/src/lib/derived/contacts.derived.ts, src/frontend/src/tests/lib/derived/contacts.derived.spec.ts
We want to sort the contact list by names.
- Create derived store to check if contact store is initialized.
- Use the derived in `AddressBookModal` component.
- Create store to sort contacts.
- Use it in the component `AddressBookModal`.
Added tests.
=> feat(frontend): Sort contacts list

src/frontend/src/btc/derived/btc-contacts.derived.ts, src/frontend/src/eth/derived/eth-contacts.derived.ts, src/frontend/src/icp/derived/ic-contacts.derived.ts, src/frontend/src/sol/derived/sol-contacts.derived.ts, src/frontend/src/tests/btc/derived/btc-contacts.derived.spec.ts, src/frontend/src/tests/eth/derived/eth-contacts.derived.spec.ts, src/frontend/src/tests/icp/derived/ic-contacts.derived.spec.ts, src/frontend/src/tests/sol/derived/sol-contacts.derived.spec.ts
We need to implement network contacts stores that are gonna be used in the Address Picker send step.
=> feat(frontend): implement network contacts stores

src/frontend/src/env/dapp-descriptions.json
Label was not desired like that.
Change label.
=> feat(frontend): change button label for decideid dapp

src/frontend/src/lib/components/address-book/AddressBookModal.svelte
After updating an address the user should land on `Edit contact` step.
- improves update flow
https://github.com/user-attachments/assets/080e9d7d-8b6d-4a60-bf99-cf0289c34e0c
=> feat(frontend): improves update address flow

src/frontend/src/lib/components/send/SendDestinationTabs.svelte, src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/types/send.ts, src/frontend/src/tests/lib/components/send/SendDestinationTabs.spec.ts
Destination tab and selected contact vars should defined in the most parent component so we can access them in different send wizard steps.
=> feat(frontend): destination tab and selected contact vars

src/frontend/src/lib/utils/error.utils.ts
When replacing fields from an instance of Error, its message may contain either JSON-like key-value pairs or plain text. Therefore, we need to support and remove both JSON-style key patterns and plain text key patterns to ensure reliable cleanup.
- Improved buildTextPattern to support both quoted and unquoted key-value formats.
- Updated replaceErrorFields to apply both JSON-style and plain text regex patterns.
=> fix(frontend): fixed replaceErrorFields

src/frontend/src/btc/components/send/BtcSendReview.svelte, src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte, src/frontend/src/eth/components/send/EthSendReview.svelte, src/frontend/src/eth/components/send/EthSendTokenWizard.svelte, src/frontend/src/icp/components/send/IcSendReview.svelte, src/frontend/src/icp/components/send/IcSendTokenWizard.svelte, src/frontend/src/sol/components/send/SolSendReview.svelte, src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
To start using the new SendReview form design, we should pass `selectedContact` from wizard to the form.
=> feat(frontend): use selectedContact param in Send Review forms

src/frontend/src/lib/components/send/KnownDestination.svelte, src/frontend/src/lib/components/send/KnownDestinations.svelte, src/frontend/src/lib/components/send/SendContactName.svelte, src/frontend/src/lib/components/send/SendDestinationTabs.svelte, src/frontend/src/tests/lib/components/send/KnownDestination.spec.ts
We want to display contact data for a recently used address if it's available in the contacts object.
=> feat(frontend): display contact data in KnownDestination

src/frontend/src/lib/components/vip/VipRewardStateModal.svelte
- upgrades `VipRewardStateModal`
=> refactor(frontend): upgrades VipRewardStateModal to svelte5

src/frontend/src/icp/components/convert/IcConvertTokenWizard.svelte, src/frontend/src/lib/components/convert/ConvertModal.svelte, src/frontend/src/lib/components/convert/ConvertWizard.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendQrCodeScan.svelte
=> refactor(frontend): upgrades SendQrCodeScan to svelte5

src/frontend/src/lib/components/address/DestinationValue.svelte, src/frontend/src/lib/components/convert/ConvertAmountDisplay.svelte, src/frontend/src/lib/components/convert/ConvertFeeTotal.svelte, src/frontend/src/lib/components/convert/ConvertNetwork.svelte, src/frontend/src/lib/components/send/ReviewNetwork.svelte, src/frontend/src/lib/components/send/SendDataDestination.svelte, src/frontend/src/lib/components/swap/SwapDetailsIcp.svelte, src/frontend/src/lib/components/swap/SwapFee.svelte, src/frontend/src/lib/components/swap/SwapFees.svelte, src/frontend/src/lib/components/swap/SwapLiquidityFees.svelte, src/frontend/src/lib/components/swap/SwapNetworkFee.svelte, src/frontend/src/lib/components/swap/SwapProvider.svelte, src/frontend/src/lib/components/swap/SwapReview.svelte, src/frontend/src/lib/components/swap/SwapRoute.svelte, src/frontend/src/lib/components/ui/ModalValue.svelte
ModalValue is now migrated to Svelte 5.
=> refactor(frontend): migrate ModalValue to Svelte 5

src/frontend/src/lib/components/send/SendTokensList.svelte, src/frontend/src/lib/components/swap/SwapTokensList.svelte, src/frontend/src/lib/components/tokens/ModalTokensListItem.svelte
For component `ModalTokensListItem` it is ok to use directly `Token` type instead of `CardData`. Its usage will become more explicit.
=> refactor(frontend): Change input of `ModalTokensListItem` to be `Token`

src/frontend/src/icp/utils/icrc.utils.ts
I left an unnecessary check in util `mapIcrcToken` for the icon.
=> chore(frontend): Remove unnecessary nullish check in `mapIcrcToken`

src/frontend/src/sol/components/tokens/SolTokenModal.svelte, src/frontend/src/tests/sol/components/tokens/SolTokenModal.spec.ts
We now can update the design on SolTokenModal, as well as to switch from token to pageToken.
=> feat(frontend): SolTokenModal update

package-lock.json, package.json
We want to keep up-to-date with II playwright library.
=> chore(frontend): bump II playwright

src/frontend/src/lib/components/ui/ButtonNext.svelte
=> refactor(frontend): upgrades ButtonNext to svelte 5

src/frontend/src/lib/components/ui/CardAmountDescription.svelte
- upgrades `CardAmountDescription`
=> refactor(frontend): upgrades CardAmountDescription to svelte 5

src/frontend/src/lib/components/guard/RewardGuard.svelte, src/frontend/src/lib/types/reward.ts, src/frontend/src/lib/utils/rewards.utils.ts, src/frontend/src/tests/lib/components/guard/RewardGuard.spec.ts, src/frontend/src/tests/lib/utils/rewards.utils.spec.ts
Currently the sprinkles episode 3 is hardcoded but it should be loaded dynamically to also support future seasons. Soon season 4 of sprinkles will start.
- loads campaign dynamically
=> feat(frontend): loads campaign information dynamically

src/frontend/src/env/reward-campaigns.json
The end date of the active campaign should be changed to June 26.
- updates active campaign end date
=> feat(frontend): updates active campaign end date

src/frontend/src/lib/components/send/SendContacts.svelte
In component `SendContacts` we will change the logic of how the addresses are filtered, using case-sensitive logic. So, before that, we expand the logic maintaining the same flow, to be easier to modify after.
=> refactor(frontend): Expand logic of component `SendContacts`

src/frontend/src/lib/components/send/KnownDestinations.svelte
In component `KnownDestinations` we need to partially match the addresses based on network case-sensitiveness.
=> feat(frontend): Use case-sensitive partial comparison in component `KnownDestinations`

src/frontend/src/lib/components/transactions/Transaction.svelte
We need to match the alias in the transaction list based on network case-sensitiveness.
=> feat(frontend): Use network case-sensitiveness in transaction list alias

src/frontend/src/lib/components/address-book/DeleteAddressConfirmBottomSheet.svelte, src/frontend/src/lib/components/address-book/DeleteAddressConfirmContent.svelte, src/frontend/src/lib/components/address-book/DeleteContactConfirmBottomSheet.svelte
We can simplify  address book components by using BottomSheetConfirmationPopup.
=> refactor(frontend): BottomSheetConfirmationPopup in address book files

src/backend/backend.did, src/backend/src/lib.rs, src/backend/tests/it/custom_token.rs, src/declarations/backend/backend.did, src/declarations/backend/backend.did.d.ts, src/declarations/backend/backend.factory.certified.did.js, src/declarations/backend/backend.factory.did.js, src/declarations/icp_swap_factory/icp_swap_factory.did, src/declarations/icp_swap_factory/icp_swap_factory.did.d.ts, src/declarations/icp_swap_factory/icp_swap_factory.factory.certified.did.js, src/declarations/icp_swap_factory/icp_swap_factory.factory.did.js, src/declarations/icp_swap_pool/icp_swap_pool.did, src/declarations/icp_swap_pool/icp_swap_pool.did.d.ts, src/declarations/icp_swap_pool/icp_swap_pool.factory.certified.did.js, src/declarations/icp_swap_pool/icp_swap_pool.factory.did.js
BREAKING CHANGE: this PR includes a new BE method, therefore it contains did changes.
For deleting custom tokens (`icrc` and `spl`), we need to implement a new endpoint.
=> feat(backend)!: implement remove_custom_token

package-lock.json, package.json
This PR prepares the release of version `v1.5.2`.
=> chore(release): v1.5.2

src/frontend/src/icp/components/tokens/IcTokenModal.svelte, src/frontend/src/lib/components/tokens/TokenModal.svelte, src/frontend/src/tests/icp/components/tokens/IcTokenModal.spec.ts
Similar as with custom erc20 tokens, we want to enable the delete functionality for all unknown to OISY ICRC tokens.
=> feat(frontend): enable deletion of custom ICRC tokens

src/frontend/src/tests/icp/api/icp-ledger.api.spec.ts
For coverage, some tests for icp-ledger API methods.
=> test(frontend): Tests for icp-ledger API

src/frontend/src/env/avatar.env.ts
Introducing a feature flag for the Avatar functionality allows us to keep the code integrated but hidden from users until the feature is fully ready for release. This enables incremental development without impacting the live experience.
Added a feature flag to control visibility/activation of the Avatar component.
=> feat(frontend): add Avatar feature flag

src/frontend/src/lib/components/common/ListItem.svelte, src/frontend/src/lib/components/common/ModalListItem.svelte
To make the ListItem components more versatile and re-usable, we extend it with some additional snippets as well as adjust its styles.
=> feat(frontend): update ListItem components

src/frontend/src/lib/i18n/de.json
We added german support. Some texts were missing.
- texts from token edit/delete
=> chore(frontend): Add missing german texts

src/frontend/src/env/dapp-descriptions.json, src/frontend/src/lib/i18n/de.json, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/types/i18n.d.ts
Let's add Taggr to the carousel
- add Taggr to the carousel
**EN**
**DE**
=> feat(frontend): Add Taggr carousel card

src/frontend/src/icp/derived/ic-contacts.derived.ts, src/frontend/src/lib/constants/analytics.contants.ts
This PR fixes an issue with parsing a principal in Address picker.
=> fix(frontend): issue with parsing a principal in Address picker

package-lock.json, package.json, src/frontend/src/icp/derived/ic-contacts.derived.ts, src/frontend/src/lib/constants/analytics.contants.ts
This PR includes the v1.5.5 hotfix that was just released.
=> fix(frontend): address parsing issue

src/frontend/src/env/tokens/tokens-spl/tokens.spyx.env.ts, src/frontend/src/env/tokens/tokens.spl.env.ts, src/frontend/src/sol/assets/spyx.svg
Tokenized shares from https://xstocks.com/products
- add token SPYx
=> chore(frontend): Add xStock SPYx Solana token

src/frontend/src/sol/utils/sol-instructions.utils.ts, src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
Unfortunately, I missed a good part when managing cycles for the Solana RPC Canister: we need to send cycles more dynamically, since the number of requests is too elevated, and it consumes too many cycles.
For now, we just revert the usage of the Solana RPC Canister, and work on the cycles-management separately.
=> fix(frontend): Remove usage of Solana RPC canister because missing cycles

src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/hero/Balance.svelte
Adding fix for the Private mode Toast meessage to be shown only on P shortcode
Manual testing
=> feat(frontend): toast only on the shortcode

src/frontend/src/btc/components/send/BtcSendDestination.svelte, src/frontend/src/eth/components/send/EthSendDestination.svelte, src/frontend/src/icp/components/send/IcSendDestination.svelte, src/frontend/src/lib/components/hero/Header.svelte, src/frontend/src/lib/components/send/SendInputDestination.svelte, src/frontend/src/sol/components/send/SolSendDestination.svelte
Since we need to make an adjustment in that component, we upgrade it to svelte 5.
- Upgraded component to svelte 5
Manually tested, working
=> chore(frontend): Send input destination svelte 5

src/frontend/src/lib/api/backend.api.ts, src/frontend/src/lib/components/core/Menu.svelte, src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/guard/ShortcutGuard.svelte, src/frontend/src/lib/components/hero/Balance.svelte, src/frontend/src/lib/utils/privacy.utils.ts, src/frontend/src/tests/lib/utils/privacy.utils.spec.ts
Fix tracking of Privacy Mode plausible events 
Add the correct source of the trigger
=> feat(frontend): setPrivacy policy fix for plausible events 

src/frontend/src/eth/services/eth-balance.services.ts, src/frontend/src/eth/services/eth-transactions.services.ts, src/frontend/src/icp-eth/services/eth.services.ts, src/frontend/src/lib/components/rewards/UserSnapshotWorker.svelte, src/frontend/src/tests/eth/services/eth-balance.services.spec.ts, src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
The service `trackEvent` has an useful property to print a warning to console.
=> refactor(frontend): Replace console with property of `trackEvent` service

src/frontend/src/tests/icp/components/core/IcCkListener.spec.ts
For coverage, some base tests for component `IcCkListener`.
=> test(frontend): Component `IcCkListener`

package-lock.json, package.json, src/frontend/src/lib/components/signer/SignerPermissions.svelte
We want to pull in the latest changes for the `gix-components` package.
* Ran `npm run update:gix-cmp:next`
* CI should pass
* The pulled in changes should have been tested before being committed to their repositories.
=> build(frontend): Bump gix-components to next

src/frontend/src/tests/lib/components/core/WalletWorkers.spec.ts
Some tests for component `WalletWorkers`.
=> test(frontend): Component `WalletWorkers`

dfx.json, scripts/build.llm.sh, scripts/deploy.sh, scripts/did.delete.types.mjs, scripts/generate.sh, src/declarations/llm/index.d.ts, src/declarations/llm/llm.did, src/declarations/llm/llm.did.d.ts, src/declarations/llm/llm.factory.certified.did.js, src/declarations/llm/llm.factory.did.js
Similar to other "external" canister, we want to integrate the LLM canister into OISY. This PR includes all related build files, declarations and dfx.json update.
=> feat(build): add LLM canister declarations and build files

src/frontend/src/lib/components/exchange/ExchangeBalance.svelte, src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte, src/frontend/src/lib/components/transactions/AllTransactions.svelte, src/frontend/src/lib/components/transactions/AllTransactionsList.svelte, src/frontend/src/lib/components/transactions/AllTransactionsLoader.svelte, src/frontend/src/lib/derived/balances.derived.ts, src/frontend/src/lib/derived/network-tokens.derived.ts, src/frontend/src/lib/derived/tokens.derived.ts, src/frontend/src/routes/(app)/activity/+page.svelte, src/frontend/src/tests/lib/derived/network-tokens.derived.spec.ts, src/frontend/src/tests/lib/derived/tokens.derived.spec.ts, src/frontend/src/tests/utils/derived.test-utils.ts
Since we support `fungible` and `non-fungible` tokens, we want to have separate lists for those types.
- adds fungible tokens list
=> feat(frontend): adds fungible tokens list

src/frontend/src/tests/lib/api/llm.api.spec.ts
For better coverage, adding some basic tests for the LLM API methods.
=> test(frontend): LLM API tests

src/frontend/src/tests/lib/components/loaders/Loader.spec.ts
Some mocks of the `Loader` test cases were not correctly implemented. We fix it with this PR.
- fixes test cases
=> feat(frontend): improves Loader test cases

src/frontend/src/lib/components/ai-assistant/AiAssistantActionButton.svelte, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantActionButton.spec.ts
AiAssistantActionButton component:
=> feat(frontend): AiAssistantActionButton component

src/frontend/src/lib/components/ai-assistant/AiAssistantBotMessage.svelte, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantBotMessage.spec.ts
AiAssistantBotMessage component:
=> feat(frontend): AiAssistantBotMessage component

src/frontend/src/lib/utils/tokens.utils.ts
During the migration to Custom tokens from User tokens, in ERC20, I forgot to adapt the version when saving: it may happen that the versions of the tokens are not in sync (disconnection, logging out while saving, etc).
We verified at least one case where this would happen.
This fix, to be removed when the migration is over, adapt the version of the Custom tokens from their store.
Verified on that specific case and it worked.
=> fix(frontend): Adapt version of ERC20 Custom tokens from User tokens

src/frontend/src/lib/i18n/vi.json
We import languages files before we enable them in a later PR. This allows hubs to provide missing texts directly via PRs.
- add the vietnamese language file
\-
=> chore(frontend): Add Vietnamese language file

src/frontend/src/lib/i18n/cs.json
We import languages files before we enable them in a later PR. This allows hubs to provide missing texts directly via PRs.
- add cs language file
\-
=> chore(frontend): Add Czech language file

src/frontend/src/lib/components/ai-assistant/AiAssistantConsoleButton.svelte, src/frontend/src/lib/i18n/en.json, src/frontend/src/routes/(app)/+layout.svelte
This is the final PR of the basic AI console setup - we can now open/close it on both desktop and mobile screens.
=> feat(frontend): enable AI console

src/frontend/src/env/i18n.ts, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/stores/i18n.store.ts, src/frontend/src/lib/types/languages.ts
Cherry-picking PR https://github.com/dfinity/oisy-wallet/pull/7633 to add Italian language in release `v1.5.11`.
=> feat(frontend): Add Italian support

package-lock.json, package.json
This PR prepares the release of version v1.5.11.
=> chore(release): v1.5.11

package-lock.json, package.json
Introduce client-side image compression to reduce upload payloads and improve performance.
Added `"browser-image-compression": "^2.0.2"` to `package.json`
=> feat(frontend): add browser image compressor

src/frontend/src/lib/components/hero/Balance.svelte, src/frontend/src/lib/i18n/cs.json, src/frontend/src/lib/i18n/de.json, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/i18n/pt.json, src/frontend/src/lib/i18n/vi.json, src/frontend/src/lib/i18n/zh-CN.json, src/frontend/src/lib/types/i18n.d.ts
Adding the localization of the aria label in the Privacy mode toggle
=> chore(frontend): Localize aria label of privacy mode toggle

src/frontend/src/lib/config/swap.config.ts, src/frontend/src/lib/enums/wizard-steps.ts, src/frontend/src/lib/i18n/cs.json, src/frontend/src/lib/i18n/de.json, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/i18n/pt.json, src/frontend/src/lib/i18n/vi.json, src/frontend/src/lib/i18n/zh-CN.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/config/swap.config.spec.ts
As part of the cross-chain swap flow, we need show new wizard steps for tokens and filters. 
Added new wizard steps to the wizard-steps.ts
=> feat(frontend): added new swap wizard steps

src/frontend/src/lib/components/contact/EditAvatar.svelte
Fixed $derived state of the items into EditAvatar
=> fix(frontend): add changes to EditAvatar

scripts/build.icp_swap_factory.sh, scripts/build.icp_swap_pool.sh, src/declarations/icp_swap_factory/icp_swap_factory.did, src/declarations/icp_swap_factory/icp_swap_factory.did.d.ts, src/declarations/icp_swap_factory/icp_swap_factory.factory.certified.did.js, src/declarations/icp_swap_factory/icp_swap_factory.factory.did.js, src/declarations/icp_swap_pool/icp_swap_pool.did, src/declarations/icp_swap_pool/icp_swap_pool.did.d.ts, src/declarations/icp_swap_pool/icp_swap_pool.factory.certified.did.js, src/declarations/icp_swap_pool/icp_swap_pool.factory.did.js
We need to update the Pool and Factory canisters for the ICP Swap integration. This PR updates the URLs used to fetch these canisters in the build scripts.
- Updated the icpSwap Git URL in the build scripts.
- Adjusted the init methods for the Factory and Pool canisters accordingly.
=> chore(build): updated icp swap git url and adjusted init method

src/frontend/src/lib/components/core/WalletWorkers.svelte
Migrating component `WalletWorkers` to Svelte 5.
=> feat(frontend): Migrate component `WalletWorkers` to Svelte 5

src/frontend/src/lib/components/ai-assistant/AiAssistantShowContactsToolItem.svelte, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantShowContactsToolItem.spec.ts
AiAssistantShowContactsToolItem component:
=> feat(frontend): AiAssistantShowContactsToolItem component

src/frontend/src/lib/components/ai-assistant/AiAssistantShowContactsTool.svelte, src/frontend/src/lib/constants/ai-assistant.constants.ts, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantShowContactsTool.spec.ts
AiAssistantShowContactsTool component:
=> feat(frontend): AiAssistantShowContactsTool component

src/frontend/src/lib/components/ai-assistant/AiAssistantToolResults.svelte, src/frontend/src/lib/types/ai-assistant.ts, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantToolResults.spec.ts
AiAssistantToolResults component:
=> feat(frontend): AiAssistantToolResults component

src/frontend/src/lib/types/kongswap.ts, src/frontend/src/tests/lib/utils/exchange.utils.spec.ts, src/frontend/src/tests/lib/validation/kongswap.validation.spec.ts, src/frontend/src/tests/mocks/kongswap.mock.ts
The public KongSwap API has a breaking change - we need to adjust KongSwapTokenMetricsSchema accordingly.
=> feat(frontend): update KongSwapTokenMetricsSchema according to new specs

src/frontend/src/env/tokens/tokens-spl/tokens.honx.env.ts, src/frontend/src/env/tokens/tokens.spl.env.ts, src/frontend/src/sol/assets/honx.svg
Tokenized shares from https://xstocks.com/products
- add token HONx
=> chore(frontend): Add xStock HONx Solana token

src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/services/swap.services.ts, src/frontend/src/lib/types/swap.ts, src/frontend/src/tests/lib/services/swap-errors.services.spec.ts, src/frontend/src/tests/lib/services/swap.services.spec.ts
=> fix(frontend): renamed swap error key

src/frontend/src/lib/components/swap/SwapWizard.svelte
Added missing prop bind:failedSteps={swapFailedProgressSteps} in SwapWizard
=> fix(frontend): added missing prop

src/frontend/src/lib/types/ai-assistant.ts, src/frontend/src/lib/utils/ai-assistant.utils.ts, src/frontend/src/tests/lib/utils/ai-assistant.utils.spec.ts
We now need to introduce 2 helper methods that are going parse from contacts to "AI contacts" (with hidden addresses) and other way around.
=> feat(frontend): ai-assistant utils

src/frontend/src/lib/constants/ai-assistant.constants.ts
A few adjustments of the AI assistant system prompt.
=> feat(frontend): update AI assistant system prompt

src/frontend/src/lib/services/nft.services.ts, src/frontend/src/tests/lib/services/nft.services.spec.ts, src/frontend/src/tests/mocks/erc1155-tokens.mock.ts
The nft service implementation should also be able to load the nfts of `erc1155` contracts.
- updates service implementation
=> feat(frontend): updates nft service so that it also loads nfts of erc1155 contracts

package-lock.json, package.json, src/frontend/src/lib/components/swap/SwapAmountsContext.svelte, src/frontend/src/lib/components/swap/SwapWizard.svelte, src/frontend/src/lib/services/swap.services.ts, src/frontend/src/lib/types/swap.ts, src/frontend/src/tests/lib/services/swap.services.spec.ts
As we made a hotfix, this PR updates the main branch to reflect those changes and ensure both branches are in sync.
=> fix(frontend): pull version 1.6.3

src/frontend/src/lib/schema/nft.schema.ts, src/frontend/src/lib/services/nft.services.ts, src/frontend/src/tests/lib/services/nft.services.spec.ts
Nfts of erc1155 contracts do have balances. We want to be able to load this balances.
- load balances
=> feat(frontend): loads balances of nfts

src/frontend/src/lib/schema/nft.schema.ts, src/frontend/src/lib/types/nft.ts, src/frontend/src/tests/lib/components/nfts/NftCard.spec.ts
Soon we will work with nft collections which means we need a collection schema.
- introduces collection schema
=> refactor(frontend): introduces collection schema

src/frontend/src/lib/components/swap/SwapWizard.svelte
To better understand user behavior and improve analytics, this PR adds a new usdSourceValue property to the swap tracking event.
Added usdSourceValue to the trackEvent payload for both successful and failed swap events
=> feat(frontend): added new usdsourceValue to plausible event for swap

src/frontend/src/lib/components/nfts/NftCard.svelte, src/frontend/src/lib/components/nfts/NftsDisplayHandler.svelte, src/frontend/src/lib/schema/nft.schema.ts, src/frontend/src/lib/services/nft.services.ts, src/frontend/src/lib/stores/nft.store.ts, src/frontend/src/lib/utils/nfts.utils.ts, src/frontend/src/tests/lib/components/nfts/NftCard.spec.ts, src/frontend/src/tests/lib/services/nft.services.spec.ts, src/frontend/src/tests/lib/stores/nft.store.spec.ts, src/frontend/src/tests/lib/utils/nfts.utils.spec.ts, src/frontend/src/tests/mocks/nfts.mock.ts
To have a better naming we want to rename the nft contract to collection
- renames nft contract to collection
=> refactor(frontend): renames nft contract to collection

src/frontend/src/lib/components/ai-assistant/AiAssistantToolResults.svelte, src/frontend/src/lib/types/ai-assistant.ts
We need to update AI tool result type as it's possible the result of a tool parsing won't be available.
=> feat(frontend): update AI tool result type

src/frontend/src/lib/services/ai-assistant.services.ts
Adding missing JSDoc to the askLlm service.
=> chore(frontend): add missing JSDoc to askLlm service

src/frontend/src/lib/i18n/cs.json
We added new labels and texts
- also add the Czech translations
=> chore(frontend): Add missing Czech texts

src/frontend/src/lib/services/ai-assistant.services.ts, src/frontend/src/tests/lib/services/ai-assistant.services.spec.ts
Now we need to implement a service that is gonna parse and execute the LLM tool response.
=> feat(frontend): executeTool service

src/frontend/src/lib/services/ai-assistant.services.ts, src/frontend/src/tests/lib/services/ai-assistant.services.spec.ts
We can now connect the executeTool service with the askLlm function.
=> feat(frontend): use executeTool service

src/frontend/src/lib/schema/nft.schema.ts, src/frontend/src/lib/types/nft.ts, src/frontend/src/lib/utils/nfts.utils.ts
In order to keep naming more consistent, we update the naming of the NFT collecton types.
- Adjusted type namings
- Adjusted zod schema namings
=> refactor(frontend): Nft collection types

src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
fixes `eth-transactions.services.spec.ts` test case
=> refactor(frontend): fixes eth transactions test case

src/frontend/src/lib/i18n/pt.json
We received a latest file
- add latest pt.json file
=> chore(frontend): Update latest Portuguese translations

src/frontend/src/lib/utils/nfts.utils.ts, src/frontend/src/tests/lib/utils/nfts.utils.spec.ts
Implements new `findNewNftIds` utils function.
=> feat(frontend): implements findNewNftIds utils function

package-lock.json, package.json
This PR prepares the release of version `v1.6.5`.
=> chore(release): v1.6.5

src/frontend/src/lib/stores/nft.store.ts, src/frontend/src/tests/lib/stores/nft.store.spec.ts
Implements `updateSelectedNfts` nft store function
=> feat(frontend): implements updateSelectedNfts nft store function

src/frontend/src/eth/providers/alchemy.providers.ts, src/frontend/src/lib/services/nft.services.ts, src/frontend/src/tests/eth/providers/alchemy.providers.spec.ts, src/frontend/src/tests/lib/services/nft.services.spec.ts
When loading a user's owned NFTs, we also want to return their balance.
=> refactor(frontend): returns loaded balance with nft id

src/frontend/src/lib/stores/nft.store.ts
Fixes the nft comparison of the nft store's `addAll` function.
=> fix(frontend): fixes nft store function addAll

src/frontend/src/lib/components/loaders/LoaderNfts.svelte, src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts, src/frontend/src/tests/mocks/erc1155-tokens.mock.ts
When the application is running we want to check inan interval of 2 minutes if the user received some new erc1155 nfts. If new nfts were received, we want to load them.
=> feat(frontend): implements new erc1155 nft handling

src/frontend/src/lib/components/loaders/LoaderNfts.svelte, src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts
When the application is running we want to check in an interval of 2 minutes if the user removed some nfts. If nfts were removed, we want to also remove them from the application.
=> feat(frontend): handles removed nfts

src/frontend/src/lib/i18n/fr.json
We received an updated fr.json
- Update changed provides in this PR: https://github.com/dfinity/oisy-wallet/pull/8394
- "onchain" (one word) - maintained consistency with source material
- "tokens" - kept in English for crypto-native feel, avoiding "jetons" which feels dated
- Crypto terms preserved: DEX, AMM, Network Custody, DFINITY Foundation, ...
- Why Oisy? paragraphs
- dApps short descriptions
=> chore(frontend): Update French locales

src/frontend/src/eth/components/swap/SwapEthWizard.svelte, src/frontend/src/icp/components/swap/SwapIcpWizard.svelte, src/frontend/src/lib/components/swap/SwapReview.svelte, src/frontend/src/lib/components/swap/SwapWizard.svelte
Migrated SwapReview component to Svelte5
=> refactor(frontend): migrated swap review svelte5

src/frontend/src/env/networks/networks-evm/networks.evm.env.ts, src/frontend/src/eth/components/swap/SwapEthWizard.svelte, src/frontend/src/icp/components/swap/SwapIcpWizard.svelte, src/frontend/src/lib/components/swap/SwapReview.svelte, src/frontend/src/lib/components/swap/SwapWizard.svelte
We would need to render different fees for icp and evm networks, so we need to pass this component as Snippet.
Added ability to render SwapFees via snippet.
=> feat(frontend): added snippet for SwapFees in ReviewModal

src/frontend/src/lib/components/tokens/SendTokenReview.svelte
We need to extend `SendTokenReview` with some additional props to make it re-usable for the AI assistant console.
=> feat(frontend): update SendTokenReview component

src/frontend/src/lib/components/nfts/NftsDisplayHandler.svelte
We want that the displayed collections can be filtered by the `network` filter.
=> refactor(frontend): filters displayed collections

src/frontend/src/lib/types/ai-assistant.ts, src/frontend/src/lib/utils/ai-assistant.utils.ts, src/frontend/src/tests/lib/utils/ai-assistant.utils.spec.ts
We need to create a util that is going to parse review_send_token tool args.
=> feat(frontend): util for parsing review_send_token tool args

src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts
Sometimes the `LoaderNfts` test cases do have some unexpected behaviour. We want to resolve this.
=> fix(frontend): fixes LoaderNfts test cases

src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendIcToken.svelte, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendIcToken.spec.ts
In this PR, a new component for displaying the IC review_send_token tool has been added.
=> feat(frontend): AiAssistantReviewSendIcToken component

src/frontend/src/lib/components/privacy-policy/PrivacyPolicyLink.svelte, src/frontend/src/lib/components/terms-of-use/TermsOfUseLink.svelte, src/frontend/src/lib/i18n/ar.json, src/frontend/src/lib/i18n/cs.json, src/frontend/src/lib/i18n/de.json, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/i18n/fr.json, src/frontend/src/lib/i18n/hi.json, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/i18n/ja.json, src/frontend/src/lib/i18n/pl.json, src/frontend/src/lib/i18n/pt.json, src/frontend/src/lib/i18n/ru.json, src/frontend/src/lib/i18n/vi.json, src/frontend/src/lib/i18n/zh-CN.json, src/frontend/src/lib/types/i18n.d.ts
Same as the LicenseLink we add link components for the new Terms of Use and Privacy Policy.
Added components
Added texts
=> feat(frontend): Terms and privacy links

src/frontend/src/env/agreements.json, src/frontend/src/env/schema/env-agreements.schema.ts, src/frontend/src/env/types/env-agreements.ts
Adds the json with the update dates for the diffrent agreements.
- Added zod schema
- Added TS type
- Added json with initial dates set to today
=> chore(frontend): Env agreements

src/frontend/src/eth/components/swap/SwapEthWizard.svelte
=> fix(frontend): added check for swap type

src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendBtcToken.svelte, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendBtcToken.spec.ts
Some of the warning were not added to the send BTC AI tool. Additionally, we need to adjust code according to the latest changes in BTC send components.
=> feat(frontend): additional warnings in send BTC AI tool

src/frontend/src/lib/constants/ai-assistant.constants.ts, src/frontend/src/lib/services/ai-assistant.services.ts, src/frontend/src/lib/utils/ai-assistant.utils.ts, src/frontend/src/tests/lib/utils/ai-assistant.utils.spec.ts
To allow sending one single token on different networks, we need to introduce an additional argument for review_send_token tool.
=> feat(frontend): networkId argument for review_send_token tool

src/frontend/src/eth/components/swap/SwapEthWizard.svelte
Added new plausible property for swap error for Velora
=> feat(frontend): adde new analytics property to swaperror

package-lock.json, package.json
This PR prepares the release of version `v1.6.8`.
=> chore(release): v1.6.8

src/frontend/src/eth/types/erc1155-custom-token.ts, src/frontend/src/eth/types/erc721-custom-token.ts, src/frontend/src/lib/types/token-toggleable.ts
The new `section` field should be available on the erc721 custom token and erc1155 custom token to be able to update it's value.
=> feat(frontend): adds section field to erc721 and erc1155 custom token

src/frontend/src/lib/constants/ai-assistant.constants.ts
We need to simplify AI assistant system prompt and related tools.
=> feat(frontend): simplify AI assistant system prompt

src/frontend/src/lib/components/ai-assistant/AiAssistantMessages.svelte, src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendBtcToken.svelte, src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendEthToken.svelte, src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendIcToken.svelte, src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendSolToken.svelte, src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendTokenTool.svelte, src/frontend/src/lib/components/ai-assistant/AiAssistantToolResults.svelte, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendBtcToken.spec.ts, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendEthToken.spec.ts, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendIcToken.spec.ts, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendSolToken.spec.ts, src/frontend/src/tests/lib/components/ai-assistant/AiAssistantReviewSendTokenTool.spec.ts
To prevent some unwanted results, we'd like to make only the last review_send_token tool executable/
=> feat(frontend): make only the last review_send_token tool executable

src/frontend/src/lib/components/agreements/AcceptAgreementsCheckbox.svelte, src/frontend/src/lib/components/core/Modals.svelte, src/frontend/src/lib/derived/modal.derived.ts, src/frontend/src/lib/stores/modal.store.ts
We changed the prop for the NFTImageConsentModal but forgot to include the modal in the central Modals component and to adjust the stores.
- Extended modals component
- Adjusted stores
=> refactor(frontend): Nft consent modal

package-lock.json, package.json, src/frontend/src/sol/types/sol-instructions.ts, src/frontend/src/sol/utils/sol-instructions-token-2022.utils.ts, src/frontend/src/sol/utils/sol-instructions.utils.ts
To parse WalletConnect Solana instructions better, we include the parsers for Token-2022.
=> feat(frontend): Parse Solana Token-2022 instructions for WalletConnect

src/frontend/src/lib/components/nfts/NftCardSkeleton.svelte, src/frontend/src/lib/components/nfts/NftCollection.svelte, src/frontend/src/lib/components/nfts/NftCollectionList.svelte
The `NftCardSkeleton` should be more dynamic. Now it takes a parameter that indicates how many times the skeleton should be display.
=> refactor(frontend): updates NftCardSkeleton component

src/frontend/src/lib/components/loaders/Loader.svelte, src/frontend/src/lib/components/loaders/LoaderNfts.svelte, src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts
As long as the `NFT_ENABLED` feature flag is disabled no nft related data should be loaded.
=> feat(frontend): prevents loading nfts

src/frontend/src/lib/components/swap/SwapAmountsContext.svelte
Fix timer stop condition to prevent continuous swap-amounts requests
=> fix(frontend): fixed swapAmount stopTimer condition

src/frontend/src/lib/utils/nfts.utils.ts, src/frontend/src/tests/lib/utils/nfts.utils.spec.ts
We want to have a utils function to find the nfts that belongs to a specific network.
=> feat(frontend): implements findNftsByNetwork function

src/frontend/src/lib/api/backend.api.ts, src/frontend/src/tests/lib/api/backend.api.spec.ts
The next step is to implement the experimental features API method.
=> feat(frontend): add experimental features api method

src/frontend/src/lib/components/settings/SettingsExperimentalFeatures.svelte, src/frontend/src/lib/i18n/ar.json, src/frontend/src/lib/i18n/cs.json, src/frontend/src/lib/i18n/de.json, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/i18n/fr.json, src/frontend/src/lib/i18n/hi.json, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/i18n/ja.json, src/frontend/src/lib/i18n/pl.json, src/frontend/src/lib/i18n/pt.json, src/frontend/src/lib/i18n/ru.json, src/frontend/src/lib/i18n/vi.json, src/frontend/src/lib/i18n/zh-CN.json, src/frontend/src/lib/types/i18n.d.ts, src/frontend/src/tests/lib/components/settings/SettingsExperimentalFeatures.spec.ts
We now need to create a UI component for the new settings.
=> feat(frontend): SettingsExperimentalFeatures component

src/frontend/src/lib/components/ui/InputText.svelte, src/frontend/src/sol/components/tokens/SolAddTokenForm.svelte
We have issue while importing Solana token in ManageToken Modal.
- Update types for bindable values
- Remove fallback bindable value when input is undefined
=> fix(frontend): fixed import solana token for bindable value

src/frontend/src/lib/constants/ai-assistant.constants.ts
We want to teach LLM about OISY so it can support users with some basic questions about the wallet.
=> feat(frontend): provide more info about OISY to LLM via system prompt

src/frontend/src/eth/components/loaders/LoaderMultipleEthTransactions.svelte, src/frontend/src/tests/eth/components/loaders/LoaderMultipleEthTransactions.spec.ts
Migrate component `LoaderMultipleEthTransactions` to Svelte 5.
=> refactor(frontend): Migrate `LoaderMultipleEthTransactions` to Svelte 5

src/frontend/src/lib/components/rewards/RewardCard.svelte, src/frontend/src/lib/components/rewards/RewardModal.svelte
The loading of the campaign eligibility needs to happen inside a `derived` to be dynamic.
=> fix(frontend): fixes loading of campaign eligibility

src/frontend/src/env/reward-campaigns.json, src/frontend/src/lib/i18n/en.json
s1e5 is not yet fully ready
- extend s1e4
- s1e5 starts later. slightly change the card title to "coming soon"
=> chore(frontend): Extend Sprinkles s1e4 to Sept 24

src/frontend/src/lib/components/nfts/NftMetadataList.svelte
Theres no need to get the token first as we have a util which takes the collection directly to check if a token is erc1155
=> refactor(frontend): Simplify NftMetadataList

src/frontend/src/icp/types/ic-token.ts, src/frontend/src/icp/utils/icrc.utils.ts, src/frontend/src/tests/icp/utils/icrc.utils.spec.ts
We need an util method that checks is icrc token supports icrc2 standard
Added new util method isIcrcTokenSupportIcrc2
Covered new logic with tests.
=> feat(frontend): added isIcrcTokenSupportsIcrc2 util

src/frontend/src/lib/components/send/SendDestination.svelte, src/frontend/src/lib/components/send/SendForm.svelte, src/frontend/src/tests/lib/components/send/SendDestination.spec.ts
Migrating component `SendDestination` to Svelte 5.
=> refactor(frontend): Migrate `SendDestination` to Svelte 5

src/frontend/src/eth/components/send/EthSendAmount.svelte, src/frontend/src/eth/components/send/EthSendForm.svelte
Migrating component `EthSendAmount` to Svelte 5.
=> refactor(frontend): Migrate `EthSendAmount` to Svelte 5

src/frontend/src/env/dapp-descriptions.json, src/frontend/src/lib/i18n/ar.json, src/frontend/src/lib/i18n/cs.json, src/frontend/src/lib/i18n/de.json, src/frontend/src/lib/i18n/en.json, src/frontend/src/lib/i18n/fr.json, src/frontend/src/lib/i18n/hi.json, src/frontend/src/lib/i18n/it.json, src/frontend/src/lib/i18n/ja.json, src/frontend/src/lib/i18n/pl.json, src/frontend/src/lib/i18n/pt.json, src/frontend/src/lib/i18n/ru.json, src/frontend/src/lib/i18n/vi.json, src/frontend/src/lib/i18n/zh-CN.json, src/frontend/src/lib/types/i18n.d.ts
Carousel should also get a carousel card.
- add caffeine
=> chore(frontend): Add caffeine carousel card

scripts/update-agent.sh
The script `update-agent.sh` seems unused and therefore can be deleted.
=> chore(scripts): remove unused update-agent.sh script

src/frontend/src/btc/components/send/BtcSendDestination.svelte, src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
Migrate component `BtcSendDestination` to Svelte 5.
=> refactor(frontend): Migrate `BtcSendDestination` to Svelte 5

src/frontend/src/lib/components/common/MaxBalanceButton.svelte
Migrate component `MaxBalanceButton` to Svelte 5.
=> refactor(frontend): Migrate `MaxBalanceButton` to Svelte 5

src/frontend/src/lib/components/send/KnownDestinations.svelte, src/frontend/src/lib/components/send/SendContacts.svelte, src/frontend/src/lib/components/send/SendDestinationTabs.svelte, src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
Finish migrating component `SendDestinationTabs` to Svelte 5.
=> refactor(frontend): Completely migrate `SendDestinationTabs` to Svelte 5

src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte, src/frontend/src/sol/components/send/SolSendDestination.svelte
Migrate component `SolSendDestination` to Svelte 5.
=> refactor(frontend): Migrate `SolSendDestination` to Svelte 5

src/frontend/src/icp/components/send/IcSendDestination.svelte, src/frontend/src/lib/components/address/DestinationWizardStep.svelte, src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
Migrate component `IcSendDestination` to Svelte 5.
=> refactor(frontend): Migrate `IcSendDestination` to Svelte 5

src/frontend/src/lib/components/ui/Json.svelte
Migrating component `Json` to Svelte 5.
=> refactor(frontend): Migrate `Json` component to Svelte 5

src/frontend/src/lib/components/wallet-connect/WalletConnectForm.svelte, src/frontend/src/lib/components/wallet-connect/WalletConnectSession.svelte
Migrate component `WalletConnectForm` to Svelte 5.
=> refactor(frontend): Migrate `WalletConnectForm` component to Svelte 5

src/frontend/src/lib/components/nfts/NftImageConsentModal.svelte, src/frontend/src/tests/lib/components/nfts/NftImageConsentModal.spec.ts
If the media consent has not been given, do not display the external link icon.
Conditionally render the icon links
Added tests
=> refactor(frontend): Dont show media link in consent modal if no consent

src/frontend/src/lib/components/agreements/AcceptAgreementsModal.svelte, src/frontend/src/lib/services/user-agreements.services.ts, src/frontend/src/lib/types/user-agreements.ts, src/frontend/src/tests/lib/components/agreements/AcceptAgreementsModal.spec.ts, src/frontend/src/tests/lib/services/user-agreements.services.spec.ts
Since we are going to reuse it, we extract the service to accept the user agreements.
=> refactor(frontend): Extract service to accept user agreements

src/frontend/src/lib/schema/coingecko.schema.ts, src/frontend/src/lib/schema/network.schema.ts, src/frontend/src/lib/types/coingecko.ts
New schema for Coingecko Platform ID.
=> refactor(frontend): Create schema for Coingecko Platform ID

src/frontend/src/lib/components/send/SendData.svelte
We re-arrange all the slots of SendData to give a proper order, as per design.
=> refactor(frontend): Re-arrange slots in component `SendData`

src/frontend/src/lib/components/rewards/RewardStateModal.svelte
Small refactoring to simplify the `$effect` rune in component `RewardStateModal`.
=> refactor(frontend): Simplify logic in `RewardStateModal`

src/frontend/src/lib/stores/swap-icrc-tokens.store.ts, src/frontend/src/tests/lib/stores/swap-icrc-tokens.store.spec.ts
Refactored types for SwappableStore
=> refactor(frontend): changed types for swappableStore

src/frontend/src/tests/lib/services/auth.services.spec.ts
Adding tests for some auth services.
=> test(frontend): Suite test for auth services

src/frontend/src/lib/components/manage/ManageTokens.svelte, src/frontend/src/lib/components/send/SendModal.svelte, src/frontend/src/lib/components/send/SendTokenContext.svelte, src/frontend/src/lib/components/swap/SwapModal.svelte, src/frontend/src/lib/components/tokens/ModalNetworksFilter.svelte
Migrate component `SendModal` (and its direct children) to Svelte 5.
=> refactor(frontend): Migrate `SendModal` to Svelte 5

.github/workflows/frontend-checks.yml
To avoid conflicts, we make the artifacts for the coverage reports more unique.
=> feat(devops): Make coverage reports artifacts more unique

src/frontend/src/lib/components/about/AboutItem.svelte, src/frontend/src/lib/components/navigation/DocumentationLink.svelte, src/frontend/src/lib/components/ui/ExternalLink.svelte
To keep the UI consistent we adapt the hover color of the components in the header.
https://github.com/user-attachments/assets/b16c6bf6-7ad9-4c38-9d4a-d0f2057bf8bc
=> style(frontend): Adapt hover color for header elements
