- src/frontend/src/lib/components/auth/ButtonAuthenticateWithLicense.svelte
- src/frontend/src/lib/constants/analytics.contants.ts
To be more consistent, we rename the event `TRACK_COUNT_AUTHENTICATION_CLICK` to `TRACK_COUNT_SIGN_IN_CLICK`.
> refactor(frontend): rename event that click the authentication button

- src/frontend/src/tests/eth/rest/etherscan.rest.spec.ts
To help us with the explicit Ethereum transaction types, we set it in the test for Etherscan rest.
> chore(frontend): explicit type in test for Etherscan rest

- src/frontend/src/lib/types/transaction.ts
In the entire code we don't use the props `type`, `maxPriorityFeePerGas` and `maxFeePerGas` of interface EthersTransaction (and its derived). So we can remove them.
This will help us with the migration to `ethers` v6 too, since their types change.
> feat(frontend): remove unnecessary properties in Ethereum Transaction interface

- src/frontend/src/eth/providers/alchemy.providers.ts
- src/frontend/src/eth/providers/etherscan.providers.ts
- src/frontend/src/eth/rest/etherscan.rest.ts
- src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts
- src/frontend/src/lib/types/transaction.ts
- src/frontend/src/tests/eth/rest/etherscan.rest.spec.ts
- src/frontend/src/tests/eth/utils/transactions.utils.spec.ts
- src/frontend/src/tests/mocks/eth-transactions.mock.ts
We need to migrate to `ethers` v6: one of the biggest change was the deprecation of `BigNumber` in favour of built-in `bigint` (see [documentation](https://docs.ethers.org/v6/migrating/#migrate-bigint)).
Unfortunately, `alchemy-sdk` is still not updated to the newest version of `ethers` (issue https://github.com/alchemyplatform/alchemy-sdk-js/issues/489). That means that we have to adapt one to the other, until they bump it.
So, we set explicitly the types of `ethers` and adjust them in a mapper inside the `AlchemyProvider` class.
- Explicitly set props `gasLimit`, `gasPrice` and chainId in interface `EthersTransaction`.
- Create mapper in class `AlchemyProvider`.
- Prepare type `TransactionResponseWithBigInt` to use `ethers` props instead of `alchemy-sdk`.
- Adapt the rest of the usages. …
> feat(frontend): use BigInt instead of BigNumber in Ethers transaction interace

- src/frontend/src/eth/components/convert/ConvertToCkETH.svelte
- src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte
- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/components/fee/FeeStoreContext.svelte
- src/frontend/src/eth/components/send/ConvertToCkERC20.svelte
- src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
- src/frontend/src/tests/lib/components/convert/ConvertWizard.spec.ts
It was decided to stop updating fees when user is already on the conversion review step. To do that for ETH and ERC20, a few steps are required.
1. Move fee context initialization from EthConvertTokenWizard to respective parent component (same as it's done for BTC) - ConvertToCkERC20 and ConvertToCkETH. The reason is that the wizard is being rerendered (and therefore fee context is reset) on each step change.
2. Stop observing when on the REVIEW step.
3. Update FeeContext to not trigger `updateFee` method on 
Existing tests are updated. Also, tested both flows manually.
> feat(frontend): do not update fees on ETH/ERC20 convert review step

- .github/workflows/binding-checks.yml
One of [zizmor security suggestions](https://woodruffw.github.io/zizmor/audits/#template-injection) is to disallow possible injections via template expansions. So we remove them in CI `binding-checks`, in favour of env variables.
> refactor(devops): remove possible attacker-controllable code in CI for binding checks

- .github/actions/deploy-backend/action.yml
- .github/actions/oisy-backend/action.yml
- .github/workflows/backend-checks.yml
- .github/workflows/backend-tests.yml
- .github/workflows/deploy-to-environment.yml
One of [zizmor security suggestions](https://woodruffw.github.io/zizmor/audits/#unpinned-uses) is to pin the third party actions to a specific commit, to avoid possible liabilities. So we pin [actions/cache to version v4.2.3](https://github.com/actions/cache/tree/v4.2.3).
> refactor(devops): pin actions/cache to specific version

- src/frontend/src/tests/routes/layout.spec.ts
As per new lint rule (PR https://github.com/dfinity/oisy-wallet/pull/5675),  we should avoid using `import()` type annotations. So we remove it.
> refactor(frontend): use importOriginal in tests for layout page

- .github/actions/create-pr/action.yml
One of [zizmor security suggestions](https://woodruffw.github.io/zizmor/audits/#unpinned-uses) is to pin the third party actions to a specific commit, to avoid possible liabilities. So we pin [peter-evans/create-pull-request to version v6.0.5](https://github.com/peter-evans/create-pull-request/tree/v6.0.5).
> refactor(devops): pin peter-evans/create-pull-request to specific version

- .github/actions/docker-build-backend/action.yml
- .github/actions/docker-build-base/action.yml
One of [zizmor security suggestions](https://woodruffw.github.io/zizmor/audits/#unpinned-uses) is to pin the third party actions to a specific commit, to avoid possible liabilities. So we pin [docker/setup-buildx-action to version v3.10.0](https://github.com/docker/setup-buildx-action/tree/v3.10.0) and [docker/build-push-action to version v5.4.0](https://github.com/docker/build-push-action/releases/tag/v5.4.0).
> refactor(devops): pin docker actions to specific version

- .github/actions/release-notes/action.yml
One of [zizmor security suggestions](https://woodruffw.github.io/zizmor/audits/#unpinned-uses) is to pin the third party actions to a specific commit, to avoid possible liabilities. So we pin [release-drafter/release-drafter to version v6.1.0](https://github.com/release-drafter/release-drafter/tree/v6.1.0).
> refactor(devops): pin release-drafter/release-drafter to specific version

- .github/actions/prepare/action.yml
One of [zizmor security suggestions](https://woodruffw.github.io/zizmor/audits/#unpinned-uses) is to pin the third party actions to a specific commit, to avoid possible liabilities. So we pin [actions/setup-node to version v4.3.0](https://github.com/actions/setup-node/tree/v4.3.0).
> refactor(devops): pin actions/setup-node to specific version

- src/frontend/src/icp/schedulers/ic-wallet-balance-and-transactions.scheduler.ts
- src/frontend/src/icp/workers/icp-wallet.worker.ts
- src/frontend/src/icp/workers/icrc-wallet.worker.ts
- src/frontend/src/tests/icp/workers/ic-wallet-balance-and-transactions.worker.spec.ts
Technically speaking, the scheduler/worker for the ICRC wallets fetches both transactions and balance. Since we are going to change the logic a bit to have different functions internally, one for transactions and one for balance, it seems correct to rename `IcWalletTransactionsScheduler` to `IcWalletBalanceAndTransactionsScheduler`, even if a little verbose.
> refactor(frontend): IcWalletTransactionsScheduler --> IcWalletBalanceAndTransactionsScheduler

- src/frontend/src/icp/schedulers/ic-wallet-balance-and-transactions.scheduler.ts
- src/frontend/src/icp/workers/icp-wallet.worker.ts
- src/frontend/src/icp/workers/icrc-wallet.worker.ts
In PR https://github.com/dfinity/oisy-wallet/pull/5708 I forgot to rename the loading function inside the ICRC wallet worker: for consistency we rename it from `getTransactions` to `getBalanceAndTransactions`.
> refactor(frontend): rename loading function for ICRC wallet worker

- src/frontend/src/icp-eth/components/convert/ConvertETH.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
We are using the enabled/disabled networks. That means that we need to hide the CK-conversion buttons in the ICRC tokens in case Ethereum networks are disabled.
- Simplify component `ConvertEth` to have a reusable `isNetworkDisabled` reactive variable.
- Use the variable to disable the conversion button (for good measure).
- Create derived store `ckEthereumNativeTokenEnabledNetwork` that identifies if there is a twin token network enabled.
- Use the new store in ethToCkETHEnabled and erc20ToCkErc20Enabled.
- I moved the last two derived store at the end of the file, since the declaration was being done after them.
Local replica:
https://github.com/user-attachments/assets/e47e594c-0cd0-4ca8-8ca6-d202f8507802
> feat(frontend): hide ck conversion button when Ethereum is disabled

- src/frontend/src/lib/components/convert/ConvertModal.svelte
- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/utils/wizard-modal.utils.ts
- src/frontend/src/tests/lib/utils/wizard-modal.utils.spec.ts
The function `goToWizardSendStep` should be renamed to `goToWizardStep` since it is not only used for the `send` flow.
- renames function
> feat(frontend): renames goToWizardStep function

- src/frontend/src/lib/styles/global/gix.scss
The modal contents are not taking full width for a certain screen width region.
Force max width to 100%
Before:
After:
> fix(frontend): Fix modal content width

- src/frontend/src/lib/components/auth/AuthGuard.svelte
- src/frontend/src/lib/components/auth/ButtonAuthenticateWithLicense.svelte
- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/stores/modal.store.ts
When a user starts the login process and then closes it, the new help modal should appear.
- opens auth help modal
https://github.com/user-attachments/assets/5d6f5788-756a-4e85-990f-171303aed707
> feat(frontend): uses auth help modal

- src/frontend/src/lib/components/auth/ButtonAuthenticateWithLicense.svelte
- src/frontend/src/lib/constants/analytics.contants.ts
Safari expects popups to be triggered directly by a user interaction, such as a click event. If anything interferes with that interaction—like an intermediate event handler—Safari considers it suspicious, blocks the popup, and requires the user to manually confirm its opening.
This is what's currently happening: the addition of a track event between the click action and the sign-in with Internet Identity (which opens in a popup) breaks the expected flow.
It's also worth noting that even if the user manually confirms the popup, the sign-up process will still fail, as communication between the dapps will be blocked.
The issue currently occurs on production.
- Delete / remove track event for analytics
Issue replicated locally.
> fix(frontend): remove track event which breaks sign-on on Safari

- .github/workflows/deploy-to-environment.yml
- canister_ids.json
- dfx.json
- scripts/build.ic-domains.test.expected
- scripts/domains.json
We would like more test environments
- Add test networks `test_fe_5` and `test_fe_6`.
Canisters have been added to cycleops
Added the same controllers as fe1:
```
$ dfx canister info frontend --network test_fe_1
Controllers: 2yjpj-uumzi-wnefi-5tum7-qt6yq-7gtxo-i4jt5-enll5-pma6q-2gild-mqe 4jngj-yiaaa-aaaal-ajk5q-cai 5vdms-kaaaa-aaaap-aa3uq-cai bzhxb-2565m-do3pw-yqhb3-jon2m-phepr-lccqh-zv7qq-q52q2-ognw4-yqe cvthj-wyaaa-aaaad-aaaaq-cai octm5-iokwb-gqpnh-ex5pj-cxu6r-tewzp-eqeti-c4zte-qiuge-7mw3m-mqe rwwce-664pe-wijgn-qwcil-ufg26-rr23o-6wyhl-nga3p-2oejc-dpw52-cae vfm3e-ya34n-35cug-tvdt3-yajjv-ct5pn-a5j43-djtk7-ipzr7-22fv3-iqe yit3i-lyaaa-aaaan-qeavq-cai yo6ep-dyaaa-aaaal-ajs6q-cai
$ for user in 2yjpj-uumzi-wnefi-5tum7-qt6yq-7gtxo-i4jt5-enll5-pma6q-2gild-mqe 4jngj-yiaaa-aaaal-ajk5q-cai …
```
> feat(devops): Add testnets 5&6

- package-lock.json
- package.json
Resolve another Vite server vunerability ([GHSA-356w-63v5-8wf4](https://github.com/vitejs/vite/security/advisories/GHSA-356w-63v5-8wf4))
- Bump vite v6.2.6
> build(frontend): bump vite (GHSA-356w-63v5-8wf4)

- src/frontend/src/lib/components/auth/LandingPage.svelte
- src/frontend/src/lib/components/hero/HeroSignIn.svelte
On Safari the auth help modal was offset initially presumably due to a rendering bug.
We could solve the issue by placing the modal on the root of the page instead of in a nested element.
Tested on FE3 on Stefans machine.
> fix(frontend): Fixes auth help modal on Safari

- src/frontend/src/lib/components/auth/SigningInHelpLink.svelte
> style(frontend): SigningInHelpLink alignment on mobile

- src/frontend/src/eth/components/send/SendReviewNetwork.svelte
In the network icons refactoring we missed one of the logos.
Updated so it uses the NetworkLogo component
#Tests
> fix(frontend): Update missing network logo

- src/frontend/src/lib/services/analytics.services.ts
Currently, Juno analytics is disabled across all environments (PROD, BETA, STAGING, etc.) to ensure that Plausible analytics is the sole tracking solution, preventing any potential asynchronous issues.
Disabling Juno analytics for all environments to ensure consistency in tracking.
> fix(frontend): disabled juno analytics for all env

- package-lock.json
- package.json
Removed the Juno analytics packages, as we are now using Plausible for tracking and no longer need Juno.
Removed the Juno analytics from package.json and package.lock.json
> feat(frontend): removed junobuild/analytics packages

- .github/workflows/frontend-update-coverage-thresholds.yml
To have some wiggle room and not get bombed with PRs, we round the thresholds to the closest (lower) integer.
Run with CI https://github.com/dfinity/oisy-wallet/actions/runs/14444846353 and created PR https://github.com/dfinity/oisy-wallet/pull/5843
> feat(devops): round vitest coverage thresholds to floor integer

- dfx.json
- src/declarations/rewards/rewards.did
- src/declarations/rewards/rewards.did.d.ts
- src/declarations/rewards/rewards.factory.certified.did.js
- src/declarations/rewards/rewards.factory.did.js
- src/frontend/src/lib/api/reward.api.ts
- src/frontend/src/lib/canisters/reward.canister.ts
- src/frontend/src/lib/services/reward.services.ts
- src/frontend/src/tests/lib/services/reward.services.spec.ts
- vitest.config.ts
A new release of the rewards canister is available.
- Bump the rewards canister version to 0.3.1:
- Implements the referrer logic
- Adds return values to `set_referrer()` to explain why a given call might fail.
CI should update bindings.
> chore(rewards): Bump rewards canister

- scripts/deploy.sh
Two deploy lies are unneeded.
- mkdir is not needed, as the commands that care do (and should) create the directory themselves.
- Downloading Wasms is also not needed, as the relevant commands do that themselves
Existing CI
> chore(devops): Delete unneeded lines

- dfx.json
- scripts/build.ckbtc_minter.args.sh
- scripts/build.ckbtc_minter.sh
- scripts/deploy.ckbtc.sh
`dfx deploy X` should just work for all canisters.
- Set default arguments for `ckbtc_minter`, so that `dfx deploy` just works.
Existing CI should suffice
> chore(devops): dfx deploy ckbtc_minter

- src/frontend/src/lib/components/auth/AuthHelpIdentityForm.svelte
- src/frontend/src/lib/components/auth/AuthHelpOtherForm.svelte
- src/frontend/src/lib/components/dapps/DappModal.svelte
- src/frontend/src/lib/components/referral/ReferralCodeModal.svelte
- src/frontend/src/lib/components/ui/ExternalLink.svelte
Instead of defining the `flex-row-reverse` of external links over the `styleClass` we added a `rowReverse` flag.
- adds `rowReverse` flag on external link
> feat(frontend): adds rowReverse flag to ExternalLink.svelte

- src/frontend/src/lib/rest/blockchain.rest.ts
- src/frontend/src/tests/btc/workers/btc-wallet.worker.spec.ts
- src/frontend/src/tests/lib/rest/blockchain.rest.spec.ts
- src/frontend/src/tests/mocks/blockchain.mock.ts
Some of the Blockchain API calls require the CORS parameter turned on (see [documentation](https://www.blockchain.com/explorer/api/q)). Otherwise it raises an error:
**Credits to @dominikayyildiz** 
Added the CORS parameter to `fetchBlockchainApi`
Added some unittests, but I tested in test environment:
> fix(frontend): enable CORS params in Blockchain API calls

- src/frontend/src/tests/sol/components/send/SolSendForm.spec.ts
- src/frontend/src/tests/sol/components/tokens/SolTokenMenu.spec.ts
- src/frontend/src/tests/sol/derived/sol-transactions.derived.spec.ts
- src/frontend/src/tests/sol/schedulers/sol-wallet.scheduler.spec.ts
- src/frontend/src/tests/sol/services/sol-address.services.spec.ts
- src/frontend/src/tests/sol/services/sol-signatures.services.spec.ts
- src/frontend/src/tests/sol/services/sol-transactions.services.spec.ts
- src/frontend/src/tests/sol/utils/sol-instructions.utils.spec.ts
- src/frontend/src/tests/sol/utils/sol-sign.utils.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few issues. So, in preparation, for now we apply the rule [vitest/padding-around-all](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/padding-around-all.md) on the `sol` test folder.
> chore(frontend): format sol tests with vitest/padding-around-all

- src/frontend/src/tests/icp/components/send/IcSendForm.spec.ts
- src/frontend/src/tests/icp/derived/ckbtc-transactions.derived.spec.ts
- src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts
- src/frontend/src/tests/icp/schema/ic-token.schema.spec.ts
- src/frontend/src/tests/icp/services/icrc.services.spec.ts
- src/frontend/src/tests/icp/utils/map-icrc-data.spec.ts
- src/frontend/src/tests/icp/workers/ic-wallet-balance-and-transactions.worker.spec.ts
- src/frontend/src/tests/icp/workers/ic-wallet-balance.worker.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few issues. So, in preparation, for now we apply the rule [vitest/padding-around-all](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/padding-around-all.md) on the `icp` test folder.
> chore(frontend): format icp tests with vitest/padding-around-all

- src/frontend/src/tests/eth/components/loaders/LoaderMultipleEthTransactions.spec.ts
- src/frontend/src/tests/eth/components/send/EthSendForm.spec.ts
- src/frontend/src/tests/eth/services/eth-balance.services.spec.ts
- src/frontend/src/tests/eth/services/eth-transactions-batch.services.spec.ts
- src/frontend/src/tests/eth/utils/qr-code.utils.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few issues. So, in preparation, for now we apply the rule [vitest/padding-around-all](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/padding-around-all.md) on the `eth` test folder.
> chore(frontend): format eth tests with vitest/padding-around-all

- src/frontend/src/tests/btc/derived/btc-pending-sent-transactions.derived.spec.ts
- src/frontend/src/tests/btc/schema/btc-post-message.schema.spec.ts
- src/frontend/src/tests/btc/stores/btc-pending-sent-transactions.store.spec.ts
- src/frontend/src/tests/btc/workers/btc-wallet.worker.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few issues. So, in preparation, for now we apply the rule [vitest/padding-around-all](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/padding-around-all.md) on the `btc` test folder.
> chore(frontend): format btc tests with vitest/padding-around-all

- src/shared/src/types/token.rs
The user token types are for EVM only.  This is not clear from the Rustdoc.
- Make it clear in the `UserToken` types that they are for EVM only.
N/A
> docs(shared): User token comments

- src/shared/src/types/network.rs
Network IDs are fragmented in the code, with different systems in different parts of the code.
- Add a network ID that:
- Supports arbitrary EVM network IDs, as specified in chainlist.org
- Groups mainnet & testnets
The type is currently unused.
> feat(shared): Define network IDs

- src/frontend/src/tests/btc/workers/btc-wallet.worker.spec.ts
- src/frontend/src/tests/icp/workers/ic-wallet-balance-and-transactions.worker.spec.ts
- src/frontend/src/tests/icp/workers/ic-wallet-balance.worker.spec.ts
- src/frontend/src/tests/sol/schedulers/sol-wallet.scheduler.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few issues. So, in preparation, for now we apply the rule [vitest/prefer-hooks-in-order](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-hooks-in-order.md) that enforces a specific order for hooks:
```ts
// consistent order of hooks
['beforeAll', 'beforeEach', 'afterEach', 'afterAll']
```
> refactor(frontend): sort hooks in tests

- src/frontend/src/tests/lib/schema/network.schema.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises quite a few issues. So, in preparation, for now we apply the rule [vitest/no-commented-out-tests](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-commented-out-tests.md) that suggests to use the `.skip` clause instead of commenting tests.
> refactor(frontend): skip tests instead of commenting them

- src/frontend/src/tests/eth/utils/transactions.utils.spec.ts
In the tests for `mapEthTransactionUi` util, the last one was not being called correctly: it should verify that it maps an ID to `undefined` if the transaction hash does not exist. However, since `.toBeUndefined` was not being called, it was giving false positives.
Now that we fix it, we can see that, in fact, the utils maps it not to be `undefined` but an empty string.
> fix(frontend): test for `mapEthTransactionUi` was not being called correctly

- src/frontend/src/lib/components/convert/ConvertContexts.svelte
The following 2 convert-related contexts will be re-used multiple times, therefore it makes sense to create a separate component for that (similar as with the send context).
> feat(frontend): ConvertContexts component

- src/frontend/src/lib/components/address-book/Avatar.svelte
- src/frontend/src/lib/components/icons/IconAvatar.svelte
An avatar circle is needed in multiple components of the address book. In order to not reimplement this functionality everywhere, this PR adds a gneral purpose avatar component.
Out of scope: Different colors since it is not decided yet which colors will be available and how the color will be selected.
Compare: https://www.figma.com/design/dUNegIE5geiWu7916IC07c/6.-OISY---Theme-library?node-id=7346-24689&t=ijJPPUCQYntRRkHa-0
Add avatar component.
> feat(frontend): Add avatar component

- .github/workflows/deploy-to-environment.yml
We are using Plausible instead of Juno, so we remove the env variables from the deployment CI.
> chore(devops): remove Juno env variables form deployment CI

- src/frontend/src/eth/components/wallet-connect/WalletConnectSendReview.svelte
- src/frontend/src/eth/services/eth-transaction.services.ts
- src/frontend/src/eth/utils/transactions.utils.ts
- src/frontend/src/icp-eth/utils/cketh-transactions.utils.ts
- src/frontend/src/tests/eth/utils/transactions.utils.spec.ts
Instead of having 2 different functions, it makes sense to re-use a single implementation.
> refactor(frontend): reuse decodeErc20AbiDataValue for ckERC20 txs

- src/frontend/src/env/networks/networks-evm/networks.evm.env.ts
- src/frontend/src/lib/components/guard/AddressGuard.svelte
- src/frontend/src/lib/components/loaders/Loader.svelte
- src/frontend/src/lib/components/receive/ReceiveAddresses.svelte
- src/frontend/src/lib/derived/networks.derived.ts
We should include the EVM networks in the checks to load/verify the ETH address, since it is the same address for all of them. So, we create derived stores that are a mirror of the Ethereum ones and, apart form the ck-conversions, use them in the same exact code.
- Create lists of EVM supported networks (mainnet and testnet).
- Derived store `networkEvmMainnetEnabled` that verifies if any EVM mainnet networks is enabled.
- Derived store `networkEvmTestnetEnabled` that verifies if any EVM testnet networks is enabled.
- Use the new derived stores in the same place as the respective Ethereum stores (apart form ck-conversions).
Current tests are sufficient.
> feat(frontend): check for EVM enabled networks for the address loaders

- src/frontend/src/env/networks/networks-evm/networks.evm.base.env.ts
- src/frontend/src/env/networks/networks-evm/networks.evm.bsc.env.ts
- src/frontend/src/env/networks/networks.btc.env.ts
- src/frontend/src/env/networks/networks.eth.env.ts
- src/frontend/src/env/networks/networks.sol.env.ts
- src/frontend/src/lib/utils/env.networks.utils.ts
- src/frontend/src/tests/lib/utils/env.networks.utils.spec.ts
We are adding more networks, so to avoid repetition of code, we can create utils re-used for all the chains with different params.
In this case, we create an util that defines the supported tokens for a chain, and we use it in the env constants.
- Create util that replicate existing code of `SUPPORTED_BASE_NETWORKS`, `SUPPORTED_BSC_NETWORKS`, `SUPPORTED_BITCOIN_NETWORKS`, `SUPPORTED_ETHEREUM_NETWORKS` and `SUPPORTED_SOLANA_NETWORKS`.
Added new tests.
> feat(frontend): util to define the supported tokens for a specific chain

- src/frontend/src/icp/components/convert/HowToConvertEthereumWizardSteps.svelte
- src/frontend/src/lib/enums/wizard-steps.ts
The following wizard steps will be re-used in both Receive and HowTo flows, therefore it makes sense to make them re-usable.
> feat(frontend): HowToConvertEthereumWizardSteps component

- src/frontend/src/tests/icp/components/info/InfoBitcoin.spec.ts
Adding missing tests for InfoBitcoin to increase an overall test coverage.
> test(frontend): add tests for InfoBitcoin

- src/frontend/src/lib/config/convert.config.ts
One of the preparations needed for the next steps - we need to export ConvertWizardStepsParams.
> refactor(frontend): export ConvertWizardStepsParams

- src/frontend/src/lib/utils/wizard-modal.utils.ts
One of the preparations needed for the next steps -  we need to allow WizardStepsHowToConvert to be passed as stepName.
> feat(frontend): allow WizardStepsHowToConvert to be passed as stepName

- scripts/did.update.types.mjs
Fixes https://github.com/dfinity/oisy-wallet/security/code-scanning/4
In the script to update `did` types, there may be a race condition (CodeQL [js/file-system-race](https://github.com/github/codeql/blob/626c752a0b8cfd98bcf1f4b622d73bbe6f078a4c/javascript/ql/src/Security/CWE-367/FileSystemRace.ql)) when writing the file:
```ts
...
if (!existsSync(factoryPath)) {
resolve();
return;
}
...
await writeFile(factoryPath, cleanInit, 'utf8');
// The file may have changed since it was checked
...
```
So, to avoid it, we do similar to other scripts and open the file before writing it.
> fix(build): Fix code scanning alert no. 4: avoid possible race condition when updating `did` types

- scripts/build.tokens.ckerc20.ts
Fixes https://github.com/dfinity/oisy-wallet/security/code-scanning/6
In the script to build ckERC20 tokens, there may be a race condition (CodeQL [js/file-system-race](https://github.com/github/codeql/blob/626c752a0b8cfd98bcf1f4b622d73bbe6f078a4c/javascript/ql/src/Security/CWE-367/FileSystemRace.ql)) when creating the logo file:
```ts
...
if (existsSync(file)) {
return;
}
...
writeFileSync(file, svgContent, 'utf-8');
// The file may have changed since it was checked
...
```
So, to avoid it, we do similar to other scripts and open the file before writing it.
> fix(build): Fix code scanning alert no. 6: avoid possible race condition when creating ckERC20 tokens.

- src/frontend/src/icp-eth/components/info/InfoEthereum.svelte
- src/frontend/src/icp-eth/components/send/ConvertETHToCkETHWizard.svelte
- src/frontend/src/icp-eth/config/how-to-convert.config.ts
- src/frontend/src/icp/components/convert/HowToConvertEthereumInfo.svelte
- src/frontend/src/icp/components/convert/HowToConvertEthereumModal.svelte
- src/frontend/src/icp/components/info/Info.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
- src/frontend/src/tests/icp-eth/components/info/InfoEthereum.spec.ts
- src/frontend/src/tests/icp/components/convert/HowToConvertEthereumModal.spec.ts
- src/frontend/src/tests/icp/components/convert/HowToConvertEthereumWizardSteps.spec.ts
- src/frontend/src/tests/icp/components/info/Info.spec.ts
We need to migrate the HowToConvert modals from Send to Convert wizard. This update simplifies a lot of things but requires quite a few changes in all related components.
The current functionality of the modal stays unchanged, except of the wizard that gets opened on the "conversion" button click.
Note: I'll migrate the affected by this PR components to Svelte 5 in follow up PRs.
https://github.com/user-attachments/assets/4e82f321-be4c-4fc2-a354-3b9b4ad4a9d4
> feat(frontend): use convert wizard in HowToConvert flow

- src/frontend/src/eth/config/receive.config.ts
- src/frontend/src/lib/enums/wizard-steps.ts
Previously, the receive config was defined directly in the component. As a part of migration to the convert flow, I'm moving it to a separate file.
> feat(frontend): receive wizard config

- src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereumModal.svelte
- src/frontend/src/icp/components/receive/IcReceiveInfoCkEthereum.svelte
- src/frontend/src/lib/utils/wizard-modal.utils.ts
- src/frontend/src/tests/icp/components/receive/IcReceiveCkEthereumModal.spec.ts
Similar as with the HowToConvert flow, we need to migrate the IcReceive modal from Send to Convert wizard.
The current functionality of the modal stays unchanged, except of the wizard that gets opened on the "conversion" button click.
Note: I'll migrate the affected by this PR components to Svelte 5 in follow up PRs.
https://github.com/user-attachments/assets/e9e60f8b-9686-4cf1-bd7f-53d186dd78ad
> feat(frontend): update IcReceiveCkEthereum components

- src/frontend/src/tests/icp-eth/components/info/InfoEthereum.spec.ts
- src/frontend/src/tests/icp/components/info/InfoBitcoin.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises a few warnings. For example, it requires an explicit statement after `expect(...)`.
In this specific case there is not much difference since `getByText` would fail if it doesn't find anything, but for consistency, we add `toBeDefined()` at the end.
> refactor(frontend): use `toBeDefined` in tests for Info banner

- scripts/did.update.types.mjs
As @bitdivine found, the PR #5963 is causing issues with bindings creation (since the files may already exists). So for now, we will revert it, and find another solution.
> fix(build): Revert PR #5963: Fix code scanning alert no. 4

- src/frontend/src/env/tokens/tokens.btc.env.ts
- src/frontend/src/env/tokens/tokens.sol.env.ts
- src/frontend/src/lib/constants/tokens.constants.ts
As per suggestion https://github.com/dfinity/oisy-wallet/pull/5995#discussion_r2053560449 , to keep the code more organized and consistent, we move the definition of supported tokens to each respective module.
> refactor(frontend): move supported tokens constants to respective modules

- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
Just for consistency, we wrap the tokens utils tests into a top-level `describe`.
> refactor(frontend): wrap tokens utils tests

- src/frontend/src/env/networks/networks.icrc.env.ts
- src/frontend/src/env/tokens/groups/groups.btc.env.ts
- src/frontend/src/env/tokens/tokens.btc.env.ts
Splitting PR https://github.com/dfinity/oisy-wallet/pull/5918.
We are going to use `groupData` to group similar ("twin") tokens. Currently we are using different props depending on the type of token (for example `twinToken` for ICRC, or `twinTokenSymbol` for ERC20). With groupData, we aim to have a single center of aggregation for "twin" tokens.
In this PR we create the group for token BTC.
> feat(frontend): add BTC token group data

- src/frontend/src/tests/btc/components/convert/ConvertToCkBTC.spec.ts
- src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
- src/frontend/src/tests/eth/providers/etherscan.providers.spec.ts
- src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
- src/frontend/src/tests/icp-eth/components/info/InfoEthereum.spec.ts
- src/frontend/src/tests/icp/components/convert/HowToConvertEthereumModal.spec.ts
- src/frontend/src/tests/icp/components/info/Info.spec.ts
- src/frontend/src/tests/icp/components/receive/IcReceiveCkEthereumModal.spec.ts
- src/frontend/src/tests/icp/components/transactions/IcTransactions.spec.ts
- src/frontend/src/tests/lib/components/convert/ConvertModal.spec.ts
- src/frontend/src/tests/lib/components/convert/ConvertWizard.spec.ts
- src/frontend/src/tests/lib/components/core/Listener.spec.ts
- src/frontend/src/tests/lib/components/loaders/Loader.spec.ts
- src/frontend/src/tests/lib/components/transactions/AllTransactions.spec.ts
- src/frontend/src/tests/lib/components/transactions/AllTransactionsList.spec.ts
- src/frontend/src/tests/lib/components/transactions/Transactions.spec.ts
- src/frontend/src/tests/lib/utils/listener.utils.spec.ts
- vitest.setup.ts
For the coming PR https://github.com/dfinity/oisy-wallet/pull/6021 , we will have to mock more methods for Etherscan throughout the code. So it makes sense to extract the mocks and put them in a single place.
> refactor(frontend): move Etherescan mocks to vitest setup

- src/frontend/src/env/tokens/tokens.icrc.json
The ledger canister of ICRC token vUSD is having some issues, apparently not fixable in the short-term. As hotfix, we temporarily remove it from the default list.
> feat(frontend): remove ICRC token vUSD

- scripts/build.csp.mjs
Fixes https://github.com/dfinity/oisy-wallet/security/code-scanning/14
To fix the problem, we need to modify the regular expression to include </script > (with a whitespace in the end).
> fix(build): Fix code scanning alert no. 14: Bad HTML filtering regexp

- src/frontend/src/lib/components/hero/Actions.svelte
Instead of using store `tokenWithFallback` (that we need to deprecated), we use the (almost) equivalent `pageToken` store in component `Actions`, with an additional check.
> refactor(frontend): use `pageToken` store in `Actions` component

- src/frontend/src/tests/lib/components/qr/VipRewardStateModal.spec.ts
We are going to add the vitest linter (PR https://github.com/dfinity/oisy-wallet/pull/5797), but it raises a few warnings. For example, it requires an explicit statement after `expect(...)`.
> refactor(frontend): use `.includes` in tests for `VipRewardStateModal`

- src/frontend/src/lib/components/hero/Actions.svelte
Reverting PR #6039, since there can be a race condition for slower networks where `pageToken` is not immediately loaded.
> fix(frontend): revert PR #6039: use `pageToken` store in `Actions` component

- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
We need to move SendTokenContext to SendModal in order to have access to the context in the future Destination wizard step (will be added to SendModal).
> refactor(frontend): move SendTokenContext to SendModal

- src/frontend/src/icp/services/icrc.services.ts
- src/frontend/src/tests/icp-eth/services/custom-token.services.spec.ts
- src/frontend/src/tests/icp/services/icrc.services.spec.ts
There are some cases where the ledger canister fails completely (most recently we had the episode with [vUSD](https://github.com/dfinity/oisy-wallet/pull/6043)). In those cases, we prefer to ignore the failing ledger canisters and proceed with the working ones during the loading of metadata of ICRC custom tokens.
Otherwise the current implementation resets them all, and does not show anything.
- Await all the promises to load metadata of ICRC custom tokens, successful and failing.
- Filter out the failing ones.
- Reset the ICRC custom token store for the failed.
Adapted and added tests.
> feat(frontend): ignore failed metadata fetched during loading of ICRC custom tokens

- src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte
- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
- src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
Before extracting destination input into a separate wizard step, we need to refactor the Send flow by moving QrCode step up to the SendModal component. It also allows us to clean up the components and to avoid some code repetitions.
> refactor(frontend): move QrCode step to SendModal

- .github/workflows/update-next.yml
The CI to update `ic-js` was not working correctly because we use brackets in the script to loop through the packages. But `sh` (that is the default shell of GitHub) does not recognize this syntax (see [failed CI](https://github.com/dfinity/oisy-wallet/actions/runs/14593319705/job/40933323682)).
So, we forcibly run the script in `bash` (see [working CI](https://github.com/dfinity/oisy-wallet/actions/runs/14620237906)).
> fix(build): CI to update `ic-js` was not working

- src/frontend/src/lib/components/settings/SettingsVersion.svelte
Inserting a white space between the Git data labels and the values themselves, for better readability.
> style(frontend): whitespace between Git labels and Git data

- src/frontend/src/btc/components/transactions/BtcTransaction.svelte
- src/frontend/src/eth/components/transactions/EthTransaction.svelte
- src/frontend/src/icp/components/transactions/IcTransaction.svelte
- src/frontend/src/lib/components/auth/ButtonAuthenticateWithLicense.svelte
- src/frontend/src/lib/components/auth/SigningInHelpLink.svelte
- src/frontend/src/lib/components/core/Menu.svelte
- src/frontend/src/lib/components/dapps/DappsCarouselSlide.svelte
- src/frontend/src/lib/components/dapps/DappsExplorerSignedIn.svelte
- src/frontend/src/lib/components/guard/RewardGuard.svelte
- src/frontend/src/lib/components/guard/UrlGuard.svelte
- src/frontend/src/lib/components/networks/NetworksSwitcher.svelte
- src/frontend/src/lib/components/rewards/RewardsGroup.svelte
- src/frontend/src/lib/components/settings/Settings.svelte
- src/frontend/src/lib/components/wallet-connect/WalletConnectSession.svelte
- src/frontend/src/lib/stores/modal.store.ts
- src/frontend/src/sol/components/transactions/SolTransaction.svelte
- src/frontend/src/tests/lib/components/guard/UrlGuard.spec.ts
- src/frontend/src/tests/lib/stores/modal.store.spec.ts
It is useful to have a defined ID for each modal. For now we start with the modals that were requiring data as input too.
- Make method `setTypeWithData` of `modalStore` accept an ID too.
- Adapt usage of `modalStore` throughout the code for the modals that were changed: create modal ID and pass it.
Adapted tests.
> feat(frontend): add ID to modal store that have data input

- src/frontend/src/lib/components/send/SendWizard.svelte
We can use directly the EVM native token instead of the Ethereum one inside the Send flow for EVM networks.
> feat(frontend): use EVM native token for Send flow of EVM networks

- src/frontend/src/env/tokens/tokens-evm/tokens-base/tokens.eth.env.ts
- src/frontend/src/env/tokens/tokens-evm/tokens-bsc/tokens.bnb.env.ts
- src/frontend/src/env/tokens/tokens-evm/tokens.evm.env.ts
- src/frontend/src/env/tokens/tokens.eth.env.ts
- src/frontend/src/evm/utils/native-token.utils.ts
We will need to use the EVM native tokens for all the same flows of the base Ethereum network. So, for now, we first create an util to check if a token is a native EVM token (similar to util `isSupportedEthTokenId`).
> feat(frontend): create util to check supported native EVM tokens

- src/frontend/src/lib/components/address-book/AddressBookModal.svelte
- src/frontend/src/lib/components/address-book/AddressBookStep.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/lib/enums/progress-steps.ts
- src/frontend/src/lib/types/contact.ts
- src/frontend/src/tests/lib/components/address-book/AddressBookModal.spec.ts
In order to add more modals (like show contact and edit contact), the address book should use the `WizardModal` from gix components.
- Added step component for the address book.
- Migrated the address book modal to `WizardModal`
See this PR to see full feature demo: https://github.com/dfinity/oisy-wallet/pull/6071
> feat(frontend): Use wizard for address book

- vite.config.ts
There is a known issue with `ethers` package: the BNB Smart Chain (BSC) API URLs are not updated (see issue https://github.com/ethers-io/ethers.js/issues/4951). However we have the BSC network among our list of networks, so we need to temporarily patch it to the correct URL.
To do that we create a custom plugin and apply it (credits to @peterpeterparker ).
- Create custom plugin to replace the URLs.
- Adapt `vite` configs to replace the wrong BSC API URLs.
Tested in test canister and it works as expected:
> feat(build): temporary replace correct BSC API url for package `ethers`

- src/frontend/src/lib/services/token.services.ts
- src/frontend/src/tests/lib/services/token.services.spec.ts
From service `autoLoadToken` we extract a sub-function called `autoLoadToken` that will take as input the token directly, instead of searching it based on the input parameters.
> refactor(frontend): extract sub-function that auto load token

- src/frontend/src/eth/components/loaders/LoaderEthTransactions.svelte
We should check when we are in an EVM networks in the same steps that we check when we are in an Ethereum network. However I missed one check in a previous PR.
> fix(frontend): forgotten check for EVM networks

- src/frontend/src/env/rest/etherscan.env.ts
- src/frontend/src/eth/rest/etherscan.rest.ts
- src/frontend/src/tests/eth/rest/etherscan.rest.spec.ts
Similar to what we did in PR https://github.com/dfinity/oisy-wallet/pull/6021 , we adapt class `EtherscanRest` to use the [Etherscan API v2](https://docs.etherscan.io/etherscan-v2), that allows for multi-chain queries.
That allows us to expand it to EVM networks.
- Force class `EtherscanRest` to use new API v2 URL for Etherscan.
- Make class `EtherscanRest` accept the chain ID and adapt the methods.
- Add all EVM tokens to the list of providers.
Adapted tests.
I did not pass too much time creating more tests or making it more modular for repeated code, because the class `EtherescanRest` will be deprecated by:
- PR https://github.com/dfinity/oisy-wallet/pull/5953
> feat(frontend): add EVM networks to `EtherescanRest` class using API v2

- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/evm/derived/networks.derived.ts
The ERC20 derived store (both default and user tokens) now includes ERC20 from other networks. So, we must include the EVM networks among the checks when filtering.
> feat(frontend): add EVM networks to derived stores for ERC20 tokens

- src/frontend/src/eth/derived/erc20.derived.ts
Since we have now more ERC20 over different networks, like EVM networks (different chain IDs), it makes sense to include the chain ID in the checks.
- Change derived store `erc20DefaultTokensAddresses` to check the chain IDs between user tokens and default tokens.
- Remove deprecated store `erc20DefaultTokensAddresses`.
Current tests are sufficient.
> refactor(frontend): include chain ID check in derived store `erc20UserTokensToggleable`

- src/frontend/src/eth/providers/infura-erc20.providers.ts
Similar to what we did in PR https://github.com/dfinity/oisy-wallet/pull/6027, we include the EVM networks in the Infura providers for ERC20 tokens.
> feat(frontend): add EVM networks to Infura ERC20 providers

- src/frontend/src/lib/utils/token.utils.ts
Util `mapDefaultTokenToToggleable` can be simplified to use an assertion-util for ERC20 tokens.
> refactor(frontend): simplify util `mapDefaultTokenToToggleable`

- src/frontend/src/env/pow.env.ts
After the merge of [PR](https://github.com/dfinity/oisy-wallet/pull/6120) on friday, this error suddenly appreas in oiwsy-wallet: Unexpected end of JSON input. For the moment we disable the evaluation of the VITE_POW_FEATURE_ENABLED and just set it to false, to avoid the issue until a fallback is implemented and  the secret VITE_POW_FEATURE_ENABLED is set to false.
> fix(frontend): disable evaluation of pow feature flag

- src/frontend/src/lib/derived/exchange.derived.ts
- src/frontend/src/lib/services/exchange.services.ts
- src/frontend/src/lib/validation/coingecko.validation.ts
Coingecko ID for BNB token should be `binancecoin` instead of `bnb`.
> fix(frontend): correct Coingecko ID for BNB

- src/frontend/src/lib/i18n/en.json
We'd like to reflect that we have new networks in the app.
Added Base and BNB to the texts
> fix(frontend): Loader Text - added Base and BNB to the retrieve keys text

- src/frontend/src/eth/providers/infura-ckerc20.providers.ts
Method `getFeeData` of class `InfuraCkErc20Provider` is not used. We can remove it.
> chore(frontend): remove unused method `getFeeData` from `InfuraCkErc20Provider`

- src/frontend/src/eth/services/eth-transaction.services.ts
As per design of method `getTransactions` of Alchemy provider:
```ts
/**
* Returns the transaction with hash or null if the transaction is unknown.
*
* If a transaction has not been mined, this method will search the
* transaction pool. Various backends may have more restrictive transaction
* pool access (e.g. if the gas price is too low or the transaction was only
* recently sent and not yet indexed) in which case this method may also return null.
*
* NOTE: This is an alias for {@link TransactNamespace.getTransaction}.
*
* @param transactionHash The hash of the transaction to get.
* @public
*/
```
That means that pending transactions found using service `processPendingTransaction` are not necessarily found (we have practical example with Base network).
That said, it is acceptable to just …
> feat(frontend): ignore for Etherum and EVM pending transactions not found

- src/frontend/src/env/tokens/tokens.sns.deprecated.env.ts
The remaining ICP from Seers were emptied, the dapp canister was unregistered from the DAO, and ultimately it was renamed renamed to `---- ex Seers ---- / ---- please unlist ----`.
So we mark the ICRC token Seers as deprecated.
Proposals:
https://nns.ic0.app/proposal/?u=u67kc-jyaaa-aaaaq-aabpq-cai&proposal=380
https://nns.ic0.app/proposal/?u=u67kc-jyaaa-aaaaq-aabpq-cai&proposal=381
https://nns.ic0.app/proposal/?u=u67kc-jyaaa-aaaaq-aabpq-cai&proposal=382
Credits to @peterpeterparker
> feat(frontend): mark SNS token Seers as deprecated

- src/frontend/src/btc/components/convert/ConvertToCkBTC.svelte
- src/frontend/src/icp-eth/components/convert/ConvertETH.svelte
- src/frontend/src/icp/components/convert/ConvertToBTC.svelte
- src/frontend/src/lib/components/buy/Buy.svelte
- src/frontend/src/lib/components/buy/BuyButton.svelte
- src/frontend/src/lib/components/hero/ButtonHero.svelte
- src/frontend/src/lib/components/receive/ReceiveButton.svelte
- src/frontend/src/lib/components/receive/ReceiveButtonWithModal.svelte
- src/frontend/src/lib/components/send/SendButton.svelte
- src/frontend/src/lib/components/send/SendButtonWithModal.svelte
- src/frontend/src/lib/components/swap/SwapButton.svelte
- src/frontend/src/lib/components/swap/SwapButtonWithModal.svelte
- Upgrades ButtonHero
- Upgrades BuyButton
- Upgrades SwapButton
- Upgrades ReceiveButton
- Upgrades SendButton
> refactor(frontend): upgrades ButtonHero to svelte5

- src/frontend/src/lib/components/core/Listener.svelte
- src/frontend/src/tests/lib/components/core/Listener.spec.ts
As per the rest of the features, the `EthListener` should be enabled for EVM networks.
> feat(frontend): add `EthListener` to EVM networks

- src/frontend/src/lib/components/rewards/RewardsGroup.svelte
> refactor(frontend): upgrades RewardsGroup to svelte 5

- src/frontend/src/lib/components/rewards/RewardDateBadge.svelte
- src/frontend/src/lib/components/ui/Badge.svelte
- src/frontend/src/lib/components/ui/DateBadge.svelte
- upgrades `RewardDateBadge`
- upgrades `DateBadge`
- upgrades `Badge`
> refactor(frontend): upgrades Badge to svelte 5

- src/frontend/src/env/rest/etherscan.env.ts
- src/frontend/src/eth/services/eth-transactions-batch.services.ts
- src/frontend/src/lib/services/batch.services.ts
- src/frontend/src/tests/eth/services/eth-transactions-batch.services.spec.ts
- src/frontend/src/tests/lib/services/batch.services.spec.ts
This PR fixes 2 related issues:
1. Batch mechanism for fetching ETH txs had an error - instead of creating an array with promises to execute them later by the `batch` function, it was invoking the async function immediately, hence all requests to Etherscan API were made at the same time. 
2. After fixing the error above, I realized `ETHERSCAN_MAX_CALLS_PER_SECOND` was not set correctly - to fetch tx data for a token, we make 2 requests to Etherscan API, therefore that constant should be set as `rate-limit-number / 2`. Our rate limit in BETA and PROD is 10, staging - 5.
Fixed the functions and the const.
Adjusted.
> fix(frontend): issue with loading eth txs in batches

- src/frontend/src/env/tokens/tokens.btc.env.ts
Bitcoin purchases are currently unavailable due to a missing Onramper configuration in the Bitcoin token settings. Users must be able to purchase Bitcoin as intended
- Added buy.onramperId property for **bitcoin** in `tokens.btc.env.ts`
- Successfully bought bitcoins with  Revolut Pay and Guardarian
> feat(frontend): enabled BTC for onramper in mainnet integration

- src/frontend/src/lib/components/rewards/RewardsRequirements.svelte
- Upgrades `RewardsRequirements`
> refactor(frontend): upgrades RewardsRequirements to svelte 5

- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/icp-eth/derived/icrc-erc20.derived.ts
- src/frontend/src/icp-eth/types/icrc-erc20.ts
- src/frontend/src/lib/schema/post-message.schema.ts
- src/frontend/src/lib/services/exchange.services.ts
- src/frontend/src/lib/types/coingecko.ts
- src/frontend/src/lib/types/network.ts
- src/frontend/src/lib/workers/exchange.worker.ts
We want to track the price for all ERC20 tokens, including the ones for EVM networks. To do so, we need to use the Coingecko platform ID for each respective network, when fetching the prices.
- Move derived store `enabledErc20TokensAddresses` (since it is used only for that scope, preferable to have all concentrated there).
- Add additional field `coingeckoId` to all the derived stores used when creating the list of ERC20 addresses to fetch.
- Create new types for the interface that is now provided by the derived stores and by the ERC20 price request params.
- Adapt service `syncExchange` to reduce the address-with-network object to a list of network-and-addresses
Deployed:
> feat(frontend): use Coingecko platform ID to map prices of all ERC20

- src/frontend/src/lib/components/rewards/RewardStateModal.svelte
> refactor(frontend): upgrades RewardStateModal to svelte 5

- src/frontend/src/env/tokens/tokens-evm/tokens-bsc/tokens-bep20/tokens.usdc.env.ts
- src/frontend/src/env/tokens/tokens-evm/tokens-bsc/tokens-bep20/tokens.usdt.env.ts
BSC USDC and USDT use 18 digits and not 6.
> fix(frontend): BSC USDC and USDT digits

- src/frontend/src/eth/components/fee/FeeContext.svelte
When we introduced the usage of Infura Gas API in PR https://github.com/dfinity/oisy-wallet/pull/6158 for fee data calculation, we should have included for all tokens.
> fix(frontend): use suggested fee data for ERC20 tokens too

- src/frontend/src/env/tokens/tokens-evm/tokens-bsc/tokens-bep20/tokens.usdc.env.ts
- src/frontend/src/env/tokens/tokens-evm/tokens-bsc/tokens-bep20/tokens.usdt.env.ts
Since they have different decimals, the sum of the pure balance of the BEP20 tokens with their ERC20 twins will not work when grouping them. So, while working on a fix, we temporary un-group them for the release.
> feat(frontend): remove the group data from BEP20 tokens

- src/frontend/src/lib/components/auth/LandingPage.svelte
> refactor(frontend): upgrades LandingPage to svelte 5

- src/frontend/src/lib/components/auth/ButtonAuthenticateWithLicense.svelte
- Upgrades `ButtonAuthenticateWithLicense`
> refactor(frontend): upgrades ButtonAuthenticateWithLicense to svelte 5

- src/frontend/src/lib/components/carousel/Controls.svelte
> refactor(frontend): upgrades Controls to svelte 5

- src/frontend/src/lib/services/exchange.services.ts
Coingecko requests are actually case-sensitive when treating contract addresses, so we need to adjust the functions.
> fix(frontend): do not use lower case for contract addresses in Coingecko requests

- src/frontend/src/lib/utils/rewards.utils.ts
- src/frontend/src/tests/lib/utils/rewards.utils.spec.ts
We want to be able to find out if a campaign has ended exactly like we already check if a campaign is upcoming or ongoing.
- implements `isEndedCampaign`
> feat(frontend): implements isEndedCampaign function

- .github/workflows/frontend-remove-unused-components.yml
According to [POSIX cron documentation](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07), the day-of-week and day-of-month are linked by OR logic and not AND logic:
> The specification of days can be made by two fields (day of the month and day of the week). If month, day of month, and day of week are all <asterisk> characters, every day shall be matched. If either the month or day of month is specified as an element or list, but the day of week is an <asterisk>, the month and day of month fields shall specify the days that match. If both month and day of month are specified as an <asterisk>, but day of week is an element or list, then only the specified days of the week match. Finally, if either the month or day of month is specified as an element or …
> fix(devops): correct cron expression for CI to remove components

- src/frontend/src/lib/components/networks/NetworkLogo.svelte
> refactor(frontend): upgrades NetworkLogo to svelte 5

- src/frontend/src/lib/components/ui/Logo.svelte
> refactor(frontend): upgrades Logo to svelte 5

- src/frontend/src/lib/constants/app.constants.ts
We aim to integrate with ICP Swap and in this PR is provided config to get ICP_SWAP_CANISTER_ID depends on env.
Added new ICP_SWAP_CANISTER_ID to constant env file
> feat(frontend): added env varaible to constant for ICP Swap

- src/frontend/src/lib/types/transactions.ts
- src/frontend/src/lib/utils/transactions.utils.ts
- src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
- src/frontend/src/tests/mocks/ic-transactions.mock.ts
In order to get all the needed info about known destinations from transactions list, we need to implement a new util.
> feat(frontend): implement getKnownDestinations util

- src/frontend/src/lib/components/ui/Input.svelte
While building the frontend, noticed there is a linter warning in the `Input` component.
> fix(frontend): onclick event in Input

- src/frontend/src/lib/components/ui/LogoButton.svelte
Small fix for the LogoButton component - `styleClass` was added but never used.
> fix(frontend): use styleClass in LogoButton

- src/frontend/src/eth/providers/etherscan.providers.ts
There is a missing parameter chainId in method `erc20Transactions` of class `EtherscanProvider`. It was not raised since the method is still unused.
> fix(frontend): missing chain ID in class `EtherscanProvider` for ERC20

- src/frontend/src/icp/components/transactions/IcTransactionsScroll.svelte
- src/frontend/src/icp/services/ic-transactions.services.ts
It seems more consistent to rename the function `loadNextTransactions` to `loadNextIcTransactions` since we already have `loadNextSolTransactions` too.
> refactor(frontend): rename service to load the next IC transactions

- src/frontend/src/lib/api/icp-swap-factory.api.ts
- src/frontend/src/lib/services/icp-swap.services.ts
- src/frontend/src/tests/lib/canisters/icp-swap-factory.spec.ts
- src/frontend/src/tests/lib/services/icp-swap.services.spec.ts
Refactored the ICP Swap logic for consistency with other files and updated the test to properly mock the canister method.
- Refactored ICP Swap logic
- Aligned structure with other modules
- Updated test to mock canister method correctly
> refactor(frontend): refactored icp swap logic

- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/tests/lib/components/send/SendDestinationWizardStep.spec.ts
We need to have a component for the Send Destination step. Base on `sendToken`, it decides which components should be rendered.
> feat(frontend): SendDestinationWizardStep component

- src/frontend/src/lib/components/contact/Avatar.svelte
- src/frontend/src/lib/constants/contact.constants.ts
- src/frontend/src/lib/types/utils.ts
- src/frontend/src/lib/utils/contact.utils.ts
- src/frontend/src/tests/lib/utils/contact.utils.spec.ts
Move the color selection in a utils file in order to reuse the functionality for the contact header later.
- Move computation into a separate file
- Enhancement: Make the hash computation functional
Added tests
> feat(frontend): Make contact color computation reusable

- src/frontend/src/btc/components/convert/BtcConvertProgress.svelte
- src/frontend/src/lib/components/swap/SwapProgress.svelte
- src/frontend/src/lib/components/ui/InProgress.svelte
To avoid repetition of code we substitute `[ProgressStep, ...ProgressStep[]]` with existing `ProgressSteps`.
> refactor(frontend): use `ProgressSteps` instead of `ProgressStep` array

- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/config/send.config.ts
- src/frontend/src/lib/enums/wizard-steps.ts
- src/frontend/src/tests/lib/config/send.config.spec.ts
The last step is to add SendDestinationWizard step to the Modal and update all related events. Additionally, we fetch ETH transactions in case selected token standard is ETH in order to generate known destinations derived.
> feat(frontend): update SendModal component

- src/frontend/src/lib/components/send/KnownDestination.svelte
- src/frontend/src/lib/components/send/KnownDestinations.svelte
The idea is to make only the Known destinations section scrollable, so the input stays always on top (same as with the Tokens screen). Also, we need to decrease destination font size.
> style(frontend): KnownDestinations styling

- src/frontend/src/sol/components/fee/SolFeeDisplay.svelte
- src/frontend/src/tests/sol/components/send/SolSendForm.spec.ts
We need to update the way we display SOL fees in the Send form. Note: displaying `< 0.01$` instead of `~ 0.00$` will be tackled separately.
> feat(frontend): update appearance of SOL fees in the Send form

- .github/workflows/frontend-update-coverage-thresholds.yml
- vitest.config.ts
The checks for tests coverage are a bit flaky, since the calculation can change for a few basis points: we round the thresholds to the lowest integers; so, if we are close to it, the checks keep failing.
Example: threshold is set at 84%, real coverage is at 84.01%, but the flaky calculation returns sometimes 83.98%.
To avoid this, we change the workflow that changes the thresholds to reduce them by 0.50% instead of flooring them. That should be enough margin for flakiness in the calculation.
> feat(devops): Reduce coverage thresholds by 0.50%

- src/frontend/src/icp/components/transactions/IcTransactionsScroll.svelte
- src/frontend/src/icp/services/ic-transactions.services.ts
- src/frontend/src/tests/icp/components/transactions/IcTransactionsScroll.spec.ts
- src/frontend/src/tests/mocks/infinite-scroll.mock.ts
- src/frontend/src/tests/utils/transactions-stores.test-utils.ts
In the coming PR https://github.com/dfinity/oisy-wallet/pull/6438, we want to re-use the logic of `IcTransactionsScroll` to loads the next transactions (that are missing) in the Activity page.
To avoid repetition of code, we extract the checks done in the component to the service `loadNextIcTransactions`.
- Rename service loadNextIcTransactions to loadNextIcTransactionsRequest.
- Create new function service loadNextIcTransactions that is a wrapper of the old one plus the checks from `IcTransactionsScroll` component.
- Remove the checks from `IcTransactionsScroll`.
- NOTE: we leave the nullish check for lastId in the component, because we will not need them in the Activity page.
Created new tests both for the component and the service. To mock the `InfiniteScroll` component to dispatch the …
> feat(frontend): extract checks from `IcTransactionsScroll` component

- src/frontend/src/icp/utils/icrc.utils.ts
- src/frontend/src/tests/icp/utils/icrc.utils.spec.ts
To be more correct, the util `mapIcrcToken` shall use the `standard` provided by the existing list, instead of fixing it to `icrc`.
- Change the default condition for `standard` in the mapper.
Since we are here, I added tests for all ICRC utils.
> feat(frontend): default standard in ICRC util `mapIcrcToken`

- src/frontend/src/lib/utils/token-toggle.utils.ts
Since the input of util `isIcrcTokenToggleDisabled` is always a defined token, we don't need to check for nullish values.
> chore(frontend): remove unnecessary check in util `isIcrcTokenToggleDisabled`

- vitest.config.ts
We don't have unittests for the scripts: run them in the workflows, or manually. Plus some of them are tested in the workflows too.
So, I think it makes sense to remove them from vitest coverage analysis.
> feat(devops): remove script folder from vitest coverage analysis

- src/frontend/src/icp/components/transactions/IcTransactionsScroll.svelte
- src/frontend/src/tests/icp/components/transactions/IcTransactionsScroll.spec.ts
- src/frontend/src/tests/mocks/infinite-scroll.mock.ts
- src/frontend/src/tests/utils/transactions-stores.test-utils.ts
For component `IcTransactionsScroll`, we should test if the transactions are not loaded anymore once they are finished.
> test(frontend): additional test for `IcTransactionsScroll`

- src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts
When testing derived store `icKnownDestinations`, the timestamp created for the mock transactions can be higher than the previous one. So, to avoid flakiness (see [failed CI workflow](https://github.com/dfinity/oisy-wallet/actions/runs/14937269291/job/41967527170?pr=6476)), we need to confirm that the store takes the most recent timestamp.
> test(frontend): flaky timestamp for test of `icKnownDestinations`

- src/frontend/src/lib/schema/post-message.schema.ts
- src/frontend/src/tests/icp/workers/btc-statuses.worker.spec.ts
- src/frontend/src/tests/icp/workers/ckbtc-minter-info.worker.spec.ts
- src/frontend/src/tests/icp/workers/ckbtc-update-balance.worker.spec.ts
- src/frontend/src/tests/icp/workers/cketh-minter-info.worker.spec.ts
- src/frontend/src/tests/mocks/workers.mock.ts
- src/frontend/src/tests/sol/workers/sol-wallet.worker.spec.ts
We create simple tests to verify the correct scheduler calls for the workers that switch the messages that are posted.
> test(frontend): add simple tests for message switch in simple workers

- src/frontend/src/eth/providers/infura-erc20.providers.ts
- src/frontend/src/tests/eth/providers/etherscan.providers.spec.ts
- src/frontend/src/tests/eth/providers/infura-erc20.providers.spec.ts
We are having some situations where the Base transactions are failing due to too little gas provided. After analyzing the code, we are calculating the fee for ERC20 based on the estimate gas of the `approve` method of ERC20, plus a buffer of 50%. However, it seems it is not enough for Base `transfer` method.
To solve it at top-tier level, we modify the calculation of the fee to get the max value between the estimated gas for `approve` method and the one for `transfer` method.
- Modify class `InfuraErc20Provider` to have method `getFeeData` fetch estimated fees both for approve and transfer.
- Return the max between them.
Since we are here, we create tests for the entire module. Plus test in a test canister, before and after and it worked.
- Wallet: …
> feat(frontend): ERC20 fee is max between `approve` and `transfer`

- src/frontend/src/icp/components/receive/IcReceive.svelte
- src/frontend/src/icp/utils/icrc.utils.ts
- src/frontend/src/lib/schema/token.schema.ts
- src/frontend/src/tests/icp/utils/icrc.utils.spec.ts
We want to start supporting [IC DIP-20 tokens](https://github.com/Psychedelic/DIP20), specifically [XTC](https://github.com/Psychedelic/dank/tree/main/xtc). In this PR, we introduce the new standard.
- Add `dip20` among the token standard.
- Create util to check the correct new standard.
- Use the util in the receive modal.
Add tests.
> feat(frontend): introduce DIP-20 standard

- src/frontend/src/btc/components/send/BtcSendReview.svelte
- src/frontend/src/lib/components/send/SendReview.svelte
The design update of the BtcSendReview component. This PR also includes related `SendReview` changes. 
Note: in order not to update all the network forms at once, I left an unused `source` prop which allows us to introduce changes gradually.
> feat(frontend): update BtcSendReview component

- src/frontend/src/tests/lib/schema/post-message.schema.spec.ts
We can use a pre-existing list for the tests of `PostMessageRequestSchema`.
> refactor(frontend): generalize tests for `PostMessageRequestSchema`

- src/frontend/src/icp/services/ic-send.services.ts
- src/frontend/src/tests/icp/services/ic-send.services.spec.ts
- src/frontend/src/tests/mocks/ic-tokens.mock.ts
- src/frontend/src/tests/mocks/identity.mock.ts
Providing services to send IC tokens of standard DIP-20.
- Add service `sendDip20` similar to service `sendIcrc`.
- Use the new service in the generic `sendIc` service.
Added tests.
> feat(frontend): send services for IC DIP-20 tokens

- src/frontend/src/lib/components/send/SendModal.svelte
We need to reset all values (not only `destination`) when user updates a token to send.
> feat(frontend): reset all values on sendToken change

- src/frontend/src/lib/components/rewards/AllRewardsList.svelte
Now the `reward service` does provide a function to load the campaign eligibility data and we want to use it to write the data to our reward store.
- loads eligibility data
> feat(frontend): loads campaign eligibilities with reward service

- .github/workflows/deploy-to-environment.yml
The updated dfx does not deploy to staging.  There is one env var that is now required to use a plaintext key, and one of the flags we use is now deprecated.
- Update the dfx configuration.
Deployment to fe5: https://github.com/dfinity/oisy-wallet/actions/runs/14998375156
> fix(devops): Fix dfx settings for staging

- src/frontend/src/lib/types/reward.ts
When the types `MinLoginsCriterion`, `MinTransactionsCriterion` and `MinTotalAssetsUsdCriterion` were added, i forgot to remove the unused attributes from the type `CampaignCriterion`.
- removes unused attributes
> refactor(frontend): removes unused CampaignCriterion attributes

- src/frontend/src/lib/types/transaction.ts
- src/frontend/src/lib/types/transactions.ts
- src/frontend/src/lib/utils/transactions.utils.ts
- src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
We need to update the KnownDestinations utils according to the new specs - the addresses should be grouped based on networks, and not only based on a single token.
> feat(frontend): update KnownDestinations utils

- src/frontend/src/btc/derived/btc-transactions.derived.ts
- src/frontend/src/eth/derived/eth-transactions.derived.ts
- src/frontend/src/icp/derived/ic-transactions.derived.ts
- src/frontend/src/lib/types/transaction.ts
- src/frontend/src/lib/types/transactions.ts
- src/frontend/src/lib/utils/transactions.utils.ts
- src/frontend/src/sol/derived/sol-transactions.derived.ts
- src/frontend/src/tests/btc/derived/btc-transactions.derived.spec.ts
- src/frontend/src/tests/eth/derived/eth-transactions.derived.spec.ts
- src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts
- src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
- src/frontend/src/tests/sol/derived/sol-transactions.derived.spec.ts
We need to update the KnownDestinations stores according to the new specs. ]
Note: there are a few differences in txs stores that do not allow us to easily re-use the code inside `knownDestinations` derived.
> feat(frontend): update KnownDestinations stores

- src/backend/src/lib.rs
- src/backend/src/user_profile.rs
- src/backend/tests/it/user_credentials.rs
- src/shared/src/types.rs
- src/shared/src/types/result_types.rs
We want to use the result types in the tests too. So we need to move them to the shared folder.
> refactor(frontend): move `result_types` to shared folder

- src/frontend/src/lib/components/convert/ConvertAmountDisplay.svelte
- src/frontend/src/lib/components/convert/ConvertAmountExchange.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/tests/lib/components/convert/ConvertAmountDisplay.spec.ts
- src/frontend/src/tests/lib/components/convert/ConvertAmountExchange.spec.ts
We need to hide skeleton in ConvertAmountExchange if exchange rate is not available for a token.
1. `ConvertAmountExchange` update - the exchange skeleton will be shown only while `value` is not available.
2. Replaced hardcoded testIds in the related components.
Added new tests.
> fix(frontend): update ConvertAmountExchange skeleton logic

- src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
- src/frontend/src/sol/stores/sol-fee.store.ts
- src/frontend/src/tests/sol/components/send/SolSendForm.spec.ts
- src/frontend/src/tests/sol/components/send/SolSendReview.spec.ts
We need to extend the sol-fee context with additional store for the token id in which the fee will be paid (similar as in the eth-fee context).
> feat(frontend): add token id store to the sol-fee context

- src/frontend/src/lib/components/send/SendFeeInfo.svelte
- src/frontend/src/lib/components/ui/MessageBox.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/send/SendFeeInfo.spec.ts
In order to display an info banner when a fee symbol does not match with a send token symbol, we need to have a new reusable component.
> feat(frontend): SendFeeInfo component

- src/frontend/src/eth/components/send/EthSendForm.svelte
- src/frontend/src/sol/components/send/SolSendForm.svelte
We can now start using the `SendFeeInfo` component in ETH and SOL send flows.
> feat(frontend): use SendFeeInfo in SOL/ETH send

- src/frontend/src/lib/components/swap/SwapReview.svelte
- src/frontend/src/lib/components/swap/SwapWizard.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/stores/swap.store.ts
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/stores/swap.store.spec.ts
Refactored failedSwapStore to support storing error messages with their variant type and optional url.
- Updated failedSwapStore to support structured error data: { message, variant, url? }
- Adjusted usage across components to match the new structure
Added unit tests to cover the new structure and ensure correct behavior
> feat(frontend): refactored swapFailedStore

- src/frontend/src/lib/components/convert/ConvertAmountExchange.svelte
- src/frontend/src/tests/lib/components/convert/ConvertAmountExchange.spec.ts
We need to improve the ConvertAmountExchange component so it can handle the following cases:
1. If `usdValue` is 0, we display it as `$0.00`.
2. If `usdValue` is less than 0.01, we display it as `< $0.00`.
3. If `usdValue` is greater than 0.01, we display it as `~$0.03`.
> feat(frontend): improve ConvertAmountExchange component

- src/frontend/src/env/networks/networks-evm/networks.evm.env.ts
- src/frontend/src/env/networks/networks-evm/networks.evm.polygon.env.ts
- src/frontend/src/env/tokens/tokens-evm/tokens.evm.env.ts
- src/frontend/src/lib/constants/tokens.constants.ts
- src/frontend/src/lib/derived/network.derived.ts
- src/frontend/src/lib/derived/token.derived.ts
- src/frontend/src/lib/utils/network.utils.ts
- src/frontend/src/tests/eth/components/loaders/LoaderEthBalances.spec.ts
- src/frontend/src/tests/eth/components/loaders/LoaderMultipleEthTransactions.spec.ts
- src/frontend/src/tests/lib/components/guard/AddressGuard.spec.ts
- src/frontend/src/tests/lib/derived/all-tokens.derived.spec.ts
- src/frontend/src/tests/lib/derived/network-tokens.derived.spec.ts
- src/frontend/src/tests/lib/derived/token.derived.spec.ts
- src/frontend/src/tests/lib/derived/tokens.derived.spec.ts
- src/frontend/src/tests/lib/services/loader.services.spec.ts
- src/frontend/src/tests/lib/utils/network.utils.spec.ts
As for the other networks, we need to define the default token of Polygon networks.
- Create util to check id a network ID is Polygon.
- Create derived store to verify the current network if it's Polygon.
- Map the current network to POL default token if it's Polygon network.
More test and current tests will be sufficient.
> feat(frontend): define default token for Polygon networks

- src/frontend/src/lib/components/swap/SwapWizard.svelte
- src/frontend/src/lib/services/swap.services.ts
Refactored the token swap logic to move the provider-specific method call into a separate function. While calling the swap method dynamically could be risky, using the `SwapProvider` enum ensures that only valid keys are used. This provides type safety and guarantees that the corresponding method exists at compile time. The main goal of this change is to improve readability, structure, and testability of the swap logic.
Extracted the dynamic provider call from the swap function into a dedicated helper
> feat(frontend): add execution for swapService based on selected provider

- src/frontend/src/env/tokens/tokens-evm/tokens.erc20.env.ts
- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/tests/btc/utils/token.utils.spec.ts
- src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
- src/frontend/src/tests/icp-eth/utils/token.utils.spec.ts
- src/frontend/src/tests/sol/utils/spl.utils.spec.ts
- src/frontend/src/tests/sol/utils/token.utils.spec.ts
All the current ERC20 tokens for EVM networks (and their wrapped standard like BEP20) are treated the same way. So, to improve manageability, we can collect them in a single list that can be updated accordingly.
> refactor(frontend): collect all EVM ERC20 tokens in a single list

- src/frontend/src/eth/derived/eth-transactions.derived.ts
- src/frontend/src/tests/eth/derived/eth-transactions.derived.spec.ts
For ETH network tokens, we want to display known destinations that only belongs to the selected token network.
> feat(frontend): known destinations only for the current ETH network

- src/frontend/src/lib/components/swap/SwapModal.svelte
The filter field during the `swap` process should be reset after `canceling` the process or when `selecting` a token.
- resets filter
**before:**
https://github.com/user-attachments/assets/4d0b33ad-5bf9-4f1e-8f5c-cf672b74f710
**after:**
https://github.com/user-attachments/assets/c7d64d1e-e427-4203-a5c0-9ac18772c2bd
> feat(frontend): resets filter field after closing

- src/frontend/src/lib/components/tokens/TokenInputCurrency.svelte
- src/frontend/src/lib/components/tokens/TokenInputCurrencyUsd.svelte
The `InputField` in the `swap` and `send` form do have a bad padding which cuts off the visible digits too early,
- fixes padding
**before:**
**after:**
> fix(frontend): fixes TokenInputCurrency and TokenInputCurrencyUsd field padding

- src/frontend/src/lib/components/send/KnownDestinations.svelte
- src/frontend/src/lib/types/transactions.ts
- src/frontend/src/lib/utils/transactions.utils.ts
- src/frontend/src/tests/btc/derived/btc-transactions.derived.spec.ts
- src/frontend/src/tests/eth/derived/eth-transactions.derived.spec.ts
- src/frontend/src/tests/icp/derived/ic-transactions.derived.spec.ts
- src/frontend/src/tests/lib/components/send/KnownDestinations.spec.ts
- src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
- src/frontend/src/tests/sol/derived/sol-transactions.derived.spec.ts
We need to sort all known destinations by timestamp. To do that, we add `address` to the `knownDestinations` stores and sort the values before filtering them in the UI component.
> feat(frontend): sort known destinations by timestamp

- src/frontend/src/lib/types/swap.ts
- src/frontend/src/lib/utils/swap.utils.ts
- src/frontend/src/tests/lib/utils/swap.utils.spec.ts
The logic for calculating and formatting the minimum expected receive amount after applying slippage was previously duplicated and embedded inside components. This PR introduces a dedicated utility function to centralize that logic, improve code reuse, and increase overall clarity and maintainability.
- Added `formatReceiveOutMinimum` utility:
- Accepts `slippageValue`, `receiveAmount`, and `decimals`
- Calculates slippage-adjusted amount
- Formats the result based on token precision
- Simplified related component logic by delegating formatting to the new utility
- Added unit tests for `formatReceiveOutMinimum`
- Covers valid numeric and string input
- Handles edge cases like empty, null, and undefined slippage
- Validates formatting and calculation behavior
> feat(frontend): added new formatReceiveOutMinimun util

- src/frontend/src/lib/components/settings/SettingsModalEnabledNetworks.svelte
This is the fix for the issue that was introduced after making `enabledNetworks` reactive. As a part of the migration to Svelte 5, the further refactorings need to be done to this component.
> fix(frontend): issue with SettingsModalEnabledNetworks

- src/frontend/src/lib/components/swap/SwapDetailsIcp.svelte
- src/frontend/src/lib/components/swap/SwapForm.svelte
- src/frontend/src/lib/components/swap/SwapProvider.svelte
- src/frontend/src/lib/components/swap/SwapReview.svelte
- src/frontend/src/tests/lib/components/swap/SwapDetailsIcp.spec.ts
The logic for calculating and formatting the minimum receive amount with slippage was previously handled inline within components. This led to code duplication and reduced clarity. The goal of this change is to centralize that logic using a utility function (`formatReceiveOutMinimum`) to improve readability, reusability, and testability.
- Replaced inline slippage calculation and formatting in ICP swap view with `formatReceiveOutMinimum` utility
- Reduced duplication and improved separation of concerns between logic and UI
> feat(frontend): replace manual slippage formatting with formatReceiveOutMinimum

- src/frontend/src/lib/components/swap/SwapProviderListItem.svelte
- src/frontend/src/lib/components/swap/SwapProviderListModal.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/swap/SwapProviderListItem.spec.ts
The previous logic for displaying the USD balance in swap providers showed $0.00. This changes would show USD value not available instead
- Refactored `getUsdBalance` utility
- Ensured it returns `undefined` gracefully when data is incomplete
- Updated swap provider UI to handle missing USD values with shorter fallback text
- Added unit tests for `getUsdBalance`
> feat(frontend): improve getUsdBalance to safely handle undefined values

- src/frontend/src/lib/components/icons/IconDots.svelte
- src/frontend/src/lib/components/networks/NetworkButton.svelte
We want to be able to hide the balances on the `NetworkButton` whether the `privacy mode` is turned on or off.
- adds `IconDots`
- adds privacy mode to `NetworkButton`
> feat(frontend): adds privacy mode to NetworkButton

- src/frontend/src/lib/components/hero/Balance.svelte
We want to be able to hide the balance on the transaction page Hero component if privacy mode is on.
- adds privacy mode to `Balance`
**on:**
**off:**
> feat(frontend): adds privacy mode to Balance

- src/frontend/src/lib/components/tokens/TokenBalance.svelte
- src/frontend/src/lib/components/tokens/TokenCard.svelte
We want to be able to hide the balances on the displayed tokens if privacy mode is on.
- add privacy mode to `TokenCard`
**on:**
**off:**
> feat(frontend): adds privacy mode to TokenCard

- src/frontend/src/lib/components/ui/ButtonMenu.svelte
We want to be able to set `Tags` to the Menu items.
- supports `Tags`
> feat(frontend): enables to set Tags to ButtonMenu

- src/frontend/src/lib/schema/address.schema.ts
- src/frontend/src/lib/types/address.ts
- src/frontend/src/sol/utils/sol-address.utils.ts
- src/frontend/src/tests/lib/schema/address.schema.spec.ts
In order to be able to parse solana adresses, this PR adds a `SolAddressSchema`
- Adds `SolAddressSchema`
- Use `SolAddressSchema` to infer `SolAddress` type
> feat(frontend): Add Solana address schema

- src/frontend/src/lib/components/navigation/NavigationItem.svelte
> refactor(frontend): upgrades NavigationItem to svelte 5

- src/frontend/src/lib/components/navigation/NavigationMenuMainItems.svelte
- Upgrades `NavigationMenuMainItems`
> refactor(frontend): upgrades NavigationMenuMainItems to svelte 5

- src/frontend/src/icp/services/ic-send.services.ts
We want to clean up the Send flow from the convert-related things. To do that, we need to make targetNetwork optional in sendIc.
> refactor(frontend): make targetNetwork optional in sendIc

- src/frontend/src/icp-eth/components/core/CkEthereumPendingTransactionsListener.svelte
We included the CK Ethereum pending transactions listener in the main page. However, this triggers too many calls. Just as HOTFIX, we disable the reactivity of the component for now. In the meanwhile we investigate.
NOTE: we simplified the reactivity too, since it had redundant elements.
> fix(frontend): HOTFIX: Disable reactivity for CK Ethereum pending transactions

- src/frontend/src/lib/schema/address.schema.ts
- src/frontend/src/lib/types/address.ts
- src/frontend/src/tests/lib/schema/address.schema.spec.ts
In order to be able to parse Eth adresses, this PR adds a `EthAddressSchema`
- Adds `EthAddressSchema`
- Use `EthAddressSchema` to infer `EthAddress` type
> feat(frontend): Add EthAddressSchema

- src/frontend/src/eth/providers/alchemy-erc20.providers.ts
- src/frontend/src/tests/eth/providers/alchemy-erc20.providers.spec.ts
As per thread https://github.com/ethers-io/ethers.js/issues/4784#issuecomment-2820177791:
> By default, etherjs uses RPC Filter and turns off polling. Filter relies on `eth_newFilter` / `eth_getFilterChanges`, both of which are state interfaces and need to store `filterId` status on the node. For service providers with distributed architectures such as Infura and QuickNode, each request may hit a different backend node, and these nodes do not share `filter` status. Therefore, they choose to disable `eth_newFilter` and `eth_getFilterChanges` and only support stateless requests (such as `eth_getLogs`) to ensure system stability and scalability.
This causes an extreme amount of console logs. Not errors, since it is expected according to https://github.com/ethers-io/ethers.js/issues/4796.
So, …
> fix(frontend): Add `polling` for Alchemy providers

- src/frontend/src/env/tokens/tokens-erc20/tokens.jasmy.env.ts
- src/frontend/src/env/tokens/tokens.erc20.env.ts
- src/frontend/src/eth/utils/erc20.utils.ts
- src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
Similar to others ERC20 tokens, we move the JASMY token to the list of additional ERC20 tokens.
> refactor(frontend): Move JASMY token to additional ERC20 tokens

- src/frontend/src/lib/components/swap/SwapProgress.svelte
As part of our migration to Svelte 5, this PR focuses on migrating the SwapProgress component to Svelte 5.
Migrated the SwapProgress component to Svelte 5.
> feat(frontend): migrated SwapProgress component to svelte 5

- src/frontend/src/env/tokens/tokens-erc20/tokens.dmail.env.ts
- src/frontend/src/env/tokens/tokens.erc20.env.ts
- src/frontend/src/eth/utils/erc20.utils.ts
- src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
Similar to others ERC20 tokens, we move the DMAIL token to the list of additional ERC20 tokens.
> refactor(frontend): Move DMAIL token to additional ERC20 tokens

- src/frontend/src/eth/services/erc20.services.ts
To solve one of our TODOs, instead of loading the metadata for all the User Tokens, we first check if we already have them in our static code metadata.
> feat(frontend): Use static metadata for user Tokens

- src/frontend/src/env/tokens/tokens-erc20/tokens.matic.env.ts
- src/frontend/src/env/tokens/tokens.erc20.env.ts
- src/frontend/src/eth/utils/erc20.utils.ts
- src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
Similar to others ERC20 tokens, we move the MATIC token to the list of additional ERC20 tokens.
> refactor(frontend): Move MATIC token to additional ERC20 tokens

- src/frontend/src/icp/components/send/IcSendAmount.svelte
- src/frontend/src/icp/components/send/IcSendForm.svelte
- src/frontend/src/tests/icp/components/send/IcSendAmount.spec.ts
As the next step of the Send flow clean up, we remove convert-related code from IcSendAmount.
> refactor(frontend): remove convert-related code from IcSendAmount

- src/frontend/src/icp/components/send/IcReviewNetwork.svelte
- src/frontend/src/icp/components/send/IcSendReview.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/tests/icp/components/send/IcSendReview.spec.ts
As the next step of the Send flow clean up, we remove `networkId` from IC send review form and related components.
> refactor(frontend): remove networkId usage from IC Send review

- src/frontend/src/eth/components/fee/EthFeeDisplay.svelte
- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/constants/eth.constants.ts
- src/frontend/src/tests/eth/components/fee/EthFeeDisplay.spec.ts
We want to update the ETH fees appearance logic:
1. To make sure we don't update UI too often, we throttle the `maxGasFee` update by 10s. On practice, It only affects Base tokens where the fees are being changed every ~1s. 
2. We now display skeleton only on initial fee fetch. The idea is to add some indicator (e.g. loader) that provides user a visual feedback when the fee values changes. It will be done separately.
> feat(frontend): update ETH fees logic

- src/frontend/src/lib/components/swap/SwapSlippage.svelte
- src/frontend/src/lib/components/tokens/TokenInputCurrency.svelte
- src/frontend/src/lib/components/tokens/TokenInputCurrencyToken.svelte
- src/frontend/src/lib/components/tokens/TokenInputCurrencyUsd.svelte
- src/frontend/src/lib/components/ui/InputCurrency.svelte
Since we upgraded the component to svelte 5 we also need to use the new `snippets` instead of `slots`.
- replaces `slots` with `snippets`
> refactor(frontend): upgrades TokenInputCurrency

- scripts/build.cycles_depositor.sh
- scripts/download.ckbtc.sh
- scripts/download.cketh.sh
- scripts/download.icp.sh
- scripts/generate.sh
- scripts/setup.bitcoin-node.sh
- scripts/test.backend.sh
We download a lot of data with curl.  In some places we try to make this more efficient by not downloading a file if it already exists, however that breaks if the URL changes, giving strange results.  We have a script now that does this properly, so we can roll it out everywhere.
- Use  `download-immutable` in most places where we used to curl.
Existing tests should verify that existing functionality still works.
> refactor(devops): No repeat downloads

- src/frontend/src/lib/components/ui/ButtonIcon.svelte
In order to be able to disable event propagation, this PR exposes the `MouseEvent` to the `onclick` event handler.
Expose the event in `ButtonInput`
> feat(frontend): Forward mouse event in ButtonIcon

- src/frontend/src/env/caip10-chains.env.ts
One more step towards removing non-null assertions: refactoring `CAIP10_CHAINS` to adapt to nullish chain IDs.
> refactor(frontend): remove non-null assertion from `CAIP10_CHAINS`

- src/frontend/src/lib/components/swap/SwapForm.svelte
One more step towards removing non-null assertions: refactoring `SwapForm` to adapt to nullish values of slippage.
> refactor(frontend): remove non-null assertion from `SwapForm`

- src/frontend/src/btc/components/send/BtcSendForm.svelte
- src/frontend/src/btc/components/send/BtcSendReview.svelte
- src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte
We want to remove convert-related code from BTC send components.
> refactor(frontend): remove convert-related code from BTC send components

- src/frontend/src/eth/components/loaders/LoaderEthBalances.svelte
- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/tests/eth/services/erc20.services.spec.ts
When we are loading metadata from existing static tokens, we should compare the addresses without being case-sensitive.
> fix(frontend): Loading metadata shall be case-insensitive

- src/frontend/src/lib/components/contact/AddressItemActions.svelte
- src/frontend/src/lib/components/contact/AddressListItem.svelte
- src/frontend/src/tests/lib/components/contact/AddressItemActions.spec.ts
The actions for addresses will be reused in contact card
- Created new component for address actions
> refactor(frontend): Make address line item actions reusable

- src/frontend/src/sol/components/send/SolSendForm.svelte
- src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
We want to remove convert-related code from SOL send components.
> refactor(frontend): remove convert-related code from SOL send components

- src/frontend/src/lib/constants/token-account-id.constants.ts
- src/frontend/src/lib/utils/token-account-id.utils.ts
- src/frontend/src/tests/lib/utils/token-account-id.utils.spec.ts
To display the supported networks for a given contact address, this PR adds a utility to get from `TokenAccountIdType` to the supported networks
- Adds `getNetworksForTokenAccountIdType`
- Add a test to ensure all types returns some networks
> feat(frontend): Add utility to get supported networks for token account id

- src/frontend/src/lib/types/utils.ts
No need to use `any` in type util `KeysOfUnion`. We can replace it with `unknown`.
> chore(frontend): Remove usage of `any` in `KeysOfUnion`

- src/frontend/src/eth/utils/eth.utils.ts
- src/frontend/src/lib/components/tokens/ManageTokenToggle.svelte
- src/frontend/src/lib/derived/token.derived.ts
- src/frontend/src/lib/utils/token-toggle.utils.ts
- src/frontend/src/tests/eth/utils/eth.utils.spec.ts
- src/frontend/src/tests/lib/utils/token-toggle.utils.spec.ts
The utils `isEthereumTokenToggleDisabled` and `isEthereumTokenToggleEnabled` are not exactly doing what the name suggests.
Basically, they should define whether an Ethereum or EVM native token can be toggled or not. For example, we don't want to give the choice to disable the ETH token in specific cases.
To that scope we refactor a bit the utils to understand better their scope.
- Move utils to proper module `eth.utils.ts`.
- Rename them to `isStandardEthereumToken` and `isNotStandardEthereumToken`.
- Adapt usage.
We created new tests, and since we are here, for all the ETH utils.
> refactor(frontend): Correct utils to verify Standard Ethereum tokens

- src/backend/src/lib.rs
- src/backend/tests/it/contacts.rs
We must allow non-anonymous users to call the address book endpoints. The guard `caller_is_allowed` currently used  only allows controllers and allowed principles (which must be registered on canister level) to call the endpoint.
- Updated the create_contact function to use the caller_is_not_anonymous guard.
- Updated the delete_contact function to use the caller_is_not_anonymous guard.
- Uncommenting test_contacts_are_isolated_between_users since the all valid principles are allowed to call the create_contact endpoint
> feat(backend): correct incorrect guards used for the contact endpoints

- src/frontend/src/env/networks/networks.icrc.env.ts
- src/frontend/src/icp/utils/icrc.utils.ts
- src/frontend/src/tests/icp/utils/icrc.utils.spec.ts
As requested, we need to overwrite GHOSTNODE token symbol with a custom value.
> feat(frontend): custom symbols for icrc tokens

- src/frontend/src/icp/services/icrc.services.ts
- src/frontend/src/icp/utils/icrc.utils.ts
- src/frontend/src/tests/icp/utils/icrc.utils.spec.ts
We can use the `oisySymbol` prop for the custom symbols of ICRC tokens.
> refactor(frontend): Use `OisySymbol` for custom symbols

- src/frontend/src/lib/components/ui/Button.svelte
Allows the button text to be aligned left. Needed in AddressBookEdit step. See: https://github.com/dfinity/oisy-wallet/pull/6557
Adds property to set text alignement.
> feat(frontend): Allow button text to be aligned left

- src/frontend/src/lib/components/address/InputAddress.svelte
To react in the address form to any errors, this PR exposes the error.
- Expose the error
No tests are added since for testing the `svelte-htm` library would be neede, which we don't have integrated.
> feat(frontend):  Expose InputAddress parse error

- src/frontend/src/lib/components/address-book/EditContactStep.svelte
- src/frontend/src/lib/components/contact/AddressListItem.svelte
- src/frontend/src/lib/components/contact/ContactCard.svelte
- src/frontend/src/lib/components/icons/lucide/IconTrash.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/address-book/EditContactStep.spec.ts
- src/frontend/src/tests/lib/components/contact/AddressListItem.spec.ts
Adds the contact edit step where the user will be able to manage addresses, delete the contact and jump to the contact form to modify the name.
- Adds contact edit step
- Adds additional tests
Note: The delete confirmation is not yet implemented.
[vokoscreenNG-2025-05-26_10-11-41.webm](https://github.com/user-attachments/assets/e7adb884-3d08-42fe-8826-61c0e986d3d3)
> feat(frontend): Add edit contact step

- src/frontend/src/lib/constants/analytics.contants.ts
- src/frontend/src/lib/services/manage-tokens.services.ts
- src/frontend/src/tests/lib/services/manage-tokens.services.spec.ts
It is useful to know which tokens are included and which ones are disabled by the users. So that we can have static metadata for them (or remove them) and improve performance.
> feat(frontend): Create event for enabled and disabled tokens

- src/frontend/src/lib/components/ui/Tabs.svelte
- src/frontend/src/tests/lib/components/ui/Tabs.spec.ts
To implement the update design for the SendDestinationWizardStep, we need to create a new component - `Tabs`.
> feat(frontend): implement Tabs component

- src/frontend/src/lib/components/send/KnownDestinations.svelte
- src/frontend/src/lib/components/send/SendContacts.svelte
- src/frontend/src/lib/components/send/SendDestinationTabs.svelte
- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/send/KnownDestinations.spec.ts
- src/frontend/src/tests/lib/components/send/SendDestinationTabs.spec.ts
- src/frontend/src/tests/mocks/transactions.mock.ts
We continue extending the SendDestinationWizardStep by introducing `SendDestinationsTabs`.
> feat(frontend): SendDestinationsTabs component and related updates

- src/frontend/src/sol/components/transactions/SolTransactionModal.svelte
- src/frontend/src/tests/sol/components/transactions/SolTransactionModal.spec.ts
Were refactoring how the transaction details modal look.
Adjusted design according to Figma
Added tests
SOL receive:
SOL send:
> refactor(frontend): SOL Transaction details

- src/frontend/src/lib/utils/token-account-id.utils.ts
- src/frontend/src/tests/lib/utils/token-account-id.utils.spec.ts
In order to serialize Icrcv2 Addresses to strings, this PR adds the missing functionality to the `getTokenAccountIdAddressString` method.
- Completes getTokenAccountIdAddressString implementation
- Adds test to verify serialization to string
- Adds test to ensure parsing and serialization leads to original string
> feat(frontend): Add missing implementation for Icrcv2 token account id to address string

- src/frontend/src/lib/components/send/KnownDestination.svelte
We now want to use Avatar component in KnownDestination, for now it will be always displayed with the "anonymous" icon.
> feat(frontend): use Avatar component in KnownDestination

- src/frontend/src/lib/components/address-book/AddressBookModal.svelte
- src/frontend/src/lib/constants/analytics.contants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/address-book/AddressBookModal.spec.ts
- src/frontend/src/tests/mocks/manage-contacts.service.mock.ts
In order to really save the contacts in the backend, this PR integrates the contacts store and contacts.service with minimal changes. Further optimization to come.
- Use service methods for contacts CRUD
- Use contacts store for address book
> feat(frontend): Use real contacts backend in address book 

- src/frontend/src/lib/components/address/AddressCard.svelte
For an upcoming feature we need an info variant on the AddressCard component.
- Added variant to component
Default variant:
Info variant:
> refactor(frontend): Address Card variant

- src/frontend/src/lib/components/address-book/EditAddressStep.svelte
For the upcoming feature #6980 we need the possibility to use an address from modal data and prefill and disable the EditAddress input.
Take modal data address if supplied and prefill/disable address input
WIth entrypoint & address defined in store data:
Without store data:
> refactor(frontend): Use modaldata address in edit address book step

- src/frontend/src/lib/services/custom-tokens.services.ts
- src/frontend/src/tests/lib/services/custom-tokens.services.spec.ts
The `Principal` objects of the Ledger and Index canister IDs of custom tokens are saved in the cached as `Uint8Array` objects. So we need to parse them correctly when we re-fetch them form the cache.
Add mapper for Icrc tokens in service `loadNetworkCustomTokens`.
Included tests.
> fix(frontend): Correctly parse `Principal` from cached tokens

- src/frontend/src/lib/components/address/SkeletonAddressCard.svelte
- src/frontend/src/lib/components/transactions/TransactionContactCard.svelte
We are going to provide possibly undefined addresses to the component TransactionContactCard. That is because we will be showing the owner address in a Solana transaction, that is derived from the ATA address, and that takes a bit of time (async function).
While it is loading, we will show a skeleton.
> feat(frontend): `To` and `From` are optional in `TransactionContactCard`

- src/frontend/src/lib/types/contacts.ts
- src/frontend/src/lib/utils/contacts.utils.ts
- src/frontend/src/tests/lib/utils/contacts.utils.spec.ts
Before creating stores for each network, we need to implement a util for parsing `contacts` and returning a dictionary with contacts by address type. It will be used in the Address Picker step in the Send flow.
> feat(frontend): network contacts util

- src/frontend/src/btc/components/transactions/BtcTransactionModal.svelte
- src/frontend/src/eth/components/transactions/EthTransactionModal.svelte
- src/frontend/src/icp/components/transactions/IcTransactionModal.svelte
- src/frontend/src/sol/components/transactions/SolTransactionModal.svelte
- src/frontend/src/tests/btc/components/transactions/BtcTransactionModal.spec.ts
- src/frontend/src/tests/eth/components/transactions/EthTransactionModal.spec.ts
- src/frontend/src/tests/icp/components/transactions/IcTransactionModal.spec.ts
- src/frontend/src/tests/sol/components/transactions/SolTransactionModal.spec.ts
We decided to remove the information about the user address in the transaction modal. For example, when it is a `receive` transaction, the `To` field will not appear.
> style(frontend): Remove address from transaction modal if it is myself

- src/frontend/src/lib/components/address-book/AddressBookModal.svelte
- src/frontend/src/tests/lib/components/address-book/AddressBookModal.spec.ts
After creating a new contact the user should land on the `contact card` instead of the `contact list`.
- improves flow
**before:**
https://github.com/user-attachments/assets/5c4b96e5-af14-4695-aa0a-bf0f94e3d52b
**after:**
https://github.com/user-attachments/assets/aff5fec2-3daa-45a3-a587-ceaa82a821f6
> feat(frontend): improves create contact flow

- src/frontend/src/lib/components/address-book/AddressBookModal.svelte
- src/frontend/src/tests/lib/components/address-book/AddressBookModal.spec.ts
In the SAVE_ADDRESS flow we should close the modal once the address has been added.
- added condition with close modal call
- added comment explaining this is end of the flow
https://github.com/user-attachments/assets/459379fa-7c3f-4010-937e-7fc95f801a73
> fix(frontend): Close address book modal if addres has been added in SAVE_ADDRESS flow

- src/frontend/src/lib/i18n/en.json
Since also show apps in the explorer, we should correctly name them apps and not dapps.
Note: The page header was already set to "Explore Apps"
Labels and alts texts for buttons change from dapp to app
> feat(frontend): change labels and alts from dapp to app

- src/frontend/src/lib/i18n/en.json
The 2 texts we show when an index canister is not set or not working properly are very 'cryptic'.
Change the texts according to Pierre's suggestions.
**Missing index canister**
**Failing index canister**
> feat(frontend): change index canister issue messages

- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
We need to pass networkId to BtcSendDestination for the validation to work correctly.
> fix(frontend): pass networkId to BtcSendDestination

- src/frontend/src/lib/components/contact/ContactCard.svelte
According to comment https://github.com/dfinity/oisy-wallet/pull/7039#discussion_r2114015180 we need to remove a class because the element is not flex anymore.
Removed `items-center` class
> refactor(frontend): Cleanup classes in contact card

- src/frontend/src/lib/components/send/KnownDestination.svelte
- src/frontend/src/lib/components/send/KnownDestinations.svelte
- src/frontend/src/tests/lib/components/send/KnownDestination.spec.ts
We should use `onClick` prop instead of `on:click` event in KnownDestination.
> refactor(frontend): switch to onClick prop in KnownDestination

- package-lock.json
- package.json
Ideally we should bump ethers and already adapt the code in the same PR, since there was a quasi-breaking change (at least for our code, see https://github.com/ethers-io/ethers.js/issues/4975#issuecomment-2910714249). To monitor the correct code execution, we will tackle this with PR:
- https://github.com/dfinity/oisy-wallet/pull/7013
For now, we revert it to the previous version.
> feat(frontend): Revert bumping of ethers from 6.14.3 to 6.13.7

- src/frontend/src/lib/components/address-book/AddressBookModal.svelte
Allow always to close address book wizard with the cross on top right.
- Allow pointer events in address book
> feat(frontend): Allow closing address book with cross

- src/frontend/src/lib/components/address-book/AddressBookStep.svelte
Text of add contact input breaks into two lines on small screen. Makes input and button responsive.
- Hide button text on small scerens
- Use flex to resize search input and button
[vokoscreenNG-2025-05-30_10-14-43.webm](https://github.com/user-attachments/assets/265382cf-ced4-41db-82f4-27b892516fc0)
> fix(frontend): Make search and add contact button responsive

- src/frontend/src/icp/derived/ic-contacts.derived.ts
- src/frontend/src/tests/icp/derived/ic-contacts.derived.spec.ts
We need to separate `icNetworkContacts` for the ICP and ICRC cases in order to display only valid addresses for the selected IC token.
> feat(frontend): display only valid contacts for ICP/ICRC tokens

- src/frontend/src/lib/components/contact/Avatar.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
The primary goal is to make the Avatar component more accessible, aligning with best practices for web accessibility.
Updated the Avatar component to include role="img" and aria-label attributes.
Manual Testing: 
Verified that screen readers announce the avatar correctly with both name and alt props.
Ensured that the IconAvatar component renders without issues.
> fix(frontend): add aria-label and role to avatar element

- src/frontend/src/btc/components/send/BtcSendDestination.svelte
- src/frontend/src/eth/components/send/EthSendDestination.svelte
- src/frontend/src/icp/components/send/IcSendDestination.svelte
- src/frontend/src/lib/components/send/SendContact.svelte
- src/frontend/src/lib/components/send/SendContacts.svelte
- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
- src/frontend/src/lib/components/send/SendInputDestination.svelte
- src/frontend/src/sol/components/send/SolSendDestination.svelte
- src/frontend/src/tests/lib/components/send/SendContacts.spec.ts
- src/frontend/src/tests/lib/components/send/SendInputDestination.spec.ts
Similar to what we do with the "recent destinations", we should filter use contacts based on the inputted address. Also, the "unknown destination" message should be only displayed if the address is not available in any of the categories.
> feat(frontend): filter network contacts

- src/frontend/src/lib/components/send/SendContact.svelte
- src/frontend/src/tests/lib/components/send/SendContact.spec.ts
- src/frontend/src/tests/lib/components/send/SendDestinationTabs.spec.ts
We need to display contact label if available in SendContact.
> feat(frontend): display contact label if available in SendContact

- src/frontend/src/btc/components/send/BtcSendForm.svelte
- src/frontend/src/btc/components/send/BtcSendTokenWizard.svelte
- src/frontend/src/eth/components/send/EthSendForm.svelte
- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
- src/frontend/src/icp/components/send/IcSendForm.svelte
- src/frontend/src/icp/components/send/IcSendTokenWizard.svelte
- src/frontend/src/lib/components/send/SendDestination.svelte
- src/frontend/src/lib/components/send/SendForm.svelte
- src/frontend/src/lib/components/send/SendModal.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
- src/frontend/src/sol/components/send/SolSendForm.svelte
- src/frontend/src/sol/components/send/SolSendTokenWizard.svelte
If user selects a contact as a receiver while sending tokens, we should display it accordingly in the Send form.
> feat(frontend): display selectedContact in Send forms

- src/frontend/src/lib/components/send/SendContact.svelte
There was an issue with the address label extraction in SendContact.
> fix(frontend): incorrect address labels in SendContact

- src/frontend/src/lib/components/address/AddressForm.svelte
- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/lib/constants/token-account-id.constants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/schema/contact.schema.ts
- src/frontend/src/lib/schema/token-account-id.schema.ts
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/address/AddressForm.spec.ts
There are validation errors in the backend when an address with an alias more than 50 characters is saved. This PR adds FE validation for this.
- Adds a ContactAddressUi schema
- Adds validation to the address form
> feat(frontend): Add label validation

- src/frontend/src/sol/components/transactions/SolTransactionModal.svelte
- src/frontend/src/tests/sol/components/transactions/SolTransactionModal.spec.ts
After PR #7100 , we can use directly the props fromOwner and toOwner of the Solana transaction, instead of calculating the owner addresses in the component.
> feat(frontend): Use Solana transaction data for owner address

- src/frontend/src/sol/derived/sol-transactions.derived.ts
- src/frontend/src/tests/sol/derived/sol-transactions.derived.spec.ts
The store for known Solana recipient should show the owner address instead of the ATA address. We can do it thanks to the changes of https://github.com/dfinity/oisy-wallet/pull/7100
> feat(frontend): Show owner address instead of ATA for recent Solana recipients

- src/frontend/src/sol/schedulers/sol-wallet.scheduler.ts
- src/frontend/src/tests/sol/schedulers/sol-wallet.scheduler.spec.ts
The Solana services request quite an high number of queries, especially for multiple tokens and transactions. To try and amend at least a bit more for the limit of request per seconds, we increase the number of retries for the Solana wallet worker.
> feat(frontend): Increase the number of Solana wallet sync retries

- src/frontend/src/lib/components/send/KnownDestinations.svelte
- src/frontend/src/lib/components/send/SendDestination.svelte
- src/frontend/src/lib/components/send/SendDestinationTabs.svelte
We also need to save contact for the next steps if selected in the known destinations list. Also, we should display it correctly with the badge and font-bold on the Send Form screen.
> feat(frontend): save contact if selected in the known destinations list

- src/frontend/src/lib/components/contact/ContactCard.svelte
- src/frontend/src/lib/components/ui/ButtonIcon.svelte
We enhance the styling of the contact addresses group cards.
- Adjusted ButtonIcon to allow to set height prop as well
- Adjusted padding between Avatar and Name as well as the address list left padding
- Adjusted hover state colors
- Adjusted card bg
Hover on first address:
Hover on caret icon:
Hover on last contact:
Mobile:
> style(frontend): Address group enhancements

- src/frontend/src/lib/components/address-book/ShowContactStep.svelte
The add address button is not correctly styled.
Adjusted to `secondary-light` and added more vertical padding as defined by Dan
> style(frontend): Add address button

- package-lock.json
- src/frontend/src/lib/components/address-book/EditAddressStep.svelte
- src/frontend/src/tests/lib/components/address-book/EditAddressStep.spec.ts
The motivation behind this PR is to enhance user experience by ensuring that the Save button is only enabled when alias is  changed during the edit process.
Introduced originalLabel and labelChanged Derived States.
Updated Save Button Logic - Modified the disabled property of the Save button to consider both the form's validity (isInvalid) and whether the alias has been altered (labelChanged).
Unit test
Verifies that the Save button remains disabled if the alias field is not modified during editing.
> feat(frontend): disable save button if alias is not changed

- src/frontend/src/lib/components/address-book/EditAddressStep.svelte
- src/frontend/src/lib/components/address/AddressForm.svelte
- src/frontend/src/sol/components/transactions/SolTransaction.svelte
- src/frontend/src/tests/lib/components/address-book/EditAddressStep.spec.ts
The primary goal of this PR is to enhance the user experience by implementing context-sensitive autofocus behavior in the address form. Specifically, when adding a new address, the focus should automatically be set to the address input field; when editing an existing address, the focus should shift to the label input field. This behavior is conditioned to activate only on desktop devices to maintain optimal usability across different platforms.
Introduced a new prop in the AddressForm component to determine which input field should receive focus upon rendering.
Using the isDesktop() function to ensure autofocus behavior is only applied on desktop devices.
Implemented conditional logic within the AddressForm to set focus.
Add 2 Unit Tests:
Verified that the focusField prop correctly sets …
> feat(frontend): add focus to the input depends on the view

- src/frontend/src/lib/components/share/ShareButton.svelte
> refactor(frontend): upgrades ShareButton to svelte 5

- src/frontend/src/lib/components/swap/SwapProvider.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
We had an unlocalized value displayed in SwapProvider.
> refactor(frontend): use localized value in SwapProvider

- src/frontend/src/lib/components/common/ModalListItem.svelte
- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/tests/lib/components/common/ModalListItem.spec.ts
- src/frontend/src/tests/lib/components/tokens/TokenModal.spec.ts
We need to create a re-usable TokenModal component. It is based on the existing `Token` component, but now includes the Modal-related usage. Also, instead of `Value`, `ModalValue` is now used for displaying the data.
UPD: the design is now a bit different
> feat(frontend): TokenModal component

- src/frontend/src/icp-eth/services/eth.services.ts
- src/frontend/src/lib/constants/analytics.contants.ts
We want to track errors that concerns loading pending Ethereum transactions (and hide the toast, that is not useful to the user).
> feat(frontend): Track errors while loading pending Ethereum transactions

- src/frontend/src/lib/components/address-book/ContactForm.svelte
- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/address-book/ContactForm.spec.ts
We introduced a maximum character limit of 100 for the contact name.
Added a derived reactive value isNameTooLong to check if the contact name exceeds 100 characters.
Rendered an animated error message using slide transition when the name exceeds the limit.
Updated the error message to use replacePlaceholders with the correct max length from a constant.
Added a new unit test to ensure the error message is displayed when the name exceeds 100 characters.
Manual testing:
Snapshot and visual check for the slide transition animation of the error message.
> feat(frontend): validate contact name

- src/frontend/src/lib/components/send/SendTokensList.svelte
- src/frontend/src/lib/components/swap/SwapTokensList.svelte
- src/frontend/src/lib/components/tokens/ModalTokensListItem.svelte
In Svelte 5 event dispatchers are deprecated. So we can remove it from `ModalTokensListItem`.
> feat(frontend): Remove event dispatcher from `ModalTokensListItem` component

- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
In send flow when we select a contact, the contact is displayed correctly on the next form where we can enter the amount to send. When we go back and click next again the contact doesnt show anymore.
We want to persist the selected contect when navigating the send modal wizard, except for when we select another contact.
Removed the reset of the contact on mounting the select contact step.
https://github.com/user-attachments/assets/a159c60f-fd30-4e0a-9bef-23bb8581b6fc
> fix(frontend): Keep selected contact during whole send flow

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/canisters/backend.canister.ts
- src/frontend/src/tests/lib/canisters/backend.canister.spec.ts
For deleting user tokens, we need to expose the related method of the backend canister.
> feat(frontend): expose backend's remove_user_token method

- src/frontend/src/lib/components/tokens/TokenModalDeleteConfirmation.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/tokens/TokenModalDeleteConfirmation.spec.ts
We need to implement a component for confirming token deletion.
> feat(frontend): TokenModalDeleteConfirmation component

- src/frontend/src/lib/utils/address.utils.ts
- src/frontend/src/tests/lib/utils/address.utils.spec.ts
It is useful to use a generic function to get the case-sensitiveness of a network, either by type of address or by network ID.
It will be used for the known destinations and the contacts too.
- Create map of networks to address type.
- Create util `getCaseSensitiveness` that uses either network Id or address type.
- Use it in the code.
Added tests.
> feat(frontend): Util to get the case-sensitiveness of a network

- src/frontend/src/lib/components/send/KnownDestinations.svelte
In component `KnownDestinations` we will change the logic of how the addresses are filtered, using case-sensitive logic. So, before that, we expand the logic maintaining the same flow, to be easier to modify after.
> refactor(frontend): Expand logic of component `KnownDestinations`

- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/lib/components/tokens/TokenModalContent.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/tokens/TokenModal.spec.ts
We can now introduce the token delete functionality to the TokenModal component. For now, it will only work for "user tokens" (erc20), but later will be extended with ICRC/SPL deletions (BE needs to have a new endpoint for that).
> feat(frontend): add delete functionality to TokenModal

- src/frontend/src/lib/components/send/SendContacts.svelte
In PR https://github.com/dfinity/oisy-wallet/pull/7242 I simplified the component `SendContacts` in the wrong way: I should have used `Object.entries`, so that there is no need to use the util to get the value from the record.
> refactor(frontend): Correctly simplify component `SendContacts`

- src/frontend/src/eth/components/tokens/EthTokenModal.svelte
- src/frontend/src/eth/derived/erc20.derived.ts
- src/frontend/src/tests/eth/components/tokens/EthTokenModal.spec.ts
The last step of enabling the deletion of custom ERC20 tokens is to check whether a token is a non-default ERC20 and pass `isDeletable` prop to TokenModal accordingly.
> feat(frontend): enable deletion of custom ERC20 tokens

- src/frontend/src/eth/components/tokens/EthAddTokenReview.svelte
- src/frontend/src/lib/utils/address.utils.ts
- src/frontend/src/sol/components/tokens/SolAddTokenReview.svelte
- src/frontend/src/tests/lib/utils/address.utils.spec.ts
For util `areAddressesEqual` it is more versatile if we use the network ID.
> feat(frontend): Use network ID instead of address type in util `areAddressesEqual`

- src/frontend/src/lib/api/idb-tokens.api.ts
- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/lib/types/idb-tokens.ts
- src/frontend/src/tests/lib/api/idb-tokens.api.spec.ts
- src/frontend/src/tests/lib/components/tokens/TokenModal.spec.ts
When user removes an ERC20 token, we should also delete it from IDB.
> feat(frontend): remove ERC20 token from IDB on token delete

- src/frontend/src/lib/utils/address.utils.ts
- src/frontend/src/lib/utils/contact.utils.ts
- src/frontend/src/tests/lib/utils/address.utils.spec.ts
- src/frontend/src/tests/lib/utils/contact.utils.spec.ts
We need to match the contacts based on network case-sensitiveness even in the transaction list.
- Adapt util `areAddressesEqual` to accept both network ID and address type.
- Use it in util `getContactForAddress` that the transaction list apply to match addresses.
Matched transaction with lower case address to a contact with some upper case character.
> feat(frontend): Use network case-sensitiveness in transaction list

- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/tokens/TokenModal.spec.ts
We need to make the title of TokenModalDeleteConfirmation shorter - `Delete token`.
> feat(frontend): change title of the Token Modal delete confirmation

- src/frontend/src/lib/components/send/SendContactName.svelte
- src/frontend/src/lib/components/transactions/Transaction.svelte
- src/frontend/src/lib/utils/contact.utils.ts
- src/frontend/src/tests/lib/utils/contact.utils.spec.ts
To avoid repetition of code we create an util to filter the address inside a contact. 
- Util `filterAddressFromContact` will filter among the addresses of a contact, based on network case-sensitiveness (it uses existing code).
- Use the util in the code.
Added tests.
> feat(frontend): Util to filter an address inside a contact

- src/frontend/src/tests/lib/components/swap/SwapWizard.spec.ts
The tests for `SwapWizard` are causing a bit of flakiness since they have a debounce check for non-nullish identity (component `IcTokenFeeContext`), and they sign out in case of nullish identity. Since it is debounced, it happens only if the tests takes longer that the interval, hence the flakiness.
To avoid it, we mock the identity and we mock the sign out function.
> test(frontend): Remove flakiness from `SwapWizard` tests

- src/frontend/src/eth/components/transactions/EthTransactionModal.svelte
- src/frontend/src/eth/components/transactions/EthTransactionStatus.svelte
Component `EthTransactionStatus` was using the `token` store, but we are trying to deprecate it, so we can use directly the `token` props from its parent.
> feat(frontend): Remove `token` store from `EthTransactionStatus`

- src/frontend/src/lib/components/address-book/EditContactNameStep.svelte
- src/frontend/src/lib/components/address-book/InputContactName.svelte
- src/frontend/src/tests/lib/components/address-book/InputContactName.spec.ts
- src/frontend/src/tests/lib/components/address-book/InputContactNameTestHost.svelte
In order for a future feature where we want to have a create contact page in the address book, we clean up the current forms as they have been built differently.
- Renamed to input because the form inside the component makes compositions difficult and moved the form to the page where the submit happens and the input is used
- No exported variables in the component anymore
- Cleaned up usage of form
- Removed manually event handler for key presses (submit on enter - now down with form submit)
- Cleaned up isValid vars
- Added a condition to not submit when disabled (it was possible to submit multiple times when hitting enter multiple times)
Added a test host component and adjusted the tests accordingly
> refactor(frontend): Contact name form

- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
In PR #7205, we wanted to avoid resetting the selected contact when moving back and forth between steps in the send flow. However, this causes inconsistencies if the user modify the address in the input:
https://github.com/user-attachments/assets/429d41bb-cddf-47c6-87a0-a798b905ba67
So, we re-instate resetting the selected contact:
https://github.com/user-attachments/assets/57f84af8-1a00-42fa-a2c8-ade6851b499d
> feat(frontend): REVERT: reset selected contact when going back in send flow

- src/frontend/src/lib/components/address-book/EditContactNameStep.svelte
- src/frontend/src/tests/lib/components/address-book/InputContactName.spec.ts
When the default value of isValid is true, the submit button briefly is enabled before validation triggers and sets it to disabled.
isValid default value to false
Tests adjusted
> refactor(frontend): Contact name input default value isValid false

- src/frontend/src/tests/lib/components/convert/ConvertWizard.spec.ts
Similar to PR #7269.
The tests for `ConvertWizard` are causing a bit of flakiness since they have a debounce check for non-nullish identity (fee context components), and they sign out in case of nullish identity. Since it is debounced, it happens only if the tests takes longer that the interval, hence the flakiness.
To avoid it, we mock the identity and we mock the sign out function.
> test(frontend): Remove flakiness from `ConvertWizard` tests

- src/frontend/src/lib/components/address-book/AddressBookModal.svelte
- src/frontend/src/lib/components/address-book/EditContactNameStep.svelte
- src/frontend/src/tests/lib/components/address-book/EditContactNameStep.spec.ts
Svelte components should not export derived state. For example:
<script>
let title = $derived(...);
export { title };
</script>
This pattern is non-standard and unsupported. The goal of this PR is to proactively refactor components to avoid such usage and ensure long-term stability with Svelte.
Replaced export $derived(...) with $bindable<string>() in $props().
Used $effect to update title reactively based on editingContact.name.
In the parent, bound title as editContactNameTitle and displayed it in the modal's title slot.
Verified modal title updates dynamically when editing contact names.
Confirmed no regressions via manual testing.
> fix(frontend): Title for Edit contact Name step

- src/frontend/src/lib/components/ui/HeroButtonGroup.svelte
> refactor(frontend): upgrades HeroButtonGroup to svelte 5

- src/frontend/src/lib/utils/contact.utils.ts
- src/frontend/src/tests/lib/utils/contact.utils.spec.ts
To make `networkContacts` identifiers really unique, we are going to extend the keys with contact ids. It is going to be used in plenty of tests, therefore for convenience we need to create a separate util.
> fix(frontend): getNetworkContactKey util

- src/frontend/src/lib/components/rewards/RewardRequirement.svelte
- src/frontend/src/lib/enums/reward-criterion-type.ts
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/lib/types/reward.ts
- src/frontend/src/lib/utils/rewards.utils.ts
We want to support the new `Hangover` requirement for the campaigns. With this requirement we show for how many days in a row you didn't win a reward.
- supports `hangover` requirement
**New:**
> feat(frontend): implements new hangover campaign requirement

- src/frontend/src/lib/components/send/SendInputDestination.svelte
The component `SendInputDestination` is used both in the send flow and in the convert flow. That means that, since we use the send context to define the destination network, we need to add the convert context for the same tasks too.
> fix(frontend): Use convert context in component `SendInputDestination`

- src/frontend/src/env/reward-campaigns.json
- src/frontend/src/lib/components/rewards/RewardStateModal.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/tests/lib/components/rewards/RewardStateModal.spec.ts
Every sprinkles season does have a custom win modal configuration. The configuration for season 4 needs some adjustments.
- updates win modal for season 4
**New:**
> feat(frontend): updates win modal for season 4 wins

- src/frontend/src/lib/api/backend.api.ts
- src/frontend/src/lib/canisters/backend.canister.ts
- src/frontend/src/tests/lib/canisters/backend.canister.spec.ts
In this PR, the new `remove_custom_token` endpoint is made available for the client.
> feat(frontend): expose remove_custom_token

- src/frontend/src/icp/services/worker.icrc-wallet.services.ts
- src/frontend/src/lib/schedulers/scheduler.ts
- src/frontend/src/tests/icp/services/worker.icrc-wallet.services.spec.ts
After PR #7337, we don't really need to call the worker stop, since it is correctly done when re-starting it.
> refactor(frontend): Remove unnecessary worker stop in `initIcrcWalletWorker`

- src/frontend/src/eth/components/tokens/HideTokenModal.svelte
- src/frontend/src/icp/components/tokens/IcHideTokenModal.svelte
- src/frontend/src/lib/components/core/Modals.svelte
- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/components/tokens/TokenMenu.svelte
- src/frontend/src/lib/derived/modal.derived.ts
- src/frontend/src/lib/stores/modal.store.ts
When a user applys a `network filter` and then disabled a token, the `network filter` is also removed. Even after hiding a token, the filter should still be active.
- fixes hide token flow
**before:**
https://github.com/user-attachments/assets/3a0f1bb2-f5cf-4f96-afb7-567389031f96
**after:**
https://github.com/user-attachments/assets/f7d23cec-6782-49bd-ac82-225b6d5393e2
> feat(frontend): improves hide token flow

- src/frontend/src/eth/services/eth-address.services.ts
Since we are going to derive the ETH address in the frontend directly, we need to first refactor the services to handle the feature.
> refactor(frontend): Extract function to get the ETH address

- src/frontend/src/icp/utils/icrc-account.utils.ts
The implementation for getIcrcSubaccount() is currently not correct and has therefore to be fixed.
- Refactored getIcrcSubaccount logic to leverage a new getAccountIdentifier utility
> feat(frontend): using getAccountIdentifier() to create IcrcSubaccount

- src/frontend/src/icp/api/ckbtc-minter.api.ts
- src/frontend/src/tests/icp/api/ckbtc-minter.api.spec.ts
- src/frontend/src/tests/icp/api/icrc-ledger.api.spec.ts
- src/frontend/src/tests/mocks/btc.mock.ts
For coverage, some tests for ckbtc-minter API methods.
> test(frontend): Tests for ckbtc-minter API

- src/frontend/src/lib/api/idb-tokens.api.ts
- src/frontend/src/tests/lib/api/idb-tokens.api.spec.ts
Similar to other tokens, we should have a method for deleting a single SOL token from IDB.
> feat(frontend): deleteIdbSolToken method

- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/sol/components/tokens/SolTokenModal.svelte
- src/frontend/src/sol/derived/spl.derived.ts
- src/frontend/src/tests/sol/components/tokens/SolTokenModal.spec.ts
We can now enable deletion of non-default SPL tokens.
> feat(frontend): enable deletion of custom SPL tokens

- src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte
- src/frontend/src/lib/components/manage/AddTokenByNetworkDropdown.svelte
- src/frontend/src/tests/lib/components/manage/AddTokenByNetworkDropdown.spec.ts
We need to extract the dropdown code from `AddTokenByNetwork` so it can be re-used in the Edit ICRC token modal.
> feat(frontend): extract network dropdown from AddTokenByNetwork

- src/frontend/src/lib/components/core/Modals.svelte
- src/frontend/src/lib/components/rewards/AllRewardsList.svelte
- src/frontend/src/lib/components/rewards/RewardsEligibilityContext.svelte
- src/frontend/src/tests/lib/components/rewards/AllRewardsList.spec.ts
- src/frontend/src/tests/lib/components/rewards/RewardsEligibilityContext.spec.ts
It is currently not possible to open a Reward modal via Carousel. This started to be the case after some refactorings made for the airdrops feature a few months ago. To fix that, we need to do a few steps:
1. Move `RewardModal` to the global `Modals` component so it can be opened within any part of the app.
2. Extract the context initialisation into a separate component and re-use it in `Modals` and `AllRewardsList`.
> fix(frontend): issue with Reward modal not being openable via Carousel

- src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte
- src/frontend/src/lib/components/manage/AddTokenByNetworkDropdown.svelte
We need to improve the appearance of disabled inputs/selects in Token edit modal.
> style(frontend): disabled background to inputs in Token edit modal

- src/frontend/src/lib/components/tokens/TokenModalContent.svelte
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/tokens/TokenModalContent.spec.ts
We need to update TokenModalContect in order to handle the custom icrc token edit functionality. The changes include:
1. For better code structure, the index canister modal item was moved from `IcTokenModal` to `TokenModalContent`.
2. If a token is ICRC, and it has an indexCanisterId - we display the value, if no id available AND we pass `onEditClick` from parent (same as with the delete functionality) - we display an edit button as well as warning banner.
Updated.
> feat(frontend): TokenModalContent updates

- src/frontend/src/eth/components/fee/FeeContext.svelte
- src/frontend/src/eth/providers/infura.providers.ts
- src/frontend/src/lib/utils/bigint.utils.ts
- src/frontend/src/tests/lib/utils/bigint.utils.spec.ts
We are integrating more EVM networks. However, not all of them have the gas limit defined the same as Ethereum.
They don't necessarily all use 21k for `transfer` transactions. In fact, for Arbitrum, the normal transfers are failing, since we don't provide enough gas limit.
- Change util maxBigInt to have overloads, so that the type is guaranteed if one of the two inputs is non-nullish.
- Create method to estimate gas from provider in class `InfuraProvider`.
- Take the max between the current hard-coded values and the estimated ones.
Tested manually in FE test canister 2, and the transaction wen through:
https://github.com/user-attachments/assets/13f98a23-8ee4-4b71-8b29-bd024d36af37
> feat(frontend): Estimate gas for Ethereum/EVM instead of hard-coded values

- src/frontend/src/icp/services/icrc.services.ts
- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/tests/lib/components/tokens/TokenModal.spec.ts
To make a newly added indexCanisterId being used by the ICRC wallet worker, we need to reset the related token store before updating it with the new data from BE (which will include indexCanisterId).
> feat(frontend): relaunch ICRC worker on indexCanisterId being added

- src/frontend/src/eth/providers/infura-cketh.providers.ts
- src/frontend/src/lib/constants/analytics.contants.ts
We have sudden spikes in the number of `getLogs` calls to Infura, which is causing issues. However, we are not sure when and how they happen.
We create an event to track the number of calls to Infura's getLogs endpoint.
> feat(frontend): Track `getLogs` calls to Infura

- src/frontend/src/lib/stores/user-tokens.store.ts
- src/frontend/src/tests/lib/stores/user-tokens.store.spec.ts
It may happen that some ERC20 share the same address thorough different networks. However, OISY was consider them duplicates. We fix that.
- Change method setAll of user token store to identify ERC20 tokens both by address and chain ID.
Added tests and practical example:
> fix(frontend): Allow ERC20 tokens with same address and different networks

- src/frontend/src/icp/services/ic-add-custom-tokens.service.ts
- src/frontend/src/tests/icp/services/ic-add-custom-tokens.service.spec.ts
The user should not be able to add the ICp token, since it is always present.
Adjust assertion of already-available tokens, passing ICP tokens together with ICRC tokens.
Adjusted tests and tested manually in local replica:
> fix(frontend): User cannot add ICP token

- src/frontend/src/lib/components/manage/AddTokenByNetwork.svelte
- src/frontend/src/lib/components/send/SendForm.svelte
When we submit the forms in both the Sending flow or when adding a new token, we dispatch `icNext` in the form's `on:submit`, and the parent reacts by removing (destroying) the form component and showing another one before the browser finishes submitting the form, which triggers the warning:
"Form submission canceled because the form is not connected"
This happens because the browser thinks the form is being submitted (default behavior of method="POST"), but the DOM element is gone by the time the actual submission would happen.
To fix it, since we are not using the actual POST submission (we are dispatching an event instead and the validation happens with functions), we prevent the default browser behavior.
> fix(frontend): Avoid disconnected form when sending or adding tokens

- src/frontend/src/env/networks/networks.env.ts
- src/frontend/src/env/networks/networks.icp.env.ts
- src/frontend/src/icp/utils/icrc.utils.ts
- src/frontend/src/lib/components/settings/SettingsModalEnabledNetworks.svelte
- src/frontend/src/lib/derived/networks.derived.ts
- src/frontend/src/lib/derived/user-networks.derived.ts
- src/frontend/src/lib/schema/network.schema.ts
- src/frontend/src/lib/utils/address.utils.ts
- src/frontend/src/lib/utils/network.utils.ts
- src/frontend/src/lib/utils/user-networks.utils.ts
- src/frontend/src/tests/lib/derived/user-networks.derived.spec.ts
- src/frontend/src/tests/lib/utils/network.utils.spec.ts
- src/frontend/src/tests/mocks/user-networks.mock.ts
- src/frontend/src/tests/mocks/user-profile.mock.ts
There are a few ICRC tokens that we define as "testnet" tokens, for example ckSepoliaETH or ckSepoliaUSDC. They are linked to their respective twin tokens but on testnets.
Since there is no test network for IC network, we first decided to show them in the IC network AND only if testnets are enabled. However, that is a bit confusing since we show a wrong balance (the sum of "normal" tokens and "testnet" tokens).
Since these tokens are really just for testing and developing purposes, the new proposal is to separate them from IC network and put them in a pseudo-test-network, that is simply a replica of IC network.
- Create pseudo-network for ICRC "testnet" tokens: it is a copy of the existing IC network.
- Add it to the respective lists of networks.
- Expand util isNetworkIdICP (the …
> feat(frontend): Create pseudo-network for ICRC test tokens

- src/frontend/src/lib/components/manage/ManageTokensModal.svelte
On splitting and moving logic out for saving tokens a bug snuck in which breaks the saving in the manage tokens modal. This was due to the change in how the event data is propagated between the `ManageTokens` and `ManageTokensModal` components.
Fixed the param which was wrongly read
Manually tested, works like before
> fix(frontend): Save manage tokens modal

- src/frontend/src/icp/derived/ic-contacts.derived.ts
- src/frontend/src/icp/utils/icp-account.utils.ts
- src/frontend/src/lib/constants/analytics.contants.ts
- src/frontend/src/tests/icp/utils/icp-account.utils.spec.ts
Instead of just skipping principal addresses with subaccounts, we need to correctly handle such a case. To do that, we move the address parsing logic to a separate util `parseIcrcAccountToAccountIdentifierText`. Also, the temporary plausible event can now be removed.
> feat(frontend): handle subaccounts in icNetworkContacts

- src/frontend/src/lib/constants/app.constants.ts
- src/frontend/src/tests/lib/constants/app.constants.spec.ts
It is useful to associate each env to its own backend canister if any happens to exist.
> feat(build): Associate each env to its backend but only if exists

- src/frontend/src/btc/services/worker.btc-wallet.services.ts
- src/frontend/src/icp/services/worker.btc-statuses.services.ts
- src/frontend/src/icp/services/worker.ck-minter-info.services.ts
- src/frontend/src/icp/services/worker.ckbtc-update-balance.services.ts
- src/frontend/src/icp/services/worker.dip20-wallet.services.ts
- src/frontend/src/icp/services/worker.icp-wallet.services.ts
- src/frontend/src/icp/services/worker.icrc-wallet.services.ts
- src/frontend/src/icp/services/worker.pow-protection.services.ts
- src/frontend/src/lib/services/worker.auth.services.ts
- src/frontend/src/lib/services/worker.exchange.services.ts
- src/frontend/src/sol/services/worker.sol-wallet.services.ts
Just to be consistent and improve readability, we rename the inputs of the workers as `dataMsg` instead of `data` and deconstruct it as `const { msg, data } = dataMsg`
> refactor(frontend): Normalize input names for workers

- src/backend/backend.did
- src/backend/tests/it/custom_token.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/shared/src/impls.rs
- src/shared/src/types/custom_token.rs
- src/shared/src/types/tests.rs
We need to deprecate `UserToken` in favour of `CustomToken`: the latter are adapted to be multi-chain, and having a single type extremely simplifies the code.
As first step, we add a variant in the backend to the `CustomToken` type.
Note that the new types are a copy of the existing types used already in `UserToken` type.
BREAKING CHANGE: the interface of the backend changes a bit, adding the new variants.
- Create variant for ERC20 tokens, similar to SPL tokens, but with the addition of chain IDs.
Added tests.
> feat(backend)!: Add ERC20 variant to Custom tokens

- src/frontend/src/icp/services/ic-add-custom-tokens.service.ts
- src/frontend/src/icp/services/icrc.services.ts
- src/frontend/src/lib/components/tokens/TokenModal.svelte
- src/frontend/src/tests/lib/components/tokens/TokenModal.spec.ts
We need to improve the token editing feature by asserting indexCanisterId before saving it. Mostly, it is needed to check whether an index id matches with the provided ledger id. 
Also, we need to improve the onSuccess callback of `loadCustomTokens` - previously, it was only triggered after query calls, but since we cannot guarantee that they succeed, it's better to call `onSuccess` on both certified and uncertified calls.
> feat(frontend): use assertIndexCanisterId for Icrc tokens editing

- src/frontend/src/env/tokens/tokens.spl.env.ts
These 2 tokens don't have a price on coingecko yet.
For now disable them, and add them back once they are traded and have a price.
> chore(frontend): Disable 2 xStock Solana tokens that don't have a price (yet)

- vitest.config.ts
It does not really make sense to have the test coverage for `+page` modules in routes folder: there is no practical way of testing it correctly.
> test(frontend): Exclude `+page` modules from coverage

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/hero/Balance.svelte
- src/frontend/src/lib/components/hero/HeroContent.svelte
Final round of hero adjustments proposed by Dan.
- Font medium for balance like "Top up your wallet" text
- Reduced border radius and padding on mobile
- Reduced spacing between balance and Token name / total balance and "Top up your wallet" text
Token Mobile:
Token Tablet:
Token Desktop:
Homepage Mobile:
Homepage Tablet:
Homepage Desktop:
> style(frontend): Hero adjustments

- src/frontend/src/eth/services/erc20.services.ts
- src/frontend/src/eth/stores/erc20-custom-tokens.store.ts
- src/frontend/src/eth/types/address.ts
- src/frontend/src/eth/utils/erc20.utils.ts
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/custom-token.ts
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/sol/stores/spl-custom-tokens.store.ts
- src/frontend/src/tests/eth/services/erc20.services.spec.ts
We are going to deprecate `UserToken` in favour of `CustomToken`, to have a single type normalized among all networks.
However, we are going to have them in parallel for a certain amount of time, so that the migration is smoother.
In this PR, we create the mirror service to load ERC20 custom tokens from the backend: it is a mix of the existing services for ERC20 `UserToken` and SPL `CustomToken`.
- Create ERC20 custom token store: this is identical to SPL custom tokens store. Note that the store initialization function has still not the proper name.
- Create service to load ERC20 custom tokens (and its sub-functions): this has the same basic structure of what we do for SPL custom tokens, but obviously using the filters and the metadata services that already exists for ERC20 `UserToken`.
- …
> feat(frontend): Services to load ERC20 Custom Tokens

- src/frontend/src/icp/components/transactions/IcTransactionsCkBTCListeners.svelte
- src/frontend/src/icp/components/transactions/IcTransactionsCkEthereumListeners.svelte
- src/frontend/src/lib/components/ui/DelayedTooltip.svelte
When we render `children` as snippet, we don't necessarily require to create a nullish check.
> refactor(frontend): Remove unnecessary nullish checks for `children` snippet

- src/frontend/src/icp/services/worker.pow-protection.services.ts
- src/frontend/src/icp/types/pow-protector-listener.ts
- src/frontend/src/lib/components/pow/PowProtector.svelte
- src/frontend/src/tests/icp/services/worker.pow-protector.services.spec.ts
When we destroy a component that initiate a worker, we stop such worker. However, we do not destroy it.
To fix it, we create a new function called `destroy`.
In this PR, we tackle the PoW worker.
- Refactor a sub-function for `stop` in the workers.
- Create `destroy` method, using `worker.terminate`.
Existing and new tests suffice.
> feat(frontend): Completely terminate PoW workers on destroy

- src/frontend/src/icp/components/core/IcCkListener.svelte
- src/frontend/src/icp/services/worker.btc-statuses.services.ts
- src/frontend/src/icp/services/worker.ck-minter-info.services.ts
- src/frontend/src/icp/services/worker.ckbtc-update-balance.services.ts
- src/frontend/src/icp/types/ck-listener.ts
- src/frontend/src/tests/btc/components/convert/ConvertToCkBTC.spec.ts
When we destroy a component that initiate a worker, we stop such worker. However, we do not destroy it.
To fix it, we create a new function called `destroy`.
In this PR, we tackle the ck-related workers.
- Refactor a sub-function for `stop` in the workers.
- Create `destroy` method, using `worker.terminate`.
Existing and new tests suffice.
> feat(frontend): Completely terminate ck-related workers on destroy

- src/frontend/src/lib/types/qr-code.ts
A simple refactoring to simplify the code of schema `NumericParamsSchema` and `StringParamsSchema`.
> refactor(frontend): simplify code of QR code types

- src/frontend/src/lib/components/send/SendModal.svelte
We want to keep the destination address during the send flow, once entered. So selecting a token where the address would be invalid just results in the validation error showing.
It should only reset on modal close.
-  Removed reset in callback when navigating the send wizard
https://github.com/user-attachments/assets/a4045c10-ea7d-4e04-a49c-375c8f784880
> feat(frontend): Keep To address during send flow

- scripts/build.csp.mjs
The CSP is raising a warning for a new WalletConnect endpoint:
> fix(build): Add new WalletConnect endpoint to CSP

- src/frontend/src/sol/services/sol-address.services.ts
To be more clear we can rename one of the parameters of the service getSolAddress to receive the network as input, not necessarily the derivation path.
> refactor(frontend): Simplify services to load Solana addresses

- src/frontend/src/lib/api/idb-transactions.api.ts
- src/frontend/src/lib/services/auth.services.ts
- src/frontend/src/tests/lib/api/idb-transactions.api.spec.ts
- src/frontend/src/tests/lib/services/auth.services.spec.ts
When the user logs out, we need to clean the IDB stores that cached the transactions.
> feat(frontend): Services to clear IDB transactions stores

- src/frontend/src/lib/components/ui/SplitPane.svelte
To improve performance, we should avoid rendering the mobile navigation in DOM, if not needed. Until now we were rendering it, but hiding it too. However, with Responsive component, we can use the Svelte `{#if}` statement and avoid rendering it, until necessary.
Note that we combine both. This ensures:
- It's only in the DOM when it should be
- And it behaves responsively too
No changes in behaviour:
https://github.com/user-attachments/assets/4f4ef257-cd71-4af7-b1b8-2e1614c548c9
> style(frontend): Use `Responsive` component for `SplitPane`

- src/frontend/src/routes/(app)/+layout.svelte
- src/frontend/src/routes/(app)/+page.svelte
To improve performance, we should avoid rendering the mobile navigation in DOM, if not needed. Until now we were rendering it, but hiding it too. However, with Responsive component, we can use the Svelte `{#if}` statement and avoid rendering it, until necessary.
Note that we combine both. This ensures:
- It's only in the DOM when it should be
- And it behaves responsively too
> style(frontend): Use `Responsive` component for dApp carousel

- .github/workflows/e2e-tests.yml
We temporarily disable the E2E tests from automatically run: they are currently failing and costing too much in workflow force.
> test(e2e): Disable CIs for E2E tests

- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/sol/services/wallet-connect.services.ts
As suggested by @ilbertt , we unify the strings that represent an executed transaction on WalletConnect.
> refactor(frontend): Single string for WalletConnect executed transaction

- src/frontend/src/eth/stores/eth-transactions.store.ts
- src/frontend/src/tests/eth/derived/eth-transactions.derived.spec.ts
- src/frontend/src/tests/eth/stores/eth-transactions.store.spec.ts
- src/frontend/src/tests/lib/api/idb-transactions.api.spec.ts
It makes more sense to rename method `reset()` to `resetAll()` in the Ethereum transactions store.
> refactor(frontend): Rename method that resets in Ethereum transactions store

- src/frontend/src/lib/i18n/pt.json
Tags in the Dapp Explorer are too long in Portuguese.
- Shorten them. Also don't translate idioms.
Sources:
-  https://pt.wikipedia.org/wiki/M%C3%ADdias_sociais
- <img width="434" height="262" alt="image" src="https://github.com/user-attachments/assets/9cd6c2b6-9529-4a99-abeb-a27e268674ab" />
> chore(frontend): Fix Portuguese dapp category names

- src/frontend/src/env/plausible.env.ts
We want to track the plausible events for each test canister.
> feat(build): Diverse domain in Plausible for test canisters

- src/frontend/src/lib/services/worker.exchange.services.ts
- src/frontend/src/tests/lib/services/worker.exchange.service.spec.ts
This PR is just a split of @DecentAgeCoder 's PR https://github.com/dfinity/oisy-wallet/pull/7797 .
> # Motivation
> 
> Workers are not being properly terminated, causing memory leaks. In this PR we fix the issue of the Exchange worker that isn't properly terminated on destroy.
> 
> `ExchangeWorker.svelte` gets "terminated" when `ExchangeWorker.svelte` gets unmounted or the user navigates to to a page that doesn't include the component `ExchangeWorker.svelte`
> Wallet worker lifecycle is bound to tokens array
> The missing worker termination for exchange or wallet workers could be the primary source of the memory leak
> 
> # Changes
> 
> - Changed worker type: From `const exchangeWorker: Worker` to `let exchangeWorker: Worker | null`.
> - Added optional chaining: Used `?.` for all …
> fix(frontend): Completely terminate Exchange workers on destroy

- src/frontend/src/btc/components/receive/BtcReceive.svelte
- src/frontend/src/btc/services/btc-address.services.ts
- src/frontend/src/eth/services/eth-address.services.ts
- src/frontend/src/lib/services/address.services.ts
- src/frontend/src/lib/stores/address.store.ts
- src/frontend/src/lib/utils/address.utils.ts
- src/frontend/src/sol/components/receive/SolReceive.svelte
- src/frontend/src/sol/services/sol-address.services.ts
In the address store initializer we do not really need to import `StorageStoreData` type, since we just need the `Option` modifier, and the `Storage` prefix does not really make sense in this context.
> refactor(frontend): simplify types in `initAddressStore`

- src/frontend/src/lib/api/idb-balances.api.ts
The return type of `getIdbBalances` is not a possible array of `Balance` but a single possible `Balance`.
> fix(frontend): Correct type in service `getIdbBalances`

- src/frontend/src/lib/api/idb-balances.api.ts
- src/frontend/src/lib/services/listener.services.ts
- src/frontend/src/tests/lib/services/listener.services.spec.ts
Similar to what we did for transactions, we sync the IDB cache with our balances store when there is the first initialization sync.
- Created service to get a balance from IDB cache by token.
- Use the new service in `syncWalletFromIdbCache`.
New tests.
> feat(frontend): Sync balances from IDB cache during initial wallet sync

- src/frontend/src/lib/components/balances/BalancesIdbSetter.svelte
- src/frontend/src/lib/components/loaders/Loaders.svelte
Similar to what we did for the transactions stores, we will start using the IDB services that store the balances in the cache.
The idea is that each change in the balances store would trigger caching it. That is because the balances store is handled in various places in the code, and it becomes quite un-maintainsble to add the code in each use. 
- Create component `BalancesIdbSetter` to cache the balances (very similar to the transacitons one): we separate the reactivity and we limit it only to the balances store. This will avoid useless updates.
- Add the `BalancesIdbSetter` to `Loaders`.
Manual test worked too:
> feat(frontend): component to save the IDB store for balances

- src/frontend/src/lib/components/core/WalletWorkers.svelte
- src/frontend/src/tests/lib/components/core/WalletWorkers.spec.ts
To avoid too many calls on loading, we debounce the trigger of the wallet workers.
> feat(frontend): Debounce wallet workers trigger

- src/frontend/src/lib/schema/currency.schema.ts
- src/frontend/src/lib/stores/currency-exchange.store.ts
- src/frontend/src/lib/stores/currency.store.ts
- src/frontend/src/lib/types/currency.ts
- src/frontend/src/tests/lib/stores/currency.store.spec.ts
We will need the interfaces and types of the currency stores to be used by the workers types too. Since the latter are set in zod, it seems a good time to migrate the others to zod too.
> refactor(frontend): Create zod schemas for types of currency stores

- src/frontend/src/env/schema/env-icrc-token.schema.ts
- src/frontend/src/env/schema/env-sns-token.schema.ts
- src/frontend/src/env/schema/env-token-ckerc20.schema.ts
- src/frontend/src/icp/schema/ic-token.schema.ts
- src/frontend/src/lib/schema/nft.schema.ts
- src/frontend/src/lib/schema/post-message.schema.ts
- src/frontend/src/lib/schema/token.schema.ts
As per [zod documentation](https://zod.dev/v4/changelog?id=deprecates-merge), the `.merge` method is deprecated.
The suggestion is to replace it:
```
// .merge (deprecated)
const ExtendedSchema = BaseSchema.merge(AdditionalSchema);
// .extend (recommended)
const ExtendedSchema = BaseSchema.extend(AdditionalSchema.shape);
// or use destructuring (best tsc performance)
const ExtendedSchema = z.object({
...BaseSchema.shape,
...AdditionalSchema.shape,
});
```
We choose the deconstruction.
- Change all instances of `.merge` to a deconstruction method.
All current tests should work as usual.
> feat(frontend): Remove deprecated zod method `.merge`

- src/frontend/src/lib/components/convert/ConvertAmountExchange.svelte
- src/frontend/src/lib/components/exchange/ExchangeAmountDisplay.svelte
- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/networks/NetworkButton.svelte
- src/frontend/src/lib/components/rewards/RewardEarnings.svelte
- src/frontend/src/lib/components/rewards/RewardEarningsCard.svelte
- src/frontend/src/lib/components/swap/SwapFees.svelte
- src/frontend/src/lib/components/swap/SwapProviderListModal.svelte
- src/frontend/src/lib/components/tokens/TokenExchangeBalance.svelte
- src/frontend/src/lib/components/tokens/TokenInputAmountExchange.svelte
- src/frontend/src/lib/utils/format.utils.ts
- src/frontend/src/tests/lib/components/exchange/ExchangeAmountDisplay.spec.ts
- src/frontend/src/tests/lib/utils/format.utils.spec.ts
We will let the users choose their own currency. So, we need to start formatting it correctly (some of them have 3 decimals, other no decimals at all).
The `Intl` library knows these rules when `currency` is selected in method `NumberFormat`, so we can rely on it (see [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#currency_formatting)).
- Add currency param in util `formatCurrency`.
- Use it to define the currency in `Intl.NumberFormat()`.
- Adapt the consumers to use the store `currentCurrency`.
- Remove constraints of minimum and maximum digits: the library knows exactly how many digits each currency should have.
Added test cases.
> feat(frontend): Add custom currency to util `formatCurrency`

- src/frontend/src/lib/services/loader.services.ts
When we initialize the UI, we are requesting an allowance to the Chain Fusion signer. This is useful for most of the calls that we do to the Chain Fusion signer, for example deriving the addresses, or sign a transaction.
However, if we are deriving the addresses in the frontend, we do not need tov await for the call to finish. We can accept the fact that the user will take some time until the next transaction signing, enough for the call to complete.
In any case, even if the call is not completed, the error received will just tell the user to re-try. And if there is an error, the call service will sign-out.
Initialization in beta canister is much faster:
https://github.com/user-attachments/assets/8d0a500d-e47d-4813-91d3-91c8711f59f4
> feat(frontend): Do not wait for Signer allowance if derivation is in frontend

- src/frontend/src/lib/stores/modal-tokens-list.store.ts
- src/frontend/src/tests/lib/stores/modal-tokens-list.store.spec.ts
To enable selecting different networks for cross-chain swaps, we need to update modal-tokens list store to manage the list of tokens filtered by networks ids
Added new filterNetworksIds to manage tokens selection for the modal.
Covered the new logic with tests.
> feat(frontend): added new filter by networks id to modal-tokens-list store

- src/frontend/src/lib/stores/modal-networks-list.store.ts
- src/frontend/src/tests/lib/stores/modal-networks-list.store.spec.ts
To enable selecting different networks for cross-chain swaps, we need a store to manage the list of networks shown in the modal and update filters accordingly.
Added new modalNetworksListStore to manage network selection for the modal.
Covered the new store with unit tests.
> feat(frontend): added new modal network list store

- src/frontend/src/lib/i18n/zh-CN.json
Currency feature needs localized texts, but labels for chinese are missing.
- Add Chinese
> chore(frontend): Add missing texts for currency feature

- src/frontend/src/lib/components/hero/Balance.svelte
- src/frontend/src/lib/derived/currency.derived.ts
- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/tests/lib/derived/currency.derived.spec.ts
It is useful to have a direct derived store for the current currency symbol:
> feat(frontend): Derived store with current currency symbol

- src/frontend/src/eth/providers/infura-erc721.providers.ts
The metadata of an `nft` can contain the url to the image as `image` or `image_url`. We want to be able to support both options.
- improves loading of metadata image
> feat(frontend): improves loading of nft metadata image

- src/frontend/src/lib/components/currency/CurrencyDropdown.svelte
The list of currencies in the dropdown should be sorted by their name in the current language.
- Create mapped and sorted currencies list in CurrencyDropdown component.
- Adapt the rest of the component.
Current tests shall work. And a practical one:
> feat(frontend): Sort currencies by name in dropdown

- src/frontend/src/lib/components/contact/EditAvatar.svelte
Unnecessary initializers in EditAvatar for params `onReplaceImage` and `onRemoveImage`.
> chore(frontend): Remove unnecessary default values in `EditAvatar`

- src/frontend/src/eth/components/tokens/EthAddTokenReview.svelte
- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/sol/components/tokens/SolAddTokenReview.svelte
There is a duplicate message for errors in importing tokens.
> chore(frontend): Remove duplicate error message for importing tokens

- vitest.setup.ts
No need to import the global `vi` in vitest setup file.
> chore(test): Remove vitest global imports from setup file

- src/frontend/src/lib/components/swap/SwapReview.svelte
- src/frontend/src/lib/constants/swap.constants.ts
This Link should go to a specific anchor, about withdraw from ICPSwap.
- adjust the link and the constant name
> chore(frontend): Adjust link to ICPSwap help page

- src/backend/backend.did
- src/backend/tests/it/custom_token.rs
- src/declarations/backend/backend.did
- src/declarations/backend/backend.did.d.ts
- src/declarations/backend/backend.factory.certified.did.js
- src/declarations/backend/backend.factory.did.js
- src/frontend/src/eth/services/erc721.services.ts
- src/frontend/src/lib/types/custom-token.ts
- src/frontend/src/lib/utils/custom-token.utils.ts
- src/frontend/src/tests/lib/utils/custom-token.utils.spec.ts
- src/shared/src/impls.rs
- src/shared/src/types/custom_token.rs
- src/shared/src/types/tests.rs
We want to have a single interface for ERC tokens in the backend: the existing ERC20 and ERC721 interfaces are the exact same after PR https://github.com/dfinity/oisy-wallet/pull/7970.
BREAKING CHANGE: the interface's name of the `CustomToken` variant ERC20 and ERC721 changed.
- Merge ERC20 and ERC721 interfaces into a single one without symbol and decimals.
- Adapt the frontend.
Current tests where adapted.
> feat(backend)!: Single interface for ERC tokens in CustomToken

- src/frontend/src/eth/providers/infura-erc721.providers.ts
- src/frontend/src/lib/utils/nfts.utils.ts
- src/frontend/src/tests/lib/utils/nfts.utils.spec.ts
For standard ERC-1155, we will require the same parser of URLs as the ones used for ERC-721. Basically, we need to adapt `ipfs:` protocols and parse the string to an URL.
To do so, we extract the existing code in a separate util.
- Create util parseMetadataResourceUrl that is a copy of the existing code in the Infura ERC721 providers.
- Adapt the rest of the code.
Created tests.
> feat(frontend): Util to parse NFT metadata URLs

- src/frontend/src/lib/types/custom-token.ts
- src/frontend/src/lib/utils/custom-token.utils.ts
- src/frontend/src/tests/lib/utils/custom-token.utils.spec.ts
Similar to ERC20 and ERC721, we integrate ERC1155 in the util that maps Frontend custom tokens to Backend ones.
> feat(frontend): Map ERC1155 in custom tokens util

- src/frontend/src/icp/stores/ic-transactions.store.ts
- src/frontend/src/icp/utils/ic-transactions.utils.ts
- src/frontend/src/lib/api/idb-transactions.api.ts
- src/frontend/src/lib/types/idb-transactions.ts
- src/frontend/src/lib/utils/transactions.utils.ts
- src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
Creating a single type `IcCertifiedTransactionsData` to avoid duplication of code.
> refactor(frontend): Extract type for certified IC transactions data

- src/frontend/src/lib/api/idb-transactions.api.ts
- src/frontend/src/lib/types/idb-transactions.ts
- src/frontend/src/lib/utils/transactions.utils.ts
- src/frontend/src/sol/stores/sol-transactions.store.ts
- src/frontend/src/tests/lib/utils/transactions.utils.spec.ts
Creating a single type `SolCertifiedTransactionsData` to avoid duplication of code.
> refactor(frontend): Extract type for certified SOL transactions data

- src/frontend/src/lib/components/tokens/HideTokenModal.svelte
- src/frontend/src/lib/components/tokens/TokenMenu.svelte
- src/frontend/src/lib/derived/page-token.derived.ts
- src/frontend/src/lib/derived/token.derived.ts
- src/frontend/src/tests/lib/derived/page-token.derived.spec.ts
- src/frontend/src/tests/lib/derived/token.derived.spec.ts
- src/frontend/src/tests/mocks/page.store.mock.ts
- src/frontend/src/tests/utils/derived.test-utils.ts
In an effort to deprecate the token store, we replace the `tokenToggleable` derived store with the equivalent that is derived from the `pageToken`.
It is ok, since the consumers all refers to places where the page token is defined.
- Create copy of `tokenToggleable` store as `pageTokenToggleable`.
- Adapt usages.
- Unrelated: we remove deprecated `tokenStandard` derived store.
Added tests.
> feat(frontend): Replace Toggleable prop of token store with page-token store

- src/frontend/src/lib/api/idb-balances.api.ts
- src/frontend/src/lib/api/idb-transactions.api.ts
- src/frontend/src/lib/utils/idb.utils.ts
- src/frontend/src/tests/lib/api/idb-balances.api.spec.ts
- src/frontend/src/tests/lib/api/idb-transactions.api.spec.ts
- src/frontend/src/tests/lib/services/auth.services.spec.ts
- src/frontend/src/tests/lib/utils/idb.utils.spec.ts
The IDB cache for transactions and balances uses multi-keys for the database. That means that we need to delete all the keys that starts with user's principal.
- Create IDB util to delete data from cache if multi-keys and the first one is a principal.
- Adapt existing methods.
Added tests and manual test worked.
> fix(frontend): Correctly delete the multi-keys from IDB cache

- src/frontend/src/lib/components/ui/PageTitle.svelte
Migrating `PageTitle` component to Svelte 5.
> feat(frontend): Migrate component `PageTitle` to Svelte 5

- src/frontend/src/lib/components/networks/NetworkWithLogo.svelte
- src/frontend/src/lib/components/ui/TextWithLogo.svelte
Migrating `NetworkWithLogo` component (and its direct children) to Svelte 5.
> feat(frontend): Migrate component `NetworkWithLogo` to Svelte 5

- src/frontend/src/sol/api/solana.api.ts
- src/frontend/src/sol/utils/sol-instructions.utils.ts
For better manageability, we extract a sub-service for the Solana RPC: `getAccountInfo`.
> refactor(frontend): Extract sub-service of `getAccountInfo` for Solana RPC

- src/frontend/src/eth/components/send/EthSendTokenWizard.svelte
It is useful to track which network is being used in the ETH send flow.
> feat(frontend): Track network in ETH send flow

- src/frontend/src/lib/styles/global/gix.scss
The toast warning should have the correct color of the warning and not of the error.
> style(frontend): Use correct colors for toast warning

- src/frontend/src/eth/components/transactions/EthTransactionStatus.svelte
Component `EthTransactionStatus` listens real-time to the block numbers, to verify the current status of the open transaction inside a Transaction modal. However, it is missing the logic that if the status is already finalised, it should not keep listening.
> fix(frontend): Do not listen to ETH transaction status if already finalised

- src/frontend/src/lib/components/manage/ManageTokensModal.svelte
In preparation of integrating ERC1155 in component `ManageTokensModal`, we remove the duplication of code in sub-service `saveEthToken`.
> refactor(frontend): Avoid duplication of code in `ManageTokensModal`

- src/frontend/src/tests/eth/services/erc1155.services.spec.ts
- src/frontend/src/tests/eth/services/erc20.services.spec.ts
- src/frontend/src/tests/eth/services/erc721.services.spec.ts
- src/frontend/src/tests/icp-eth/services/custom-token.services.spec.ts
- src/frontend/src/tests/icp/services/icrc.services.spec.ts
- src/frontend/src/tests/lib/api/idb-addresses.api.spec.ts
- src/frontend/src/tests/lib/api/idb-balances.api.spec.ts
- src/frontend/src/tests/lib/api/idb-tokens.api.spec.ts
- src/frontend/src/tests/lib/api/idb-transactions.api.spec.ts
- src/frontend/src/tests/lib/derived/currency.derived.spec.ts
- src/frontend/src/tests/lib/derived/i18n.derived.spec.ts
- src/frontend/src/tests/lib/services/auth.services.spec.ts
- src/frontend/src/tests/lib/utils/idb.utils.spec.ts
- vitest.setup.ts
The package `idb-keyval` is mocked a lot of times, and in general there is no practical use-case yet where we need it working completely in the unittests, because it uses the browser. So, to avoid repetition of code, we move it to the file that has the Vitest setup.
> test(frontend): Move `idb-keyval` mocks to vitest setup file

- src/frontend/src/eth/providers/alchemy.providers.ts
Alchemy websockets are buggy. So, we force one more layer of "destroying" for the websocket providers.
> fix(frontend): Turn listener off for Alchemy websocket providers

- src/frontend/src/eth/providers/infura-erc721.providers.ts
- src/frontend/src/eth/services/erc721.services.ts
- src/frontend/src/lib/components/manage/ManageTokensModal.svelte
- src/frontend/src/lib/constants/analytics.contants.ts
To have a better control of the ERC tokens imported by the user, we replicate the interface check done with ERC115, but we do it for ERC721 this time.
Furthermore, we implement a tracking event for unrecognized interfaces.
- Make class `InfuraErc721Provider` extend `InfuraErc165Provider` (similar to `InfuraErc1155Provider`).
- Create method `isInterfaceErc721` for class `InfuraErc721Provider`.
- Create service to check if an ERC is indeed a 721 interface and use it when saving new custom tokens.
- Track event for unrecognized interfaces.
No changes in local replica.
> feat(frontend): Use interface to distinguish ERC721 in ManageTokensModal

- src/frontend/src/lib/components/ui/InProgress.svelte
- src/frontend/src/lib/components/ui/InProgressWizard.svelte
- src/frontend/src/lib/styles/global/gix.scss
To support displaying a failed step in the ProgressSteps component (e.g., when a step fails in the swap flow), we need to adjust the logic to check whether a specific step is marked as failed.
- Added a new failedSteps prop that can be updated from the parent component
- Added a condition to identify and highlight failed steps
- Adjusted styles for failed step
> feat(frontend): added new step failed to progress Steps

- src/frontend/src/env/tokens/tokens-spl/tokens.aznx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.cmcsax.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.cscox.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.dfdvx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.hdx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.honx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.llyx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.pepx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.pgx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.unhx.env.ts
- src/frontend/src/env/tokens/tokens-spl/tokens.vtix.env.ts
We add the relevant authorities for all the new x-stocks Solana 2022 tokens.
> chore(frontend): Add authorities to new Solana x-stock tokens

- src/frontend/src/env/tokens/tokens.icrc.json
Their index canister is dead for a while now
- Remove POPEYE from our curated tokenlist
> chore(frontend): Remove POPEYE icrc token

- src/frontend/src/lib/components/swap/SwapWizard.svelte
- src/frontend/src/tests/lib/components/swap/SwapWizard.spec.ts
Added support for showing the Withdrawing step in the SwapWizard only for the ICP Swap provider.
- Introduced swapWithWithdrawing prop in SwapWizardUpdated test props
- Updated related test props accordingly
> feat(frontend): added swapWithWithdrawing prop to SwapWizard

- .github/workflows/backend-tests.yml
We want to use the status check `backend-tests-pass` to allow (or not) the merging of a PR. However, we have the issue that if the PR does not modify the files specified in the event trigger (in this case all backend-related files), the workflow does not run, and the status check is not elaborated. 
To bypass this issue, we specify the files to watch for each job of the workflow, so that the workflow always runs, but not necessarily "work" if the files are not changed.
- Use custom action `check-backend-changes` in each job of the workflow that runs the backend tests.
The CI workflow ran in this same PR correctly.
> feat(devops): Always run backend tests

- src/frontend/src/lib/services/swap-errors.services.ts
- src/frontend/src/tests/lib/services/swap-errors.services.spec.ts
We need to track the status of swapSucceeded to determine whether to withdraw the destination or source token after a failed swap.
Added swapSucceeded property to SwapError for improved error context
Added unit tests
> feat(frontend): added new swapSucceded property to ICP Swap Error

- .github/workflows/backend-tests.yml
- src/frontend/src/lib/components/swap/SwapWizard.svelte
- src/frontend/src/lib/services/swap-errors.services.ts
- src/frontend/src/lib/services/swap.services.ts
- src/frontend/src/lib/stores/swap.store.ts
- src/frontend/src/lib/types/swap.ts
- src/frontend/src/tests/lib/services/swap.services.spec.ts
For icpSwap, we need to track whether the swap was successful in order to determine whether to retrieve the source token or the destination token. This status is now stored.
Added logic to store swapSucceded status
> feat(frontend): adjusted logic of icpSwap to set swapSucced prop

- src/frontend/src/eth/constants/erc165.constants.ts
When importing an erc1155 contract there is an warning displayed in the browsers console because there is an unexpected `;` in the abi defintion. To prevent this, we remove it from the definition.
- removes unused `;` from abi
> refactor(frontend): removes unused semicolon from abi definition

- src/frontend/src/lib/derived/contacts.derived.ts
- src/frontend/src/lib/types/contact.ts
- src/frontend/src/tests/lib/derived/contacts.derived.spec.ts
Since the original contact address schema does not include any unique identifiers, we need to create an extended store where we manually add `id` to each address. This is needed for the AI assistant feature - we will be hiding the address values before feeding the data to LLM, and then parsing the response back by using these generated ids.
> feat(frontend): extended address contacts derived

- src/frontend/src/lib/components/ai-assistant/AiAssistantConsole.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantMessages.svelte
- src/frontend/src/lib/derived/ai-assistant.derived.ts
- src/frontend/src/lib/services/ai-assistant.services.ts
- src/frontend/src/lib/stores/ai-assistant.store.ts
- src/frontend/src/lib/types/ai-assistant.ts
- src/frontend/src/tests/lib/components/ai-assistant/AiAssistantConsole.spec.ts
- src/frontend/src/tests/lib/components/ai-assistant/AiAssistantMessages.spec.ts
- src/frontend/src/tests/lib/derived/ai-assistant.derived.spec.ts
- src/frontend/src/tests/lib/services/ai-assistant.services.spec.ts
- src/frontend/src/tests/lib/stores/ai-assistant.store.spec.ts
As the next step of preparing our code for handling LLM tools, we need to extend the types and UI components with the `tool` field. The services that request and parse tool responses will be added in the next PRs.
> feat(frontend): extend AI types and components with tools response

- src/frontend/src/lib/components/swap/SwapAmountsContext.svelte
- src/frontend/src/lib/components/swap/SwapWizard.svelte
- src/frontend/src/lib/services/swap.services.ts
- src/frontend/src/lib/types/swap.ts
- src/frontend/src/tests/lib/services/swap.services.spec.ts
As we encountered issues with ICRC-1 tokens when swapping via ICPSwap, this PR disables swap logic for ICRC-1 tokens in ICPSwap.
> fix(frontend): disabled icrc1 tokens for icpSwap

- src/frontend/src/lib/components/nfts/NftCard.svelte
The images of the nfts were displayed in different sizes, but we want to display all of the the same size.
- displays all images the same size
**before:**
**after:**
> feat(frontend): nft images should be displayed correctly

- src/frontend/src/lib/components/nfts/NftCard.svelte
- src/frontend/src/tests/lib/components/nfts/NftCard.spec.ts
- src/frontend/src/tests/mocks/nfts.mock.ts
Nfts of erc1155 contracts do have a balance which means we also want to display this balance for the nfts.
- displays balances
**before:**
**after:**
> feat(frontend): displays nft balances

- src/frontend/src/lib/components/nfts/NftCard.svelte
The names that are too long should be truncated.
**before:**
**after:**
> refactor(frontend): truncate too long names

- src/frontend/src/lib/services/ai-assistant.services.ts
- src/frontend/src/tests/lib/services/ai-assistant.services.spec.ts
We need to implement a method that is going to request a semantical contacts filter from LLM. It filters out all sensitive contacts info (addresses) before sending it to AI. After LLM replies, we parse the response to ContactUi[].
> feat(frontend): implement askLlmToFilterContacts method

- scripts/build.csp.mjs
> TL;DR: we got lucky
I implemented a 404 page in the Juno Console. One thing led to another, and I ended up having to hash the filenames of `main.js` loaders (because 404.html and index.html both live in the same folder, at the root). That’s when I noticed an issue on mainnet: the loaders were no longer being loaded, and the frontend was crashing!
The root cause was that the loader was always being fetched from the root directory. This wouldn’t normally be an issue—*if* all loaders had the same content and were named `main.js` but, since I started hashing the filenames… yolo.
Long story short, I fixed the issue by using a relative path for the loaders (in this [PR](https://github.com/junobuild/juno/pull/1826)). While doing that, I realized the same issue exists in OISY. Fortunately, …
> chore(frontend): fix main.js loader paths

- src/frontend/src/lib/utils/ai-assistant.utils.ts
- src/frontend/src/tests/lib/services/ai-assistant.services.spec.ts
- src/frontend/src/tests/lib/utils/ai-assistant.utils.spec.ts
To be aligned with the ContactUi interface, we need to remove `id` from addresses when parsing LLM response.
> feat(frontend): remove id from addresses while parsing LLM result

- src/frontend/src/lib/utils/exchange.utils.ts
- src/frontend/src/tests/lib/utils/exchange.utils.spec.ts
In case kong token metrics does not have a price yet (e.g. there is no a pool yet created for the token), we want to ignore it completely instead of showing the token balance as 0.
> feat(frontend): ignore kong token metrics if price is 0

- src/frontend/src/lib/api/icp-swap-pool.api.ts
- src/frontend/src/lib/canisters/icp-swap-pool.canister.ts
- src/frontend/src/tests/lib/canisters/icp-swap-pool.spec.ts
We need to fetch ICP Swap pool metadata to compare token0 and token1 addresses with balance0 and balance1, ensuring we withdraw the correct token amounts after a failed swap.
- Added a new getPoolMetadata API that calls the ICP Swap canister’s metadata method.
Covered new logic with tests.
> feat(frontend): added new icp-swap getPoolMetadata call

- src/frontend/src/lib/types/transaction.ts
The `Transaction` object should also support nft transactions which means it needs an optional `tokenId` field.
- adds `tokenId` to `Transaction`
> feat(frontend): adds tokenId to transaction

- src/frontend/src/lib/api/idb-balances.api.ts
- src/frontend/src/tests/lib/api/idb-balances.api.spec.ts
Similar as with the deletion per principal, we now need all the methods for a complete "clear" of IDB balances.
> feat(frontend): clear idb-balances methods

- src/frontend/src/lib/api/idb-addresses.api.ts
- src/frontend/src/tests/lib/api/idb-addresses.api.spec.ts
Similar as with the deletion per principal, we now need all the methods for a complete "clear" of IDB addresses.
> feat(frontend): clear idb-addresses methods

- src/frontend/src/lib/components/auth/LockPage.svelte
The only thing left is to start using the clearAllPrincipalsStorages option on logout in LockPage.
> feat(frontend): use clearAllPrincipalsStorages on logout in LockPage

- src/frontend/src/env/tokens/tokens.icrc.json
- Windoge98 has no index
- WindogeXP ledger just was not responding due to a low cycles balance, causing an error for all users. (I topped it up a little).
- remove them
> chore(frontend): Remove windoge tokens

- src/frontend/src/lib/components/ui/Logo.svelte
The `Logo` should not always be displayed rounded. It should be configurable whether the `Logo` is rounded or not. 
- updates `Logo`
> feat(frontend): extends Logo implementation

- package-lock.json
- package.json
`zod-schemas` has been patched to accept any `@dfinity/principal` version which is technically correct and makes the maintenance easier.
- Bump v1.1.0
> build(frontend): bump zod-schemas for any principal lib

- package-lock.json
- package.json
The latest version of `verifiable-credentials` accepts any principal library which is useful for maintenance reason.
- Bump latest `@dfinity/verifiable-credentials`
> build(frontend): bump verifiable-credentials

- src/frontend/src/lib/components/ui/ButtonDone.svelte
We need an additional variant for the ButtonDone component.
Added optional variant prop.
Variant primary or prop not passed:
Variant secondary-light
> refactor(frontend): Done button variant

- src/frontend/src/lib/components/ui/Badge.svelte
- src/frontend/src/lib/types/style.ts
We need a new type of badge for the NFT traits.
- Added variant to BadgeVariant
- Added styles for new variant
> refactor(frontend): New NFT trait badge type

- src/frontend/src/lib/components/tokens/TokensMenu.svelte
For the upcoming NFT pages we are going to use bottom sheets on mobile for the top right action menus. For consistency we also update the existing one on the token list page.
- Added bottom sheet variant on small screens to render the conten instead of the popover
- Changed primitive list to our List component for styling consistency
Desktop:
Small screens:
> refactor(frontend): Token list settings uses bottom sheet

- src/frontend/src/lib/components/common/ListItemButton.svelte
- src/frontend/src/tests/lib/components/common/ListItemButton.spec.ts
- src/frontend/src/tests/lib/components/common/ListItemButtonTest.svelte
We make a shared component for ListItems that render a button, as it will be used in multiple Popover menus on the assets page.
- Added component
Added tests
> feat(frontend): ListItemButton

- src/frontend/src/sol/services/spl.services.ts
It does not make sense the only SPL tokens are being loaded with query. We should use the default strategy that is both query and update, like the other custom tokens.
> feat(frontend): Load SPL custom tokens with query and update

- src/frontend/src/lib/services/manage-tokens.services.ts
- src/frontend/src/tests/lib/services/manage-tokens.services.spec.ts
To have an easier analysis of the errors, we use the mapper for the IC errors when saving custom tokens.
> fix(frontend): Use mapper for IC errors during saving of custom tokens

- src/backend/backend.did
- src/backend/src/lib.rs
- src/declarations/backend/backend.did
With the new version of rust (PR https://github.com/dfinity/oisy-wallet/pull/8180), we have a lint warning in the documentation:
```
error: item in documentation is missing backticks
--> src/backend/src/lib.rs:962:59
|
962 | /// * `ContactNotFound` - If no contact for the proivided contact_id could be found
|                                                           ^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
= note: `-D clippy::doc-markdown` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::doc_markdown)]`
help: try
|
962 - /// * `ContactNotFound` - If no contact for the proivided contact_id could be found
962 + /// * `ContactNotFound` - If no contact for the proivided `contact_id` …
```
> chore(backend): Fix lint warning in documentation

- src/frontend/src/icp/services/worker.icp-wallet.services.ts
- src/frontend/src/icp/utils/wallet.utils.ts
- src/frontend/src/tests/icp/utils/wallet.utils.spec.ts
We are going to onboard more tokens with standard `icp` (as defined in the the codebase). That means that we need to generalize all the services and workers for this type of standard, since right now they are "hard-coded" to be used only by ICP token.
In this PR, we generalize the input data for the ICP wallet worker.
- Worker initializer now accepts a token as input (similar to the other IC workers).
- Remove hard-coded ICP token data.
- Adapt generic IC wallet worker initializer to accept `token` as input.
Adapted tests.
> feat(frontend): Generalize ICP wallet workers for any token

- src/frontend/src/icp/derived/ic-contacts.derived.ts
- src/frontend/src/icp/derived/ic-transactions.derived.ts
- src/frontend/src/icp/utils/ic-transactions.utils.ts
We can use util `isTokenIcp` to define if a token is an `icp` standard, instead of comparing it directly with the ICP token.
> refactor(frontend): Use util `isTokenIcp` whenever possible

- src/frontend/src/lib/components/loaders/LoaderNfts.svelte
- src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts
When the application is running we want to check in an interval of 2 minutes if the user has some updated nfts. If nfts were updated, we want to also update them in the application.
> feat(frontend): handles updated nfts

- src/frontend/src/icp/components/swap/SwapIcpForm.svelte
- src/frontend/src/tests/icp/components/swap/SwapIcpForm.spec.ts
This PR introduces a new SwapIcpForm component, that is main Wrapper for SwapForm but works only with ICP networks.
- Added new NewSwapForm component
Covered new logic with tests.
> feat(frontend): added new SwapIcpForm component

- src/frontend/src/btc/services/btc-utxos.service.ts
- src/frontend/src/tests/btc/services/btc-utxos.service.spec.ts
The PR aims to ensure that the selection of  theUTXO when preparing the BTC send must have at least 6 confirmations. This change improves the reliability of BTC transaction handling.
- Replaced the incorrect usage of `UNCONFIRMED_BTC_TRANSACTION_MIN_CONFIRMATIONS` with `CONFIRMED_BTC_TRANSACTION_MIN_CONFIRMATIONS` in the `btc-utxos.service.ts` file.
- Updated the test case in `btc-utxos.service.spec.ts` to align with the change, setting `minConfirmations` to 6 instead of 1.
- Updated the test file `btc-utxos.service.spec.ts` to match the new constant by altering the expected value for `minConfirmations` to ensure proper validation of confirmed transactions.
> feat(frontend): UTXO should be selected with at least 6 confirmations

- src/frontend/src/btc/services/btc-send.services.ts
- src/frontend/src/btc/services/btc-utxos.service.ts
- src/frontend/src/btc/utils/btc-utxos.utils.ts
- src/frontend/src/tests/btc/services/btc-send.services.spec.ts
- src/frontend/src/tests/btc/services/btc-utxos.service.spec.ts
- src/frontend/src/tests/btc/utils/btc-utxos.utils.spec.ts
The PR is aiming to improve precision in fee calculation for Bitcoin transactions by switching the unit from satoshis per vbyte to millisatoshis per vbyte. Currently only working with satochi the calculated fee can deviate up to 50 % (e.g. 1456 is rounded to 1). This PR ensures more accurate fee estimates.
- Changed the fee unit returned by `getFeeRateFromPercentiles(..)` from `feeRateSatoshisPerVByte` ` to `feeRateMiliSatoshisPerVByte`
- Updated fee rate multiplications and divisions accordingly, introducing more precise calculations by working in millisatoshis.
- Adjusted minimum and maximum fee thresholds to align with the new unit.
- Updated tests to reflect the changes in fee calculation, including adjustments to expected results and test case values.
- Modified test expectations in …
> feat(frontend): increasing BTC fee rate precision

- src/frontend/src/lib/components/loaders/LoaderNfts.svelte
To avoid duplication of code, we use the existing ERC utils in component `LoaderNfts` to identify the standard of the tokens.
> refactor(frontend): Use ERC utils in `LoaderNfts`

- src/frontend/src/eth/services/send.services.ts
- src/frontend/src/eth/services/wallet-connect.services.ts
- src/frontend/src/eth/types/send.ts
Since send ETH services are going to be used outside of regular send/convert flows (AI console), we need to make progress param as optional.
> feat(frontend): optional "progress" param on sending ETH

- src/frontend/src/sol/services/sol-send.services.ts
Since `sendSol` is going to be used outside of regular send/convert flows (AI console), we need to make progress param as optional.
> feat(frontend): optional "progress" param on sending SOL

- src/frontend/src/lib/components/common/ModalHero.svelte
We need to extend `ModalHero` to accept additional slot "content".
> feat(frontend): extend ModalHero component

- src/frontend/src/btc/components/send/BtcUtxosFee.svelte
- src/frontend/src/btc/services/btc-send.services.ts
- src/frontend/src/btc/services/btc-utxos.service.ts
- src/frontend/src/btc/utils/btc-utxos.utils.ts
- src/frontend/src/icp/utils/btc.utils.ts
- src/frontend/src/lib/utils/network.utils.ts
- src/frontend/src/tests/btc/services/btc-send.services.spec.ts
- src/frontend/src/tests/btc/services/btc-utxos.service.spec.ts
- src/frontend/src/tests/btc/utils/btc-utxos.utils.spec.ts
- src/frontend/src/tests/icp/utils/btc.utils.spec.ts
This Pull Request aims to enhance the Bitcoin transaction handling functionality by addressing issues related to pending transactions and fixing the incorrect processing of UTXOs (unspent transaction outputs).
- Load pending transactions into the store before checking for locked UTXOs in the `prepareBtcSend` and `validateBtcSend` functions, ensuring data is always up to date.
- Introduced the function `getPendingTransactionUtxoTxIds()`, which correctly returns the txids of the relevant UTXOs (instead of incorectly using `getPendingTransactionIds())`.
- Reorganized utility functions related to txid conversion, ensuring that txids are stored correctly when saving pending transactions (during BTC sends).
- Using as variable name 'pendingUtxoTxIds' consistently  for UTXO txid's for pending …
> feat(frontend): correctly validate UTXO tx ids's

- src/frontend/src/lib/components/manage/ManageTokensModal.svelte
As long as the `NFT` feature is not active it should not be possible to import `erc721` or `erc1155` contracts.
> feat(frontend): blocks importing nft tokens when the feature flag is not active

- src/frontend/src/lib/derived/tokens.derived.ts
- src/frontend/src/tests/lib/derived/tokens.derived.spec.ts
To let LLM know which tokens are enabled and therefore can be sent by user, we need to create a new derived which should contain all enabled unique tokens symbols.
Note: handling different networks (e.g. "ETH" on Base and Arbitrum) will be tackled separately.
> feat(frontend): enabledUniqueTokensSymbols derived

- src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts
The `handleUpdatedNfts` test case failes sometimes and we want to fix it. To solve this we mock `loadNftIdsOfToken` to prevent that some additional nfts are loaded.
> fix(frontend): mocks loadNftIdsOfToken to prevent loading nfts

- src/frontend/src/lib/stores/modal-networks-list.store.ts
- src/frontend/src/tests/lib/stores/modal-networks-list.store.spec.ts
Make the store more reusable. Some consumers don’t need network restrictions, so requiring allowedNetworkIds adds unnecessary friction. This PR makes that property optional.
- Made allowedNetworkIds optional in the context API
Added new test to cover this change.
> feat(frontend): allow to do not provide allowedNetworksIds to initModalNetworksListContext

- src/frontend/src/lib/components/ui/MarkdownSidebar.svelte
- src/frontend/src/tests/lib/components/ui/MarkdownSidebar.spec.ts
For the new Terms of Use, License agreement pages, we add a sidebar component that renders a table of contents for a list of MarkdownBlocks.
Added component
Added tests
> feat(frontend): Markdown Sidebar

- src/frontend/src/eth/components/fee/EthFeeContext.svelte
When we estimate the fee for an Ethereum transaction for ERC20, we take the maximum estimate between an `approve` transaction and a `transfer` transaction, provided the inputs.
However, since we are not passing the correct decimals of the ERC20 token, the `transfer` transaction would return an error of insufficient balance, and provide no estimate gas.
For example, if the user inputs `123` for the amount of a certain token with 9 decimals, instead of calculating the fee for `123_000_000_000`, we would be calculating it for `123_000_000_000_000_000_000` (18 decimals, that is the default of the util `parseToken`). And it most probably fails due to insufficient token balance.
To fix it, we pass the decimals of the token we are trying to send.
> fix(frontend): Pass decimals of Ethereum token when calculating fee

- src/frontend/src/lib/components/swap/Swap.svelte
We need a safe way to transition to the new NewSwapModal without breaking existing functionality. By introducing a feature flag (VELORA_SWAP_ENABLED), we can toggle between the old SwapModal and the new implementation, making rollback easy if needed.
Added conditional rendering: NewSwapModal when VELORA_SWAP_ENABLED is true, otherwise SwapModal
> feat(frontend): added render of NewSwapModal component

- .github/workflows/backend-tests.yml
In the backend tests CIs we were using the wrong output for the job `breaking-interface`
> fix(devops): Correct output name for steps in backend tests

- src/frontend/src/lib/components/networks/NetworkSwitcherList.svelte
We need to disable testenvs for swap
Added condition to show testenvs if supportedNetworks are not provided.
> fix(frontend): disabled testenvs for swap

- src/frontend/src/env/networks/networks.icp.env.ts
- src/frontend/src/lib/derived/networks.derived.ts
- src/frontend/src/tests/lib/derived/networks.derived.spec.ts
For LLM to know which networks are currently enabled, we create a special derived store.
> feat(frontend): enabledNetworksSymbols derived store

- src/frontend/src/eth/components/swap/SwapEthForm.svelte
CustomValidate wasn’t being triggered after sourceToken changed. This PR adds a reactive Svelte effect to recalculate and run the validation whenever sourceToken updates.
Added a Svelte effect to validate sourceToken on change.
> fix(frontend): adjusted custom error for customValidate

- src/frontend/src/env/tokens/tokens.icrc.json
Token RSIC.OT has the ledger without cycles, and it seems it is not being maintained. We remove it from our list or ICRC additional tokens.
> feat(frontend): Remove RSIC.OT from ICRC additional tokens

- src/frontend/src/lib/components/ai-assistant/AiAssistantConsole.svelte
- src/frontend/src/lib/components/core/Footer.svelte
- src/frontend/src/routes/(app)/+layout.svelte
We need to move the AI console inside the footer so the soical icons can be properly rendered when the console is open. It also solves the positioning issues.
> feat(frontend): render AI console inside the footer

- src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendBtcToken.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendEthToken.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendIcToken.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendSolToken.svelte
- src/frontend/src/lib/constants/analytics.contants.ts
On top of "success"/"failed" send events, we'd like to track how many times the review_send_token tool was confirmed.
> feat(frontend): track review_send_token tool confirmation

- src/frontend/src/lib/components/agreements/AcceptAgreementsCheckbox.svelte
- src/frontend/src/lib/components/agreements/AcceptAgreementsModal.svelte
- src/frontend/src/lib/constants/test-ids.constants.ts
- src/frontend/src/lib/i18n/ar.json
- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/fr.json
- src/frontend/src/lib/i18n/hi.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/ja.json
- src/frontend/src/lib/i18n/pl.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/ru.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/lib/components/agreements/AcceptAgreementsModal.spec.ts
We add the services to save the user agreements in the `AcceptAgreementsModal`.
- Use backend method `updateUserAgreements` when accepting the terms and agreements.
- Emit call to refresh the user profile.
- Remove `preventDefault` settings in the checkbox.
Included unittests (and test IDs). But here a practical on:
https://github.com/user-attachments/assets/aed235e4-0907-4c9f-a0b0-5f915f324326
> feat(frontend): Add service to save agreements in `AcceptAgreementsModal`

- src/frontend/src/lib/components/agreements/AcceptAgreementsModal.svelte
- src/frontend/src/tests/lib/components/agreements/AcceptAgreementsModal.spec.ts
For the current time in `bigint` we already have the util `nowInBigIntNanoSeconds`.
> refactor(frontend): Use existing util for current time in `AcceptAgreementsModal`

- scripts/build.csp.mjs
We miss the WSS opening in the Content Security Policy sources
> fix(build): Missing `wss` sources in Content Security Policy

- src/frontend/src/lib/components/contact/Avatar.svelte
- src/frontend/src/lib/components/contact/AvatarWithBadge.svelte
- src/frontend/src/lib/types/style.ts
Design needs a smaller avatar size for transaction lists
This Pr is part of https://github.com/dfinity/oisy-wallet/pull/8695
Added size="xxc" variant to Avatar styles.
Manual test
> feat(frontend): add Avatar variant

- src/frontend/src/tests/lib/services/wallet-connect.services.spec.ts
- src/frontend/src/tests/sol/services/sol-signatures.services.integration.spec.ts
For coverage, we add more tests to the WalletConnect services in `lib`.
> test(frontend): More tests for WalletConnect base services

- src/frontend/src/lib/components/core/IntervalLoader.svelte
- src/frontend/src/lib/components/loaders/LoaderNfts.svelte
- src/frontend/src/tests/lib/components/loaders/LoaderNfts.spec.ts
When using an `IntervalLoader` we want to be able to skip the first loading process.
> feat(frontend): Enables to skip the first interval of IntervalLoader

- src/frontend/src/lib/derived/user-experimental-features.derived.ts
- src/frontend/src/tests/lib/derived/user-experimental-features.derived.spec.ts
Now, we need to create some additional derived stores for the  user experimental features functionality.
> feat(frontend): user experimental features derived stores

- src/frontend/src/lib/components/settings/Settings.svelte
We can finally display the new SettingsExperimentalFeatures component. The condition is the AI assistant feature flag - it's the only available option for now, so we decided to hide the whole settings section if the flag is not enabled.
> feat(frontend): display SettingsExperimentalFeatures

- src/frontend/src/btc/components/transactions/BtcTransactions.svelte
- src/frontend/src/eth/components/transactions/EthTransactions.svelte
- src/frontend/src/icp/components/transactions/IcTransactions.svelte
- src/frontend/src/lib/components/transactions/Transactions.svelte
- src/frontend/src/sol/components/transactions/SolTransactions.svelte
Migrating `Transactions` component (and its direct children) to Svelte 5.
> refactor(frontend): Migrate `Transactions` component to Svelte 5

- src/frontend/src/eth/utils/erc1155.utils.ts
- src/frontend/src/eth/utils/erc20.utils.ts
- src/frontend/src/eth/utils/erc721.utils.ts
- src/frontend/src/eth/utils/token.utils.ts
- src/frontend/src/lib/components/nfts/NftCollectionActionButtons.svelte
- src/frontend/src/lib/components/nfts/NftImageConsentModal.svelte
- src/frontend/src/tests/eth/utils/erc1155.utils.spec.ts
- src/frontend/src/tests/eth/utils/erc20.utils.spec.ts
- src/frontend/src/tests/eth/utils/erc721.utils.spec.ts
When possible we would prefer to use the utils `isTokenErc1155`, `isTokenErc721` and `isTokenErc20`.
> refactor(frontend): Use ERC tokens utils to check the standard

- src/frontend/src/tests/icp/workers/ic-wallet-balance-and-transactions.worker.spec.ts
We are doing more and more specific tests for the ICRC wallet workers. So, for manageability and to simplify the code we refactor the tests to avoid using functions to call them: they are not so generic anymore.
> test(frontend): Simplify tests for IC wallet workers

- src/frontend/src/lib/components/ai-assistant/AiAssistantMessages.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantShowContactsTool.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantToolResults.svelte
- src/frontend/src/tests/lib/components/ai-assistant/AiAssistantShowContactsTool.spec.ts
- src/frontend/src/tests/lib/components/ai-assistant/AiAssistantToolResults.spec.ts
If AI console is already in the loading state, we need to prevent additional clicks on ShowContactTool items.
> feat(frontend): consider "loading" flag in ShowContactsTool

- src/frontend/src/eth/components/convert/ConvertToCkEth.svelte
- src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte
- src/frontend/src/eth/components/send/ConvertToCkErc20.svelte
- src/frontend/src/eth/components/swap/SwapEthWizard.svelte
- src/frontend/src/eth/components/transactions/EthTransactions.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/derived/eth-transactions.derived.ts
- src/frontend/src/eth/derived/token.derived.ts
- src/frontend/src/icp-eth/components/info/InfoEthereum.svelte
- src/frontend/src/icp-eth/derived/cketh.derived.ts
- src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendTokenTool.svelte
- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
- src/frontend/src/lib/stores/convert.store.ts
- src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
Just to avoid confusion, we rename the derived store `ethereumToken` to `nativeEthereumToken`.
> refactor(frontend): Rename derived store for native Ethereum/EVM token

- src/frontend/src/env/caip10-chains.env.ts
- src/frontend/src/lib/providers/wallet-connect.providers.ts
To avoid passing unnecessary CAIP keys, we split them into mainnet and devnet.
> refactor(frontend): Split CAIP-10 chains keys into mainnet and devnet

- src/frontend/src/lib/components/send/SendInputDestination.svelte
Address Field does not show the right end of the address
Override the gix/components default padding value and set the input’s right padding to 80px so the full value remains visible.
> fix(frontend): fixed send input padding value

- src/frontend/src/env/oisy.metadata.json
Our PM used an underscore in the link, although it's obvious that gitbook uses dashes.
- change the link
> chore(frontend): Fix AI Assistant Gitbook link

- src/frontend/src/sol/utils/sol-instructions-token.utils.ts
- src/frontend/src/tests/sol/utils/sol-instructions-token.utils.spec.ts
To make util `parseSolTokenInstruction` more type-safe, we use a forced casting to never to discover if we forgot to track some specific variants.
Since we are here, we add tests.
> refactor(frontend): Make util `parseSolTokenInstruction` more type-safe

- src/frontend/src/sol/utils/sol-instructions-system.utils.ts
- src/frontend/src/tests/sol/utils/sol-instructions-system.utils.spec.ts
To make util `parseSolSystemInstruction` more type-safe, we use a forced casting to never to discover if we forgot to track some specific variants.
Since we are here, we add tests.
> refactor(frontend): Make util `parseSolSystemInstruction` more type-safe

- src/frontend/src/sol/utils/sol-instructions-token-2022.utils.ts
- src/frontend/src/tests/sol/utils/sol-instructions-token-2022.utils.spec.ts
To make util `parseSolToken2022Instruction` more type-safe, we use a forced casting to never to discover if we forgot to track some specific variants.
Since we are here, we add tests.
> refactor(frontend): Make util `parseSolToken2022Instruction` more type-safe

- dfx.json
- src/declarations/rewards/rewards.did
- src/declarations/rewards/rewards.did.d.ts
- src/declarations/rewards/rewards.factory.certified.did.js
- src/declarations/rewards/rewards.factory.did.js
- src/frontend/src/lib/types/reward.ts
- src/frontend/src/lib/utils/rewards.utils.ts
- src/frontend/src/tests/lib/services/reward.services.spec.ts
- src/frontend/src/tests/lib/utils/rewards.utils.spec.ts
The candid API has new fields that were not marked as optional.  They need to be optional, so that the new front end code works with the old rewards canister.
- Bump rewards canister
> chore(rewards): Bump rewards canister release

- src/frontend/src/eth/providers/alchemy.providers.ts
- src/frontend/src/tests/eth/providers/alchemy.providers.spec.ts
It was announced that [alchemy-sdk](https://github.com/alchemyplatform/alchemy-sdk-js) will be deprecated soon:
> Warning
> 
> The Alchemy SDK JS has been deprecated and will be archived January 2026. The software will only receive minimal support until then. New and existing users are encourage to use the following tools instead:
So, we need to start taking care of the migration.
In this first PR we just rename the current provider of class `AlchemyProvider`, so that we can include a new one after and slowly migrate.
> refactor(frontend): Start deprecating `alchemy-sdk` in `AlchemyProvider`

- src/frontend/src/tests/icp/utils/btc.utils.spec.ts
- src/frontend/src/tests/lib/services/reward.services.spec.ts
- src/frontend/src/tests/lib/utils/rewards.utils.spec.ts
Whenever possible, we use the `toNullable` util for the tests of the rewards canister.
> test(frontend): Use `toNullable` util in rewards canister tests

- src/frontend/src/eth/components/convert/ConvertToCkEth.svelte
- src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte
- src/frontend/src/eth/components/send/ConvertToCkErc20.svelte
- src/frontend/src/eth/components/swap/SwapEthWizard.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSendTokenModal.svelte
- src/frontend/src/eth/derived/token.derived.ts
- src/frontend/src/icp-eth/components/info/InfoEthereum.svelte
- src/frontend/src/icp/components/receive/IcReceiveCkEthereum.svelte
- src/frontend/src/lib/components/ai-assistant/AiAssistantReviewSendTokenTool.svelte
- src/frontend/src/lib/components/send/SendWizard.svelte
- src/frontend/src/lib/stores/convert.store.ts
- src/frontend/src/tests/eth/components/convert/EthConvertTokenWizard.spec.ts
To be more consistent, we rename the derived store `nativeEthereumToken` to `nativeEthereumTokenWithFallback`, extracting the one without fallback.
> refactor(frontend): Rename derived store for native Ethereum token

- src/frontend/src/lib/types/ai-assistant.ts
- src/frontend/src/lib/utils/ai-assistant.utils.ts
- src/frontend/src/tests/lib/utils/ai-assistant.utils.spec.ts
We want to keep the send status of a ReviewSendTokensToolResult item in the store instead of component, so the data persists when console is getting closed and then reopened.
The store function to toggle the status, as well as the UI part of the feature will follow separately.
> feat(frontend): extend ReviewSendTokensToolResult with id and status

- src/frontend/src/icp/api/icrc-ledger.api.ts
- src/frontend/src/tests/icp/api/icrc-ledger.api.spec.ts
Since we now use the latest ledger-icrc package version, we can expose the newly added API method needed for identifying whether a ledger supports e.g. ICRC-2 standard.
> feat(frontend): expose icrc1SupportedStandards of ledger-icrc

- src/frontend/src/lib/components/exchange/ExchangeBalance.svelte
- src/frontend/src/lib/components/hero/Balance.svelte
We have an issue for wallet balances with non dollar currencies - they don't fit into the balance block
- Update Balance.svelte to use responsive text sizing (text-4xl on small, text-5xl starting medium)
- Update ExchangeBalance.svelte to use responsive text sizing (text-4xl on small, text-5xl starting medium)
- Ensures larger balance amounts fit properly on small mobile devices
- Maintains visual hierarchy across all screen sizes
**Issue:** 
**Now:**
> feat(frontend): improve responsive text sizing for balance components

- src/frontend/src/lib/api/kong_backend.api.ts
- src/frontend/src/lib/canisters/kong_backend.canister.ts
- src/frontend/src/lib/components/swap/Swap.svelte
- src/frontend/src/lib/services/swap.services.ts
- src/frontend/src/lib/types/canister.ts
- src/frontend/src/tests/lib/services/swap.services.spec.ts
We encountered an issue retrieving tokens from the KongSwap canister due to a response-size limit. As a hotfix, we switched to fetching tokens individually.
- Implemented Promise.allSettled in allIcrcTokens to request tokens one by one.
- For each supported token, retrieve metadata from kong_swap.
Fixed tests.
> fix(frontend): load kongswap tokens

- src/frontend/src/lib/components/qr/QrCodeScanner.svelte
QR scanner used old colors 
- Remove blue-purple overlay from QR scanner camera view
- Use elegant single-line CSS solution: color: transparent
- Improve user experience with clear, unobstructed camera view for QR scanning
Before: 
After:
> feat(frontend): add transparent background to QR code scanner

- src/frontend/src/lib/components/wallet-connect/WalletConnectForm.svelte
The QR code scanner used old colors. 
- Remove purple background overlay for transparent camera view
- Update outline to use tertiary color with thinner dashed border
- Create cleaner, more polished QR scanning interface
> feat(frontend): improve WalletConnect QR scanner styling

- .github/repo_policies/BOT_APPROVED_FILES
Since some CI updates icons and logos of IC tokens, we need to allow the Bot to update them.
> ci(bot): Allow bot to modify tokens images logos

- scripts/check.unused.svelte.mjs
The CI that checks for unused Svelte components, ignores the tests: we want to see if the components are effectively used.
However, it is giving false positive for Svelte components that are auxiliary and used ONLY in the tests.
For now, we ignore such component in the analysis, and we will follow-up with a way to check if they are effectively used, and used ONLY in the tests.
> feat(devops): Ignore test folder when checking unused Svelte components

- src/frontend/src/lib/components/settings/Settings.svelte
- src/frontend/src/lib/components/settings/SettingsExperimentalFeatures.svelte
- src/frontend/src/lib/i18n/ar.json
- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/fr.json
- src/frontend/src/lib/i18n/hi.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/ja.json
- src/frontend/src/lib/i18n/pl.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/ru.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/i18n.d.ts
Fixing some small translation issues.
- Adjusted AI setting translation (havent been reactive so didnt change on language change)
- Added translation for hardcoded "General" text
DE:
EN:
FR:
> fix(frontend): Settings translation fixes

- src/frontend/src/lib/components/nfts/NftsList.svelte
Since we don't know if we are still loading nfts or not, we do not display the skeletons anymore when all imported collections are empty.
**Old:**
**New:**
> fix(frontend): Displays empty nfts list when collections are all empty

- src/frontend/src/eth/components/transactions/EthTransactions.svelte
- src/frontend/src/icp/components/transactions/IcTransactions.svelte
- src/frontend/src/lib/components/loaders/Loaders.svelte
- src/frontend/src/lib/components/send/SendDestinationWizardStep.svelte
- src/frontend/src/routes/(app)/activity/+page.svelte
Some of the sprinkles programs require to have the list of the user transactions too to work. For Ethereum and EVMs, the transactions loaders are created only in the Activity page and in the transactions list for each token.
Now, we need for all the pages (rewards, assets, etc). So, we move the main loader to the global `Loaders` component. And we remove the listeners from the transactions lists too.
> feat(frontend): Always load all Ethereum transactions

- .github/workflows/frontend-update-coverage-thresholds.yml
- src/frontend/src/routes/+layout.svelte
- src/frontend/src/tests/routes/layout.spec.ts
Just a small refactoring to reorganize correctly the tests of the main app `layout` dividing the flow of the `BroadcastChannel` in a different `describe` statement.
> refactor(frontend): Reorganize the tests for App Layout

- .github/workflows/e2e-tests.yml
For the merge queue, we are running ALWAYS the E2E tests. However, it is not necessary if there are not changed files related to it (for now).
> fix(devops): Do not run unnecessary E2E tests for merge queue

- src/frontend/src/lib/components/send/SendReview.svelte
We want to reuse the component `SendReview` in the WalletConnect flow: this will maintain consistency of style and layout.
However, WalletConnect review requires specific actions on approval and rejection, while `SendReview` has already set the actions.
In this PR we provide a custom toolbar that otherwise will default to the existing one.
- Adapt the Props of `SendReview` to accept either the actions callbacks or a completely new toolbar.
- Adapt the code
Existing tests should work as expected.
> feat(frontend): Optional toolbar in SendReview component

- src/frontend/src/lib/components/auth/ButtonAuthenticateWithHelp.svelte
- src/frontend/src/tests/lib/components/auth/ButtonAuthenticateWithHelp.spec.ts
Just to be sure, we set the auth lock store to false on login.
> feat(frontend): Set IDB lock cache to false on login

- .github/workflows/frontend-update-coverage-thresholds.yml
We have reached a stable rhythm for coverage thresholds, so we won’t be increasing them aggressively with each PR. However, keeping a strict floor limit introduces the risk of falling close to that minimum and then needing to add a large batch of new tests all at once.
By removing the fixed floor for threshold values, we can maintain the right level of coverage while avoiding frequent or sudden updates to the limits.
> feat(devops): Do not floor coverage thresholds

- .github/workflows/frontend-update-coverage-thresholds.yml
We don't need 50 bps of margins in the coverage thresholds. The flakiness is at maximum 0.05%, so we can reduce it and still be conservative.
> feat(devops): Reduce coverage threshold margins to 0.10%

- src/frontend/src/eth/utils/qr-code.utils.ts
- src/frontend/src/icp/stores/ethereum-fee.store.ts
- src/frontend/src/lib/utils/qr-code.utils.ts
Small refactoring to remove unnecessary `undefined` type from optional params.
> chore(frontend): Remove unnecessary `undefined` type in optional params

- src/frontend/src/eth/components/wallet-connect/EthWalletConnectMessage.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSignReview.svelte
We want to make the WalletConnect modal more verbose and try to parse the messages for Ethereum sign transactions.
To this scope, we first extract a specific component for the message.
> refactor(frontend): Extract component for ETH WalletConnect message

- src/frontend/src/lib/components/nfts/NftCollectionCard.svelte
- src/frontend/src/lib/utils/nfts.utils.ts
- src/frontend/src/tests/lib/utils/nfts.utils.spec.ts
- vitest.config.ts
We need to make some adjustments to the Nft search filtering.
- The search should match all collections by collection name or if any Nft in that collection matches the query in Nft name or Nft token ID.
- The search should match all Nfts by collection name, Nft name or Nft token ID.
- Nft collection cards should display only the matched Nfts.
- Adjusted the filter method in Nfts util with some utility functions to clean the filter method up
- Also use the filter method in NftCollectionCard
Adjusted/extended filter utils tests to cover all different new cases
> feat(frontend): Nft filter changes

- src/frontend/src/lib/components/nfts/NftSettingsMenu.svelte
- src/frontend/src/lib/components/nfts/NftSortMenu.svelte
- src/frontend/src/lib/components/tokens/TokenMenu.svelte
- src/frontend/src/lib/components/tokens/TokensFilter.svelte
- src/frontend/src/lib/components/tokens/TokensMenu.svelte
The menu buttons were all enable-dependent on the ERC20 tokens store being initialized, however it is not coherent, since they are used for all networks and none of them really has any direct dependency on ERC20 tokens.
Furthermore, it means that if the Ethereum/EVM networks are disabled, all these components would be disabled too, and it does not really work for the user.
> fix(frontend): Remove ERC20 dependency from menu buttons

- src/frontend/src/eth/services/eth-transactions.services.ts
- src/frontend/src/lib/i18n/ar.json
- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/fr.json
- src/frontend/src/lib/i18n/hi.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/ja.json
- src/frontend/src/lib/i18n/pl.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/ru.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
There is really no need for a toast error when a token that was being used to fetch transaction is suddenly disabled.
> feat(frontend): Remove toast error when ETH token disabled for loading transactions

- vitest.config.ts
I never noticed that the test files were included in the coverage calculation of `vitest`. This is conceptually wrong and obviously it raises the average a lot, since we MUST run them to have the coverage.
> fix(frontend): Exclude test files from coverage calculation

- src/frontend/src/lib/components/guard/UrlGuard.svelte
- src/frontend/src/lib/components/loaders/Loader.svelte
- src/frontend/src/lib/components/wallet-connect/WalletConnectSession.svelte
- src/frontend/src/lib/services/loader.services.ts
- src/frontend/src/lib/stores/loader.store.ts
- src/frontend/src/tests/lib/components/guard/UrlGuard.spec.ts
- src/frontend/src/tests/lib/components/loaders/Loader.spec.ts
- src/frontend/src/tests/lib/services/loader.services.spec.ts
To avoid confusion, we rename the store `loading` to `initialLoading`, since it is set ONLY during the first loading process.
> refactor(frontend): Rename the `loading` store for the initial loader

- src/frontend/src/eth/components/loaders/LoaderMultipleEthTransactions.svelte
- src/frontend/src/eth/services/eth-balance.services.ts
- src/frontend/src/eth/services/eth-transactions.services.ts
- src/frontend/src/lib/i18n/ar.json
- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/en.json
- src/frontend/src/lib/i18n/fr.json
- src/frontend/src/lib/i18n/hi.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/ja.json
- src/frontend/src/lib/i18n/pl.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/ru.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
- src/frontend/src/lib/types/i18n.d.ts
- src/frontend/src/tests/eth/services/eth-balance.services.spec.ts
- src/frontend/src/tests/eth/services/eth-transactions.services.spec.ts
There is no need to provide an error feedback to the user if during loading of transactions/balances, the ETH address is not available (still loading, disabled, etc).
> feat(frontend): Remove toast error for loading transactions or balance without address

- src/frontend/src/lib/components/tokens/ManageTokensButton.svelte
The manage tokens button was enable-dependent on the ERC20 tokens store being initialized, however it is not coherent, since it is used for all networks and it has no direct dependency on ERC20 tokens.
Furthermore, it means that if the Ethereum/EVM networks are disabled, it would be disabled too, and it does not really work for the user.
> feat(frontend): Remove ERC20 dependency from the manage tokens button

- src/frontend/src/lib/components/loaders/Loader.svelte
Suggestion by @peterpeterparker: https://github.com/dfinity/oisy-wallet/pull/9290#pullrequestreview-3285157460
> That said, we can probably smoothness the loading even a bit more in other PRs.
> 
> For example, assuming you updated the resulting video provided in the PR after the first iteration, would removing the fade on line 285 even make the boot more smooth?
https://github.com/user-attachments/assets/79300c0f-c3dc-4437-93f6-0b30b14d6d61
https://github.com/user-attachments/assets/31119d44-bc45-4a16-872b-c301f1221705
> style(frontend): Remove fading from initial loader for frontend derivation

- src/frontend/src/lib/i18n/cs.json
- src/frontend/src/lib/i18n/de.json
- src/frontend/src/lib/i18n/fr.json
- src/frontend/src/lib/i18n/it.json
- src/frontend/src/lib/i18n/ja.json
- src/frontend/src/lib/i18n/pl.json
- src/frontend/src/lib/i18n/pt.json
- src/frontend/src/lib/i18n/vi.json
- src/frontend/src/lib/i18n/zh-CN.json
We added the "by clicking this button you agree...." text back.
- Add translations for the other languages
> feat(frontend): Translations for terms of use instruction

- .github/workflows/e2e-tests.yml
When one of the PRs in the merge group has changed E2E-related files, the E2E tests should run, since we have a compulsory status check in those cases.
> fix(devops): Run E2E tests for merge group when necessary

- src/frontend/src/lib/components/core/Banner.svelte
In the `Banner` component, the two separate banners (one for the environment and one for PWA) are using the same variable to be visible or not. This causes each banner to close both, and that is not intended by the user.
To fix it, we assign separate variables to each closing action.
> fix(frontend): Remove concurrency from `Banner` component

- src/frontend/src/lib/components/manage/ManageTokensModal.svelte
Component `ManageTokens` does not emit the event `icClose`. So we can remove it in `ManageTokensModal`.
> chore(frontend): Remove unused event in `ManageTokensModal`

- src/frontend/src/lib/components/swap/SwapTokensList.svelte
Type `TokenUi` has already `Token` as generic default.
> refactor(frontend): Remove unnecessary generic from `TokenUi` in `SwapTokensList`

- src/frontend/src/btc/components/transactions/BtcTransaction.svelte
- src/frontend/src/eth/components/transactions/EthTransaction.svelte
- src/frontend/src/icp/components/transactions/IcTransaction.svelte
- src/frontend/src/lib/components/transactions/Transaction.svelte
- src/frontend/src/sol/components/transactions/SolTransaction.svelte
- src/frontend/src/tests/lib/components/transactions/Transaction.spec.ts
The `fee` prop of `Transaction` component is never used. So, the logic of adding the `fee` for incoming transactions is not used. We can remove it and decide that the amount that is passed to `Transaction` is the one to be displayed.
> refactor(frontend): Remove fee calculation in `Transaction`

- scripts/test.backend.sh
`BITCON_CANISTER_WASM` --> `BITCOIN_CANISTER_WASM`
> chore(devops): Typo in `test.backend.sh` script

- src/frontend/src/lib/components/send/SendData.svelte
- src/frontend/src/sol/components/wallet-connect/SolWalletConnectSignReview.svelte
Since we are going to add a `destinationNetwork` in `SendData`, we rename the existing network slot to `sourceNetwork`.
> refactor(frontend): Rename network slot in `SendData`

- src/frontend/src/lib/components/wallet-connect/WalletConnectData.svelte
- src/frontend/src/lib/components/wallet-connect/WalletConnectModalValue.svelte
As per decision, the WalletCOnnect modal should not give the impression that the transaction is native of OISY, meaning, as hint, that it should have a different style from the normal modals. We are opting for a simple one.
So, as first step we extract a common component for the component `WalletConnectModalValue`. 
Example:
> feat(frontend): Specific component for values in WalletConnect modals

- scripts/test.backend.sh
- src/shared/src/types/agreement.rs
There are too many logs entry during the backend tests:
As per [forum suggestion](https://forum.dfinity.org/t/pocketic-multi-subnet-canister-testing/24901/11), we mute the server specifically.
The [custom test run](https://github.com/dfinity/oisy-wallet/actions/runs/18231427006/job/51915714079) in this same PR shows that it works:
> test(backend): Mute Pocket IC server

- src/frontend/src/lib/components/send/SendSource.svelte
To be consistent, we can use existing component `WalletConnectModalValue` in `SendSource`.
> refactor(frontend): Use existing component in `SendSource`

- src/frontend/src/lib/components/ui/Value.svelte
- src/frontend/src/lib/components/wallet-connect/WalletConnectModalValue.svelte
To avoid repetition of code and for manageability, we can re-use component `Value` in component `WalletConnectModalValue`.
> feat(frontend): Use component `Value` in `WalletConnectModalValue`

- src/frontend/src/eth/components/wallet-connect/WalletConnectSendReview.svelte
- src/frontend/src/lib/components/send/SendData.svelte
As per decision, the WalletConnect modal should not give the impression that the transaction is native of OISY, meaning, as hint, that it should have a different style from the normal modals. We are opting for a simple one: label + data.
- Add slot for destination network in `SendData`.
- Rollback `WalletConnectSendReview` to use a `SendData`.
- Mount the networks slots: source and destination.
- Adapt the other slots.
We will tackle additional data and adjustments of single data components in other PRs. For example, we will need to change the fee component to be simpler.
Example:
> feat(frontend): Differentiate the modal of WalletConnect

- src/frontend/src/lib/components/contact/ContactWithAvatar.svelte
- src/frontend/src/lib/components/transactions/Transaction.svelte
We need a specific component that shows a string of the contact plus the avatar. Since the logic is already in the `Transaction` component, we can extract it.
No changes in the UI.
> feat(frontend): Extract component for contact with avatar

- src/frontend/src/sol/services/sol-send.services.ts
Just noticed that in service `setLifetimeAndFeePayerToTransaction` there is an unnecessary deconstruction of the `latestBlockhash` object.
> refactor(frontend): Remove unnecessary deconstruction in `setLifetimeAndFeePayerToTransaction`

- src/frontend/src/lib/components/ai-assistant/AiAssistantShowBalanceToolCard.svelte
- src/frontend/src/lib/components/exchange/ExchangeTokenValue.svelte
- src/frontend/src/lib/components/hero/Balance.svelte
- src/frontend/src/lib/components/swap/SwapTokensList.svelte
- src/frontend/src/lib/components/tokens/TokenGroupCard.svelte
- src/frontend/src/lib/components/tokens/TokensDisplayHandler.svelte
- src/frontend/src/lib/components/tokens/TokensList.svelte
- src/frontend/src/lib/components/transactions/AllTransactions.svelte
- src/frontend/src/lib/derived/network-tokens.derived.ts
- src/frontend/src/lib/stores/modal-tokens-list.store.ts
- src/frontend/src/lib/types/ai-assistant.ts
- src/frontend/src/lib/types/token-card.ts
- src/frontend/src/lib/types/token-group.ts
- src/frontend/src/lib/types/token-ui-group.ts
- src/frontend/src/lib/types/token-ui.ts
- src/frontend/src/lib/types/token.ts
- src/frontend/src/lib/utils/ai-assistant.utils.ts
- src/frontend/src/lib/utils/token-card.utils.ts
- src/frontend/src/lib/utils/token-group.utils.ts
- src/frontend/src/lib/utils/token-list.utils.ts
- src/frontend/src/lib/utils/token.utils.ts
- src/frontend/src/lib/utils/tokens.utils.ts
- src/frontend/src/tests/lib/components/tokens/TokensDisplayHandler.spec.ts
- src/frontend/src/tests/lib/components/tokens/TokensDisplayHandlerTest.svelte
- src/frontend/src/tests/lib/utils/token-card.utils.spec.ts
- src/frontend/src/tests/lib/utils/token-group.utils.spec.ts
- src/frontend/src/tests/lib/utils/token-list.utils.spec.ts
- src/frontend/src/tests/lib/utils/tokens.utils.spec.ts
To avoid circular reference, we extract the types for Token UI and Token Group UI to separate modules.
> refactor(frontend): Extract types of Token UI to separate modules

- src/frontend/src/btc/components/send/BtcSendAmount.svelte
- src/frontend/src/eth/components/send/EthSendAmount.svelte
- src/frontend/src/icp/components/send/IcSendAmount.svelte
- src/frontend/src/lib/components/convert/ConvertAmountDestination.svelte
- src/frontend/src/lib/components/convert/ConvertAmountSource.svelte
- src/frontend/src/lib/components/swap/SwapForm.svelte
- src/frontend/src/lib/components/tokens/TokenInput.svelte
- src/frontend/src/sol/components/send/SolSendAmount.svelte
Migrating component `TokenInput` to Svelte 5.
Notice that the event `nnsInput` was never used in any of the consumers.
> refactor(frontend): Migrate component `TokenInput` to Svelte 5

- .github/dependabot.yml
We will allow dependabot to bump the lint packages, to keep up with current updates.
> feat(dependabot): Let it bump lint packages

- src/frontend/src/lib/components/guard/RewardGuard.svelte
- src/frontend/src/tests/lib/components/guard/RewardGuard.spec.ts
We simplify a bit the logic of `RewardGuard` to be faster. And we re-organize the tests to split them.
> refactor(frontend): Simplify logic in `RewardGuard`

- src/frontend/src/lib/components/send/SendFeeInfo.svelte
The balance exposed during the fee payment was not reactive.
> fix(frontend): Make balance for fee reactive

- src/frontend/src/eth/components/wallet-connect/EthWalletConnectMessage.svelte
- src/frontend/src/eth/components/wallet-connect/WalletConnectSignReview.svelte
- src/frontend/src/tests/eth/components/wallet-connect/EthWalletConnectMessage.spec.ts
To keep everything in one place, we move the method of WalletConnect inside the component `EthWalletConnectMessage`.
> refactor(frontend): Move WalletConnect method inside `EthWalletConnectMessage`

- src/frontend/src/eth/components/wallet-connect/EthWalletConnectSignModal.svelte
We want to include the Ethereum domain name in the WalletConnect sign modal.
> feat(frontend): Add domain name in WalletConnect modal for Ethereum

- src/frontend/src/sol/services/sol-send.services.ts
- src/frontend/src/tests/sol/services/sol-send.services.spec.ts
It is actually safer to use `transferChecked` for all Token-2022 programs in Solana.
> feat(frontend): Use `transferChecked` for all Token-2022 SPL

- src/frontend/src/eth/components/wallet-connect/EthWalletConnectSignModal.svelte
- src/frontend/src/sol/components/wallet-connect/SolWalletConnectSignModal.svelte
Migrating `EthWalletConnectSignModal` and `SolWalletConnectSignModal`.
> refactor(frontend): Migrate WalletConnect sign modals to Svelte 5

- src/frontend/src/btc/components/convert/BtcConvertReview.svelte
- src/frontend/src/btc/components/convert/BtcConvertTokenWizard.svelte
- src/frontend/src/eth/components/convert/EthConvertReview.svelte
- src/frontend/src/eth/components/convert/EthConvertTokenWizard.svelte
- src/frontend/src/icp/components/convert/IcConvertReview.svelte
- src/frontend/src/icp/components/convert/IcConvertTokenWizard.svelte
Component `ConvertReview` does not emit an `icBack` event.
> chore(frontend): Remove inexistent event from `ConvertReview`

- src/frontend/static/manifest.webmanifest
A small correction in the manifest when we create short-links for Ethereum.
> fix(build): Correct filter for Ethereum in manifest

- src/frontend/src/lib/components/swap/Swap.svelte
- src/frontend/src/lib/components/swap/SwapTokensList.svelte
We need to display allIcrcTokens instead of kongswapTokens in the swapModalTokenList.
Updated the logic to use allIcrcTokens instead of kongswapTokens.
> feat(frontend): load all icrc tokens for swap modal tokens

- src/frontend/src/eth/components/tokens/EthAddTokenForm.svelte
- src/frontend/src/icp/components/tokens/IcAddTokenForm.svelte
At runtime, we receive an error that an optional string should not be binded with an empty string, but with `undefined`.
> fix(frontend): Do not bind undefined props with empty string

- src/frontend/src/lib/components/navigation/MobileNavigationMenu.svelte
- src/frontend/src/routes/(app)/+layout.svelte
Since the sticky headers for transaction dates can also appear at the bottom of a page it can overlap the mobile nav.
Changed z-index for mobile nav and AI assistant to 3.
Before:
After:
The AI assistant still covers the mobile nav:
The header modals and popups still cover the mobile nav:
> refactor(frontend): Sticky headers overlapping mobile nav
